// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Auxiliar
{
    public partial class PaisAuxiliar
    {
        public string Codigo { get; set; }
        public string Codpais { get; set; }
        public string Dscpais { get; set; }
        public string Codcontinente { get; set; }
        public string Dsccontinente { get; set; }
    }
}