// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Auxiliar
{
    public partial class UbigeoAuxiliar
    {
        public string CodigoUbigeo { get; set; }
        public string DepartamentoUbigeo { get; set; }
        public string ProvinciaUbigeo { get; set; }
        public string DistritoUbigeo { get; set; }
        public string CodigoUbigeoReniec { get; set; }
    }
}