// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using MINEDU.IEST.Estudiante.Entity.Auxiliar;
#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Auxiliar
{
    public partial class AuxiliarDbContext : DbContext
    {
        public AuxiliarDbContext()
        {
        }

        public AuxiliarDbContext(DbContextOptions<AuxiliarDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PaisAuxiliar> TblPais { get; set; }
        public virtual DbSet<UbigeoAuxiliar> TblUbigeos { get; set; }
        public virtual DbSet<UvwCarrera> UvwCarreras { get; set; }
        public virtual DbSet<UvwInstitucion> UvwInstitucions { get; set; }
        public virtual DbSet<UvwUbigeoReniec> UbigeoReniec { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.TblPaiConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TblUbigeoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UvwCarreraConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UvwInstitucionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UbigeoReniecConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
