--/***************************************************************************************************************************************
--AUTOR				:	Juan Tovar
--FECHA DE CREACION	:	20/06/2019
--LLAMADO POR			:
--DESCRIPCION			:	Actualiza el registro de una Meta por programa de estudio de una institución
--REVISIONES			:
-------------------------------------------------------------------------------------------------------------
--VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-------------------------------------------------------------------------------------------------------------
--/*
--	1.0			21/11/2019		MALVA			MODIFICACIÓN PARA QUE FILTRE EL PERIODO LECTIVO INSTITUCIÓN PARA LA SUBCONSULTA DE RESOLUCIONES.
--- 1.1			21/01/2020		MALVA			MODIFICACIÓN DE ACUERDO A CAMBIOS EN LA INTERFACE DE REGISTRO DE METAS POR PROGRAMA DE ESTUDIOS. 
--*/
--  TEST:		exec dbo.USP_ADMISION_UPD_META_CARRERA_INSTITUCION 10319,0,0,7055,0,6,'44492255'
--****************************************************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_ADMISION_UPD_META_CARRERA_INSTITUCION]
(	
	@ID_PERIODOS_LECTIVOS_POR_INSTITUCION				INT, 
	@ID_META_CARRERA_INSTITUCION						INT ,
	@ID_TURNOS_POR_INSTITUCION							INT ,
	--@ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION	INT , 	
	--@ID_CARRERAS_POR_INSTITUCION						INT,		
	@ID_PLAN_ESTUDIO									INT, 
	@META_DISP_TOTAL									INT,		
	@META												INT,
	@USUARIO							VARCHAR(20)

)
AS
BEGIN
	DECLARE 
	@ID_INSTITUCION INT,
	@ANIO INT, 
	@CANT_METAS_SEDE INT,
	@CANT_META_ANT INT,	
	@ID_PERIODO_LECTIVO_INSTITUCION_UNO INT, 
	@ID_META_CARRERA_INSTITUCION_PRINC INT,
	@ESTADO_APERTURADO INT =7,	
	@RESULT INT, 
	@ID_CARRERAS_POR_INSTITUCION INT, 
	@ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION INT, 
	@ES_PERIODO_LECTIVO_INSTITUCION_UNO BIT,
	@ID_META_CARRERA_INSTITUCION_AMPL INT

	
	SET @ID_PERIODO_LECTIVO_INSTITUCION_UNO = (	SELECT top 1 
												tplxi.ID_PERIODOS_LECTIVOS_POR_INSTITUCION 
												FROM transaccional.periodos_lectivos_por_institucion tplxi 
												INNER JOIN maestro.periodo_lectivo mpl on tplxi.ID_PERIODO_LECTIVO= mpl.ID_PERIODO_LECTIVO
												WHERE ID_INSTITUCION=@ID_INSTITUCION 
												AND ES_ACTIVO=1 AND mpl.ANIO=@ANIO
												AND tplxi.ESTADO =@ESTADO_APERTURADO
												ORDER BY 1 ASC )
	IF 		@ID_PERIODO_LECTIVO_INSTITUCION_UNO	= @ID_PERIODOS_LECTIVOS_POR_INSTITUCION		
			set @ES_PERIODO_LECTIVO_INSTITUCION_UNO=1	
			
	SET @ID_CARRERAS_POR_INSTITUCION = (SELECT  PE.ID_CARRERAS_POR_INSTITUCION FROM transaccional.plan_estudio PE WHERE PE.ID_PLAN_ESTUDIO = @ID_PLAN_ESTUDIO)
	
	SET @ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION = (SELECT rxpli.ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION FROM transaccional.resoluciones_por_carreras_por_institucion  rxci 
	INNER JOIN transaccional.resoluciones_por_periodo_lectivo_institucion rxpli ON rxci.ID_RESOLUCION = rxpli.ID_RESOLUCION AND rxci.ES_ACTIVO=1 AND rxpli.ES_ACTIVO=1
	where ID_CARRERAS_POR_INSTITUCION = @ID_CARRERAS_POR_INSTITUCION and rxpli.ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODOS_LECTIVOS_POR_INSTITUCION)
		
	IF @ES_PERIODO_LECTIVO_INSTITUCION_UNO = 0
	BEGIN
		
		SELECT  
				@ID_META_CARRERA_INSTITUCION_AMPL = mci.ID_META_CARRERA_INSTITUCION 
		FROM 
				transaccional.meta_carrera_institucion mci
				INNER JOIN transaccional.resoluciones_por_periodo_lectivo_institucion rxpli ON mci.ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION = rxpli.ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION 
				AND mci.ES_ACTIVO=1 AND rxpli.ES_ACTIVO=1
				INNER JOIN maestro.resolucion r ON r.ID_RESOLUCION = rxpli.ID_RESOLUCION AND r.ES_ACTIVO=1 AND r.ESTADO=1
		WHERE 
				ANIO=@ANIO AND ID_PLAN_ESTUDIO=@ID_PLAN_ESTUDIO AND ID_META_CARRERA_INSTITUCION<>@ID_META_CARRERA_INSTITUCION

		IF @ID_META_CARRERA_INSTITUCION_AMPL IS NULL 
				SET @ID_META_CARRERA_INSTITUCION =0
		ELSE
				SET @ID_META_CARRERA_INSTITUCION = @ID_META_CARRERA_INSTITUCION_AMPL
	END

	IF @ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION is null
	BEGIN
			IF @ES_PERIODO_LECTIVO_INSTITUCION_UNO = 1
				SET		@RESULT =-2261
			ELSE
				SET		@RESULT =-2262
	END 
	ELSE IF @ID_META_CARRERA_INSTITUCION = 0 AND EXISTS (SELECT TOP 1 mci.ID_META_CARRERA_INSTITUCION FROM transaccional.meta_carrera_institucion mci WHERE ID_PLAN_ESTUDIO = @ID_PLAN_ESTUDIO 
						AND mci.ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION = @ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION 
						AND mci.ID_TURNOS_POR_INSTITUCION = @ID_TURNOS_POR_INSTITUCION
						AND mci.ES_ACTIVO=1)
				SET		@RESULT =-180
	ELSE
	BEGIN	
		SET @ID_INSTITUCION = (SELECT ID_INSTITUCION FROM transaccional.periodos_lectivos_por_institucion WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODOS_LECTIVOS_POR_INSTITUCION)
											  
		SET @ANIO = (
					SELECT ANIO FROM transaccional.periodos_lectivos_por_institucion TPLXI
					INNER JOIN maestro.periodo_lectivo MPL ON TPLXI.ID_PERIODO_LECTIVO= MPL.ID_PERIODO_LECTIVO AND TPLXI.ES_ACTIVO=1 
					WHERE TPLXI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODOS_LECTIVOS_POR_INSTITUCION
				)					
		SET @ID_PERIODO_LECTIVO_INSTITUCION_UNO = (	SELECT top 1 
													tplxi.ID_PERIODOS_LECTIVOS_POR_INSTITUCION 
													FROM transaccional.periodos_lectivos_por_institucion tplxi 
													INNER JOIN maestro.periodo_lectivo mpl on tplxi.ID_PERIODO_LECTIVO= mpl.ID_PERIODO_LECTIVO
													WHERE ID_INSTITUCION=@ID_INSTITUCION 
													AND ES_ACTIVO=1 AND mpl.ANIO=@ANIO
													AND tplxi.ESTADO =@ESTADO_APERTURADO
													ORDER BY 1 ASC )

		SET @ID_META_CARRERA_INSTITUCION_PRINC = (SELECT TMCI.ID_META_CARRERA_INSTITUCION FROM transaccional.meta_carrera_institucion  TMCI
													INNER JOIN transaccional.resoluciones_por_periodo_lectivo_institucion RXPLI 
													ON TMCI.ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION = RXPLI.ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION AND TMCI.ES_ACTIVO=1
													AND RXPLI.ES_ACTIVO=1
													WHERE ID_TURNOS_POR_INSTITUCION= @ID_TURNOS_POR_INSTITUCION AND TMCI.ID_PLAN_ESTUDIO= @ID_PLAN_ESTUDIO
													AND RXPLI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION_UNO)
					
		IF @ID_META_CARRERA_INSTITUCION > 0 
		BEGIN				
				SET @CANT_META_ANT = (SELECT META FROM transaccional.meta_carrera_institucion WHERE ID_META_CARRERA_INSTITUCION=@ID_META_CARRERA_INSTITUCION)
				SET @CANT_METAS_SEDE= (SELECT SUM(META_SEDE) FROM transaccional.meta_carrera_institucion_detalle 
						WHERE ID_META_CARRERA_INSTITUCION = @ID_META_CARRERA_INSTITUCION_PRINC AND ES_ACTIVO=1 AND ID_PERIODOS_LECTIVOS_POR_INSTITUCION= @ID_PERIODOS_LECTIVOS_POR_INSTITUCION)
		
				PRINT CONVERT (VARCHAR(5), @CANT_METAS_SEDE)
				IF (@CANT_METAS_SEDE > @META_DISP_TOTAL -@CANT_META_ANT +  @META )
					SET @RESULT = -239
				ELSE
					BEGIN
						update transaccional.meta_carrera_institucion
						set 
							META= @META, 
							ES_ACTIVO= (CASE WHEN @META =0 THEN 0 ELSE 1 END), 
							USUARIO_MODIFICACION= @USUARIO,
							FECHA_MODIFICACION =GETDATE()
						where 
							ID_META_CARRERA_INSTITUCION= @ID_META_CARRERA_INSTITUCION

						SET @RESULT =1 
					END
		END
		ELSE 
		BEGIN
			INSERT INTO transaccional.meta_carrera_institucion
			(	
				ID_TURNOS_POR_INSTITUCION,
				ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION,
				ID_CARRERAS_POR_INSTITUCION,
				ANIO,
				META,
				ES_ACTIVO,
				ESTADO, 
				USUARIO_CREACION,
				FECHA_CREACION, 
				ID_PLAN_ESTUDIO
			)
			VALUES 
			(	
				@ID_TURNOS_POR_INSTITUCION,
				@ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION,
				@ID_CARRERAS_POR_INSTITUCION,
				@ANIO,
				@META,
				1,
				1,
				@USUARIO,
				GETDATE(),
				@ID_PLAN_ESTUDIO
			)
			SET @RESULT =1 
		END
	END 
END
SELECT @RESULT




--************************************************************************************
 --74. USP_ADMISION_SEL_RESULTADOS_MODALIDAD_DETALLE.sql
GO


