CREATE PROCEDURE [dbo].[USP_EVALUACION_INS_CARGA_MASIVA_EVALUACIONES_NOTAS]
(
@ID_EVALUACION_CARGA_MASIVA			INT,
@NOTAS_UNIDADES_DIDACTICAS			NVARCHAR(MAX), 
@USUARIO							VARCHAR(20)
)
AS
DECLARE @RESULT INT
SET @RESULT =0 
BEGIN

	MERGE INTO transaccional.evaluacion_carga_masiva_detalle AS TARGET
		USING (
					SELECT	 
					SUBSTRING(SplitData,0,CHARINDEX(':',SplitData))  ID_UNIDAD_DIDACTICA, 
					SUBSTRING(SplitData,CHARINDEX(':',SplitData) + 1, LEN(SplitData) - CHARINDEX(':',SplitData)) NOTA					
					FROM dbo.UFN_SPLIT(@NOTAS_UNIDADES_DIDACTICAS,'|')
		) AS SOURCE ON  TARGET.ID_UNIDAD_DIDACTICA = SOURCE.ID_UNIDAD_DIDACTICA		
		AND  TARGET.ID_EVALUACION_CARGA_MASIVA= @ID_EVALUACION_CARGA_MASIVA			
		WHEN MATCHED
		THEN
			UPDATE
			SET ES_ACTIVO = 1,
				NOTA = SOURCE.NOTA,
				ESTADO=1,
				USUARIO_MODIFICACION = @USUARIO,
				FECHA_MODIFICACION = GETDATE()
		WHEN NOT MATCHED BY TARGET
		THEN
			INSERT (ID_EVALUACION_CARGA_MASIVA,
						 ID_UNIDAD_DIDACTICA,
						 NOTA,
						 ES_ACTIVO,
						 ESTADO,
						 USUARIO_CREACION,
						 FECHA_CREACION)
			VALUES(
				@ID_EVALUACION_CARGA_MASIVA,
				SOURCE.ID_UNIDAD_DIDACTICA,
				SOURCE.NOTA,
				1,
				1,	
				@USUARIO,
				GETDATE()		
			)
		WHEN NOT MATCHED BY SOURCE AND TARGET.ID_EVALUACION_CARGA_MASIVA= @ID_EVALUACION_CARGA_MASIVA
		THEN
			UPDATE
			SET
				ES_ACTIVO = 0,				
				USUARIO_MODIFICACION = @USUARIO,
				FECHA_MODIFICACION = GETDATE();
SET @RESULT =1
	
END
RETURN (@RESULT)
GO


