--USP_TRANSACCIONAL_INS_PROCESO_SISTEMA 208, 71, 'MALVA'

CREATE PROCEDURE [dbo].[USP_TRANSACCIONAL_INS_PROCESO_SISTEMA]
@ID_TIPO_PROCESO INT, 
@ID_REGISTRO_ASOCIADO INT, --ID_CARGA
@USUARIO VARCHAR(20)
AS 
BEGIN
	IF EXISTS (SELECT * FROM transaccional.proceso_sistema WHERE ID_TIPO_PROCESO= @ID_TIPO_PROCESO AND ID_REGISTRO_ASOCIADO= @ID_REGISTRO_ASOCIADO)
	SELECT -180
	ELSE
	BEGIN
			INSERT INTO transaccional.proceso_sistema
			(ID_TIPO_PROCESO, ID_REGISTRO_ASOCIADO, ES_ACTIVO, ESTADO, USUARIO_CREACION, FECHA_CREACION)
			VALUES 
			(@ID_TIPO_PROCESO, @ID_REGISTRO_ASOCIADO, 1,1,@USUARIO, GETDATE())
			SELECT 1
	END
END
GO


