CREATE PROCEDURE [dbo].[USP_MATRICULA_INS_RESERVA_MATRICULA]
(    
	@ID_ESTUDIANTE_INSTITUCION INT, 
	@ID_PERIODOS_LECTIVOS_POR_INSTITUCION INT,
	@ID_MOTIVO_RESERVA INT, 
	@ID_TIEMPO_PERIODO_RESERVA INT,
	@USUARIO VARCHAR(20)
)
AS
BEGIN
	DECLARE @RESULT INT,
	@ID_RESERVA_MATRICULA INT,
	@ID_REINGRESO_ESTUDIANTE INT
	DECLARE @FECHA_FIN_MATRICULA DATETIME
	DECLARE @FECHA_ACTUAL DATE

	SET @FECHA_FIN_MATRICULA = (SELECT TOP 1 FECHA_FIN FROM transaccional.programacion_matricula WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODOS_LECTIVOS_POR_INSTITUCION AND ES_ACTIVO=1 ORDER BY FECHA_FIN DESC)
	SET @FECHA_ACTUAL = (SELECT SYSDATETIME())

	SELECT 
	@ID_RESERVA_MATRICULA = trm.ID_RESERVA_MATRICULA,
	@ID_REINGRESO_ESTUDIANTE = tre.ID_REINGRESO_ESTUDIANTE
	FROM transaccional.reserva_matricula trm
	left join transaccional.reingreso_estudiante tre on trm.ID_RESERVA_MATRICULA= tre.ID_RESERVA_MATRICULA AND tre.ES_ACTIVO=1
	WHERE trm.ID_ESTUDIANTE_INSTITUCION= @ID_ESTUDIANTE_INSTITUCION
	and trm.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODOS_LECTIVOS_POR_INSTITUCION
	and trm.ES_ACTIVO=1

	IF @ID_RESERVA_MATRICULA IS NOT NULL AND @ID_REINGRESO_ESTUDIANTE IS NULL
	BEGIN
		SET @RESULT = -180  --HA RESERVADO Y NO HA REINGRESADO
	END
	ELSE IF (@FECHA_ACTUAL > @FECHA_FIN_MATRICULA)
	BEGIN
		SET @RESULT = -328
	END
	ELSE
	BEGIN
		INSERT INTO transaccional.reserva_matricula
		(ID_ESTUDIANTE_INSTITUCION, ID_PERIODOS_LECTIVOS_POR_INSTITUCION, ID_MOTIVO_RESERVA, ID_TIEMPO_PERIODO_RESERVA, ES_ACTIVO, ESTADO, USUARIO_CREACION, FECHA_CREACION)
		VALUES 
		(@ID_ESTUDIANTE_INSTITUCION,@ID_PERIODOS_LECTIVOS_POR_INSTITUCION,  @ID_MOTIVO_RESERVA,@ID_TIEMPO_PERIODO_RESERVA,1,1, @USUARIO, GETDATE() )
		SET @RESULT = 1
	END
	SELECT @RESULT
END
GO


