-------------------------------------------------------------------------------------------------------------
--AUTOR				:	Juan Tovar
--FECHA DE CREACION	:	04/04/2020
--LLAMADO POR			:
--DESCRIPCION			:	Asignar carga masiva del IEST
--REVISIONES			:
-------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE [dbo].[USP_TRANSACCIONAL_INS_ASIGNAR_INSTITUCION_MASIVO]
(
	@ID_INSTITUCION INT,
	@CODIGO_MODULAR NVARCHAR(max) ,
	@USUARIO VARCHAR(20)	
)
AS

--DECLARE @ID_TIPO_GESTION INT = (SELECT ISNULL((SELECT ID_TIPO_OPCION FROM maestro.periodo_lectivo WHERE ID_PERIODO_LECTIVO = @ID_PERIODO_LECTIVO),0))
--DECLARE @CODIGOS_MODULARES_EN_USO NVARCHAR(MAX), 
DECLARE @CODIGOS_MODULARES_EN_USO NVARCHAR(MAX), @RESULT NVARCHAR(MAX) =''
BEGIN TRANSACTION T1
BEGIN TRY
	MERGE INTO transaccional.asignación_institucion_carga AS TARGET
		USING (
			SELECT DISTINCT			
				I.ID_INSTITUCION ID_INSTITUCION		
			FROM db_auxiliar.dbo.UVW_INSTITUCION I
			WHERE 
				I.CODIGO_MODULAR  IN (SELECT SplitData FROM dbo.UFN_SPLIT(UPPER(@CODIGO_MODULAR), '|'))
			) AS SOURCE 
			ON (TARGET.ID_INSTITUCION = SOURCE.ID_INSTITUCION) --AND TARGET.ID_INSTITUCION=@ID_INSTITUCION
		WHEN MATCHED
		THEN		
			UPDATE 
			SET ES_ACTIVO = 1,
				USUARIO_MODIFICACION =@USUARIO,		
				FECHA_MODIFICACION = GETDATE()
			
		WHEN NOT MATCHED BY TARGET
		THEN
			
		INSERT (
		ID_INSTITUCION,
		ES_ACTIVO,
		ESTADO,
		USUARIO_CREACION,
		FECHA_CREACION
		)
		VALUES
		(
		SOURCE.ID_INSTITUCION,
		1,
		1,
		@USUARIO,
		GETDATE()
		)

		WHEN NOT MATCHED BY SOURCE 
		THEN
		UPDATE 
			SET ES_ACTIVO=0,
				USUARIO_MODIFICACION =@USUARIO,		
				FECHA_MODIFICACION = GETDATE();

	   SELECT @CODIGOS_MODULARES_EN_USO =COALESCE(@CODIGOS_MODULARES_EN_USO+', ','')  + MI.CODIGO_MODULAR FROM transaccional.asignación_institucion_carga PLXI
	   INNER JOIN db_auxiliar.dbo.UVW_INSTITUCION MI ON PLXI.ID_INSTITUCION= MI.ID_INSTITUCION AND PLXI.ES_ACTIVO=1 
	   WHERE MI.CODIGO_MODULAR NOT IN (SELECT SplitData FROM dbo.UFN_SPLIT(UPPER(@CODIGO_MODULAR), '|'))
	   AND PLXI.ID_INSTITUCION=@ID_INSTITUCION
	   
COMMIT TRANSACTION T1
IF @CODIGOS_MODULARES_EN_USO <>'' SET @RESULT= CONVERT(VARCHAR(MAX), @CODIGOS_MODULARES_EN_USO)
ELSE 	SET @RESULT  = '1'
END TRY
BEGIN CATCH
    IF @@ERROR<>0
    BEGIN		
	   ROLLBACK TRANSACTION T1
	   
	   SET @RESULT = '-1'

    END
END CATCH
SELECT @RESULT