CREATE PROCEDURE [dbo].[USP_TRANSACCIONAL_SEL_FECHA_REINGRESO_ESTUDIANTE]
--(
 --@ID_INSTITUCION INT
--)
AS
BEGIN
	
	SELECT CONVERT(VARCHAR(10), GETDATE(), 103) FechaReingreso
	
END


EXEC USP_TRANSACCIONAL_SEL_FECHA_REINGRESO_ESTUDIANTE
GO


