CREATE PROCEDURE [dbo].[USP_MAESTROS_SEL_AULA_LISTA1]
(  
@ID_SEDE_INSTITUCION INT,
@CATEGORIA INT
)  
AS  
BEGIN  
 SET NOCOUNT ON;   
 SELECT NOMBRE_AULA Text, 
		ID_AULA Value,
		AFORO_AULA Code
 FROM maestro.aula
WHERE ID_SEDE_INSTITUCION=@ID_SEDE_INSTITUCION AND ES_ACTIVO=1 AND CATEGORIA_AULA=@CATEGORIA
order by 1 asc
END
GO


