CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_TIPO_MODALIDAD_IE_PAGINADO]( 
	@ID_INSTITUCION INT,
	@ID_MODALIDAD INT,
	@ID_TIPO_MODALIDAD INT,
	@ID_ESTADO INT,

	@Pagina					int = 1,
	@Registros				int = 10
)AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @desde INT , @hasta INT;
	SET @desde = ( @Pagina - 1 ) * @Registros;
    SET @hasta = ( @Pagina * @Registros ) + 1;  

	WITH    tempPaginado AS
	(	   				
		SELECT 
				TMXI.ID_TIPOS_MODALIDAD_POR_INSTITUCION		IdTipoModalidadInstitucion,
				TM.ID_TIPO_MODALIDAD						IdTipoModalidad,
				TM.NOMBRE_TIPO_MODALIDAD					TipoModalidad,
				M.ID_ENUMERADO								IdModalidad,
				M.VALOR_ENUMERADO							Modalidad,
				E.ID_ENUMERADO								IdEstado,
				E.VALOR_ENUMERADO							Estado,

				ROW_NUMBER() OVER ( ORDER BY M.ID_ENUMERADO, TM.ID_TIPO_MODALIDAD) AS Row,
				Total = COUNT(1) OVER ( )
		FROM maestro.tipos_modalidad_por_institucion TMXI
			INNER JOIN maestro.tipo_modalidad TM ON TM.ID_TIPO_MODALIDAD = TMXI.ID_TIPO_MODALIDAD
			INNER JOIN sistema.enumerado M ON M.ID_ENUMERADO = TM.ID_MODALIDAD
			INNER JOIN sistema.enumerado E ON E.ID_ENUMERADO = TMXI.ESTADO
		WHERE 	
		TMXI.ID_TIPOS_MODALIDAD_POR_INSTITUCION =	CASE WHEN @ID_TIPO_MODALIDAD IS NULL	OR	LEN(@ID_TIPO_MODALIDAD) = 0	OR @ID_TIPO_MODALIDAD=0	OR @ID_TIPO_MODALIDAD = ''	THEN TMXI.ID_TIPOS_MODALIDAD_POR_INSTITUCION 	ELSE @ID_TIPO_MODALIDAD	END AND
		M.ID_ENUMERADO = CASE WHEN @ID_MODALIDAD IS NULL	OR	LEN(@ID_MODALIDAD) = 0	OR @ID_MODALIDAD=0	OR @ID_MODALIDAD = ''	THEN M.ID_ENUMERADO	ELSE @ID_MODALIDAD	END AND
		E.ID_ENUMERADO = CASE WHEN @ID_ESTADO IS NULL	OR	LEN(@ID_ESTADO) = 0 OR @ID_ESTADO=0	OR @ID_ESTADO = ''	THEN E.ID_ENUMERADO	ELSE @ID_ESTADO	END AND
		TMXI.ES_ACTIVO = 1 AND TMXI.ID_INSTITUCION = @ID_INSTITUCION

	)
	SELECT  *    FROM    tempPaginado T    WHERE   ( T.Row > @desde  AND T.Row < @hasta) OR (@Registros = 0) 


END
GO


