
--USP_ADMISION_SEL_DATOS_DISTRIBUCION_MODALIDAD 1082,24
CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_DATOS_DISTRIBUCION_MODALIDAD]
(
	@ID_PERIODO_LECTIVO_INSTITUCION INT,
	@ID_MODALIDAD INT
)
AS
BEGIN
	select DEA.ID_DISTRIBUCION_EXAMEN_ADMISION IdDistribucionExamenAdmision
	from transaccional.distribucion_examen_admision DEA
	inner join transaccional.examen_admision_sede  EAS ON DEA.ID_EXAMEN_ADMISION_SEDE= EAS.ID_EXAMEN_ADMISION_SEDE AND DEA.ES_ACTIVO=1 AND EAS.ES_ACTIVO=1
	inner join transaccional.proceso_admision_periodo PAP ON PAP.ID_PROCESO_ADMISION_PERIODO= EAS.ID_PROCESO_ADMISION_PERIODO AND PAP.ES_ACTIVO=1
	WHERE PAP.ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION 
	AND EAS.ID_MODALIDAD=@ID_MODALIDAD
END
GO


