CREATE PROCEDURE [dbo].[USP_INSTITUCION_INS_PROMOCION]
(
	@ID_INSTITUCION INT,
	@ID_TIPOPROMOCION INT,
	@ID_VERSION INT,
	@ID_TIPOUD INT,
	@ID_CRITERIO VARCHAR(15),
	@VALOR INT,
	@USUARIO VARCHAR(20)

	--DECLARE @ID_INSTITUCION INT=2457
	--DECLARE @ID_TIPOPROMOCION INT=206
	--DECLARE @ID_VERSION INT=101
	--DECLARE @ID_TIPOUD INT=1
	--DECLARE @ID_CRITERIO VARCHAR(15)='65'
	--DECLARE @VALOR INT=100
	--DECLARE @USUARIO VARCHAR(20)='42122536'
)
AS

DECLARE @RESULT INT

IF EXISTS(SELECT TOP 1 ID_PROMOCION_INSTITUCION_ESTUDIANTE FROM [transaccional].promocion_institucion_estudiante
WHERE ID_INSTITUCION = @ID_INSTITUCION AND ES_ACTIVO=1 AND TIPO_VERSION=@ID_VERSION AND ID_TIPO_UNIDAD_DIDACTICA = @ID_TIPOUD AND ESTADO=1)
BEGIN
	SET @RESULT = -180 -- YA SE ENCUENTRA REGISTRADO
END
ELSE
	BEGIN    	--print 'dentro de la transaccion'
	
	INSERT INTO [transaccional].promocion_institucion_estudiante
           ([ID_INSTITUCION]
           ,[TIPO_PROMOCION]
           ,[TIPO_VERSION]
           ,[ID_TIPO_UNIDAD_DIDACTICA]
           ,[CRITERIO]
		   ,[VALOR]
           ,[ES_ACTIVO]
           ,[ESTADO]
           ,[FECHA_CREACION]
           ,[USUARIO_CREACION]
		 )

     VALUES
           (@ID_INSTITUCION 
		  ,@ID_TIPOPROMOCION	  
		  ,@ID_VERSION	  
		  ,@ID_TIPOUD
		  ,@ID_CRITERIO
		  ,@VALOR		  
		  ,1	  
		  ,1 
		  ,GETDATE()
		  ,@USUARIO	  
		  )

		
	SET @RESULT = 1
END	
SELECT @RESULT
GO


