/*************************************************************************************************************************************************
AUTOR				:	Consultores DRE
FECHA DE CREACION	:	22/01/2020
LLAMADO POR			:
DESCRIPCION			:	Registro de documento DRE histórico. 
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
/*
*/
**************************************************************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_TRANSACCIONAL_INS_DOCUMENTO_DRE_HISTORICO] (
           @ID_INSTITUCION INT,
           @ID_SEDE_INSTITUCION INT,
           @ID_PERIODO_LECTIVO INT,
           @PROGRAMA_ESTUDIO INT,
           @PROGRAMA_ESTUDIO_HISTORICO INT,
           @PLAN_ESTUDIO INT,
           @CICLO INT,
           @SECCION INT,
           @TURNO INT,
           @NIVEL_FORMATIVO INT,
		   @CODIGO_TIPO_ENUMERADO INT, /*TIPO DE DOCUMENTO TRAIDO DE ENUMERADO HISTORICO*/
		   @USUARIO VARCHAR(MAX)
)AS
DECLARE @RESULT INT
DECLARE @ID_CLASE_HISTORICA_R_TABLE TABLE (  
    ID_CLASE_HISTORICA INT NOT NULL)
DECLARE @ID_CLASE_HISTORICA_R INT
BEGIN
	IF EXISTS (SELECT TOP 1 ID_CLASE_HISTORICA FROM [maestro].[clase_historica] -- SI EXISTE LA CLASE HISTORICA, OBTENEMOS ID_CLASE_HISTORICAY SÓLO AGRAGAMOS UN NUEVO REGISTRO EN DOCUMENTOS_DRE
				WHERE 
				   ID_INSTITUCION = @ID_INSTITUCION AND
				   ID_SEDE_INSTITUCION = @ID_SEDE_INSTITUCION AND
				   ID_PERIODO_LECTIVO = @ID_PERIODO_LECTIVO AND
				   PROGRAMA_ESTUDIO = @PROGRAMA_ESTUDIO AND
				   PROGRAMA_ESTUDIO_HISTORICO = @PROGRAMA_ESTUDIO_HISTORICO AND
				   PLAN_ESTUDIO = @PLAN_ESTUDIO AND
				   CICLO = @CICLO AND
				   SECCION = @SECCION AND
				   TURNO = @TURNO AND
				   NIVEL_FORMATIVO = @NIVEL_FORMATIVO AND
				   ESTADO = 1
				)
	BEGIN

		SET @ID_CLASE_HISTORICA_R = (SELECT TOP 1 ID_CLASE_HISTORICA FROM [maestro].[clase_historica]
			WHERE 
				ID_INSTITUCION = @ID_INSTITUCION AND
				ID_SEDE_INSTITUCION = @ID_SEDE_INSTITUCION AND
				ID_PERIODO_LECTIVO = @ID_PERIODO_LECTIVO AND
				PROGRAMA_ESTUDIO = @PROGRAMA_ESTUDIO AND
				PROGRAMA_ESTUDIO_HISTORICO = @PROGRAMA_ESTUDIO_HISTORICO AND
				PLAN_ESTUDIO = @PLAN_ESTUDIO AND
				CICLO = @CICLO AND
				SECCION = @SECCION AND
				TURNO = @TURNO AND
				NIVEL_FORMATIVO = @NIVEL_FORMATIVO AND
				ESTADO = 1)

		IF EXISTS (SELECT TOP 1 ID_DOCUMENTOS_DRE FROM [transaccional].[documentos_dre] -- VALIDANDO NO SE REPITA EL DOCUMENTO DRE
					WHERE 
					   ID_CLASE_HISTORICA = @ID_CLASE_HISTORICA_R AND
					   CODIGO_TIPO_ENUMERADO = @CODIGO_TIPO_ENUMERADO AND
					   ESTADO = 1
					)
			BEGIN
				SET @RESULT = -350 --VALIDANDO NO SE REPITA EL DOCUMENTO DRE
			END
			ELSE
			BEGIN
				INSERT INTO [transaccional].[documentos_dre]
					([ID_CLASE_HISTORICA]
					,[CODIGO_TIPO_ENUMERADO]
					,[USUARIO_CREACION]
					,[FECHA_CREACION]
					,[ESTADO])
				VALUES
					(@ID_CLASE_HISTORICA_R
					, @CODIGO_TIPO_ENUMERADO
					, @USUARIO
					,GETDATE()
					,1)
				SET @RESULT = 1  
			END
	END
	ELSE
	BEGIN
		
		INSERT INTO [maestro].[clase_historica]
					([ID_INSTITUCION]
					,[ID_SEDE_INSTITUCION]
					,[ID_PERIODO_LECTIVO]
					,[PROGRAMA_ESTUDIO]
					,[PROGRAMA_ESTUDIO_HISTORICO]
					,[PLAN_ESTUDIO]
					,[CICLO]
					,[SECCION]
					,[TURNO]
					,[NIVEL_FORMATIVO]
					,[USUARIO_CREACION]
					,[FECHA_CREACION]
					,[ESTADO])
				OUTPUT INSERTED.ID_CLASE_HISTORICA INTO @ID_CLASE_HISTORICA_R_TABLE
				VALUES
					(@ID_INSTITUCION
					,@ID_SEDE_INSTITUCION
					,@ID_PERIODO_LECTIVO
					,@PROGRAMA_ESTUDIO
					,@PROGRAMA_ESTUDIO_HISTORICO
					,@PLAN_ESTUDIO
					,@CICLO
					,@SECCION
					,@TURNO
					,@NIVEL_FORMATIVO
					,@USUARIO
					,GETDATE()
					,1)

			SET @ID_CLASE_HISTORICA_R = (SELECT TOP 1 ID_CLASE_HISTORICA FROM @ID_CLASE_HISTORICA_R_TABLE);

			INSERT INTO [transaccional].[documentos_dre]
				([ID_CLASE_HISTORICA]
				,[CODIGO_TIPO_ENUMERADO]
				,[USUARIO_CREACION]
				,[FECHA_CREACION]
				,[ESTADO])
			VALUES
				(@ID_CLASE_HISTORICA_R
				, @CODIGO_TIPO_ENUMERADO
				, @USUARIO
				,GETDATE()
				,1)

		SET @RESULT = 1  
	END
END
SELECT @RESULT