/**********************************************************************************************************
AUTOR				:	MALVA
FECHA DE CREACION	:	20/06/2018
LLAMADO POR			:
DESCRIPCION			:	Registrar las convalidaciones
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
1.0			20/06/2018		MALVA			Creación
1.1			30/03/2021		JCHAVEZ			Modificación, se agregó inserción del campo ID_PLAN_ESTUDIO
TEST
	--USP_CONVALIDACION_INS_CONVALIDACION 443, 895, 87,41,118,197,773,111,'MALVA'
	--USP_CONVALIDACION_INS_CONVALIDACION 443, 895, 83,21,115,194,773,111,'MALVA' --INTERNO
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_CONVALIDACION_INS_CONVALIDACION]
(
	@ID_INSTITUCION						INT,
	@ID_PERIODO_LECTIVO_INSTITUCION		INT,
	@ID_PERSONA							INT,
	@ID_ESTUDIANTE_INSTITUCION			INT,
	@ID_TRASLADO_ESTUDIANTE				INT,	
	@ID_TIPO_CONVALIDACION				INT,
	@ID_TURNOS_POR_INSTITUCION			INT,
	@ID_SEMESTRE_ACADEMICO				INT,
	@NRO_RESOLUCION      				VARCHAR(50),
	@ARCHIVO_CONVALIDACION      		VARCHAR(50),	
	@ARCHIVO_RUTA                       VARCHAR(255),
	@USUARIO							VARCHAR(20)
)
AS
DECLARE @RESULT INT
DECLARE @ID_CARRERA_POR_INSTITUCION_DETALLE INT
DECLARE @ID_CARRERA_POR_iNSTITUCION INT

SET @ID_CARRERA_POR_INSTITUCION_DETALLE = (SELECT TOP 1 ID_CARRERAS_POR_INSTITUCION_DETALLE FROM transaccional.estudiante_institucion WHERE ID_ESTUDIANTE_INSTITUCION = @ID_ESTUDIANTE_INSTITUCION AND ES_ACTIVO = 1)
SET @ID_CARRERA_POR_iNSTITUCION = (SELECT TOP 1 ID_CARRERAS_POR_INSTITUCION FROM transaccional.carreras_por_institucion_detalle WHERE ID_CARRERAS_POR_INSTITUCION_DETALLE = @ID_CARRERA_POR_INSTITUCION_DETALLE AND ES_ACTIVO = 1)



IF NOT EXISTS (SELECT TOP 1 ID_PLAN_ESTUDIO FROM transaccional.plan_estudio WHERE ID_CARRERAS_POR_INSTITUCION = @ID_CARRERA_POR_iNSTITUCION AND ES_ACTIVO = 1)
BEGIN

SET @RESULT=-336

END
ELSE
BEGIN

IF EXISTS(SELECT TOP 1 ME.ID_MATRICULA_ESTUDIANTE FROM transaccional.matricula_estudiante ME
				WHERE ME.ID_PERIODOS_LECTIVOS_POR_INSTITUCION= @ID_PERIODO_LECTIVO_INSTITUCION AND ME.ES_ACTIVO=1 
				AND ME.ID_ESTUDIANTE_INSTITUCION=@ID_ESTUDIANTE_INSTITUCION)
 SET @RESULT = -315 
ELSE IF EXISTS(SELECT top 1 ID_CONVALIDACION FROM transaccional.convalidacion where ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION
and ID_TIPO_CONVALIDACION = @ID_TIPO_CONVALIDACION and  ID_ESTUDIANTE_INSTITUCION = @ID_ESTUDIANTE_INSTITUCION and ES_ACTIVO=1 
)
 SET @RESULT = -305 
ELSE 
BEGIN

	BEGIN TRANSACTION T1
	BEGIN TRY
			DECLARE @ID_TIPO_CONVALIDACION_TRASLADO_EXTERNO		INT = 197,	
					@ID_TIPO_CONVALIDACION_TRASLADO_INTERNO		INT = 194,
					@ID_PERSONA_INSTITUCION						INT,
					@ID_TIPO_ESTUDIANTE							INT = 190, --HISTÓRICO
				    @ID_ESTUDIANTE_INSTITUCION_CONVALIDACION	INT, 
					@ID_INSTITUCION_ORIGEN						INT,
					@ID_PENDIENTE								INT =200

					
					
			IF @ID_TIPO_CONVALIDACION =@ID_TIPO_CONVALIDACION_TRASLADO_EXTERNO OR @ID_TIPO_CONVALIDACION =@ID_TIPO_CONVALIDACION_TRASLADO_INTERNO
			BEGIN

				SET @ID_INSTITUCION_ORIGEN = (	SELECT PLXI.ID_INSTITUCION from transaccional.traslado_estudiante TTE
												INNER JOIN transaccional.situacion_academica_estudiante TSAE ON TTE.ID_SITUACION_ACADEMICA_ORIGEN= TSAE.ID_SITUACION_ACADEMICA_ESTUDIANTE AND TTE.ES_ACTIVO=1 AND TSAE.ES_ACTIVO=1
												INNER JOIN transaccional.periodos_lectivos_por_institucion PLXI ON PLXI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION= TSAE.ID_PERIODOS_LECTIVOS_POR_INSTITUCION AND PLXI.ES_ACTIVO=1
												 WHERE ID_TRASLADO_ESTUDIANTE= @ID_TRASLADO_ESTUDIANTE)
				SET @ID_PERSONA_INSTITUCION= (SELECT TOP 1 ID_PERSONA_INSTITUCION FROM maestro.persona_institucion where ID_PERSONA = @ID_PERSONA AND ID_INSTITUCION=@ID_INSTITUCION AND ESTADO=1)
				IF @ID_PERSONA_INSTITUCION IS NULL
				BEGIN
					INSERT INTO maestro.persona_institucion
					(	ID_PERSONA, ID_INSTITUCION, ESTADO_CIVIL, PAIS_PERSONA, UBIGEO_PERSONA, DIRECCION_PERSONA,
						TELEFONO,CELULAR,CORREO,ID_TIPO_DISCAPACIDAD, ID_GRADO_PROFESIONAL,
						OCUPACION_PERSONA, TITULO_PROFESIONAL, ID_CARRERA_PROFESIONAL, INSTITUCION_PROFESIONAL, 
						ANIO_INICIO, ANIO_FIN, NIVEL_EDUCATIVO, ESTADO, USUARIO_CREACION, FECHA_CREACION
					)
					SELECT	
						ID_PERSONA, @ID_INSTITUCION, ESTADO_CIVIL, PAIS_PERSONA, UBIGEO_PERSONA, DIRECCION_PERSONA,
						TELEFONO,CELULAR,CORREO,ID_TIPO_DISCAPACIDAD, ID_GRADO_PROFESIONAL,
						OCUPACION_PERSONA, TITULO_PROFESIONAL, ID_CARRERA_PROFESIONAL, INSTITUCION_PROFESIONAL, 
						ANIO_INICIO, ANIO_FIN, NIVEL_EDUCATIVO, ESTADO, @USUARIO, GETDATE()
					FROM maestro.persona_institucion 
					WHERE ID_PERSONA=@ID_PERSONA AND ID_INSTITUCION = @ID_INSTITUCION_ORIGEN
					SET @ID_PERSONA_INSTITUCION = (SELECT CONVERT(INT,@@IDENTITY))
				END		
			
				
				UPDATE transaccional.estudiante_institucion SET ES_ACTIVO=0 WHERE ID_ESTUDIANTE_INSTITUCION= @ID_ESTUDIANTE_INSTITUCION AND ES_ACTIVO=1
				
				INSERT INTO transaccional.estudiante_institucion
				(	ID_PERSONA_INSTITUCION, 
					ID_INSTITUCION_BASICA, 
					ID_CARRERAS_POR_INSTITUCION_DETALLE,
					ID_TURNOS_POR_INSTITUCION, 
					ID_SEMESTRE_ACADEMICO, 
					ID_TIPO_ESTUDIANTE,
					ANIO_EGRESO,
					ID_TIPO_DOCUMENTO_APODERADO,
					ID_TIPO_PARENTESCO,
					NUMERO_DOCUMENTO_APODERADO,
					NOMBRE_APODERADO,
					APELLIDO_APODERADO, 
					ARCHIVO_FOTO,
					ARCHIVO_RUTA,
					ES_ACTIVO,
					ESTADO,
					USUARIO_CREACION,
					FECHA_CREACION,
					ID_PERIODOS_LECTIVOS_POR_INSTITUCION,
					ID_PLAN_ESTUDIO
				)
				select 
					@ID_PERSONA_INSTITUCION,
					ID_INSTITUCION_BASICA,
					(		SELECT TCID.ID_CARRERAS_POR_INSTITUCION_DETALLE 
							FROM transaccional.traslado_estudiante TTE
								INNER JOIN transaccional.situacion_academica_estudiante TSAE	ON	TTE.ID_SITUACION_ACADEMICA_DESTINO = TSAE.ID_SITUACION_ACADEMICA_ESTUDIANTE
								INNER JOIN transaccional.plan_estudio TPE						ON	TPE.ID_PLAN_ESTUDIO=TSAE.ID_PLAN_ESTUDIO AND TPE.ES_ACTIVO=1
								INNER JOIN transaccional.carreras_por_institucion_detalle TCID	ON 	TCID.ID_CARRERAS_POR_INSTITUCION= TPE.ID_CARRERAS_POR_INSTITUCION AND TCID.ES_ACTIVO=1
								AND TCID.ID_SEDE_INSTITUCION=TSAE.ID_SEDE_INSTITUCION
								AND TSAE.ES_ACTIVO=1 AND TTE.ES_ACTIVO=1
							WHERE TTE.ID_TRASLADO_ESTUDIANTE=@ID_TRASLADO_ESTUDIANTE
					) ID_CARRERAS_POR_INSTITUCION_DETALLE,				
					@ID_TURNOS_POR_INSTITUCION,
					@ID_SEMESTRE_ACADEMICO, 
					@ID_TIPO_ESTUDIANTE,
					ANIO_EGRESO, 
					ID_TIPO_DOCUMENTO_APODERADO,
					ID_TIPO_PARENTESCO,
					NUMERO_DOCUMENTO_APODERADO,
					NOMBRE_APODERADO,
					APELLIDO_APODERADO, 
					ARCHIVO_FOTO,
					ARCHIVO_RUTA, 
					1,
					1, 
					@USUARIO,
					GETDATE(),
					@ID_PERIODO_LECTIVO_INSTITUCION,
					(		SELECT TPE.ID_PLAN_ESTUDIO
							FROM transaccional.traslado_estudiante TTE
								INNER JOIN transaccional.situacion_academica_estudiante TSAE	ON	TTE.ID_SITUACION_ACADEMICA_DESTINO = TSAE.ID_SITUACION_ACADEMICA_ESTUDIANTE
								INNER JOIN transaccional.plan_estudio TPE						ON	TPE.ID_PLAN_ESTUDIO=TSAE.ID_PLAN_ESTUDIO AND TPE.ES_ACTIVO=1
								INNER JOIN transaccional.carreras_por_institucion_detalle TCID	ON 	TCID.ID_CARRERAS_POR_INSTITUCION= TPE.ID_CARRERAS_POR_INSTITUCION AND TCID.ES_ACTIVO=1
								AND TCID.ID_SEDE_INSTITUCION=TSAE.ID_SEDE_INSTITUCION
								AND TSAE.ES_ACTIVO=1 AND TTE.ES_ACTIVO=1
							WHERE TTE.ID_TRASLADO_ESTUDIANTE=@ID_TRASLADO_ESTUDIANTE
					) ID_PLAN_ESTUDIO
				from transaccional.estudiante_institucion
				WHERE ID_ESTUDIANTE_INSTITUCION= @ID_ESTUDIANTE_INSTITUCION 
					
				SET @ID_ESTUDIANTE_INSTITUCION_CONVALIDACION	= (SELECT CONVERT(INT,@@IDENTITY))
	
			END
			ELSE  
			BEGIN --SEGUNDA CARRERA O UNIDADES DIDACTICAS
				UPDATE transaccional.estudiante_institucion SET ID_SEMESTRE_ACADEMICO= @ID_SEMESTRE_ACADEMICO
				WHERE ID_ESTUDIANTE_INSTITUCION= @ID_ESTUDIANTE_INSTITUCION AND ES_ACTIVO=1
				SET @ID_ESTUDIANTE_INSTITUCION_CONVALIDACION= @ID_ESTUDIANTE_INSTITUCION 
			END
			
			INSERT INTO transaccional.convalidacion 
									(	ID_PERIODOS_LECTIVOS_POR_INSTITUCION,
										ID_ESTUDIANTE_INSTITUCION, 
										ID_TRASLADO_ESTUDIANTE,
										ID_TIPO_CONVALIDACION,										
										ES_ACTIVO, 
										ESTADO,
										NRO_RD,
										ARCHIVO_RD,
										ARCHIVO_RUTA,
										USUARIO_CREACION, 
										FECHA_CREACION
									)
			VALUES 
				(
				 @ID_PERIODO_LECTIVO_INSTITUCION,
				 @ID_ESTUDIANTE_INSTITUCION_CONVALIDACION,
				 (CASE WHEN @ID_TRASLADO_ESTUDIANTE=0 THEN NULL ELSE @ID_TRASLADO_ESTUDIANTE END),
				 @ID_TIPO_CONVALIDACION,			
				 1,
				 @ID_PENDIENTE,
				 @NRO_RESOLUCION,
				 @ARCHIVO_CONVALIDACION,
				 @ARCHIVO_RUTA,
				 @USUARIO,
				 GETDATE()
				)					
			COMMIT TRANSACTION T1
			SET @RESULT = 1
	END TRY
	BEGIN CATCH
			IF @@ERROR<>0
			BEGIN
			   ROLLBACK TRANSACTION T1	   
			   SET @RESULT = -1
			   PRINT ERROR_MESSAGE()
			END
	END CATCH	
END
END
SELECT @RESULT
GO


