CREATE PROCEDURE [dbo].[USP_META_CRONOGRAMA_FECHAS_PERIODO]
(  
@ID_PERIODO_LECTIVO INT

)  
AS  
BEGIN  
 SET NOCOUNT ON;   
 SELECT 
 FECHA_INICIO  FechaInicio,
 FECHA_FIN     FechaFin
 FROM maestro.periodo_lectivo
WHERE ID_PERIODO_LECTIVO = @ID_PERIODO_LECTIVO
order by 1 asc
END
GO


