CREATE PROCEDURE [dbo].[USP_TRANSACCIONAL_INS_PROMOVER_PERSONA]
(
	--DECLARE @ID_PERIODO_LECTIVO_INSTITUCION INT=5511
	--DECLARE @ID_SEDE_INSTITUCION INT=1959
	--DECLARE @ID_CARRERA INT=139
	--DECLARE @ID_MOTIVO INT=128
	--DECLARE @ID_POSTULANTES_POR_MODALIDAD_RETIRADO INT=1121
	--DECLARE @ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO INT=1122
	--DECLARE @ES_ACTIVO INT=1
	--DECLARE @ESTADO INT=1
	--DECLARE @USUARIO VARCHAR(20)='42122536'

	@ID_PERIODO_LECTIVO_INSTITUCION INT,
	@ID_SEDE_INSTITUCION INT,
	--@ID_CARRERA INT,
	@ID_PLAN_ESTUDIO  INT, 
	@ID_MOTIVO INT,
	@ID_POSTULANTES_POR_MODALIDAD_RETIRADO INT,
	@ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO INT,	
	@ES_ACTIVO INT,
	@ESTADO INT,
	@USUARIO VARCHAR(20)
)
AS

DECLARE @RESULT INT
DECLARE @VALORRETIRADO INT
DECLARE @VALORPROMOVIDO INT
DECLARE @ID_CARRERA_INSTITUCION1 INT

DECLARE @ID_PERIODO_ACADEMICO INT



	   /*SET @ID_CARRERA_INSTITUCION1 = (SELECT TOP 1 ID_CARRERAS_POR_INSTITUCION FROM transaccional.carreras_por_institucion CXI
										inner join maestro.sede_institucion MSI ON CXI.ID_INSTITUCION= MSI.ID_INSTITUCION AND CXI.ES_ACTIVO=1 AND MSI.ES_ACTIVO=1
									   WHERE CXI.ID_CARRERA= @ID_CARRERA AND MSI.ID_SEDE_INSTITUCION = @ID_SEDE_INSTITUCION )*/


		SET @ID_CARRERA_INSTITUCION1  = (SELECT ID_CARRERAS_POR_INSTITUCION FROM transaccional.plan_estudio WHERE ID_PLAN_ESTUDIO = @ID_PLAN_ESTUDIO)

      SET @ID_PERIODO_ACADEMICO = (SELECT TOP 1 ID_PERIODO_ACADEMICO FROM transaccional.periodo_academico WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION AND ES_ACTIVO = 1)
	
	  IF EXISTS (SELECT TOP 1 ID_EVALUACION FROM transaccional.evaluacion 
	                         WHERE ID_PROGRAMACION_CLASE IN (SELECT ID_PROGRAMACION_CLASE FROM transaccional.programacion_clase WHERE ID_PERIODO_ACADEMICO = @ID_PERIODO_ACADEMICO AND ES_ACTIVO = 1) 
					         AND CIERRE_PROGRAMACION = 235 AND ES_ACTIVO = 1)
	  
	  BEGIN

	  SET @RESULT = -332 -- VALIDA CIERRE

	  END
	  ELSE
	  BEGIN
	  
	  	
		IF EXISTS(SELECT TOP 1 mestudiante.ID_MATRICULA_ESTUDIANTE FROM transaccional.postulantes_por_modalidad ppmod INNER JOIN maestro.persona_institucion pinstitucion
                 ON ppmod.ID_PERSONA_INSTITUCION = pinstitucion.ID_PERSONA_INSTITUCION INNER JOIN transaccional.estudiante_institucion einstitucion
                 ON pinstitucion.ID_PERSONA_INSTITUCION = einstitucion.ID_PERSONA_INSTITUCION INNER JOIN transaccional.matricula_estudiante mestudiante
                 ON einstitucion.ID_ESTUDIANTE_INSTITUCION = mestudiante.ID_ESTUDIANTE_INSTITUCION INNER JOIN maestro.sede_institucion sinstitucion
                 ON pinstitucion.ID_INSTITUCION = sinstitucion.ID_INSTITUCION
                 WHERE ppmod.ID_POSTULANTES_POR_MODALIDAD= @ID_POSTULANTES_POR_MODALIDAD_RETIRADO AND mestudiante.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION 
				 AND sinstitucion.ID_SEDE_INSTITUCION = @ID_SEDE_INSTITUCION AND ppmod.ES_ACTIVO=1 AND einstitucion.ES_ACTIVO=1 AND mestudiante.ES_ACTIVO=1)
		BEGIN
			SET @RESULT = -268 -- YA SE ENCUENTRA CON MATRICULA
		END
		ELSE
			BEGIN    	--print 'dentro de la transaccion'
				
				IF EXISTS(SELECT TOP 1 ID_PROMOVER_PERSONA_INSTITUCION FROM [transaccional].[promover_persona_institucion]
				          WHERE ID_SEDE_INSTITUCION = UPPER(@ID_SEDE_INSTITUCION) AND ES_ACTIVO=1 AND ID_PLAN_ESTUDIO =@ID_PLAN_ESTUDIO --ID_CARRERAS_POR_INSTITUCION=@ID_CARRERA_INSTITUCION1 
						  --AND MOTIVO=@ID_MOTIVO 
						  AND ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION
				          AND ID_POSTULANTES_POR_MODALIDAD_RETIRADO=@ID_POSTULANTES_POR_MODALIDAD_RETIRADO 
						  OR ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO=@ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO AND ES_ACTIVO=1)
				BEGIN
					SET @RESULT = -180 -- YA SE ENCUENTRA REGISTRADO
				END
				ELSE
					BEGIN    	--print 'dentro de la transaccion'
	
					INSERT INTO [transaccional].[promover_persona_institucion]
						   ([ID_SEDE_INSTITUCION]
						   ,[ID_CARRERAS_POR_INSTITUCION]
						   ,[ID_PERIODOS_LECTIVOS_POR_INSTITUCION]
						   ,[ID_POSTULANTES_POR_MODALIDAD_RETIRADO]
						   ,[ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO]
						   ,[MOTIVO]
						   ,ID_PLAN_ESTUDIO
						   ,[ES_ACTIVO]
						   ,[ESTADO]
						   ,[FECHA_CREACION]
						   ,[USUARIO_CREACION]
						 )

					 VALUES
						   (@ID_SEDE_INSTITUCION 
						  --,(@ID_CARRERA_INSTITUCION)	
						  ,(@ID_CARRERA_INSTITUCION1)		  
						  ,@ID_PERIODO_LECTIVO_INSTITUCION	  
						  ,@ID_POSTULANTES_POR_MODALIDAD_RETIRADO	  
						  ,@ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO		  
						  ,@ID_MOTIVO
						  ,@ID_PLAN_ESTUDIO	  
						  ,@ES_ACTIVO	  
						  ,@ESTADO 
						  ,GETDATE()
						  ,@USUARIO	  
						  )

					SET @RESULT = 1 -- REGISTRA
				END			
		END	
	END		
SELECT @RESULT
GO


