CREATE PROCEDURE [dbo].[USP_MAESTROS_SEL_ROL_PERSONAL]
(
	@VALOR_ENUMERADO	INT
	
)
AS
BEGIN
DECLARE
	@ORDEN_ENUMERADO INT


SET @ORDEN_ENUMERADO  = ( SELECT ORDEN_ENUMERADO FROM sistema.enumerado where ID_ENUMERADO = @VALOR_ENUMERADO)

SELECT 
ID_ENUMERADO      IdRol,
VALOR_ENUMERADO   Rol

FROM sistema.enumerado 
WHERE ID_TIPO_ENUMERADO=15 and ORDEN_ENUMERADO = @ORDEN_ENUMERADO

END
GO


