CREATE PROCEDURE [dbo].[USP_MATRICULA_SEL_ESTUDIANTE_PROMOVIDO_INSTITUTO] 
(
	@ID_PROMOVER_PERSONA_INSTITUCION INT,
	@ID_PROMOVIDO	INT,
	@ID_PERIODO_LECTIVO	INT
)AS
BEGIN
	
	DECLARE @ID_POSTULANTES_POR_MODALIDAD INT

	SET @ID_POSTULANTES_POR_MODALIDAD = (SELECT ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO FROM transaccional.promover_persona_institucion 
    WHERE ID_PROMOVER_PERSONA_INSTITUCION=@ID_PROMOVER_PERSONA_INSTITUCION AND ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO=@ID_PROMOVIDO)

	SELECT 
	
	TOP 1 mestudiante.ID_MATRICULA_ESTUDIANTE   
	
	FROM transaccional.postulantes_por_modalidad ppmod INNER JOIN transaccional.estudiante_institucion einstituto
    ON ppmod.ID_PERSONA_INSTITUCION = einstituto.ID_PERSONA_INSTITUCION INNER JOIN transaccional.matricula_estudiante mestudiante
    ON einstituto.ID_ESTUDIANTE_INSTITUCION = mestudiante.ID_ESTUDIANTE_INSTITUCION
	WHERE 
	ppmod.ID_POSTULANTES_POR_MODALIDAD = @ID_POSTULANTES_POR_MODALIDAD AND
	mestudiante.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO
	
END
GO


