CREATE PROCEDURE [dbo].[USP_MAESTROS_UPD_INSTITUCION_BASICA]
(
	@ID_INSTITUCION_BASICA			INT,
	@ID_TIPO_INSTITUCION_BASICA		INT,
	@CODIGO_MODULAR					VARCHAR(7),
	@NOMBRE_IE_BASICA				VARCHAR(150),
	@ID_NIVEL_IE_BASICA				INT,
	@ID_TIPO_GESTION_IE_BASICA		INT,
	@DIRECCION_IE_BASICA			VARCHAR(255),
	@ID_PAIS_BASICA					INT,
	@UBIGEO_IE_BASICA				VARCHAR(6),
	@USUARIO						VARCHAR(20)
)AS
BEGIN
	UPDATE maestro.institucion_basica
	SET ID_TIPO_INSTITUCION_BASICA = @ID_TIPO_INSTITUCION_BASICA,
		CODIGO_MODULAR_IE_BASICA = @CODIGO_MODULAR,
		NOMBRE_IE_BASICA = @NOMBRE_IE_BASICA,
		ID_NIVEL_IE_BASICA = @ID_NIVEL_IE_BASICA,
		ID_TIPO_GESTION_IE_BASICA = @ID_TIPO_GESTION_IE_BASICA,
		DIRECCION_IE_BASICA = @DIRECCION_IE_BASICA,
		UBIGEO_IE_BASICA = @UBIGEO_IE_BASICA,
		USUARIO_MODIFICACION = @USUARIO,
		FECHA_MODIFICACION = GETDATE()
	WHERE 
		ID_INSTITUCION_BASICA = @ID_INSTITUCION_BASICA
END
GO


