CREATE PROCEDURE [dbo].[USP_ADMISION_UPD_EVALUADORES]
(
	@ID_EVALUADOR_ADMISION_MODALIDAD		INT,
	@ID_PERSONAL_INSTITUCION				INT,
	@ID_MODALIDADES_POR_PROCESO_ADMISION	INT,
	@USUARIO								VARCHAR(20)
)AS 
BEGIN
	IF EXISTS (SELECT TOP 1 ID_EVALUADOR_ADMISION_MODALIDAD FROM transaccional.evaluador_admision_modalidad
				WHERE ID_PERSONAL_INSTITUCION = @ID_PERSONAL_INSTITUCION AND ID_MODALIDADES_POR_PROCESO_ADMISION = @ID_MODALIDADES_POR_PROCESO_ADMISION AND ES_ACTIVO =1
				AND ID_EVALUADOR_ADMISION_MODALIDAD <> @ID_EVALUADOR_ADMISION_MODALIDAD)
		SELECT -180
	ELSE
	BEGIN
		UPDATE transaccional.evaluador_admision_modalidad
		SET 
			ID_MODALIDADES_POR_PROCESO_ADMISION = @ID_MODALIDADES_POR_PROCESO_ADMISION,
			USUARIO_MODIFICACION = @USUARIO,
			FECHA_MODIFICACION = GETDATE()
		WHERE
			ID_EVALUADOR_ADMISION_MODALIDAD = @ID_EVALUADOR_ADMISION_MODALIDAD

		SELECT 1
	END
END
GO


