CREATE PROCEDURE [dbo].[USP_MAESTRO_SEL_REQUISITO_PROCESO_LISTA]
(
	@ID_INSTITUCION	INT,
	@ID_PROCESO		INT
)
AS
BEGIN
/*
16	ADMISIÓN
17	CONVALIDACIÓN
18	LICENCIA
19	MATRÍCULA
20	TRASLADO
*/

SELECT 	ID_REQUISITO		Value,
			NOMBRE_REQUISITO	Text,
			ID_REQUISITO		Code
FROM maestro.requisito 
WHERE ID_PROCESO=@ID_PROCESO AND ESTADO=1
ORDER BY NOMBRE_REQUISITO ASC
	
END
GO


