
-- [USP_EVALUACION_RPT_ACTA_CONSOLIDADA_NOTAS_PAGINADO]  443,895,0,0,0,0,0,0,0

CREATE PROCEDURE [dbo].[USP_EVALUACION_RPT_ACTA_CONSOLIDADA_NOTAS_PAGINADO](
	@ID_INSTITUCION							INT, 
	@ID_PERIODOS_LECTIVOS_POR_INSTITUCION	INT, 
	@ID_SEDE_INSTITUCION					INT, 	 
	@ID_PERSONAL_INSTITUCION                INT,
	@ID_CARRERA								INT, 
	@ID_UNIDAD_DIDACTICA					INT, 
	@ID_PERIODO_ACADEMICO					INT,
	@ID_TURNOS_POR_INSTITUCION				INT, 
	@ID_SECCION								INT,
	@Pagina									INT	=1, 
	@Registros								INT	=20 

)
AS  
BEGIN  
	SET NOCOUNT ON;

	DECLARE @desde INT , @hasta INT;

	SET @desde = ( @Pagina - 1 ) * @Registros;
    SET @hasta = ( @Pagina * @Registros ) + 1;
	

 SELECT A.ID_PROGRAMACION_CLASE,
		SD2.DRE_GRE									AS Dre_gre,
		SD2.ID_INSTITUCION,
		SD2.NOMBRE_INSTITUCION						AS NombreInstituto,
		G.ID_CARRERA,
		upper(G.NOMBRE_CARRERA)						as carrera,
		SD1.ID_SEDE_INSTITUCION,
		SD1.DIRECCION_SEDE							AS DireccionSede,
		SD2.CODIGO_DISTRITO							AS CODIGO_UBIGEO,
		UB.DEPARTAMENTO_UBIGEO,UB.PROVINCIA_UBIGEO,UB.DISTRITO_UBIGEO,
		NF.ID_NIVEL_FORMACION,
		NF.NOMBRE_NIVEL_FORMACION,
		PA1.ID_PERIODO_ACADEMICO					AS IdPeriodoClases,
		PA1.NOMBRE_PERIODO_ACADEMICO				AS Periodo_clases,
		PL2.ID_PERIODO_LECTIVO,
		PL2.CODIGO_PERIODO_LECTIVO					AS Periodo_lectivo,
		SA1.VALOR_ENUMERADO							AS Ciclo,
		E.ID_TIPO_ITINERARIO,
		PES.VALOR_ENUMERADO							AS PlanEstudios,
		TN2.ID_TURNO,
		TN3.VALOR_ENUMERADO							AS Turno,
		A.ID_SECCION								AS IdSeccion,
		S1.VALOR_ENUMERADO							AS Seccion,
		SD2.CODIGO_MODULAR							AS CodigoModular,
		TG.VALOR_ENUMERADO							AS TipoGestion,
		AL2.NUMERO_DOCUMENTO_PERSONA				AS IdEstudiante,
		AL2.APELLIDO_PATERNO_PERSONA + ' '+ AL2.APELLIDO_MATERNO_PERSONA+ ' ' + AL2.NOMBRE_PERSONA AS NombreAlumno,
		C.ID_UNIDAD_DIDACTICA						AS IdUnidadDidactica,
		UD1.NOMBRE_UNIDAD_DIDACTICA					AS UnidadDidactica,	
		convert(varchar(2), CAST(N2.NOTA AS INT))	AS Nota,
							
		ROW_NUMBER() OVER ( ORDER BY A.ID_PROGRAMACION_CLASE) AS Row,
		Total = count(1) OVER ()

 
 	
		--F.ID_INSTITUCION							AS IdInstitucion,
		--A.ID_SEDE_INSTITUCION						AS IdSedeInstitucion,
		--SD1.NOMBRE_SEDE								AS Sede,
		--F.ID_CARRERA								AS	IdCarrera,
		--upper(G.NOMBRE_CARRERA)						AS ProgramaEstudio,
		--I.ID_SEMESTRE_ACADEMICO	,
		--SA1.VALOR_ENUMERADO							AS SemestreAcademico,
		--A.ID_TURNOS_POR_INSTITUCION					AS IdTurnoInstitucion,
		--TN2.ID_TURNO,
		--TN3.VALOR_ENUMERADO							AS Turno,
		--PL2.ID_PERIODO_LECTIVO,
		--A.ID_SECCION								AS IdSeccion,
		--S1.VALOR_ENUMERADO							AS Seccion,
		
		--I.ID_PERIODOS_LECTIVOS_POR_INSTITUCION,
		--PL2.CODIGO_PERIODO_LECTIVO					AS Periodo_lectivo,
		--PA1.ID_PERIODO_ACADEMICO					AS IdPeriodoClases,
		--PA1.NOMBRE_PERIODO_ACADEMICO				AS Periodo_clases,
		--C.ID_UNIDAD_DIDACTICA						AS IdUnidadDidactica,
		--UD1.NOMBRE_UNIDAD_DIDACTICA					AS UnidadDidactica,
		--I.ID_MATRICULA_ESTUDIANTE					AS IdMatriculaEstudiante,
		--AL2.ID_PERSONA,
		--AL2.NUMERO_DOCUMENTO_PERSONA				AS IdEstudiante,
		--AL2.APELLIDO_PATERNO_PERSONA + ' '+ AL2.APELLIDO_MATERNO_PERSONA+ ' ' + AL2.NOMBRE_PERSONA AS NombreAlumno,
		--DOC1.ID_ROL,
		--DOC3.NUMERO_DOCUMENTO_PERSONA				AS IdDocente,
		--DOC1.ID_PERSONAL_INSTITUCION				AS IdPersonalInstitucion,
		--DOC3.NOMBRE_PERSONA	+' '+ DOC3.APELLIDO_PATERNO_PERSONA	+' '+ DOC3.APELLIDO_MATERNO_PERSONA AS Docente,
		--N1.ID_EVALUACION							AS IdEvaluacion,
		--N1.CIERRE_PROGRAMACION						AS IdEstadoCierre,
		--convert(varchar(2), CAST(N2.NOTA AS INT))	AS Nota,
		--H.ID_PROGRAMACION_CLASE						AS IdProgramacionClase,
		--0 as ESTADO01	
	FROM 
		transaccional.programacion_clase  A
		INNER JOIN transaccional.unidades_didacticas_por_programacion_clase	B	ON A.ID_PROGRAMACION_CLASE= B.ID_PROGRAMACION_CLASE AND A.ES_ACTIVO=1 AND B.ES_ACTIVO=1	
		INNER JOIN transaccional.unidades_didacticas_por_enfoque C				ON B.ID_UNIDADES_DIDACTICAS_POR_ENFOQUE = C.ID_UNIDADES_DIDACTICAS_POR_ENFOQUE AND C.ES_ACTIVO=1	
		INNER JOIN transaccional.enfoques_por_plan_estudio D					ON C.ID_ENFOQUES_POR_PLAN_ESTUDIO=D.ID_ENFOQUES_POR_PLAN_ESTUDIO AND D.ES_ACTIVO=1	
		INNER JOIN transaccional.plan_estudio E									ON D.ID_PLAN_ESTUDIO = E.ID_PLAN_ESTUDIO AND D.ES_ACTIVO=1	
		INNER JOIN transaccional.carreras_por_institucion F						ON E.ID_CARRERAS_POR_INSTITUCION =F.ID_CARRERAS_POR_INSTITUCION AND F.ES_ACTIVO=1
		INNER JOIN db_auxiliar.dbo.UVW_CARRERA G								ON F.ID_CARRERA=G.ID_CARRERA -- AND G.ESTADO=1	--reemplazoPorVista
		INNER JOIN transaccional.programacion_clase_por_matricula_estudiante H	ON A.ID_PROGRAMACION_CLASE = H.ID_PROGRAMACION_CLASE AND H.ES_ACTIVO=1			
		INNER JOIN transaccional.matricula_estudiante I							ON H.ID_MATRICULA_ESTUDIANTE = I.ID_MATRICULA_ESTUDIANTE AND I.ES_ACTIVO=1
		INNER JOIN transaccional.carreras_por_institucion_detalle J				ON F.ID_CARRERAS_POR_INSTITUCION = J.ID_CARRERAS_POR_INSTITUCION AND A.ID_SEDE_INSTITUCION =J.ID_SEDE_INSTITUCION AND J.ES_ACTIVO=1	
		--SEDES
		INNER JOIN maestro.sede_institucion	SD1									ON J.ID_SEDE_INSTITUCION=SD1.ID_SEDE_INSTITUCION
		INNER JOIN db_auxiliar.dbo.UVW_INSTITUCION SD2						ON SD1.ID_INSTITUCION=SD2.ID_INSTITUCION		
		--SEMESTRE academico		
		INNER JOIN sistema.enumerado SA1										ON I.ID_SEMESTRE_ACADEMICO =SA1.ID_ENUMERADO AND SA1.ESTADO=1
		--TURNO
		INNER JOIN maestro.turnos_por_institucion TN1							ON A.ID_TURNOS_POR_INSTITUCION=TN1.ID_TURNOS_POR_INSTITUCION AND TN1.ES_ACTIVO=1
		INNER JOIN maestro.turno_equivalencia TN2								ON TN1.ID_TURNO_EQUIVALENCIA=TN2.ID_TURNO_EQUIVALENCIA AND TN2.ESTADO=1
		INNER JOIN sistema.enumerado TN3										ON TN2.ID_TURNO= TN3.ID_ENUMERADO AND TN3.ESTADO=1
		--SECCION
		INNER JOIN sistema.enumerado S1											ON A.ID_SECCION=S1.ID_ENUMERADO AND S1.ESTADO=1
		--PERIODO LECTIVO
		INNER JOIN transaccional.periodos_lectivos_por_institucion PL1			ON I.ID_PERIODOS_LECTIVOS_POR_INSTITUCION=PL1.ID_PERIODOS_LECTIVOS_POR_INSTITUCION AND PL1.ES_ACTIVO=1
		INNER JOIN maestro.periodo_lectivo PL2									ON PL1.ID_PERIODO_LECTIVO=PL2.ID_PERIODO_LECTIVO AND PL2.ESTADO=1
		--PERIODO ACADEMICO / CLASES
		INNER JOIN transaccional.periodo_academico PA1							ON I.ID_PERIODOS_LECTIVOS_POR_INSTITUCION=PA1.ID_PERIODOS_LECTIVOS_POR_INSTITUCION and A.ID_PERIODO_ACADEMICO=PA1.ID_PERIODO_ACADEMICO AND PA1.ES_ACTIVO=1
		--UNIDAD DIDACTICA	
		INNER JOIN transaccional.unidad_didactica UD1							ON C.ID_UNIDAD_DIDACTICA=UD1.ID_UNIDAD_DIDACTICA AND UD1.ES_ACTIVO=1
		--ALUMNO
		INNER JOIN transaccional.estudiante_institucion EI						ON I.ID_ESTUDIANTE_INSTITUCION=EI.ID_ESTUDIANTE_INSTITUCION AND EI.ES_ACTIVO=1
		INNER JOIN maestro.persona_institucion AL1								ON EI.ID_PERSONA_INSTITUCION=AL1.ID_PERSONA_INSTITUCION AND AL1.ESTADO=1
		INNER JOIN maestro.persona AL2											ON AL1.ID_PERSONA=AL2.ID_PERSONA AND AL2.ESTADO=1
		--DOCENTE			
		INNER JOIN maestro.personal_institucion DOC1							ON A.ID_PERSONAL_INSTITUCION=DOC1.ID_PERSONAL_INSTITUCION AND DOC1.ES_ACTIVO=1
		INNER JOIN maestro.persona_institucion DOC2								ON DOC1.ID_PERSONA_INSTITUCION=DOC2.ID_PERSONA_INSTITUCION AND DOC2.ESTADO=1
		INNER JOIN maestro.persona DOC3											ON DOC2.ID_PERSONA=DOC3.ID_PERSONA	AND DOC3.ESTADO=1
		--NOTA
		INNER JOIN transaccional.evaluacion N1									ON H.ID_PROGRAMACION_CLASE=N1.ID_PROGRAMACION_CLASE AND N1.ES_ACTIVO=1
		LEFT JOIN transaccional.evaluacion_detalle N2							ON N1.ID_EVALUACION=N2.ID_EVALUACION AND H.ID_MATRICULA_ESTUDIANTE=N2.ID_MATRICULA_ESTUDIANTE AND N2.ES_ACTIVO=1
		--UBIGEO
		INNER JOIN db_auxiliar.dbo.UVW_UBIGEO UB								ON SD2.CODIGO_DISTRITO=UB.CODIGO_UBIGEO 	--reemplazoPorVista
		--NIVEL DE FORMACION
		INNER JOIN maestro.nivel_formacion NF									ON G.ID_NIVEL_FORMACION=NF.ID_NIVEL_FORMACION AND NF.ESTADO=1
		--PLAN DE ESTUDIOS
		INNER JOIN sistema.enumerado PES										ON E.ID_TIPO_ITINERARIO = PES.ID_ENUMERADO 
		--TIPO DE GESTION
		INNER JOIN sistema.enumerado TG											ON SD2.TIPO_GESTION= TG.ID_ENUMERADO	--reemplazoPorVista
		

	WHERE
		F.ID_INSTITUCION						= @ID_INSTITUCION AND 
		I.ID_PERIODOS_LECTIVOS_POR_INSTITUCION	= @ID_PERIODOS_LECTIVOS_POR_INSTITUCION AND 
		--A.ID_SEDE_INSTITUCION					= @ID_SEDE_INSTITUCION AND 
		(A.ID_SEDE_INSTITUCION					= @ID_SEDE_INSTITUCION OR @ID_SEDE_INSTITUCION=0) AND
		(DOC1.ID_PERSONAL_INSTITUCION			= @ID_PERSONAL_INSTITUCION OR @ID_PERSONAL_INSTITUCION = '0') AND 
		(F.ID_CARRERA							= @ID_CARRERA OR @ID_CARRERA=0) AND
		(C.ID_UNIDAD_DIDACTICA					= @ID_UNIDAD_DIDACTICA OR @ID_UNIDAD_DIDACTICA=0) AND 
		(PA1.ID_PERIODO_ACADEMICO				= @ID_PERIODO_ACADEMICO OR @ID_PERIODO_ACADEMICO=0)	AND
		(A.ID_TURNOS_POR_INSTITUCION			= @ID_TURNOS_POR_INSTITUCION OR @ID_TURNOS_POR_INSTITUCION=0) AND
		(A.ID_SECCION							= @ID_SECCION OR @ID_SECCION=0)
END
GO


