-------------------------------------------------------------------------------------------------------------
--AUTOR				:	Juan Tovar
--FECHA DE CREACION	:	12/04/2020
--LLAMADO POR			:
--DESCRIPCION			:	seleccionar fecha y hora de habilitacion de postulante
--REVISIONES			:
-------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_HABILITACION_POSTULANTE_FECHAHORAPROCESO]
(
	
	@ID_PERIODOS_LECTIVOS_POR_INSTITUCION	INT,
	@ID_SEDE_INSTITUCION	INT

)
AS
BEGIN
	DECLARE @ID_PROCESO_ADMISION INT
	DECLARE @FECHA DATE
	DECLARE @FECHAACTUAL DATE
	DECLARE @RESULT INT
	DECLARE @HORAACTUAL VARCHAR(5)
	DECLARE @HORA VARCHAR(5)

	SET @FECHAACTUAL = GETDATE()
	SET @HORAACTUAL = CONVERT (time, SYSDATETIME())

	SET @ID_PROCESO_ADMISION = (SELECT TOP 1 ID_PROCESO_ADMISION_PERIODO FROM transaccional.proceso_admision_periodo WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODOS_LECTIVOS_POR_INSTITUCION AND ES_ACTIVO = 1) 
	SET @FECHA = (SELECT TOP 1 FECHA_EVALUACION FROM transaccional.examen_admision_sede WHERE ID_PROCESO_ADMISION_PERIODO = @ID_PROCESO_ADMISION AND ID_SEDE_INSTITUCION = @ID_SEDE_INSTITUCION)
	SET @HORA = (SELECT TOP 1 HORA_EVALUACION FROM transaccional.examen_admision_sede WHERE ID_PROCESO_ADMISION_PERIODO = @ID_PROCESO_ADMISION AND ID_SEDE_INSTITUCION = @ID_SEDE_INSTITUCION)

	IF (@FECHAACTUAL > @FECHA) 
	BEGIN

	SET @RESULT = 1 --SI SE PUEDE CAMBIAR

	END
	ELSE
	BEGIN
		IF (@FECHAACTUAL = @FECHA AND @HORAACTUAL < @HORA)
		BEGIN
		SET @RESULT = 3 --SI SE PUEDE CAMBIAR
		END
		ELSE
		BEGIN
		SET @RESULT = 0 --NO SE PUEDE CAMBIAR
		END
	END

SELECT @RESULT
		
END
GO


