CREATE PROCEDURE [dbo].[USP_MATRICULA_SEL_LICENCIA_ESTUDIANTE_INSTITUTO] 
(
	@ID_INSTITUCION INT,
	@ID_PERIODOLECTIVO_INSTITUCION	INT,
	@ID_TIPO_DOCUMENTO	INT,
	@NUMERO_DOCUMENTO VARCHAR(15)
)AS
BEGIN
	DECLARE
	@ID_ESTUDIANTE_INSTITUCION INT,
	@ID_ULT_LICENCIA_ESTUDIANTE INT,
	@ID_ULT_RESERVA_MATRICULA INT,
	@ID_ULT_PERIODO_LECTIVO_SOLICITUD INT,
	@TIEMPO_LICENCIA INT,
    @FECHA_INICIO_INSTITUCION_ULT_PERIODO_LECTIVO_SOLICITUD DATE, 
	@FECHA_FIN_INSTITUCION_ULT_PERIODO_LECTIVO_SOLICITUD DATE,
	@ID_PERSONA_INSTITUCION INT


	SET @ID_PERSONA_INSTITUCION  = ( SELECT TOP 1 MPI.ID_PERSONA_INSTITUCION
									FROM maestro.persona MP
									INNER JOIN maestro.persona_institucion MPI ON MPI.ID_PERSONA= MP.ID_PERSONA
									INNER JOIN transaccional.estudiante_institucion TEI ON TEI.ID_PERSONA_INSTITUCION = MPI.ID_PERSONA_INSTITUCION 
									AND TEI.ES_ACTIVO=1
									WHERE MP.ID_TIPO_DOCUMENTO= @ID_TIPO_DOCUMENTO AND MP.NUMERO_DOCUMENTO_PERSONA=@NUMERO_DOCUMENTO
									AND MPI.ID_INSTITUCION=@ID_INSTITUCION )



	SET @ID_ULT_PERIODO_LECTIVO_SOLICITUD = (select TOP 1 TPLXI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION  from 
												(	SELECT TLE.ID_PERIODOS_LECTIVOS_POR_INSTITUCION FROM transaccional.licencia_estudiante TLE 
													INNER JOIN transaccional.estudiante_institucion ei ON ei.ID_ESTUDIANTE_INSTITUCION = TLE.ID_ESTUDIANTE_INSTITUCION
													AND ei.ES_ACTIVO=1
													WHERE ei.ID_PERSONA_INSTITUCION= @ID_PERSONA_INSTITUCION AND TLE.ES_ACTIVO=1
													UNION
													SELECT TRM.ID_PERIODOS_LECTIVOS_POR_INSTITUCION FROM transaccional.reserva_matricula TRM
													INNER JOIN transaccional.estudiante_institucion ei ON ei.ID_ESTUDIANTE_INSTITUCION = TRM.ID_ESTUDIANTE_INSTITUCION
													AND ei.ES_ACTIVO=1
													WHERE ei.ID_PERSONA_INSTITUCION= @ID_PERSONA_INSTITUCION  AND TRM.ES_ACTIVO=1
												) SubConsulta1
											INNER JOIN transaccional.periodos_lectivos_por_institucion TPLXI ON SubConsulta1.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = TPLXI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION 
											AND TPLXI.ES_ACTIVO=1
											INNER JOIN maestro.periodo_lectivo MPL ON MPL.ID_PERIODO_LECTIVO = TPLXI.ID_PERIODO_LECTIVO
											order by MPL.FECHA_INICIO DESC )



	SET @FECHA_INICIO_INSTITUCION_ULT_PERIODO_LECTIVO_SOLICITUD  = (SELECT FECHA_INICIO_INSTITUCION FROM transaccional.periodos_lectivos_por_institucion WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION= @ID_ULT_PERIODO_LECTIVO_SOLICITUD)
	SET @FECHA_FIN_INSTITUCION_ULT_PERIODO_LECTIVO_SOLICITUD  = (SELECT FECHA_FIN_INSTITUCION FROM transaccional.periodos_lectivos_por_institucion WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION= @ID_PERIODOLECTIVO_INSTITUCION)


	SET @TIEMPO_LICENCIA = (select count(ID_PERIODO_LECTIVO) from transaccional.periodos_lectivos_por_institucion 
						where --ID_PERIODOS_LECTIVOS_POR_INSTITUCION BETWEEN @ID_ULT_PERIODO_LECTIVO_SOLICITUD and @ID_PERIODOLECTIVO_INSTITUCION 
						ID_INSTITUCION =@ID_INSTITUCION
     					AND FECHA_INICIO_INSTITUCION BETWEEN  @FECHA_INICIO_INSTITUCION_ULT_PERIODO_LECTIVO_SOLICITUD AND @FECHA_FIN_INSTITUCION_ULT_PERIODO_LECTIVO_SOLICITUD  ) - 1


	SELECT
			ISNULL(TRM.ID_RESERVA_MATRICULA,0)			IdReservaMatricula,
			ISNULL(TLE.ID_LICENCIA_ESTUDIANTE,0)		IdLicenciaEstudiante,
			MP.APELLIDO_PATERNO_PERSONA + ' '
			+MP.APELLIDO_MATERNO_PERSONA + ', '
			+dbo.UFN_CAPITALIZAR(MP.NOMBRE_PERSONA)		Estudiante,
			E_CICLO.VALOR_ENUMERADO						Ciclo,
			TCXI.ID_CARRERA								IdCarrera,
			MC.NOMBRE_CARRERA							Programa, 
			MSI.ID_SEDE_INSTITUCION						IdSedeInstitucion,
			MSI.NOMBRE_SEDE								Sede,
			ti.VALOR_ENUMERADO							TipoPlanEstudios,
			pe.NOMBRE_PLAN_ESTUDIOS						PlanEstudios,
			CASE WHEN  TRM.ID_RESERVA_MATRICULA IS NOT NULL THEN 
			'RESERVA MATRICULA ' + (SELECT VALOR_ENUMERADO FROM sistema.enumerado WHERE ID_ENUMERADO = TRM.ID_MOTIVO_RESERVA)
			WHEN TLE.ID_LICENCIA_ESTUDIANTE IS NOT NULL THEN 
			'LICENCIA ' + (SELECT VALOR_ENUMERADO FROM sistema.enumerado WHERE ID_ENUMERADO = TLE.ID_TIPO_LICENCIA)
			ELSE
			''
			END											TipoLicencia,
			CASE @TIEMPO_LICENCIA                              
				WHEN 0 THEN 'NINGUN PERIODO'
				WHEN 1 THEN 'I PERIODO'
				WHEN 2 THEN 'II PERIODOS'
				WHEN 3 THEN 'III PERIODOS'
				WHEN 4 THEN 'IV PERIODOS'
				ELSE ' > IV PERIODOS'
				END  									TiempoLicencia
			 FROM transaccional.estudiante_institucion TEI 
			 INNER JOIN maestro.persona_institucion MPI ON TEI.ID_PERSONA_INSTITUCION= MPI.ID_PERSONA_INSTITUCION
			 INNER JOIN maestro.persona MP ON MP.ID_PERSONA= MPI.ID_PERSONA
			 INNER JOIN sistema.enumerado E_CICLO on E_CICLO.ID_ENUMERADO= TEI.ID_SEMESTRE_ACADEMICO
			 INNER JOIN transaccional.carreras_por_institucion_detalle TCXID ON TCXID.ID_CARRERAS_POR_INSTITUCION_DETALLE= TEI.ID_CARRERAS_POR_INSTITUCION_DETALLE AND TCXID.ES_ACTIVO=1
			 INNER JOIN transaccional.carreras_por_institucion TCXI ON TCXI.ID_CARRERAS_POR_INSTITUCION= TCXID.ID_CARRERAS_POR_INSTITUCION AND TCXI.ES_ACTIVO=1
			 INNER JOIN db_auxiliar.dbo.UVW_CARRERA MC ON MC.ID_CARRERA= TCXI.ID_CARRERA --AND MC.ESTADO=1		--reemplazoPorVista
			 INNER JOIN maestro.sede_institucion MSI ON MSI.ID_SEDE_INSTITUCION= TCXID.ID_SEDE_INSTITUCION AND MSI.ES_ACTIVO=1
			 INNER JOIN transaccional.plan_estudio pe ON pe.ID_PLAN_ESTUDIO = TEI.ID_PLAN_ESTUDIO AND pe.ES_ACTIVO=1
			 INNER JOIN sistema.enumerado ti ON ti.ID_ENUMERADO = pe.ID_TIPO_ITINERARIO
			LEFT JOIN transaccional.reserva_matricula TRM ON TEI.ID_ESTUDIANTE_INSTITUCION = TRM.ID_ESTUDIANTE_INSTITUCION AND TRM.ES_ACTIVO=1			
			LEFT JOIN transaccional.licencia_estudiante TLE ON TEI.ID_ESTUDIANTE_INSTITUCION= TLE.ID_ESTUDIANTE_INSTITUCION AND TLE.ES_ACTIVO=1
			LEFT JOIN transaccional.reingreso_estudiante ri_r ON ri_r.ID_RESERVA_MATRICULA = TRM.ID_RESERVA_MATRICULA AND ri_r.ES_ACTIVO=1
			LEFT JOIN transaccional.reingreso_estudiante ri_l ON ri_l.ID_LICENCIA_ESTUDIANTE = TLE.ID_LICENCIA_ESTUDIANTE AND ri_l.ES_ACTIVO=1
			WHERE TEI.ES_ACTIVO=1 AND -- (TRM.ID_RESERVA_MATRICULA= @ID_ULT_RESERVA_MATRICULA OR TLE.ID_LICENCIA_ESTUDIANTE= @ID_ULT_LICENCIA_ESTUDIANTE )
			TEI.ID_PERSONA_INSTITUCION = @ID_PERSONA_INSTITUCION and ri_r.ID_REINGRESO_ESTUDIANTE is NULL
			and ri_l.ID_REINGRESO_ESTUDIANTE is null AND
			(TRM.ID_ESTUDIANTE_INSTITUCION = TEI.ID_ESTUDIANTE_INSTITUCION OR TLE.ID_ESTUDIANTE_INSTITUCION = TEI.ID_ESTUDIANTE_INSTITUCION)
END	


/**********************************************************************************************************
AUTOR				:	Juan Tovar
FECHA DE CREACION	:	20/06/2019
LLAMADO POR			:
DESCRIPCION			:	Obtiene el registro del estudiante de una institución 
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
--  TEST:			
/*

*/
--**********************************************************************************************************/
GO


