CREATE PROCEDURE [dbo].[USP_MATRICULA_SEL_TIPO_TRASLADO]
(
	@ID_INSTITUTO_ORIGEN INT,
	@ID_INSTITUTO_DESTINO INT
	
)
AS
BEGIN
DECLARE @ID_TIPO_TRASLADO INT

IF @ID_INSTITUTO_ORIGEN = @ID_INSTITUTO_DESTINO
 
	SET @ID_TIPO_TRASLADO=1;
	
ELSE

    SET @ID_TIPO_TRASLADO=2;

END

		SELECT 
		ID_ENUMERADO      			IdTipoTraslado,
		VALOR_ENUMERADO             TipoTraslado 

		FROM sistema.enumerado enu 
		WHERE ID_TIPO_ENUMERADO=45 AND CODIGO_ENUMERADO=@ID_TIPO_TRASLADO
GO


