/**********************************************************************************************************
AUTOR				:	Mayra Alva
FECHA DE CREACION	:	20/06/2019
LLAMADO POR			:
DESCRIPCION			:	Obtiene los datos de la cabecera que se muestran en el reporte de nómina de matricula
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
--1.0		29/01/2020		MALVA			SE REEMPLAZÓ @ID_TIPO_ITINERARIO POR @ID_PLAN_ESTUDIO
--1.1		16/06/2020		MALVA			INTEGRACIÓN DE CAMBIOS REALIZADOS POR CONSULTORES DRE.
--  TEST:			
/*
	EXEC USP_MATRICULA_RPT_NOMINA_MATRICULA 4221,1101,6043,2255,2898,10091,113
*/
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_MATRICULA_RPT_NOMINA_MATRICULA]
(	
	
	@ID_SEDE_INSTITUCION	INT,
	@ID_CARRERA				INT,
	@ID_PLAN_ESTUDIO		INT,
	@ID_PERIODO_ACADEMICO	INT,
	@ID_TURNO_INSTITUCION	INT,
	@ID_SECCION				INT,
	@ID_SEMESTRE_ACADEMICO	INT,
	@ID_PROGRAMACION_MATRICULA INT

	--DECLARE @ID_SEDE_INSTITUCION	INT=60
	--DECLARE @ID_CARRERA				INT=1311
	--DECLARE @ID_PLAN_ESTUDIO		INT=515
	--DECLARE @ID_PERIODO_ACADEMICO	INT=3637
	--DECLARE @ID_TURNO_INSTITUCION	INT=66
	--DECLARE @ID_SECCION				INT=105
	--DECLARE @ID_SEMESTRE_ACADEMICO	INT=112
	--DECLARE @ID_PROGRAMACION_MATRICULA INT=3921
)
AS
BEGIN
DECLARE @MATRICULA_CERRADA VARCHAR(30) = '';
	--SELECT  
	--		MI.DRE_GRE ,
	--		UBIGEO.DEPARTAMENTO_UBIGEO,
	--		UBIGEO.PROVINCIA_UBIGEO,
	--		UBIGEO.DISTRITO_UBIGEO,
	--		MI.CENTRO_POBLADO,
	--		MI.NOMBRE_INSTITUCION AS NOMBRE_INSTITUTO,
	--		MI.DIRECCION AS DIRECCION_IE_PRINCIPAL,
	--		SE.DIRECCION_SEDE,
	--		CASE WHEN SE.NOMBRE_SEDE= NOMBRE_INSTITUCION THEN 'PRINCIPAL' ELSE SE.NOMBRE_SEDE END NOMBRE_SEDE,
	--		MI.CODIGO_MODULAR AS CODIGO_MODULAR_IE,
	--		E.VALOR_ENUMERADO TIPO_GESTION,
	--		'' AS TIPO_RESOLUCION_AUTORIZACION, 
	--		'' AS NRO_RESOLUCION_AUTORIZACION,
	--		'' AS FECHA_RESOLUCION_AUTORIZACION, 
	--		'' AS TIPO_RESOLUCION_REVALIDACION,
	--		'' AS NRO_RESOLUCION_REVALIDACION,
	--		'' AS FECHA_RESOLUCION_REVALIDACION	,
	--		--CAST(0 AS BIT) MATRICULA_CERRADA
	--		-- @MATRICULA_CERRADA as MATRICULA_CERRADA,
	--		CASE @MATRICULA_CERRADA 
	--				WHEN 1 THEN 'true'
	--				WHEN 0 THEN 'false'
	--				END 									AS MATRICULA_CERRADA


	--		INTO #Encabezado
	--FROM 
	--		db_auxiliar.dbo.UVW_INSTITUCION MI
	--		INNER JOIN db_auxiliar.dbo.UVW_UBIGEO UBIGEO ON UBIGEO.CODIGO_UBIGEO= MI.CODIGO_DISTRITO
	--		INNER JOIN maestro.sede_institucion SE ON SE.ID_INSTITUCION= MI.ID_INSTITUCION
	--		INNER JOIN sistema.enumerado E ON E.ID_ENUMERADO=MI.TIPO_GESTION
	--WHERE	SE.ID_SEDE_INSTITUCION=@ID_SEDE_INSTITUCION
		
	DECLARE @NOMBRE_CARRERA VARCHAR(250), @NOMBRE_NIVEL_FORMACION  VARCHAR(50), @NOMBRE_PERIODO_ACADEMICO VARCHAR(50), @TURNO VARCHAR(30), @PLAN_ESTUDIOS VARCHAR(250),
	@SECCION VARCHAR(10), @SEMESTRE_ACADEMICO VARCHAR(50), @PERIODO_LECTIVO VARCHAR(50), @PERIODO_LECTIVO_INSTITUTO INT, @FECHA_FIN DATETIME, @FECHA_ACTUAL VARCHAR(20), @FECHA_FIN_OFICIAL VARCHAR(20)

	SELECT @NOMBRE_CARRERA=UPPER(C.NOMBRE_CARRERA),
		@NOMBRE_NIVEL_FORMACION=NF.NOMBRE_NIVEL_FORMACION		
	FROM db_auxiliar.dbo.UVW_CARRERA C
		INNER JOIN maestro.nivel_formacion NF on C.TIPO_NIVEL_FORMACION = NF.CODIGO_TIPO --C.ID_NIVEL_FORMACION= NF.ID_NIVEL_FORMACION			--reemplazoPorVista
	WHERE C.ID_CARRERA=@ID_CARRERA

	SELECT @NOMBRE_PERIODO_ACADEMICO = PA.NOMBRE_PERIODO_ACADEMICO	
	FROM transaccional.periodo_academico PA 
	WHERE PA.ID_PERIODO_ACADEMICO=@ID_PERIODO_ACADEMICO
	
	SELECT @TURNO= E.VALOR_ENUMERADO
	FROM maestro.turnos_por_institucion TXI
	INNER JOIN maestro.turno_equivalencia TE ON TXI.ID_TURNO_EQUIVALENCIA= TE.ID_TURNO_EQUIVALENCIA AND TXI.ID_TURNOS_POR_INSTITUCION=@ID_TURNO_INSTITUCION
	INNER JOIN sistema.enumerado  E ON E.ID_ENUMERADO= TE.ID_TURNO	
		
	SELECT @PLAN_ESTUDIOS= ( pe.NOMBRE_PLAN_ESTUDIOS + ' (' + ti.VALOR_ENUMERADO + ')' )
	FROM transaccional.plan_estudio pe
	INNER JOIN sistema.enumerado ti ON pe.ID_TIPO_ITINERARIO = ti.ID_ENUMERADO
	where pe.ID_PLAN_ESTUDIO = @ID_PLAN_ESTUDIO

	SELECT @SECCION= E.VALOR_ENUMERADO
	FROM sistema.enumerado E
	WHERE ID_ENUMERADO=@ID_SECCION

	SELECT @SEMESTRE_ACADEMICO= E.VALOR_ENUMERADO
	FROM sistema.enumerado E
	WHERE ID_ENUMERADO=@ID_SEMESTRE_ACADEMICO
	
	SELECT @PERIODO_LECTIVO = ( SELECT PL.CODIGO_PERIODO_LECTIVO FROM 
	transaccional.periodo_academico PA
	INNER JOIN transaccional.periodos_lectivos_por_institucion PLXI ON PA.ID_PERIODOS_LECTIVOS_POR_INSTITUCION= PLXI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION AND PLXI.ES_ACTIVO=1 AND PA.ES_ACTIVO=1
	INNER JOIN maestro.periodo_lectivo PL ON PL.ID_PERIODO_LECTIVO= PLXI.ID_PERIODO_LECTIVO
	WHERE PA.ID_PERIODO_ACADEMICO = @ID_PERIODO_ACADEMICO)

	--UPDATE #Encabezado
	--SET MATRICULA_CERRADA= PM.CERRADO
	--FROM transaccional.programacion_matricula PM
	--WHERE ID_PROGRAMACION_MATRICULA=@ID_PROGRAMACION_MATRICULA

	SET @PERIODO_LECTIVO_INSTITUTO = (SELECT TOP 1 ID_PERIODOS_LECTIVOS_POR_INSTITUCION FROM transaccional.periodo_academico WHERE ID_PERIODO_ACADEMICO = @ID_PERIODO_ACADEMICO AND ES_ACTIVO = 1)

	SET @FECHA_FIN = (SELECT TOP 1 FECHA_FIN FROM transaccional.programacion_matricula WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @PERIODO_LECTIVO_INSTITUTO AND ES_ACTIVO = 1 ORDER BY ID_PROGRAMACION_MATRICULA DESC)

	--IF (CONVERT(DATE,@FECHA_FIN >= CONVERT( DATE, getdate()) 
	SET @FECHA_ACTUAL = (select convert(varchar, getdate(), 5))
	SET @FECHA_FIN_OFICIAL = (SELECT CONVERT(VARCHAR, @FECHA_FIN, 5))
	IF @FECHA_FIN_OFICIAL >= (@FECHA_ACTUAL)
	BEGIN
	SET @MATRICULA_CERRADA = 0
		
		--UPDATE #Encabezado
		--SET MATRICULA_CERRADA= 1
		--FROM transaccional.programacion_matricula PM
		--WHERE ID_PROGRAMACION_MATRICULA=@ID_PROGRAMACION_MATRICULA
	END
	ELSE
	BEGIN
		SET @MATRICULA_CERRADA = 1
		--UPDATE #Encabezado
		--SET MATRICULA_CERRADA= 0
		--FROM transaccional.programacion_matricula PM
		--WHERE ID_PROGRAMACION_MATRICULA=@ID_PROGRAMACION_MATRICULA

	END 
	
	SELECT  
			MI.DRE_GRE ,
			UBIGEO.DEPARTAMENTO_UBIGEO,
			UBIGEO.PROVINCIA_UBIGEO,
			UBIGEO.DISTRITO_UBIGEO,
			MI.CENTRO_POBLADO,
			MI.NOMBRE_INSTITUCION AS NOMBRE_INSTITUTO,
			MI.DIRECCION AS DIRECCION_IE_PRINCIPAL,
			SE.DIRECCION_SEDE,
			CASE WHEN SE.NOMBRE_SEDE= NOMBRE_INSTITUCION THEN 'PRINCIPAL' ELSE SE.NOMBRE_SEDE END NOMBRE_SEDE,
			MI.CODIGO_MODULAR AS CODIGO_MODULAR_IE,
			E.VALOR_ENUMERADO TIPO_GESTION,
			'' AS TIPO_RESOLUCION_AUTORIZACION, 
			'' AS NRO_RESOLUCION_AUTORIZACION,
			'' AS FECHA_RESOLUCION_AUTORIZACION, 
			'' AS TIPO_RESOLUCION_REVALIDACION,
			'' AS NRO_RESOLUCION_REVALIDACION,
			'' AS FECHA_RESOLUCION_REVALIDACION	,
			--CAST(0 AS BIT) MATRICULA_CERRADA
			-- @MATRICULA_CERRADA as MATRICULA_CERRADA,
			CASE @MATRICULA_CERRADA 
					WHEN 1 THEN 'true'
					WHEN 0 THEN 'false'
					END 									AS MATRICULA_CERRADA


			INTO #Encabezado
	FROM 
			db_auxiliar.dbo.UVW_INSTITUCION MI
			INNER JOIN db_auxiliar.dbo.UVW_UBIGEO UBIGEO ON UBIGEO.CODIGO_UBIGEO= MI.CODIGO_DISTRITO
			INNER JOIN maestro.sede_institucion SE ON SE.ID_INSTITUCION= MI.ID_INSTITUCION
			INNER JOIN sistema.enumerado E ON E.ID_ENUMERADO=MI.TIPO_GESTION
	WHERE	SE.ID_SEDE_INSTITUCION=@ID_SEDE_INSTITUCION


	SELECT *, @NOMBRE_CARRERA NOMBRE_CARRERA, @NOMBRE_NIVEL_FORMACION NOMBRE_NIVEL_FORMACION, @NOMBRE_PERIODO_ACADEMICO NOMBRE_PERIODO_ACADEMICO, @TURNO TURNO,
	@PLAN_ESTUDIOS PLAN_ESTUDIOS, @SECCION SECCION, @SEMESTRE_ACADEMICO SEMESTRE_ACADEMICO, @PERIODO_LECTIVO PERIODO_LECTIVO
	 FROM #Encabezado

	DROP TABLE #Encabezado

	select @FECHA_FIN_OFICIAL
	select @MATRICULA_CERRADA
	SELECT @FECHA_ACTUAL

END


--**********************************************************************
--52. USP_MATRICULA_RPT_NOMINA_MATRICULA_DETALLE.sql
GO


