CREATE PROCEDURE [dbo].[USP_ADMISION_INS_PROCESO_ADMISION]
(
	@ID_PERIODO_LECTIVO_INSTITUCION	INT,
	@NOMBRE_PROCESO_ADMISION		VARCHAR(150),
	@FECHA_INICIO					DATE,
	@FECHA_FIN						DATE,
	@MODALIDADES					VARCHAR(16),
	@NOTA_MINIMA					DECIMAL(10,2),
	@USUARIO						VARCHAR(20)	
)AS
BEGIN
	DECLARE @RESULT INT
	IF EXISTS(SELECT TOP 1 * FROM transaccional.proceso_admision_periodo
			WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION AND ES_ACTIVO = 1)
		SET @RESULT = -180
	ELSE
	BEGIN
		BEGIN TRANSACTION T1
		BEGIN TRY
			INSERT INTO transaccional.proceso_admision_periodo(ID_PERIODOS_LECTIVOS_POR_INSTITUCION,NOMBRE_PROCESO_ADMISION,FECHA_INICIO,FECHA_FIN,MODALIDADES,ES_ACTIVO,ESTADO,USUARIO_CREACION,FECHA_CREACION)
			VALUES(@ID_PERIODO_LECTIVO_INSTITUCION,@NOMBRE_PROCESO_ADMISION,@FECHA_INICIO,@FECHA_FIN,@MODALIDADES,1,1,@USUARIO,GETDATE())

			SET @RESULT = @@IDENTITY

			INSERT INTO transaccional.modalidades_por_proceso_admision(ID_PROCESO_ADMISION_PERIODO,ID_MODALIDAD,NOTA_MINIMA,ES_ACTIVO,ESTADO,USUARIO_CREACION,FECHA_CREACION)
			SELECT @RESULT,SplitData,@NOTA_MINIMA,1,96,@USUARIO,GETDATE() FROM dbo.UFN_SPLIT(UPPER(@MODALIDADES), '|')
			WHERE SplitData <> 0			
		COMMIT TRANSACTION T1
			SET @RESULT = 1
		END TRY
		BEGIN CATCH
			IF @@ERROR<>0
			BEGIN
			   ROLLBACK TRANSACTION T1	   
			   SET @RESULT = -1
			END
		END CATCH			
	END
	SELECT @RESULT
END
GO


