/**********************************************************************************************************
AUTOR				:	Juan Tovar
FECHA DE CREACION	:	20/06/2019
LLAMADO POR			:
DESCRIPCION			:	Actualiza el estado del personal de una institución
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
1.0          12/11/2019     JTOVAR        SE ACTUALIZO EL STORE PARA QUE PERMITA AL MOMENTO DE ACTUALIZAR UN ROL, PUEDA REGISTRAR OTRO SECRETARIO ACADEMICO
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_MAESTROS_UPD_PERSONAL_INSTITUCION]
(
	--DECLARE @ID_PERSONA_INSTITUCION			INT= 1327
	--DECLARE @ID_PERSONAL_INSTITUCION		INT= 1171
	--DECLARE @ID_PERIODO_LECTIVO_INSTITUCION	INT= 895

	--DECLARE @ESTADO_CIVIL					INT= 33
	--DECLARE @PAIS_PERSONA					INT= 92330
	--DECLARE @UBIGEO_PERSONA					VARCHAR(6)= 140111
	--DECLARE @DIRECCION_PERSONA				VARCHAR(255)= 'PROLONG. IQUITOS 2241'
	--DECLARE @TELEFONO						VARCHAR(15)= '4889699'
	--DECLARE @CELULAR						VARCHAR(15)= '985887454'
	--DECLARE @CELULAR2						VARCHAR(15)= ''
	--DECLARE @CORREO							VARCHAR(100)= 'lespinozav@minedu.gob.pe'
	----@ID_TIPO_DISCAPACIDAD			INT,
	--DECLARE @ID_GRADO_PROFESIONAL			INT= 43
	--DECLARE @TITULO_PROFESIONAL				VARCHAR(150)= 'SISTEMAS'
	--DECLARE @ID_CARRERA_PROFESIONAL			INT= 3
	--DECLARE @INSTITUCION_PROFESIONAL		VARCHAR(150)= 'UNI'
	--DECLARE @ANIO_INICIO					INT= 1999
	--DECLARE @ANIO_FIN						INT= 2005

	--DECLARE @CONDICION_LABORAL				INT= 50
	--DECLARE @CARGO_PERSONA					INT= 0
	--DECLARE @ID_TIPO_PERSONAL				INT= 29
	--DECLARE @ID_ROL							INT= 48
	--DECLARE @ID_PERMISO_PASSPORT			INT= 0
	--DECLARE @USUARIO						VARCHAR(20)= '42122536'
	

	@ID_PERSONA_INSTITUCION			INT,
	@ID_PERSONAL_INSTITUCION		INT,
	@ID_PERIODO_LECTIVO_INSTITUCION	INT,

	@ESTADO_CIVIL					INT,
	@PAIS_PERSONA					INT,
	@UBIGEO_PERSONA					VARCHAR(6),
	@DIRECCION_PERSONA				VARCHAR(255),
	@TELEFONO						VARCHAR(15),
	@CELULAR						VARCHAR(15),
	@CELULAR2						VARCHAR(15),
	@CORREO							VARCHAR(100),

	@ID_GRADO_PROFESIONAL			INT,
	@TITULO_PROFESIONAL				VARCHAR(150),
	@ID_CARRERA_PROFESIONAL			INT,
	@INSTITUCION_PROFESIONAL		VARCHAR(150),
	@ANIO_INICIO					INT,
	@ANIO_FIN						INT,

	@CONDICION_LABORAL				INT,
	@CARGO_PERSONA					INT,
	@ID_TIPO_PERSONAL				INT,
	@ID_ROL							INT,
	@ID_PERMISO_PASSPORT			INT,
	@ID_ROL_USUARIO					INT,
	@USUARIO						VARCHAR(20)
	
)
AS
BEGIN
	DECLARE @RESULT INT, @ID_ROL_DOCENTE INT, @ID_ROL_DIRECTOR INT, @ID_ROL_SECRETARIO INT, @ESTADO_CIVIL_UPDATE INT, @ID_TIPO_DOCUMENTO INT, @NRO_DOCUMENTO VARCHAR(16)
	SET @ID_ROL_DOCENTE = 49
	SET @ID_ROL_DIRECTOR=47
	SET @ID_ROL_SECRETARIO=48
	SET @NRO_DOCUMENTO = (SELECT MP.NUMERO_DOCUMENTO_PERSONA FROM maestro.persona_institucion MPI 
							INNER JOIN maestro.persona MP ON MPI.ID_PERSONA = MP.ID_PERSONA AND MP.ESTADO=1 AND MPI.ESTADO=1
							WHERE MPI.ID_PERSONA_INSTITUCION= @ID_PERSONA_INSTITUCION)


SET @ID_TIPO_DOCUMENTO = (SELECT TOP 1 ID_TIPO_DOCUMENTO FROM maestro.persona p INNER JOIN maestro.persona_institucion pi ON pi.ID_PERSONA = p.ID_PERSONA AND pi.ESTADO = 1 AND p.ESTADO = 1 WHERE ID_PERSONA_INSTITUCION = @ID_PERSONA_INSTITUCION)

--En caso el tipo de documento sea DNI no debe permitirse modificar el valor ya que los datos se obtienen de la validación de RENIEC
IF @ID_TIPO_DOCUMENTO = 26
BEGIN
	SET @ESTADO_CIVIL_UPDATE = (SELECT ESTADO_CIVIL FROM maestro.persona_institucion WHERE ID_PERSONA_INSTITUCION = @ID_PERSONA_INSTITUCION)
END
ELSE
BEGIN
	SET @ESTADO_CIVIL_UPDATE = @ESTADO_CIVIL
END

IF @ID_ROL = @ID_ROL_USUARIO  OR (@NRO_DOCUMENTO= @USUARIO AND @ID_ROL_USUARIO = @ID_ROL_DIRECTOR)
	SET @RESULT = -287
ELSE IF EXISTS(SELECT TOP 1 ID_ROL FROM maestro.personal_institucion
WHERE ES_ACTIVO=1 AND ESTADO=1 AND ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION AND ID_ROL=@ID_ROL AND ID_ROL =@ID_ROL_DIRECTOR 
and ID_PERSONAL_INSTITUCION<>@ID_PERSONAL_INSTITUCION
)
	
	SET @RESULT = -114	

ELSE
BEGIN 
BEGIN TRANSACTION T1
BEGIN TRY
    UPDATE maestro.persona_institucion
			SET ESTADO_CIVIL = @ESTADO_CIVIL_UPDATE,
				PAIS_PERSONA = @PAIS_PERSONA,
				UBIGEO_PERSONA = @UBIGEO_PERSONA,
				DIRECCION_PERSONA = @DIRECCION_PERSONA,
				TELEFONO = @TELEFONO,
				CELULAR = @CELULAR,
				CELULAR2 = @CELULAR2,
				CORREO = @CORREO,
				ID_GRADO_PROFESIONAL = @ID_GRADO_PROFESIONAL,
				TITULO_PROFESIONAL = @TITULO_PROFESIONAL,
				ID_CARRERA_PROFESIONAL = @ID_CARRERA_PROFESIONAL,
				INSTITUCION_PROFESIONAL = @INSTITUCION_PROFESIONAL,
				ANIO_INICIO = @ANIO_INICIO,
				ANIO_FIN = @ANIO_FIN,
				ESTADO = 1,
				USUARIO_MODIFICACION = @USUARIO,
				FECHA_MODIFICACION = GETDATE()
			WHERE ID_PERSONA_INSTITUCION = @ID_PERSONA_INSTITUCION
		
				IF EXISTS(SELECT TOP 1 ID_PERSONAL_INSTITUCION FROM maestro.personal_institucion 
									WHERE ES_ACTIVO = 1 AND ID_PERSONA_INSTITUCION = @ID_PERSONA_INSTITUCION
									AND ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION
									AND ID_ROL = @ID_ROL AND ID_PERSONAL_INSTITUCION <> @ID_PERSONAL_INSTITUCION)
				BEGIN
					RAISERROR('ERROR DE INSERCION',-1,-1) WITH SETERROR
				END
				ELSE
					UPDATE maestro.personal_institucion
					SET CONDICION_LABORAL = @CONDICION_LABORAL,
						CARGO_PERSONA = @CARGO_PERSONA,
						ID_TIPO_PERSONAL = @ID_TIPO_PERSONAL,
						USUARIO_MODIFICACION = @USUARIO,
						ID_ROL = @ID_ROL,
						ID_PERMISO_PASSPORT= @ID_PERMISO_PASSPORT,
						FECHA_MODIFICACION = GETDATE()
					WHERE ID_PERSONAL_INSTITUCION = @ID_PERSONAL_INSTITUCION
			COMMIT TRANSACTION T1		
				SET @RESULT = 1
			END TRY
			BEGIN CATCH	
				IF @@ERROR <> 0
				BEGIN
					ROLLBACK TRANSACTION T1	   
					SET @RESULT = -1
				END
			END CATCH
	
END
SELECT @RESULT
END
GO


