CREATE PROCEDURE [dbo].[USP_ARCHIVO_UPD_CARGA]
(
	@ID_CARGA INT,	
	@ID_SEDE_INSTITUCION INT , 
	@ID_PERIODO_ACADEMICO INT,
	@ID_CARRERA INT,
	@ID_TIPO_ITINERARIO INT, 
	@ID_SEMESTRE_ACADEMICO INT ,
	@ID_TURNO_INSTITUCION INT ,
	@ID_SECCION INT , 
	@ID_PROGRAMACION_MATRICULA INT
)
AS
DECLARE 
	@RESULT INT =0

BEGIN
	
	DECLARE @ID_INSTITUCION INT, 
			@ID_CARRERA_INSTITUCION INT 

	SET @ID_INSTITUCION =  (SELECT ID_INSTITUCION FROM maestro.sede_institucion WHERE ID_SEDE_INSTITUCION= @ID_SEDE_INSTITUCION)
	SET @ID_CARRERA_INSTITUCION=  ( SELECT ID_CARRERAS_POR_INSTITUCION FROM transaccional.carreras_por_institucion 
	WHERE ID_CARRERA= @ID_CARRERA AND ID_INSTITUCION= @ID_INSTITUCION AND ID_TIPO_ITINERARIO=@ID_TIPO_ITINERARIO)

	UPDATE 
		archivo.carga
	SET
		ID_SEDE_INSTITUCION = @ID_SEDE_INSTITUCION,
		ID_PERIODO_ACADEMICO = @ID_PERIODO_ACADEMICO,
		ID_CARRERAS_POR_INSTITUCION = @ID_CARRERA_INSTITUCION, 		
		ID_SEMESTRE_ACADEMICO = @ID_SEMESTRE_ACADEMICO, 
		ID_TURNOS_POR_INSTITUCION = @ID_TURNO_INSTITUCION,
		ID_SECCION = @ID_SECCION,
		ID_PROGRAMACION_MATRICULA = @ID_PROGRAMACION_MATRICULA, 	
		FECHA_CARGA= GETDATE()
	WHERE 
		ID_CARGA= @ID_CARGA
	
	SET @RESULT = @@rowcount
END
SELECT (@RESULT)
GO


