CREATE PROCEDURE [dbo].[USP_PLANIFICACION_INS_SESION_X_PROGRAMACION]
(  
@ID_PROGRAMACION_CLASE INT, 
@ID_AULA INT,
@ID_DIA INT,
@ID_TIPO_CLASE INT,
@HORA_INICIO VARCHAR(5),
@HORA_FIN VARCHAR(5),
@ID_DOCENTE_CLASE INT=0,
@ES_ACTIVO BIT=1,  
@ESTADO      smallint=1,  --118?
@USUARIO VARCHAR(20)

--DECLARE @ID_PROGRAMACION_CLASE INT=84483
--DECLARE @ID_AULA INT=12948
--DECLARE @ID_DIA INT=123
--DECLARE @ID_TIPO_CLASE INT=125
--DECLARE @HORA_INICIO VARCHAR(5)='06:00'
--DECLARE @HORA_FIN VARCHAR(5)='06:30'
--DECLARE @ID_DOCENTE_CLASE INT=10199
--DECLARE @ES_ACTIVO BIT=1  
--DECLARE @ESTADO      smallint=1  --118?
--DECLARE @USUARIO VARCHAR(20)


)  
AS 

DECLARE @RESULT INT, @ID_PERSONAL_INSTITUCION INT, @ID_PERSONAL_INSTITUCION_SECUNDARIO INT
BEGIN  

	SET @ID_PERSONAL_INSTITUCION = (SELECT TOP 1 ID_PERSONAL_INSTITUCION FROM transaccional.programacion_clase WHERE ID_PROGRAMACION_CLASE = @ID_PROGRAMACION_CLASE AND ES_ACTIVO=1)
	SET @ID_PERSONAL_INSTITUCION_SECUNDARIO = (SELECT TOP 1 ID_PERSONAL_INSTITUCION_SECUNDARIO FROM transaccional.programacion_clase WHERE ID_PROGRAMACION_CLASE = @ID_PROGRAMACION_CLASE AND ES_ACTIVO=1)

	INSERT INTO transaccional.sesion_programacion_clase(
						ID_PROGRAMACION_CLASE,
						ID_AULA,
						DIA,
						HORA_INICIO,
						HORA_FIN,
						ES_ACTIVO,
						ESTADO,
						USUARIO_CREACION,
						FECHA_CREACION,					
						ID_TIPO_CLASE,
						ID_PERSONAL_INSTITUCION,
						ID_DOCENTE_CLASE
						) 
			VALUES (	@ID_PROGRAMACION_CLASE, 
						@ID_AULA,
						@ID_DIA,
						@HORA_INICIO,
						@HORA_FIN,
						@ES_ACTIVO,
						@ESTADO,
						@USUARIO,
						GETDATE(),
						@ID_TIPO_CLASE,
						(CASE @ID_DOCENTE_CLASE WHEN '390' THEN @ID_PERSONAL_INSTITUCION ELSE @ID_PERSONAL_INSTITUCION_SECUNDARIO END),
						@ID_DOCENTE_CLASE
					)
	
	SET @RESULT = 1
END  
SELECT @RESULT
GO


