CREATE PROCEDURE [dbo].[USP_ARCHIVO_INS_CARGA_DETALLE]
(
	@ID_CARGA INT,
	--@ID_SEDE_INSTITUCION INT , 
	--@ID_PERIODO_ACADEMICO INT,
	--@ID_CARRERA INT,
	--@ID_TIPO_ITINERARIO INT, 
	--@ID_SEMESTRE_ACADEMICO INT ,
	--@ID_TURNO_INSTITUCION INT ,
	--@ID_SECCION INT , 
	--@ID_PROGRAMACION_MATRICULA INT, --?	
	@ID_TIPO_DOCUMENTO INT, --DNI, C.E., PASAPORTE
	@NUMERO_DOCUMENTO VARCHAR(16),
	@APELLIDO_PATERNO VARCHAR(50),
	@APELLIDO_MATERNO VARCHAR(50),
	@NOMBRES VARCHAR(50),
	@ID_SEXO	INT, 
	@FECHA_NACIMIENTO VARCHAR(10), 
	@ES_DISCAPACITADO BIT, 
	@ID_TIPO_DISCAPACIDAD INT, 
	@ASIGNACIONES_UNIDADES_DIDACTICAS NVARCHAR(MAX), --'4379:20|4380:15|4381:18|4382:17|4383:14|4384:16' OR '4379|4380|4382'
	
	@UBIGEO_NACIMIENTO VARCHAR(6),  
	@UBIGEO_RESIDENCIA VARCHAR(6),  
	@ID_ESTADO_CIVIL INT, 
	@ID_PAIS_NACIMIENTO INT, 
	@ID_PAIS_RESIDENCIA INT, 
	@DIRECCION_RESIDENCIA VARCHAR (255), 
	@ES_CORRECTO BIT,
	@ES_BORRADO BIT,
	@USUARIO VARCHAR(20)

)
AS
DECLARE @RESULT INT = 0
BEGIN
IF NOT EXISTS(SELECT TOP 1 ID_DET_ARCHIVO FROM archivo.carga_detalle WHERE ID_CARGA=@ID_CARGA AND ID_TIPO_DOCUMENTO= @ID_TIPO_DOCUMENTO AND NUMERO_DOCUMENTO=@NUMERO_DOCUMENTO AND ES_BORRADO=0)
BEGIN
	INSERT INTO archivo.carga_detalle
	(ID_CARGA,
	 --ID_SEDE_INSTITUCION,
	 --ID_PERIODO_ACADEMICO,
	 --ID_CARRERA,
	 --ID_TIPO_ITINERARIO,
	 --ID_SEMESTRE_ACADEMICO,
	 --ID_TURNO_INSTITUCION,
	 --ID_SECCION,
	 --ID_PROGRAMACION_MATRICULA,
	 ID_TIPO_DOCUMENTO,
	 NUMERO_DOCUMENTO, 
	 APELLIDO_PATERNO, 
	 APELLIDO_MATERNO, 
	 NOMBRES, 
	 ID_SEXO, 
	 FECHA_NACIMIENTO, 
	 ES_DISCAPACITADO, 
	 ID_TIPO_DISCAPACIDAD, 
	 UNIDADES_DIDACTICAS, 
	 UBIGEO_NACIMIENTO, 
	 UBIGEO_RESIDENCIA, 
	 ID_ESTADO_CIVIL, 
	 ID_PAIS_NACIMIENTO, 
	 ID_PAIS_RESIDENCIA, 
	 DIRECCION_RESIDENCIA, 
	 ES_CORRECTO, 
	 ES_BORRADO, 
	 FECHA_CREACION, 
	 USUARIO_CREACION )
	VALUES 
	( @ID_CARGA,
	  --@ID_SEDE_INSTITUCION,
	  --@ID_PERIODO_ACADEMICO,
	  --@ID_CARRERA,
	  --@ID_TIPO_ITINERARIO,
	  --@ID_SEMESTRE_ACADEMICO,
	  --@ID_TURNO_INSTITUCION,
	  --@ID_SECCION,
	  --@ID_PROGRAMACION_MATRICULA,
	  @ID_TIPO_DOCUMENTO,
	  @NUMERO_DOCUMENTO, 
	  @APELLIDO_PATERNO, 
	  @APELLIDO_MATERNO, 
	  @NOMBRES, 
	  @ID_SEXO, 
	  (CASE WHEN @FECHA_NACIMIENTO = '' THEN NULL ELSE @FECHA_NACIMIENTO END), 
	  @ES_DISCAPACITADO, 
	  @ID_TIPO_DISCAPACIDAD, 
	  @ASIGNACIONES_UNIDADES_DIDACTICAS , 
	  @UBIGEO_NACIMIENTO, 
	  @UBIGEO_RESIDENCIA, 
	  @ID_ESTADO_CIVIL, 
	  @ID_PAIS_NACIMIENTO, 
	  @ID_PAIS_RESIDENCIA, 
	  @DIRECCION_RESIDENCIA, 
	  @ES_CORRECTO, 
	  @ES_BORRADO, 
	  GETDATE(), 
	  @USUARIO
	)
	SET @RESULT = CONVERT(INT,@@IDENTITY)
	END
END
RETURN (@RESULT)
GO


