--/*************************************************************************************************************************************************
--AUTOR				:	Juan Tovar
--FECHA DE CREACION	:	20/06/2019
--LLAMADO POR			:
--DESCRIPCION			:	Listado de metas por programa de estudios.
--REVISIONES			:
-------------------------------------------------------------------------------------------------------------
--VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-------------------------------------------------------------------------------------------------------------
--/*
--	1.0			21/11/2019		MALVA			MODIFICACIÓN PARA QUE FILTRE EL PERIODO LECTIVO INSTITUCIÓN PARA LA SUBCONSULTA DE RESOLUCIONES.
--- 1.1			21/01/2020		MALVA			MODIFICACIÓN DE ACUERDO A CAMBIOS EN LA INTERFACE DE REGISTRO DE METAS. SE OBTIENE COLUMNA IdPlanEstudio.										
--*/
--  TEST:		USP_ADMISION_SEL_META_CARRERA_INSTITUCION_PAGINADO 2027,565,1,3000
--**************************************************************************************************************************************************/
CREATE  PROCEDURE [dbo].[USP_ADMISION_SEL_META_CARRERA_INSTITUCION_PAGINADO](
	@ID_INSTITUCION INT,
	@ID_PERIODO_LECTIVO_INSTITUCION INT,
	@Pagina					int = 1,
	@Registros				int = 10
)
AS
BEGIN
SET NOCOUNT ON;
DECLARE
	@ID_TIPO_RESOLUCION_ANUAL INT =21,
	@ID_TIPO_RESOLUCION_AMPL INT =22,
	@ANIO INT, 
	@ID_PERIODO_LECTIVO_INSTITUCION_UNO INT,
	@ESTADO_APERTURADO INT =7,
	@ES_PERIODO_LECTIVO_INSTITUCION_UNO BIT =0,

	
	@ID_TIPO_GESTION_PUBLICA INT =10061, 
	@ID_TIPO_GESTION_PRIVADA INT =10062,

	@ID_TIPO_GESTION_IE INT
	
	
	SET @ID_TIPO_GESTION_IE = (SELECT mi.TIPO_GESTION FROM db_auxiliar.dbo.UVW_INSTITUCION mi WHERE mi.ID_INSTITUCION=@ID_INSTITUCION)
	SET @ANIO = (SELECT mpl.ANIO FROM transaccional.periodos_lectivos_por_institucion tplxi
				INNER JOIN maestro.periodo_lectivo mpl on tplxi.ID_PERIODO_LECTIVO= mpl.ID_PERIODO_LECTIVO
				WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION
				AND tplxi.ES_ACTIVO=1)
		
	SET @ID_PERIODO_LECTIVO_INSTITUCION_UNO = (	SELECT top 1 
												tplxi.ID_PERIODOS_LECTIVOS_POR_INSTITUCION 
												FROM transaccional.periodos_lectivos_por_institucion tplxi 
												INNER JOIN maestro.periodo_lectivo mpl on tplxi.ID_PERIODO_LECTIVO= mpl.ID_PERIODO_LECTIVO
												WHERE ID_INSTITUCION=@ID_INSTITUCION 
												AND ES_ACTIVO=1 AND mpl.ANIO=@ANIO
												AND tplxi.ESTADO =@ESTADO_APERTURADO
												ORDER BY 1 ASC )
	IF 		@ID_PERIODO_LECTIVO_INSTITUCION_UNO	= @ID_PERIODO_LECTIVO_INSTITUCION		
			set @ES_PERIODO_LECTIVO_INSTITUCION_UNO=1	

	DECLARE @desde INT , @hasta INT;
	SET @desde = ( @Pagina - 1 ) * @Registros;
	SET @hasta = ( @Pagina * @Registros ) + 1;  

	WITH    tempPaginado AS
	(
SELECT	
		mci.ID_META_CARRERA_INSTITUCION													IdMetaCarreraInstitucionAnual, 
		ISNULL(METAS_AMPLIACION.ID_META_CARRERA_INSTITUCION, 0)							IdMetaCarreraInstitucionAmpliacion, 
		pe.ID_CARRERAS_POR_INSTITUCION													IdCarreraInstitucion, 
		pe.ID_TIPO_ITINERARIO															IdTipoItinerario, 
		cxi.ID_CARRERA																	IdCarrera,
		vc.NOMBRE_CARRERA																NombreCarrera,
		mci.META																		MetaAnual,
		CASE 
		WHEN  @ID_TIPO_GESTION_IE =@ID_TIPO_GESTION_PUBLICA 
			THEN	mci.META  -  ISNULL(SUB_CONSULTA_METAS_ALCANZADAS_ACUM_ANT.METAS_ALCANZADAS_ACUM_ANT,0)
		WHEN ( @ID_TIPO_GESTION_IE =@ID_TIPO_GESTION_PRIVADA AND @ES_PERIODO_LECTIVO_INSTITUCION_UNO=0)
			THEN	mci.META -	 ISNULL(SUB_CONSULTA_METAS_SEDES_ACUM_ANT.METAS_SEDES,0)
		WHEN (@ID_TIPO_GESTION_IE =@ID_TIPO_GESTION_PRIVADA AND @ES_PERIODO_LECTIVO_INSTITUCION_UNO=1)
			THEN mci.META
		END																				MetaDisponibleAnual,		
		ISNULL(METAS_AMPLIACION.META, 0)												MetaAmpliacion,
		mci.META	-ISNULL(SUB_CONSULTA_METAS_ALCANZADAS.METAS_ALCANZADAS,0)	
				-ISNULL(SUB_CONSULTA_METAS_ALCANZADAS_ACUM_ANT.METAS_ALCANZADAS_ACUM_ANT,0) 
				+ISNULL(METAS_AMPLIACION.META,0)										MetaDisponibleTotal, 
				ISNULL(SUB_CONSULTA_METAS_SEDES.METAS_SEDES,0)							MetaLocal,
		ISNULL(SUB_CONSULTA_METAS_ALCANZADAS.METAS_ALCANZADAS,0)						MetaAlcanzada, 
		ISNULL(SUB_CONSULTA_METAS_ALCANZADAS_ACUM_ANT.METAS_ALCANZADAS_ACUM_ANT,0)		MetaAlcanzadaAcumAnt, 
		txi.ID_TURNOS_POR_INSTITUCION													IdTurno,
		t.VALOR_ENUMERADO																Turno,
		pe.NOMBRE_PLAN_ESTUDIOS															NombrePlan,
		pe.NOMBRE_PLAN_ESTUDIOS	 + ' (' + ti.VALOR_ENUMERADO + ')'						PlanEstudios, 
		@ES_PERIODO_LECTIVO_INSTITUCION_UNO												EsPeriodoInicial,
		pe.ID_PLAN_ESTUDIO																IdPlanEstudio,
		ROW_NUMBER() OVER ( ORDER BY vc.NOMBRE_CARRERA, pe.NOMBRE_PLAN_ESTUDIOS, te.ID_TURNO	) AS Row,
	Total = count(1) OVER ()
FROM 
		transaccional.plan_estudio pe
		INNER JOIN transaccional.meta_carrera_institucion mci ON mci.ID_PLAN_ESTUDIO = pe.ID_PLAN_ESTUDIO AND pe.ES_ACTIVO=1 AND mci.ES_ACTIVO=1
		INNER JOIN transaccional.resoluciones_por_periodo_lectivo_institucion rxpl ON mci.ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION = rxpl.ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION AND rxpl.ES_ACTIVO=1
		INNER JOIN maestro.resolucion r ON r.ID_RESOLUCION = rxpl.ID_RESOLUCION AND r.ES_ACTIVO=1 AND r.ESTADO=1
		INNER JOIN transaccional.periodos_lectivos_por_institucion plxi ON plxi.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = rxpl.ID_PERIODOS_LECTIVOS_POR_INSTITUCION AND plxi.ES_ACTIVO=1
		INNER JOIN transaccional.carreras_por_institucion cxi ON cxi.ID_CARRERAS_POR_INSTITUCION = mci.ID_CARRERAS_POR_INSTITUCION AND cxi.ES_ACTIVO=1		
		INNER JOIN db_auxiliar.dbo.UVW_CARRERA vc ON vc.ID_CARRERA = cxi.ID_CARRERA 
		INNER JOIN maestro.turnos_por_institucion txi ON mci.ID_TURNOS_POR_INSTITUCION = txi.ID_TURNOS_POR_INSTITUCION AND txi.ES_ACTIVO=1
		INNER JOIN maestro.turno_equivalencia te ON te.ID_TURNO_EQUIVALENCIA = txi.ID_TURNO_EQUIVALENCIA AND txi.ES_ACTIVO=1
		INNER JOIN sistema.enumerado t ON t.ID_ENUMERADO = te.ID_TURNO 		
		INNER JOIN sistema.enumerado ti ON ti.ID_ENUMERADO = cxi.ID_TIPO_ITINERARIO
		LEFT JOIN (
				SELECT mci2.ID_PLAN_ESTUDIO, mci2.ID_TURNOS_POR_INSTITUCION, mci2.ID_META_CARRERA_INSTITUCION, mci2.META, rxpl.ID_PERIODOS_LECTIVOS_POR_INSTITUCION  FROM transaccional.meta_carrera_institucion mci2
				INNER JOIN transaccional.resoluciones_por_periodo_lectivo_institucion rxpl ON mci2.ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION= rxpl.ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION 
				AND mci2.ES_ACTIVO=1 AND rxpl.ES_ACTIVO=1
				INNER JOIN maestro.resolucion r ON r.ID_RESOLUCION = rxpl.ID_RESOLUCION AND r.ES_ACTIVO=1 AND r.ID_TIPO_RESOLUCION =22 and mci2.ANIO =@ANIO				
		) METAS_AMPLIACION ON METAS_AMPLIACION.ID_PLAN_ESTUDIO = pe.ID_PLAN_ESTUDIO AND mci.ID_TURNOS_POR_INSTITUCION = METAS_AMPLIACION.ID_TURNOS_POR_INSTITUCION 	
		AND METAS_AMPLIACION.ID_PERIODOS_LECTIVOS_POR_INSTITUCION =@ID_PERIODO_LECTIVO_INSTITUCION 
	    LEFT JOIN (
					SELECT
					--MCI.ID_CARRERAS_POR_INSTITUCION,
					MCI.ID_PLAN_ESTUDIO, 
					MCI.ID_TURNOS_POR_INSTITUCION,
					ISNULL(SUM(META_ALCANZADA),0) METAS_ALCANZADAS_ACUM_ANT				
					FROM transaccional.meta_carrera_institucion_detalle MCID
					INNER JOIN transaccional.meta_carrera_institucion MCI ON MCI.ID_META_CARRERA_INSTITUCION= MCID.ID_META_CARRERA_INSTITUCION 
					AND MCID.ID_PERIODOS_LECTIVOS_POR_INSTITUCION IN (select plxi.ID_PERIODOS_LECTIVOS_POR_INSTITUCION from transaccional.periodos_lectivos_por_institucion plxi
					inner join maestro.periodo_lectivo mpl on plxi.ID_PERIODO_LECTIVO= mpl.ID_PERIODO_LECTIVO and plxi.ES_ACTIVO=1
					where mpl.ANIO=@ANIO and plxi.ID_INSTITUCION=@ID_INSTITUCION and plxi.ID_PERIODOS_LECTIVOS_POR_INSTITUCION < @ID_PERIODO_LECTIVO_INSTITUCION)					
					AND MCID.ES_ACTIVO=1 AND MCI.ES_ACTIVO=1
					GROUP BY MCI.ID_PLAN_ESTUDIO, MCI.ID_TURNOS_POR_INSTITUCION
			)	SUB_CONSULTA_METAS_ALCANZADAS_ACUM_ANT ON SUB_CONSULTA_METAS_ALCANZADAS_ACUM_ANT.ID_PLAN_ESTUDIO=  mci.ID_PLAN_ESTUDIO --cxi.ID_CARRERAS_POR_INSTITUCION
				AND SUB_CONSULTA_METAS_ALCANZADAS_ACUM_ANT.ID_TURNOS_POR_INSTITUCION= mci.ID_TURNOS_POR_INSTITUCION
		LEFT JOIN (
					SELECT
					MCI.ID_CARRERAS_POR_INSTITUCION,
					MCI.ID_TURNOS_POR_INSTITUCION,
					ISNULL(SUM(MCID.META_SEDE),0) METAS_SEDES		
					FROM transaccional.meta_carrera_institucion_detalle MCID
					INNER JOIN transaccional.meta_carrera_institucion MCI ON MCI.ID_META_CARRERA_INSTITUCION= MCID.ID_META_CARRERA_INSTITUCION 
					AND MCID.ID_PERIODOS_LECTIVOS_POR_INSTITUCION =@ID_PERIODO_LECTIVO_INSTITUCION_UNO AND MCID.ES_ACTIVO=1 AND MCI.ES_ACTIVO=1
					GROUP BY MCI.ID_CARRERAS_POR_INSTITUCION, MCI.ID_TURNOS_POR_INSTITUCION				
			)	SUB_CONSULTA_METAS_SEDES_ACUM_ANT ON SUB_CONSULTA_METAS_SEDES_ACUM_ANT.ID_CARRERAS_POR_INSTITUCION= cxi.ID_CARRERAS_POR_INSTITUCION		 
				AND SUB_CONSULTA_METAS_SEDES_ACUM_ANT.ID_TURNOS_POR_INSTITUCION= mci.ID_TURNOS_POR_INSTITUCION
		LEFT JOIN  (	SELECT
					MCI.ID_PLAN_ESTUDIO,
					MCI.ID_TURNOS_POR_INSTITUCION,
					ISNULL(SUM(META_ALCANZADA),0) METAS_ALCANZADAS				
					FROM transaccional.meta_carrera_institucion_detalle MCID
					INNER JOIN transaccional.meta_carrera_institucion MCI ON MCI.ID_META_CARRERA_INSTITUCION= MCID.ID_META_CARRERA_INSTITUCION 
					AND MCID.ID_PERIODOS_LECTIVOS_POR_INSTITUCION =@ID_PERIODO_LECTIVO_INSTITUCION AND MCID.ES_ACTIVO=1 AND MCI.ES_ACTIVO=1
					GROUP BY MCI.ID_PLAN_ESTUDIO, MCI.ID_TURNOS_POR_INSTITUCION
			   )  SUB_CONSULTA_METAS_ALCANZADAS ON SUB_CONSULTA_METAS_ALCANZADAS.ID_PLAN_ESTUDIO=   mci.ID_PLAN_ESTUDIO ---cxi.ID_CARRERAS_POR_INSTITUCION
			   	AND SUB_CONSULTA_METAS_ALCANZADAS.ID_TURNOS_POR_INSTITUCION= mci.ID_TURNOS_POR_INSTITUCION
		LEFT JOIN (
					SELECT
					MCI.ID_CARRERAS_POR_INSTITUCION,
					MCI.ID_TURNOS_POR_INSTITUCION,
					MCI.ID_PLAN_ESTUDIO,
					ISNULL(SUM(MCID.META_SEDE),0) METAS_SEDES		
					FROM transaccional.meta_carrera_institucion_detalle MCID
					INNER JOIN transaccional.meta_carrera_institucion MCI ON MCI.ID_META_CARRERA_INSTITUCION= MCID.ID_META_CARRERA_INSTITUCION 
					AND MCID.ID_PERIODOS_LECTIVOS_POR_INSTITUCION =@ID_PERIODO_LECTIVO_INSTITUCION AND MCID.ES_ACTIVO=1 AND MCI.ES_ACTIVO=1
					GROUP BY MCI.ID_CARRERAS_POR_INSTITUCION, MCI.ID_TURNOS_POR_INSTITUCION, MCI.ID_PLAN_ESTUDIO		
				)	SUB_CONSULTA_METAS_SEDES ON SUB_CONSULTA_METAS_SEDES.ID_CARRERAS_POR_INSTITUCION= cxi.ID_CARRERAS_POR_INSTITUCION		 
				AND SUB_CONSULTA_METAS_SEDES.ID_TURNOS_POR_INSTITUCION= mci.ID_TURNOS_POR_INSTITUCION
				AND SUB_CONSULTA_METAS_SEDES.ID_PLAN_ESTUDIO = mci.ID_PLAN_ESTUDIO
		WHERE mci.ANIO=@ANIO and r.ID_TIPO_RESOLUCION=21 and plxi.ID_INSTITUCION =@ID_INSTITUCION
	)
	SELECT  *    FROM    tempPaginado T    WHERE   ( T.Row > @desde  AND T.Row < @hasta) OR (@Registros = 0) 
	END


--***************************************************
--42. USP_ADMISION_SEL_META_CARRERA_INSTITUCION_DETALLE_PAGINADO.sql
GO


