CREATE PROCEDURE [dbo].[USP_ADMISION_INS_TIPO_MODALIDAD_REQUISITO]
(
	@ID_TIPO_MODALIDAD_INSTITUCION	INT,
	@ID_REQUISITO					INT,
	@USUARIO						VARCHAR(20)
)
AS
DECLARE @RESULT INT
BEGIN
IF EXISTS (SELECT TOP 1 ID_REQUISITOS_POR_TIPO_MODALIDAD FROM maestro.requisitos_por_tipo_modalidad WHERE ID_TIPOS_MODALIDAD_POR_INSTITUCION= @ID_TIPO_MODALIDAD_INSTITUCION
AND ID_REQUISITO = @ID_REQUISITO  AND ES_ACTIVO=1)
	SET @RESULT = -180
ELSE 
BEGIN
	INSERT INTO maestro.requisitos_por_tipo_modalidad(ID_TIPOS_MODALIDAD_POR_INSTITUCION,ID_REQUISITO,ES_ACTIVO,ESTADO,USUARIO_CREACION,FECHA_CREACION)
	VALUES(@ID_TIPO_MODALIDAD_INSTITUCION,@ID_REQUISITO,1,1,@USUARIO,GETDATE())
	SET @RESULT = 1	
END
END
SELECT @RESULT
GO


