CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_REQUISITO_POSTULANTE]
(
	@ID_POSTULANTES_MODALIDAD		INT,
	@ID_PROCESO_ADMISION_PERIODO	INT,
	@ID_TIPO_MODALIDAD_INSTITUCION	INT
)AS
BEGIN
	SELECT 
		ISNULL(RXP.ID_REQUISITOS_POR_POSTULANTE, 0)		IdRequisitoPostulante,
		ISNULL(RXTM.ID_REQUISITOS_POR_TIPO_MODALIDAD,0) IdRequisitoTipoModalidad,
		R.DESCRIPCION_REQUISITO							RequisitoTipoModalidad,
		ISNULL(CONVERT(INT,RXP.ES_ACTIVO),0)			Presentado
	FROM maestro.requisitos_por_tipo_modalidad RXTM
	INNER JOIN maestro.requisito R ON R.ID_REQUISITO= RXTM.ID_REQUISITO AND RXTM.ES_ACTIVO=1
	INNER JOIN maestro.tipos_modalidad_por_institucion TMXI ON TMXI.ID_TIPOS_MODALIDAD_POR_INSTITUCION = RXTM.ID_TIPOS_MODALIDAD_POR_INSTITUCION AND TMXI.ES_ACTIVO=1
	LEFT JOIN transaccional.requisitos_por_postulante RXP ON RXTM.ID_REQUISITOS_POR_TIPO_MODALIDAD= RXP.ID_REQUISITOS_POR_TIPO_MODALIDAD 
	AND RXP.ES_ACTIVO=1 
	AND RXP.ID_POSTULANTES_POR_MODALIDAD= @ID_POSTULANTES_MODALIDAD
	WHERE 
	RXTM.ID_TIPOS_MODALIDAD_POR_INSTITUCION=@ID_TIPO_MODALIDAD_INSTITUCION 
END
GO


