
/************************************************************************************************************************************
AUTOR				:	Mayra Alva
FECHA DE CREACION	:	20/06/2019
LLAMADO POR			:
DESCRIPCION			:	Registro de sede de la institución
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
1.0			20/06/2019		MALVA			CREACIÓN
1.1			26/12/2019		MALVA			MODIFICACIÓN DE CONSULTA SE EVALÚA QUE NO SE REPITA CÓDIGO NI NOMBRE DE SEDE.
2.0			04/04/2022		JCHAVEZ			SE AGREGÓ NUEVO CAMPO RESOLUCIÓN
	
TEST:		
	USP_MAESTROS_INS_SEDE_INSTITUCION 443, '492626', '24 DE JULIO DE LA CRUZ', '240103', 'AV. 24 DE JULIO', 'HERNANDO MARQUEZ', '2512235', 'istt24julio_7@hotmail.com', 205, 'MALVA'
*************************************************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_MAESTROS_INS_SEDE_INSTITUCION]
(  
	@ID_INSTITUCION				INT, 
	@CODIGO_SEDE				VARCHAR(7),
	@NOMBRE_SEDE				VARCHAR(150),
	@CODIGO_UBIGEO_SEDE			VARCHAR(6),
	@DIRECCION_SEDE				VARCHAR(255),
	--@ID_PERSONAL_INSTITUCION     INT,
	--@DIRECTOR_SEDE				VARCHAR(150),
	@TELEFONO_SEDE				VARCHAR(15),
	@CORREO_SEDE				VARCHAR(100),
	@ID_TIPO_SEDE				INT,
	@NRO_RESOLUCION				VARCHAR(50),
	@ARCHIVO_RESOLUCION			VARCHAR(100),
    @RUTA_RESOLUCION			VARCHAR(300),
	@USUARIO					VARCHAR(20)
)  
AS 
DECLARE @RESULT INT
DECLARE @ID_TIPO_SEDE_PRINCIPAL INT = 203	
 IF EXISTS(SELECT TOP 1 CODIGO_SEDE FROM maestro.sede_institucion WHERE (CODIGO_SEDE =@CODIGO_SEDE OR NOMBRE_SEDE= @NOMBRE_SEDE ) AND ES_ACTIVO=1 AND ID_INSTITUCION=@ID_INSTITUCION)
	SET @RESULT = -180  
 ELSE 
	IF 	EXISTS (SELECT TOP 1 CODIGO_SEDE FROM maestro.sede_institucion WHERE ES_SEDE_PRINCIPAL=1 AND ES_ACTIVO=1 AND ID_INSTITUCION=@ID_INSTITUCION ) and @ID_TIPO_SEDE=@ID_TIPO_SEDE_PRINCIPAL 
		SET @RESULT = -145  
	ELSE	
	 BEGIN		

		INSERT INTO maestro.sede_institucion
		(	ID_INSTITUCION,
			CODIGO_SEDE,
			NOMBRE_SEDE,
			CODIGO_UBIGEO_SEDE,
			DIRECCION_SEDE,
			--ID_PERSONAL_INSTITUCION,
			--DIRECTOR_SEDE,
			TELEFONO_SEDE,
			CORREO_SEDE,
			ES_SEDE_PRINCIPAL,
			ID_TIPO_SEDE,
			ES_ACTIVO,
			ESTADO,
			USUARIO_CREACION,
			FECHA_CREACION,
			NRO_RESOLUCION,
			ARCHIVO_RESOLUCION,
			ARCHIVO_RUTA
		)
		VALUES(
			@ID_INSTITUCION,
			UPPER(@CODIGO_SEDE),
			UPPER(@NOMBRE_SEDE),
			RIGHT(REPLICATE('0',6) + @CODIGO_UBIGEO_SEDE,6),
			UPPER(@DIRECCION_SEDE),
			--CASE WHEN @ID_PERSONAL_INSTITUCION =0 THEN NULL ELSE @ID_PERSONAL_INSTITUCION END ,
			--UPPER(@DIRECTOR_SEDE),
			@TELEFONO_SEDE,
			@CORREO_SEDE,
			CASE WHEN @ID_TIPO_SEDE = @ID_TIPO_SEDE_PRINCIPAL THEN 1 ELSE 0 END,
			@ID_TIPO_SEDE,
			1,
			1,
			@USUARIO, 
			GETDATE(),
			UPPER(@NRO_RESOLUCION),
			@ARCHIVO_RESOLUCION,
			@RUTA_RESOLUCION
		)
		SET @RESULT = 1
	END  
SELECT @RESULT
GO


