CREATE PROCEDURE [dbo].[USP_MAESTROS_SEL_PERIODO_LECTIVO_INSTITUCION_POR_ID]
(
	@ID_PERIODO_LECTIVO_INSTITUCION		INT,
	@ID_INSTITUCION	INT
)
AS
SET NOCOUNT ON;

SELECT 
		A.ID_PERIODO_LECTIVO					IdPeriodoLectivo,
		A.ID_PERIODOS_LECTIVOS_POR_INSTITUCION	IdPeriodoLectivoInstitucion,
		A.FECHA_INICIO_INSTITUCION				FechaInicio,
		A.FECHA_FIN_INSTITUCION					FechaFin
FROM 
		transaccional.periodos_lectivos_por_institucion A
WHERE	A.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION
		AND A.ID_INSTITUCION = @ID_INSTITUCION
		AND A.ES_ACTIVO = 1
		AND A.ESTADO = 7
GO


