--USP_INSTITUCION_SEL_QUERY 'UPDATE transaccional.programacion_clase SET ESTADO=0 WHERE ID_PERIODO_ACADEMICO=3763'
CREATE PROCEDURE USP_INSTITUCION_SEL_QUERY
 @SQL NVARCHAR(MAX)
AS
BEGIN
	SELECT @SQL = '' + @SQL + ''
	EXEC sp_executesql @SQL

	SELECT 1
END