CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_POSTULANTE_MODALIDAD]
(
	@ID_INSTITUCION		INT,
	@ID_PERIODO_LECTIVO_INSTITUCION INT,
	@ID_TIPO_DOCUMENTO	INT,
	@NUMERO_DOCUMENTO	VARCHAR(15)
)
AS
BEGIN
SELECT
		P.ID_PERSONA					IdPersona,
		CASE WHEN PEI.ID_INSTITUCION = @ID_INSTITUCION THEN PEI.ID_PERSONA_INSTITUCION	ELSE 0 END 	IdPersonaInstitucion,
		P.APELLIDO_PATERNO_PERSONA		ApellidoPaterno,
		P.APELLIDO_MATERNO_PERSONA		ApellidoMaterno,
		P.NOMBRE_PERSONA				Nombre,
		P.SEXO_PERSONA					IdSexo,
		PEI.ESTADO_CIVIL				IdEstadoCivil,
		P.FECHA_NACIMIENTO_PERSONA		FechaNacimiento,
		PEI.PAIS_PERSONA				IdPaisResidencia,
		URES.CODIGO_UBIGEO				UbigeoResidencia,
		P.PAIS_NACIMIENTO				IdPaisNacimiento,
		UNAC.CODIGO_UBIGEO				UbigeoNacimiento,
		P.ID_LENGUA_MATERNA				IdLenguaMaterna,
		P.ES_DISCAPACITADO				EsDiscapacitado,		
		--PINS.ID_PERSONAL_INSTITUCION	IdPersonalInstitucion,
		PEI.DIRECCION_PERSONA			Direccion,
		PEI.CORREO						Correo,
		PEI.TELEFONO					Telefono,
		ISNULL(PEI.CELULAR,'')			Celular,
		ISNULL(sub_consulta_postulantes.ID_POSTULANTES_POR_MODALIDAD,0)	IdPostulanteModalidad
		--PEI.CORREO						Correo,
		--PEI.TELEFONO					Telefono,
		--PEI.CELULAR						Celular
FROM
		maestro.persona P
		LEFT  JOIN maestro.persona_institucion PEI ON PEI.ID_PERSONA = P.ID_PERSONA AND PEI.ID_INSTITUCION = @ID_INSTITUCION
		LEFT JOIN 
		(SELECT PXM.ID_PERSONA_INSTITUCION, PAP.ID_PERIODOS_LECTIVOS_POR_INSTITUCION, PXM.ID_POSTULANTES_POR_MODALIDAD 
			FROM transaccional.postulantes_por_modalidad PXM 
			inner join transaccional.modalidades_por_proceso_admision MXPA ON PXM.ID_MODALIDADES_POR_PROCESO_ADMISION=MXPA.ID_MODALIDADES_POR_PROCESO_ADMISION
			AND PXM.ES_ACTIVO=1 AND MXPA.ES_ACTIVO=1
			INNER JOIN transaccional.proceso_admision_periodo PAP ON MXPA.ID_PROCESO_ADMISION_PERIODO= PAP.ID_PROCESO_ADMISION_PERIODO AND PAP.ES_ACTIVO=1
			)
		sub_consulta_postulantes  ON sub_consulta_postulantes.ID_PERSONA_INSTITUCION = PEI.ID_PERSONA_INSTITUCION 
		AND sub_consulta_postulantes.ID_PERIODOS_LECTIVOS_POR_INSTITUCION= @ID_PERIODO_LECTIVO_INSTITUCION
		LEFT JOIN db_auxiliar.dbo.UVW_UBIGEO_RENIEC URES ON URES.CODIGO_UBIGEO = PEI.UBIGEO_PERSONA
		LEFT JOIN db_auxiliar.dbo.UVW_UBIGEO_RENIEC UNAC ON UNAC.CODIGO_UBIGEO = P.UBIGEO_NACIMIENTO
		
WHERE
		P.ID_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
		AND P.NUMERO_DOCUMENTO_PERSONA = @NUMERO_DOCUMENTO	
END
GO


