CREATE PROCEDURE [dbo].[USP_ADMISION_UPD_TIPO_MODALIDAD_IE]
(
	@ID_TIPO_MODALIDAD_IE	INT,
	@ID_ESTADO				INT,
	@USUARIO				VARCHAR(20)
)
AS
BEGIN
	UPDATE maestro.tipos_modalidad_por_institucion
	SET ESTADO = @ID_ESTADO,
	USUARIO_MODIFICACION = @USUARIO,
	FECHA_MODIFICACION = GETDATE()
	WHERE ID_TIPOS_MODALIDAD_POR_INSTITUCION = @ID_TIPO_MODALIDAD_IE

	SELECT @ID_TIPO_MODALIDAD_IE
END
GO


