CREATE PROCEDURE [dbo].[USP_MAESTROS_DEL_SEDE_INSTITUCION]
(
	@ID_INSTITUCION			INT,
    @ID_SEDE_INSTITUCION	INT,     
    @USUARIO				NVARCHAR(20)
)
AS
BEGIN
SET NOCOUNT ON;
	DECLARE @RESULT INT, @ID_INSTITUCION_CONSULTA INT = 0, @ID_TIPOSEDE INT

	SELECT @ID_TIPOSEDE= ID_TIPO_SEDE, @ID_INSTITUCION_CONSULTA = ID_INSTITUCION FROM maestro.sede_institucion where ID_SEDE_INSTITUCION = @ID_SEDE_INSTITUCION
	
	IF @ID_INSTITUCION <> @ID_INSTITUCION_CONSULTA
		SET @RESULT = -362
	ELSE IF @ID_TIPOSEDE = 283
		SET @RESULT = -272
	ELSE 
	BEGIN
			IF	EXISTS (SELECT TOP 1 ID_SEDE_INSTITUCION FROM maestro.aula WHERE ID_SEDE_INSTITUCION= @ID_SEDE_INSTITUCION AND ES_ACTIVO=1 )
				OR EXISTS (SELECT TOP 1 ID_SEDE_INSTITUCION FROM transaccional.carreras_por_institucion_detalle WHERE ID_SEDE_INSTITUCION= @ID_SEDE_INSTITUCION	 AND ES_ACTIVO=1 )
				OR EXISTS (SELECT TOP 1 ID_SEDE_INSTITUCION FROM transaccional.examen_admision_sede WHERE ID_SEDE_INSTITUCION= @ID_SEDE_INSTITUCION	 AND ES_ACTIVO=1 )
					SET @RESULT = -162
			ELSE
			BEGIN
				UPDATE [maestro].[sede_institucion]
				SET 
				   [ES_ACTIVO]				= 0 
				  ,[FECHA_MODIFICACION]		= GETDATE()   
				  ,[USUARIO_MODIFICACION]	= @USUARIO
				WHERE 
				   [ID_SEDE_INSTITUCION]	= @ID_SEDE_INSTITUCION		      

				SET @RESULT = 1
			END
	END
	SELECT @RESULT
END
GO


