/****** Object:  StoredProcedure [dbo].[USP_CONVALIDACION_SEL_DATOS_PLAN_ESTUDIO_ORIGEN]    Script Date: 30/09/2021 12:42:42 ******/

CREATE PROCEDURE [dbo].[USP_CONVALIDACION_SEL_DATOS_PLAN_ESTUDIO_ORIGEN]
(  
	@ID_PLAN_ESTUDIO INT,
	@ID_ESTUDIANTE_INSTITUCION_ORIGEN INT = 0
)  
AS  
BEGIN  
	SET NOCOUNT ON;   
	DECLARE @ID_SEMESTRE_ACADEMICO_MAX INT,
	@NRO_SEMESTRES INT,
	@ESTADO_NO_CONVALIDADO INT =202

	SET @NRO_SEMESTRES =
						(
							SELECT MNF.SEMESTRES_ACADEMICOS FROM transaccional.plan_estudio TPE
							INNER JOIN transaccional.carreras_por_institucion TCI ON TCI.ID_CARRERAS_POR_INSTITUCION=TPE.ID_CARRERAS_POR_INSTITUCION AND TPE.ES_ACTIVO=1 AND TCI.ES_ACTIVO=1
							INNER JOIN db_auxiliar.dbo.UVW_CARRERA MC ON MC.ID_CARRERA= TCI.ID_CARRERA 
							INNER JOIN maestro.nivel_formacion MNF ON MNF.CODIGO_TIPO = MC.TIPO_NIVEL_FORMACION --MNF.ID_NIVEL_FORMACION= MC.ID_NIVEL_FORMACION --reemplazoPorVista
							WHERE TPE.ID_PLAN_ESTUDIO= @ID_PLAN_ESTUDIO
						)
						
	
	SELECT 
		TUD.ID_UNIDAD_DIDACTICA						IdUnidadDidactica, 
		TUD.ID_SEMESTRE_ACADEMICO					IdSemestreAcademico, 
		ISNULL(MTUD.NOMBRE_TIPO_UNIDAD,'Curso')		NombreTipoUnidadDidactica,
		TUD.NOMBRE_UNIDAD_DIDACTICA					NombreUnidadDidactica, 
		ISNULL(TUD.CREDITOS,0)						Creditos,
		TUD.HORAS									Horas,
		ISNULL(SUBCONSULTA_NOTAS.NOTA,-1)			Nota
	FROM transaccional.unidad_didactica TUD
	INNER JOIN transaccional.modulo TM ON TM.ID_MODULO= TUD.ID_MODULO 
											AND TUD.ES_ACTIVO=1 
											AND TM.ES_ACTIVO=1
	LEFT JOIN maestro.tipo_unidad_didactica MTUD ON MTUD.ID_TIPO_UNIDAD_DIDACTICA= TUD.ID_TIPO_UNIDAD_DIDACTICA
	LEFT JOIN 
	(SELECT UDXE.ID_UNIDAD_DIDACTICA,ED.NOTA  
		FROM transaccional.evaluacion_detalle ED
		INNER JOIN transaccional.evaluacion E ON ED.ID_EVALUACION= E.ID_EVALUACION AND E.ES_ACTIVO=1 AND ED.ES_ACTIVO=1

		INNER JOIN transaccional.unidades_didacticas_por_programacion_clase UDXPC ON UDXPC.ID_PROGRAMACION_CLASE = E.ID_PROGRAMACION_CLASE AND UDXPC.ES_ACTIVO=1
		INNER JOIN transaccional.unidades_didacticas_por_enfoque UDXE ON UDXE.ID_UNIDADES_DIDACTICAS_POR_ENFOQUE=UDXPC.ID_UNIDADES_DIDACTICAS_POR_ENFOQUE AND UDXE.ES_ACTIVO=1
		INNER JOIN transaccional.matricula_estudiante ME ON ED.ID_MATRICULA_ESTUDIANTE= ME.ID_MATRICULA_ESTUDIANTE AND ME.ES_ACTIVO=1
		WHERE ME.ID_ESTUDIANTE_INSTITUCION= @ID_ESTUDIANTE_INSTITUCION_ORIGEN
	) SUBCONSULTA_NOTAS ON SUBCONSULTA_NOTAS.ID_UNIDAD_DIDACTICA=TUD.ID_UNIDAD_DIDACTICA 	
	WHERE TM.ID_PLAN_ESTUDIO=@ID_PLAN_ESTUDIO AND TUD.ID_SEMESTRE_ACADEMICO IN (SELECT TOP (@NRO_SEMESTRES) *  FROM dbo.UFN_SPLIT('111|112|113|114|115|116|137|138','|'))	 
	ORDER BY TUD.ID_SEMESTRE_ACADEMICO, TUD.ID_UNIDAD_DIDACTICA ASC
END
GO


