CREATE PROCEDURE [dbo].[USP_MAESTROS_SEL_FAMILIA_PRODUCTIVA_LISTA]
(  
@ID_SECTOR INT  
)  
AS  
BEGIN  
 SET NOCOUNT ON;  
 SELECT        
     NOMBRE_FAMILIA_PRODUCTIVA Text,  
     ID_FAMILIA_PRODUCTIVA Value  
 FROM maestro.familia_productiva
 WHERE (ID_SECTOR = @ID_SECTOR)     
END
GO


