/**********************************************************************************************************
AUTOR				:	Juan Chavez
FECHA DE CREACION	:	05/04/2021
LLAMADO POR			:
DESCRIPCION			:	Obtiene el detalle que se muestran en el reporte de nómina por carga masiva
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
1.0			05/04/2021		JCHAVEZ			Creación

TEST:			
	EXEC USP_MATRICULA_RPT_CARGA_MASIVA_NOMINA_DETALLE 2,2945
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_MATRICULA_RPT_CARGA_MASIVA_NOMINA_DETALLE]
(
	@ID_CARGA_MASIVA_NOMINA INT,
	@ID_INSTITUCION INT
)
AS 
BEGIN

	SELECT DISTINCT
	CMNP.ID_CARGA_MASIVA_PERSONA,
	ENU_TD.VALOR_ENUMERADO TIPO_DOCUMENTO,
	CMNP.NUMERO_DOCUMENTO,
	CMNP.NOMBRE_COMPLETO,
	LEFT(ENU_SE.VALOR_ENUMERADO,1) SEXO,
	CMNP.EDAD,
	(CASE WHEN CMNP.TIENE_DISCAPACIDAD IS NULL OR TIENE_DISCAPACIDAD =0 
		THEN 'NO'
		ELSE 'SI'
		END
	) TIENE_DISCAPACIDAD,
	UD.NOMBRE_UNIDAD_DIDACTICA, 
	CASE WHEN EXISTS (				
						SELECT TOP 1 ME.NOMBRE_UNIDAD_DIDACTICA FROM transaccional.carga_masiva_nominas_detalle ME
						WHERE ME.ID_CARGA_MASIVA_PERSONA=MAT.ID_CARGA_MASIVA_PERSONA 
								AND ME.ID_CARGA_MASIVA_NOMINA = CMN.ID_CARGA_MASIVA_NOMINA
								AND ME.NOMBRE_UNIDAD_DIDACTICA = UD.NOMBRE_UNIDAD_DIDACTICA
								AND ME.ES_ACTIVO=1			 
					 ) THEN 'SI' ELSE 'NO' END MATRICULADO
	FROM 
		transaccional.carga_masiva_nominas CMN
		INNER JOIN (SELECT DISTINCT ID_CARGA_MASIVA_NOMINA,NOMBRE_UNIDAD_DIDACTICA 
					FROM transaccional.carga_masiva_nominas_detalle 
					WHERE ID_CARGA_MASIVA_NOMINA = @ID_CARGA_MASIVA_NOMINA) UD ON CMN.ID_CARGA_MASIVA_NOMINA = UD.ID_CARGA_MASIVA_NOMINA
		INNER JOIN (SELECT DISTINCT ID_CARGA_MASIVA_NOMINA,ID_CARGA_MASIVA_PERSONA 
					FROM transaccional.carga_masiva_nominas_detalle 
					WHERE ID_CARGA_MASIVA_NOMINA = @ID_CARGA_MASIVA_NOMINA) MAT ON CMN.ID_CARGA_MASIVA_NOMINA = MAT.ID_CARGA_MASIVA_NOMINA
		INNER JOIN transaccional.carga_masiva_nominas_persona CMNP ON MAT.ID_CARGA_MASIVA_PERSONA = CMNP.ID_CARGA_MASIVA_PERSONA
		INNER JOIN sistema.enumerado ENU_TD ON ENU_TD.ID_ENUMERADO = CMNP.ID_TIPO_DOCUMENTO
		INNER JOIN sistema.enumerado ENU_SE ON ENU_SE.ID_ENUMERADO = CMNP.SEXO
	WHERE CMN.ID_CARGA_MASIVA_NOMINA = @ID_CARGA_MASIVA_NOMINA AND CMN.ID_INSTITUCION = @ID_INSTITUCION AND CMN.ES_ACTIVO = 1
ORDER BY 
		CMNP.NOMBRE_COMPLETO, UD.NOMBRE_UNIDAD_DIDACTICA
END