CREATE PROCEDURE [dbo].[USP_MAESTROS_SEL_CARRERA_PROFESIONAL_LISTA]
AS 
	SELECT 
		ID_CARRERA_PROFESIONAL Value,
		ID_CARRERA_PROFESIONAL Code,
		DESCRIPCION_CARRERA_PROFESIONAL Text
	FROM maestro.carrera_profesional
	WHERE ESTADO = 1
GO


