CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_TIPO_MODALIDAD_LISTA](
	@ID_INSTITUCION INT,
	@ID_MODALIDAD INT,
	@FILTRO INT
)AS
BEGIN
	IF @FILTRO = 1
		SELECT 		
			B.ID_TIPOS_MODALIDAD_POR_INSTITUCION Value,
			A.NOMBRE_TIPO_MODALIDAD	Text,
			ISNULL(B.ID_TIPOS_MODALIDAD_POR_INSTITUCION,0)		Code
		FROM
			maestro.tipo_modalidad A
			LEFT JOIN maestro.tipos_modalidad_por_institucion B ON B.ID_TIPO_MODALIDAD = A.ID_TIPO_MODALIDAD AND B.ES_ACTIVO = 1
		WHERE 
			B.ID_INSTITUCION = @ID_INSTITUCION
			AND A.ID_MODALIDAD = @ID_MODALIDAD
			and A.ESTADO=1
		ORDER BY A.NOMBRE_TIPO_MODALIDAD
	ELSE
		SELECT DISTINCT		
			A.ID_TIPO_MODALIDAD		Value,
			A.NOMBRE_TIPO_MODALIDAD	Text--,
			--ISNULL(B.ID_TIPOS_MODALIDAD_POR_INSTITUCION,0)		Code
		FROM
			maestro.tipo_modalidad A
			LEFT JOIN maestro.tipos_modalidad_por_institucion B ON B.ID_TIPO_MODALIDAD = A.ID_TIPO_MODALIDAD AND B.ES_ACTIVO = 1
		WHERE 
			(B.ID_INSTITUCION <> @ID_INSTITUCION OR B.ID_INSTITUCION IS NULL)
			AND A.ID_MODALIDAD = @ID_MODALIDAD
			and A.ESTADO=1
		ORDER BY A.NOMBRE_TIPO_MODALIDAD
END
GO


