CREATE PROCEDURE [dbo].[USP_ADMISION_UPD_COMISION_PROCESO_ADMISION]
(
	@ID_COMISION_PROCESO_ADMISION	INT,	
	@ID_PROCESO_ADMISION_PERIODO	INT,
	@ID_CARGO						INT,
	@USUARIO						VARCHAR(20)
)AS 
BEGIN
	IF EXISTS (SELECT TOP 1 ID_COMISION_PROCESO_ADMISION FROM transaccional.comision_proceso_admision
				WHERE ID_CARGO = @ID_CARGO AND ID_PROCESO_ADMISION_PERIODO = @ID_PROCESO_ADMISION_PERIODO AND ES_ACTIVO =1
				AND ID_COMISION_PROCESO_ADMISION <> @ID_COMISION_PROCESO_ADMISION)				
		SELECT -180
	ELSE
	BEGIN
		UPDATE transaccional.comision_proceso_admision
		SET ID_CARGO = @ID_CARGO,
			USUARIO_MODIFICACION = @USUARIO,
			FECHA_MODIFICACION = GETDATE()
		WHERE ID_COMISION_PROCESO_ADMISION = @ID_COMISION_PROCESO_ADMISION		

		SELECT @ID_COMISION_PROCESO_ADMISION
	END
END
GO


