/**********************************************************************************************************
AUTOR				:	Consultores DRE
FECHA DE CREACION	:	15/11/2019
LLAMADO POR			:
DESCRIPCION			:	Elimina un registro correspondiente al Enumerado Historico
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
1.0			15/11/2019		Consultores DRE Creación
1.1         09/11/2021		JTOVARY			Se agregó la validacion para periodo lectivo en la tabla clase historica
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_SISTEMA_DEL_ENUMERADO_HISTORICO]
(
	@CODIGO_GRUPO_ENUMERADO_HISTORICO INT,
	@ID_ENUMERADO_HISTORICO	INT,
	@ID_RESOLUCION_ENUMERADO_HISTORICO INT,
	@USUARIO nvarchar(20)	
)AS 
BEGIN
	DECLARE @EXISTE BIT = 0

	IF NOT EXISTS (SELECT TOP 1 ID_ENUMERADO_HISTORICO FROM sistema.enumerado_historico 
					WHERE CODIGO_GRUPO_ENUMERADO_HISTORICO = @CODIGO_GRUPO_ENUMERADO_HISTORICO AND ID_ENUMERADO_HISTORICO = @ID_ENUMERADO_HISTORICO AND ESTADO_ENUMERADO_HISTORICO = 1)
		SELECT -300
	ELSE
	BEGIN
		--IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 1) --ESTADO_REGISTRO
		--	IF EXISTS(	SELECT TOP 1 ID_CLASE_HISTORICA 
		--				FROM maestro.clase_historica 
		--				WHERE ESTADO = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
		--			 )
		--		SET @EXISTE = 1
		--IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 2) --TIPO_GESTION
		--	IF EXISTS(	SELECT TOP 1 ID_CLASE_HISTORICA 
		--				FROM maestro.clase_historica 
		--				WHERE TIPO_GESTION = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
		--			 )
		--		SET @EXISTE = 1
		IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 3) --TURNO
			IF EXISTS(	SELECT TOP 1 ID_CLASE_HISTORICA 
						FROM maestro.clase_historica 
						WHERE TURNO = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
					)
				SET @EXISTE = 1 
		--IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 4) --TIPO_SEDE
		--	IF EXISTS(	SELECT TOP 1 ID_CLASE_HISTORICA 
		--				FROM maestro.clase_historica 
		--				WHERE ID_SEDE_INSTITUCION = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
  --  				)
		--		SET @EXISTE = 1 
		IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 5) --PERIODO_ACADEMICO
			IF EXISTS(	SELECT TOP 1 ID_CLASE_HISTORICA 
						FROM maestro.clase_historica 
						WHERE CICLO = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
					 )
				SET @EXISTE = 1 
		IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 6) --TIPO_ITINERARIO
			IF EXISTS(	SELECT TOP 1 ID_CLASE_HISTORICA 
						FROM maestro.clase_historica 
						WHERE PLAN_ESTUDIO = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
					 )
				SET @EXISTE = 1 
		IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 7) --NIVEL_FORMATIVO
			IF EXISTS(	SELECT TOP 1 ID_CLASE_HISTORICA 
						FROM maestro.clase_historica 
						WHERE NIVEL_FORMATIVO = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
					)
				SET @EXISTE = 1 
		IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 8) --SECCION
			IF EXISTS(	SELECT TOP 1 ID_CLASE_HISTORICA 
						FROM maestro.clase_historica 
						WHERE SECCION = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
					)
				SET @EXISTE = 1 
		IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 9) --PROGRAMA_ESTUDIO
			IF EXISTS(	SELECT TOP 1 ID_CLASE_HISTORICA 
						FROM maestro.clase_historica 
						WHERE PROGRAMA_ESTUDIO = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
					)
				SET @EXISTE = 1 
		IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 10) --PERIODO LECTIVO
			IF EXISTS(	SELECT TOP 1 ID_CLASE_HISTORICA 
						FROM maestro.clase_historica
						WHERE ID_PERIODO_LECTIVO = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
					)
				SET @EXISTE = 1 
		IF (@CODIGO_GRUPO_ENUMERADO_HISTORICO = 11) --TIPO DOCUMENTO DRE
			IF EXISTS(	SELECT TOP 1 ID_DOCUMENTOS_DRE 
						FROM transaccional.documentos_dre
						WHERE CODIGO_TIPO_ENUMERADO = @ID_ENUMERADO_HISTORICO AND ESTADO = 1
					)
				SET @EXISTE = 1 

		IF @EXISTE = 1
			SELECT -162
		ELSE
			BEGIN
				IF @ID_RESOLUCION_ENUMERADO_HISTORICO <> 0 OR @ID_RESOLUCION_ENUMERADO_HISTORICO <> NULL
					BEGIN
						BEGIN TRANSACTION T1
						BEGIN TRY
							--DELETE FROM sistema.enumerado_historico
							--WHERE ID_ENUMERADO_HISTORICO = @ID_ENUMERADO_HISTORICO

							--DELETE FROM sistema.resolucion_enumerado_historico
							--WHERE ID_RESOLUCION_ENUMERADO_HISTORICO = @ID_RESOLUCION_ENUMERADO_HISTORICO

							UPDATE sistema.enumerado_historico SET
								ESTADO_ENUMERADO_HISTORICO = 0,
								USUARIO_MODIFICACION = @USUARIO,
								FECHA_MODIFICACION = GETDATE()
							WHERE ID_ENUMERADO_HISTORICO = @ID_ENUMERADO_HISTORICO

							UPDATE sistema.resolucion_enumerado_historico SET
								ESTADO = 0,
								USUARIO_MODIFICACION = @USUARIO,
								FECHA_MODIFICACION = GETDATE()
							WHERE ID_RESOLUCION_ENUMERADO_HISTORICO = @ID_RESOLUCION_ENUMERADO_HISTORICO
						COMMIT TRANSACTION T1
							SELECT 1
						END TRY	   
						BEGIN CATCH
							IF @@ERROR<>0
							BEGIN
								ROLLBACK TRANSACTION T1	   
								SELECT -300
							END
						END CATCH	
					END		
				ELSE
					BEGIN
						BEGIN TRANSACTION T1
						BEGIN TRY
							--DELETE FROM sistema.enumerado_historico
							--WHERE ID_ENUMERADO_HISTORICO = @ID_ENUMERADO_HISTORICO
							UPDATE sistema.enumerado_historico SET
								ESTADO_ENUMERADO_HISTORICO = 0,
								USUARIO_MODIFICACION = @USUARIO,
								FECHA_MODIFICACION = GETDATE()
							WHERE ID_ENUMERADO_HISTORICO = @ID_ENUMERADO_HISTORICO
						COMMIT TRANSACTION T1
							SELECT 1
						END TRY	   
						BEGIN CATCH
							IF @@ERROR<>0
							BEGIN
								ROLLBACK TRANSACTION T1	   
								SELECT -300
							END
						END CATCH	
					END
			END
	END
END