/****** Object:  StoredProcedure [dbo].[USP_INSTITUCION_INS_UDP_UNIDAD_DIDACTICA]    Script Date: 30/09/2021 12:24:33 ******/

/**********************************************************************************************************
AUTOR				:	Juan Chavez
FECHA DE CREACION	:	05/02/2021
LLAMADO POR			:
DESCRIPCION			:	Agrega o actualiza una unidad didáctica
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
--	1.0		 05/02/2021		JCHAVEZ
--  TEST:  
--			USP_INSTITUCION_INS_UDP_UNIDAD_DIDACTICA 995,100 
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_INSTITUCION_INS_UDP_UNIDAD_DIDACTICA]
(
	@ID_PLAN_ESTUDIO INT,
	@ID_TIPO_ITINERARIO INT,
	@ID_UNIDAD_DIDACTICA INT, 
    @NOMBRE_MODULO VARCHAR(MAX),
    @ID_MODULO INT,
    @CODIGO_CORRELATIVO VARCHAR(16),
    @ID_TIPO_UNIDAD_DIDACTICA INT,
    @NOMBRE_UNIDAD_DIDACTICA VARCHAR(150),
    @ID_SEMESTRE_ACADEMICO INT,
    @HORAS DECIMAL(10,2),
    @CREDITOS DECIMAL(10,2),
    @HORAS_TP DECIMAL(10,2),
    @HORAS_P DECIMAL(10,2),
    @CREDITOS_T DECIMAL(10,2),
    @CREDITOS_P DECIMAL(10,2),
    @USUARIO VARCHAR(8)
)
AS
BEGIN
	DECLARE @MSG_TRANS VARCHAR(MAX)
	DECLARE @ID_CORRELATIVO INT,
		@NUM_CORRELATIVO INT,
		@NEW_CORRELATIVO INT,
		@CODIGO_GENERADO NVARCHAR(12)

	BEGIN TRY

	BEGIN TRAN TransactSQL

	DECLARE @PLAN_ASIGNATURA INT = 99
	DECLARE @PLAN_TRANSVERSAL INT = 100
	DECLARE @PLAN_MODULAR INT = 101
	DECLARE @ID_ENFOQUES_POR_PLAN_ESTUDIO INT 
	
	SET @ID_ENFOQUES_POR_PLAN_ESTUDIO = (SELECT MIN(ID_ENFOQUES_POR_PLAN_ESTUDIO) FROM transaccional.enfoques_por_plan_estudio WHERE ID_PLAN_ESTUDIO = @ID_PLAN_ESTUDIO)
	SET @ID_TIPO_ITINERARIO = (SELECT ID_TIPO_ITINERARIO FROM transaccional.plan_estudio WHERE ID_PLAN_ESTUDIO=@ID_PLAN_ESTUDIO)

	IF (@ID_UNIDAD_DIDACTICA = 0)
	BEGIN
		INSERT INTO transaccional.unidad_didactica
		        ( ID_MODULO ,
		          ID_SEMESTRE_ACADEMICO ,
		          ID_TIPO_UNIDAD_DIDACTICA ,
		          CODIGO_UNIDAD_DIDACTICA ,
		          NOMBRE_UNIDAD_DIDACTICA ,
		          DESCRIPCION ,
		          PERIODO_ACADEMICO_I ,
		          PERIODO_ACADEMICO_II ,
		          PERIODO_ACADEMICO_III ,
		          PERIODO_ACADEMICO_IV ,
		          PERIODO_ACADEMICO_V ,
		          PERIODO_ACADEMICO_VI ,
		          TEORICO_PRACTICO_HORAS_UD ,
		          PRACTICO_HORAS_UD ,
		          HORAS ,
		          TEORICO_PRACTICO_CREDITOS_UD ,
		          PRACTICO_CREDITOS_UD ,
		          CREDITOS ,
		          CREDITOS_ME ,
		          ES_ACTIVO ,
		          ESTADO ,
		          USUARIO_CREACION ,
		          FECHA_CREACION ,
		          PERIODO_ACADEMICO_VII ,
		          PERIODO_ACADEMICO_VIII
		        )
		VALUES  ( @ID_MODULO , 
		          @ID_SEMESTRE_ACADEMICO ,  
				  (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL ELSE @ID_TIPO_UNIDAD_DIDACTICA END), 
				  (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL ELSE @CODIGO_CORRELATIVO END), 
		          @NOMBRE_UNIDAD_DIDACTICA , 
		          'MantenimientoUD' , 
		          (CASE @ID_SEMESTRE_ACADEMICO WHEN 111 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		          (CASE @ID_SEMESTRE_ACADEMICO WHEN 112 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		          (CASE @ID_SEMESTRE_ACADEMICO WHEN 113 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		          (CASE @ID_SEMESTRE_ACADEMICO WHEN 114 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		          (CASE @ID_SEMESTRE_ACADEMICO WHEN 115 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		          (CASE @ID_SEMESTRE_ACADEMICO WHEN 116 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
			      (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_MODULAR THEN @HORAS_TP ELSE NULL END) , 
		          (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_MODULAR THEN @HORAS_P ELSE NULL END) , 
		          (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN @HORAS WHEN @PLAN_TRANSVERSAL THEN @HORAS * 18 WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) , 
		          (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_MODULAR THEN @CREDITOS_T ELSE NULL END) , 
		          (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_MODULAR THEN @CREDITOS_P ELSE NULL END) , 
		          (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @CREDITOS WHEN @PLAN_MODULAR THEN @CREDITOS_T + @CREDITOS_P END) , 
		          (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_TRANSVERSAL THEN @HORAS * 18 ELSE NULL END) , 
		          1 , 
		          1 , 
		          @USUARIO , 
		          GETDATE() , 
		          (CASE @ID_SEMESTRE_ACADEMICO WHEN 137 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		          (CASE @ID_SEMESTRE_ACADEMICO WHEN 138 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END)
		        )
		
		SET @ID_UNIDAD_DIDACTICA = @@IDENTITY

		INSERT INTO transaccional.unidades_didacticas_por_enfoque
		        ( ID_ENFOQUES_POR_PLAN_ESTUDIO ,
		          ID_UNIDAD_DIDACTICA ,
		          ES_ACTIVO ,
		          ESTADO ,
		          USUARIO_CREACION ,
		          FECHA_CREACION
		        )
		VALUES  ( @ID_ENFOQUES_POR_PLAN_ESTUDIO ,
		          @ID_UNIDAD_DIDACTICA , 
		          1 ,
				  1 , 
		          @USUARIO , 
		          GETDATE()
		        )

		SET @NOMBRE_MODULO = (SELECT NOMBRE_MODULO FROM transaccional.modulo WHERE ID_MODULO = @ID_MODULO)
	END
	ELSE BEGIN
		UPDATE transaccional.unidad_didactica SET
			ID_MODULO = @ID_MODULO , 
		    ID_SEMESTRE_ACADEMICO = @ID_SEMESTRE_ACADEMICO , 
		    ID_TIPO_UNIDAD_DIDACTICA = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL ELSE @ID_TIPO_UNIDAD_DIDACTICA END), 
		    CODIGO_UNIDAD_DIDACTICA = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL ELSE @CODIGO_CORRELATIVO END), 
		    NOMBRE_UNIDAD_DIDACTICA = @NOMBRE_UNIDAD_DIDACTICA , 
		    DESCRIPCION = 'MantenimientoUD' , 
		    PERIODO_ACADEMICO_I = (CASE @ID_SEMESTRE_ACADEMICO WHEN 111 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		    PERIODO_ACADEMICO_II = (CASE @ID_SEMESTRE_ACADEMICO WHEN 112 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		    PERIODO_ACADEMICO_III = (CASE @ID_SEMESTRE_ACADEMICO WHEN 113 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		    PERIODO_ACADEMICO_IV = (CASE @ID_SEMESTRE_ACADEMICO WHEN 114 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		    PERIODO_ACADEMICO_V = (CASE @ID_SEMESTRE_ACADEMICO WHEN 115 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		    PERIODO_ACADEMICO_VI = (CASE @ID_SEMESTRE_ACADEMICO WHEN 116 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) ,
		    TEORICO_PRACTICO_HORAS_UD = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_MODULAR THEN @HORAS_TP ELSE NULL END) , 
		    PRACTICO_HORAS_UD = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_MODULAR THEN @HORAS_P ELSE NULL END) , 
		    HORAS = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN @HORAS WHEN @PLAN_TRANSVERSAL THEN @HORAS * 18 WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) , 
		    TEORICO_PRACTICO_CREDITOS_UD = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_MODULAR THEN @CREDITOS_T ELSE NULL END) , 
		    PRACTICO_CREDITOS_UD = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_MODULAR THEN @CREDITOS_P ELSE NULL END) , 
		    CREDITOS = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @CREDITOS WHEN @PLAN_MODULAR THEN @CREDITOS_T + @CREDITOS_P END) , 
		    CREDITOS_ME = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_TRANSVERSAL THEN @HORAS * 18 ELSE NULL END) , 
		    ES_ACTIVO = 1 , 
		    ESTADO= 1 , 
		    USUARIO_MODIFICACION = @USUARIO , 
		    FECHA_MODIFICACION = GETDATE() , 
		    PERIODO_ACADEMICO_VII = (CASE @ID_SEMESTRE_ACADEMICO WHEN 137 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END) , 
		    PERIODO_ACADEMICO_VIII = (CASE @ID_SEMESTRE_ACADEMICO WHEN 138 THEN (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN NULL WHEN @PLAN_TRANSVERSAL THEN @HORAS WHEN @PLAN_MODULAR THEN @HORAS_TP + @HORAS_P END) ELSE NULL END)
		WHERE ID_UNIDAD_DIDACTICA=@ID_UNIDAD_DIDACTICA
	END

	UPDATE m SET 
		m.NOMBRE_MODULO = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_ASIGNATURA THEN m.NOMBRE_MODULO ELSE @NOMBRE_MODULO END),
		m.HORAS_ME = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_TRANSVERSAL THEN mx.TOTAL_CREDITOS ELSE NULL END),
		m.TOTAL_HORAS = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_TRANSVERSAL THEN mx.TOTAL_HORAS ELSE NULL END),
		--CREDITOS_ME = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_TRANSVERSAL THEN mx.TOTAL_CREDITOS ELSE NULL END),
		m.TOTAL_HORAS_UD = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_MODULAR THEN mx.TOTAL_HORAS ELSE NULL END),
		m.TOTAL_CREDITOS_UD = (CASE @ID_TIPO_ITINERARIO WHEN @PLAN_MODULAR THEN mx.TOTAL_CREDITOS ELSE NULL END),
		m.USUARIO_MODIFICACION = @USUARIO,
		m.FECHA_MODIFICACION = GETDATE()
	FROM transaccional.modulo m
	INNER JOIN (SELECT ID_MODULO,TOTAL_HORAS=SUM(ud.HORAS),TOTAL_CREDITOS=SUM(ud.CREDITOS)
				FROM transaccional.unidad_didactica ud
				WHERE ID_MODULO = @ID_MODULO AND ud.ES_ACTIVO=1
				GROUP BY ID_MODULO) mx ON mx.ID_MODULO = m.ID_MODULO

	COMMIT TRAN TransactSQL
	SELECT 1 AS valor

	END TRY

	BEGIN CATCH
		ROLLBACK TRAN TransactSQL
		DECLARE @ERROR_MESSAGE VARCHAR(MAX) = ''
		SET @ERROR_MESSAGE = ERROR_MESSAGE() + ' -- '
		SELECT 'Error: ' + @ERROR_MESSAGE
		SELECT 0 AS valor
	END CATCH
END