CREATE PROCEDURE [dbo].[USP_MAESTROS_SEL_NIVEL_FORMACION_LISTA]
AS
SELECT 
	NOMBRE_NIVEL_FORMACION	Text,
	ID_NIVEL_FORMACION		Value,
	ID_NIVEL_FORMACION		Code
FROM 
	maestro.nivel_formacion
ORDER BY SEMESTRES_ACADEMICOS ASC
GO


