/**********************************************************************************************************
AUTOR				:	Juan Tovar
FECHA DE CREACION	:	20/06/2019
LLAMADO POR			:
DESCRIPCION			:	Inserta un registro de peridoo lectivo 
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
--  TEST:			
	EXEC USP_MAESTROS_INS_PERIODO_LECTIVO '2020-1',172,'2014-06-24 00:00:00','2014-12-24 00:00:00','MR'
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_MAESTROS_INS_PERIODO_LECTIVO]
(
	@CODIGO_PERIODO_LECTIVO VARCHAR(20),
	@ID_ENUMERADO_TIPO_OPCION INT,
	@FECHA_INICIO DATETIME,
	@FECHA_FIN DATETIME,
	@USUARIO VARCHAR(20)
)
AS
DECLARE @RESULT INT
IF EXISTS(	SELECT pl.ID_PERIODO_LECTIVO 
			FROM maestro.periodo_lectivo pl 
			WHERE pl.ESTADO=1 AND pl.ID_TIPO_OPCION = @ID_ENUMERADO_TIPO_OPCION AND 
				((@FECHA_INICIO BETWEEN pl.FECHA_INICIO AND pl.FECHA_FIN) 
				OR (@FECHA_FIN BETWEEN pl.FECHA_INICIO AND pl.FECHA_FIN))) 
BEGIN 
    SET @RESULT = -30
END
ELSE
BEGIN 
    IF EXISTS(SELECT TOP 1 ID_PERIODO_LECTIVO 
			 FROM maestro.periodo_lectivo 
			 WHERE CODIGO_PERIODO_LECTIVO = UPPER(@CODIGO_PERIODO_LECTIVO) COLLATE LATIN1_GENERAL_CI_AI  
			 AND ID_TIPO_OPCION=@ID_ENUMERADO_TIPO_OPCION AND ESTADO=1)
	    SET @RESULT = -180
    ELSE
    BEGIN    
		BEGIN TRANSACTION T1
		BEGIN TRY
			DECLARE @ANIO smallint= (SELECT CAST(LEFT(@CODIGO_PERIODO_LECTIVO,4) AS int))					  
			INSERT INTO maestro.periodo_lectivo(
			CODIGO_PERIODO_LECTIVO,ID_TIPO_OPCION,FECHA_INICIO,FECHA_FIN,ANIO,ES_ASIGNADO,ESTADO,FECHA_CREACION,USUARIO_CREACION)
			VALUES(UPPER(@CODIGO_PERIODO_LECTIVO),@ID_ENUMERADO_TIPO_OPCION,@FECHA_INICIO,@FECHA_FIN,@ANIO,0,1,GETDATE(),@USUARIO)
		  	--EXEC [USP_MAESTROS_INS_PERIODO_LECTIVO_INSTITUCION_MASIVO_DIRECTO] @@IDENTITY,@FECHA_INICIO,@FECHA_FIN,@USUARIO

		COMMIT TRANSACTION T1

		SET @RESULT = 1
		END TRY	   
		BEGIN CATCH
			IF @@ERROR<>0
			BEGIN
				ROLLBACK TRANSACTION T1	   
				SELECT -1
			END
		END CATCH
    END
END
SELECT @RESULT
GO


