/**********************************************************************************************************
AUTOR				:	Juan Tovar
FECHA DE CREACION	:	20/06/2019
LLAMADO POR			:
DESCRIPCION			:	Inserta un registro de institución básica
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
--  TEST:			
/*
	
*/
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_MAESTROS_INS_INSTITUCION_BASICA]
(
	@ID_INSTITUCION_BASICA			INT OUTPUT,
	@ID_TIPO_INSTITUCION_BASICA		INT,
	@CODIGO_MODULAR					VARCHAR(7),
	@NOMBRE_IE_BASICA				VARCHAR(150),
	@ID_NIVEL_IE_BASICA				INT,
	@ID_TIPO_GESTION_IE_BASICA		INT,
	@DIRECCION_IE_BASICA			VARCHAR(255),
	@ID_PAIS_BASICA					INT,
	@UBIGEO_IE_BASICA				VARCHAR(6),
	@USUARIO						VARCHAR(20)
)AS
BEGIN
	IF NOT EXISTS(SELECT TOP 1 ID_INSTITUCION_BASICA FROM maestro.institucion_basica
		WHERE ID_TIPO_INSTITUCION_BASICA = @ID_TIPO_INSTITUCION_BASICA AND CODIGO_MODULAR_IE_BASICA = @CODIGO_MODULAR
		AND ID_PAIS = @ID_PAIS_BASICA)
	BEGIN
		INSERT INTO maestro.institucion_basica(
			ID_TIPO_INSTITUCION_BASICA,
			CODIGO_MODULAR_IE_BASICA,
			NOMBRE_IE_BASICA,
			ID_NIVEL_IE_BASICA,
			ID_TIPO_GESTION_IE_BASICA,
			DIRECCION_IE_BASICA,
			ID_PAIS,
			UBIGEO_IE_BASICA,
			ESTADO,
			USUARIO_CREACION,
			FECHA_CREACION
		)VALUES(
			@ID_TIPO_INSTITUCION_BASICA,
			@CODIGO_MODULAR,
			@NOMBRE_IE_BASICA,
			@ID_NIVEL_IE_BASICA,
			@ID_TIPO_GESTION_IE_BASICA,
			@DIRECCION_IE_BASICA,
			@ID_PAIS_BASICA,
			@UBIGEO_IE_BASICA,
			1,
			@USUARIO,
			GETDATE()
		)
	END
	ELSE
	BEGIN
		SET @ID_INSTITUCION_BASICA = (SELECT TOP 1 ID_INSTITUCION_BASICA FROM maestro.institucion_basica
			WHERE ID_TIPO_INSTITUCION_BASICA = @ID_TIPO_INSTITUCION_BASICA AND CODIGO_MODULAR_IE_BASICA = @CODIGO_MODULAR
			AND ID_PAIS = @ID_PAIS_BASICA)

		UPDATE maestro.institucion_basica
		SET NOMBRE_IE_BASICA = @NOMBRE_IE_BASICA,
			ID_NIVEL_IE_BASICA = @ID_NIVEL_IE_BASICA,
			ID_TIPO_GESTION_IE_BASICA = @ID_TIPO_GESTION_IE_BASICA,
			DIRECCION_IE_BASICA = @DIRECCION_IE_BASICA,
			UBIGEO_IE_BASICA = @UBIGEO_IE_BASICA,
			USUARIO_MODIFICACION = @USUARIO,
			FECHA_MODIFICACION = GETDATE()
		WHERE 
			ID_INSTITUCION_BASICA = @ID_INSTITUCION_BASICA

	END
END
GO


