CREATE PROCEDURE [dbo].[USP_MAESTROS_SEL_PERIODO_LECTIVO_POR_ID]
(
	@ID_PERIODO_LECTIVO		INT,
	@ID_INSTITUCION	INT
)
AS
SET NOCOUNT ON;
DECLARE @ESTADO_PERIODO_LECTIVO_CREADO INT
--SET @ESTADO_PERIODO_LECTIVO_CREADO =	(SELECT ISNULL((SELECT ISNULL(ID_ENUMERADO,0) FROM sistema.enumerado WHERE ID_TIPO_ENUMERADO = 4 AND VALOR_ENUMERADO = 'CREADO' COLLATE LATIN1_GENERAL_CI_AI),0)) -- *4 ESTADOS PERIODOS LECTIVOS
SELECT	PL.ID_PERIODO_LECTIVO IdPeriodoLectivo,
		PL.FECHA_INICIO FechaInicio,
		PL.FECHA_FIN FechaFin,
		(SELECT COUNT(ESTADO) FROM transaccional.periodos_lectivos_por_institucion 
		WHERE ID_PERIODO_LECTIVO = PL.ID_PERIODO_LECTIVO
		AND ES_ACTIVO = 1 AND ID_INSTITUCION = @ID_INSTITUCION
		AND ESTADO <> 6) CantidadPeriodoLectivoInstitucion
FROM	maestro.periodo_lectivo PL
		--INNER JOIN sistema.enumerado E ON E.ID_ENUMERADO = PLI.ESTADO
WHERE 
		PL.ID_PERIODO_LECTIVO = @ID_PERIODO_LECTIVO
GO


