/**********************************************************************************************************
AUTOR				:	Juan Tovar
FECHA DE CREACION	:	20/06/2019
LLAMADO POR			:
DESCRIPCION			:	Inserta el registro de personal en la institución
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------

--  TEST:			
/*
	EXEC USP_MAESTROS_INS_PERSONAL_INSTITUCION  --171,195,0,26,'44147844','CYNTHIA MAGALY','YALICO','LA TORRE','1977-09-04',
	36,92330,'090601',32,92330,'140101','av. lima 123','012513744','976885522','','MIN0001@yopmail.com',43,'Contadora',
	1151,443,'UNMSM',2006,2010,895,50,0,30,49,0,'MALVA'

	1.0    12/11/2019    JTOVAR          SE AGREGO EL CAMBIO PARA QUE PERMITA EL REGISTRO DE MAS DE UN SCRETARIO ACADEMICO
	1.1    13/01/2019    JTOVAR          SE AGREGÓ VALIDACIÓN SI EL PERSONAL YA EXISTE
*/
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_MAESTROS_INS_PERSONAL_INSTITUCION]
(

	@ID_PERSONA						INT,
	@ID_PERSONA_INSTITUCION			INT,
	@ID_PERSONAL_INSTITUCION		INT,

	@ID_TIPO_DOCUMENTO				INT,
	@NUMERO_DOCUMENTO_PERSONA		VARCHAR(16),
	@NOMBRE_PERSONA					VARCHAR(50),
	@APELLIDO_PATERNO_PERSONA		VARCHAR(40),
	@APELLIDO_MATERNO_PERSONA		VARCHAR(40),
    @FECHA_NACIMIENTO_PERSONA		DATETIME,
	@SEXO_PERSONA					INT,
	--@ID_LENGUA_MATERNA			INT,
	--@ES_DISCAPACITADO				BIT,
	@PAIS_NACIMIENTO				INT,
	@UBIGEO_NACIMIENTO				VARCHAR(6),
	
	@ESTADO_CIVIL					INT,
	@PAIS_PERSONA					INT,
	@UBIGEO_PERSONA					VARCHAR(6),
	@DIRECCION_PERSONA				VARCHAR(255),
	@TELEFONO						VARCHAR(15),
	@CELULAR						VARCHAR(15),
	@CELULAR2						VARCHAR(15),
	@CORREO							VARCHAR(100),
	--@ID_TIPO_DISCAPACIDAD			INT,
	@ID_GRADO_PROFESIONAL			INT,
	@TITULO_PROFESIONAL				VARCHAR(150),
	@ID_CARRERA_PROFESIONAL			INT,
	@ID_INSTITUCION					INT,
	@INSTITUCION_PROFESIONAL		VARCHAR(150),
	@ANIO_INICIO					INT,
	@ANIO_FIN						INT,

	@ID_PERIODO_LECTIVO_INSTITUCION	INT,
	@CONDICION_LABORAL				INT,
	@CARGO_PERSONA					INT,
	@ID_TIPO_PERSONAL				INT,
	@ID_ROL							INT,
	@ID_PERMISO_PASSPORT			INT,
	@USUARIO						VARCHAR(20)


	--DECLARE @ID_PERSONA						INT=1365
	--DECLARE @ID_PERSONA_INSTITUCION			INT=1423
	--DECLARE @ID_PERSONAL_INSTITUCION		INT=0

	--DECLARE @ID_TIPO_DOCUMENTO				INT=26
	--DECLARE @NUMERO_DOCUMENTO_PERSONA		VARCHAR(16)='42122536'
	--DECLARE @NOMBRE_PERSONA					VARCHAR(50)='JUAN JOSE'
	--DECLARE @APELLIDO_PATERNO_PERSONA		VARCHAR(40)='TOVAR'
	--DECLARE @APELLIDO_MATERNO_PERSONA		VARCHAR(40)='YAÑEZ'
 --   DECLARE @FECHA_NACIMIENTO_PERSONA		DATETIME='1983-06-25'
	--DECLARE @SEXO_PERSONA					INT=35
	----@ID_LENGUA_MATERNA			INT,
	----@ES_DISCAPACITADO				BIT,
	--DECLARE @PAIS_NACIMIENTO				INT=92330
	--DECLARE @UBIGEO_NACIMIENTO				VARCHAR(6)='140117'
	
	--DECLARE @ESTADO_CIVIL					INT=32
	--DECLARE @PAIS_PERSONA					INT=92330
	--DECLARE @UBIGEO_PERSONA					VARCHAR(6)='140122'
	--DECLARE @DIRECCION_PERSONA				VARCHAR(255)='CALLE LOS ANDES 246 LOS ANGELES'
	--DECLARE @TELEFONO						VARCHAR(15)='014252656'
	--DECLARE @CELULAR						VARCHAR(15)='985656568'
	--DECLARE @CELULAR2						VARCHAR(15)=''
	--DECLARE @CORREO							VARCHAR(100)='jtovar@minedu.gob.pe'
	----@ID_TIPO_DISCAPACIDAD			INT,
	--DECLARE @ID_GRADO_PROFESIONAL			INT=43
	--DECLARE @TITULO_PROFESIONAL				VARCHAR(150)='SISTEMAS'
	--DECLARE @ID_CARRERA_PROFESIONAL			INT=1
	--DECLARE @ID_INSTITUCION					INT=1911
	--DECLARE @INSTITUCION_PROFESIONAL		VARCHAR(150)='UNI'
	--DECLARE @ANIO_INICIO					INT=1999
	--DECLARE @ANIO_FIN						INT=2005

	--DECLARE @ID_PERIODO_LECTIVO_INSTITUCION	INT=10318
	--DECLARE @CONDICION_LABORAL				INT=50
	--DECLARE @CARGO_PERSONA					INT=0
	--DECLARE @ID_TIPO_PERSONAL				INT=30
	--DECLARE @ID_ROL							INT=49
	--DECLARE @ID_PERMISO_PASSPORT			INT=0
	--DECLARE @USUARIO						VARCHAR(20)='42122536'

)
AS 
	DECLARE @RESULT INT, @ID_ROL_DOCENTE INT, @ID_ROL_DIRECTOR INT, @ID_ROL_SECRETARIO INT, @ID_ROL_JEFE_UNIDAD INT, @ID_ROL_SECRETARIA INT, @ID_JEFE_AREA INT, @ID_JEFE_ADMINISTRATIVA INT, @ID_ADMINISTRADOR INT,
	@ID_PERSONAL_SERVICIO INT, @BIBLIOTECARIO INT, @ID_AUXILIAR INT
	SET @ID_ROL_DOCENTE = 49
	SET @ID_ROL_DIRECTOR=47
	SET @ID_ROL_SECRETARIO=48

	SET @ID_ROL_JEFE_UNIDAD=218
	SET @ID_ROL_SECRETARIA=219

	SET @ID_JEFE_AREA=220
	SET @ID_JEFE_ADMINISTRATIVA=221
	SET @ID_ADMINISTRADOR=222
	SET @ID_PERSONAL_SERVICIO=223
	SET @BIBLIOTECARIO=224
	SET @ID_AUXILIAR=225

	IF EXISTS (SELECT TOP 1 personalInstitucion.ID_PERSONAL_INSTITUCION 
				FROM maestro.persona p INNER JOIN maestro.persona_institucion pinstitucion
				ON p.ID_PERSONA = pinstitucion.ID_PERSONA INNER JOIN maestro.personal_institucion personalInstitucion
				ON pinstitucion.ID_PERSONA_INSTITUCION = personalInstitucion.ID_PERSONA_INSTITUCION
				WHERE personalInstitucion.ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION AND personalInstitucion.ID_ROL=@ID_ROL
				AND p.ID_TIPO_DOCUMENTO=@ID_TIPO_DOCUMENTO AND p.NUMERO_DOCUMENTO_PERSONA=@NUMERO_DOCUMENTO_PERSONA AND personalInstitucion.ES_ACTIVO=1)
	BEGIN
	SET @RESULT = -180

	END
	ELSE
	BEGIN

		IF EXISTS(SELECT TOP 1 ID_ROL FROM maestro.personal_institucion
                       WHERE ES_ACTIVO=1 AND ESTADO=1 AND ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION AND ID_ROL=@ID_ROL 
					   AND ID_ROL IN (@ID_ROL_DIRECTOR,@ID_ROL_JEFE_UNIDAD, @ID_ROL_SECRETARIA, @ID_JEFE_AREA,@ID_JEFE_ADMINISTRATIVA,@ID_ADMINISTRADOR,@ID_PERSONAL_SERVICIO,@BIBLIOTECARIO,@ID_AUXILIAR ))
	
		SET @RESULT = -114	
	
	ELSE IF EXISTS (select TOP 1 ID_PERSONAL_INSTITUCION from maestro.personal_institucion 
						where ID_PERSONA_INSTITUCION=@ID_PERSONA_INSTITUCION 
						AND ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION AND ES_ACTIVO=1
						AND ID_ROL = @ID_ROL  )
						BEGIN
							IF @ID_ROL = @ID_ROL_DOCENTE SET @RESULT = -245
							ELSE SET @RESULT = -88
						END
	ELSE
	BEGIN
		
		BEGIN TRY
		BEGIN TRANSACTION T1
			SET @RESULT =0
			--GRABO LA PERSONA
	
			IF @ID_PERSONA = 0	
				BEGIN
					INSERT INTO maestro.persona(
					ID_TIPO_DOCUMENTO,
					NUMERO_DOCUMENTO_PERSONA,
					NOMBRE_PERSONA,
					APELLIDO_PATERNO_PERSONA,
					APELLIDO_MATERNO_PERSONA,
					FECHA_NACIMIENTO_PERSONA,
					SEXO_PERSONA,
					ID_LENGUA_MATERNA,
					UBIGEO_NACIMIENTO,
					PAIS_NACIMIENTO,
					ESTADO,
					USUARIO_CREACION,
					FECHA_CREACION
					)VALUES(
						@ID_TIPO_DOCUMENTO,
						@NUMERO_DOCUMENTO_PERSONA,
						@NOMBRE_PERSONA,
						@APELLIDO_PATERNO_PERSONA,
						@APELLIDO_MATERNO_PERSONA,
						@FECHA_NACIMIENTO_PERSONA,
						@SEXO_PERSONA,
						0,
						@UBIGEO_NACIMIENTO,
						@PAIS_NACIMIENTO,
						1,
						@USUARIO,
						GETDATE()
					)	
					SET @ID_PERSONA = CONVERT(INT,@@IDENTITY)
				END	
				ELSE
				BEGIN
					IF @ID_TIPO_DOCUMENTO <> 26
					BEGIN
						UPDATE maestro.persona
						SET NOMBRE_PERSONA=@NOMBRE_PERSONA,
						APELLIDO_PATERNO_PERSONA=@APELLIDO_PATERNO_PERSONA,
						APELLIDO_MATERNO_PERSONA=@APELLIDO_MATERNO_PERSONA,
						SEXO_PERSONA = @SEXO_PERSONA ,
						FECHA_NACIMIENTO_PERSONA=@FECHA_NACIMIENTO_PERSONA,
						PAIS_NACIMIENTO=@PAIS_NACIMIENTO,
						UBIGEO_NACIMIENTO=RIGHT(REPLICATE('0',6) + @UBIGEO_NACIMIENTO,6)
						WHERE ID_PERSONA= @ID_PERSONA
					END					
				END			
		
				
				IF @ID_PERSONA_INSTITUCION = 0
				BEGIN
					INSERT INTO maestro.persona_institucion(
					ID_PERSONA,
					ESTADO_CIVIL,
					PAIS_PERSONA,
					UBIGEO_PERSONA,
					DIRECCION_PERSONA,
					TELEFONO,
					CELULAR,
					CELULAR2,
					CORREO,
					ID_TIPO_DISCAPACIDAD,
					ID_GRADO_PROFESIONAL,
					TITULO_PROFESIONAL,
					ID_CARRERA_PROFESIONAL,
					ID_INSTITUCION,
					INSTITUCION_PROFESIONAL,
					ANIO_INICIO,
					ANIO_FIN,
					NIVEL_EDUCATIVO,
					ESTADO,
					USUARIO_CREACION,
					FECHA_CREACION
				)VALUES(
					@ID_PERSONA,
					@ESTADO_CIVIL,
					@PAIS_PERSONA,
					@UBIGEO_PERSONA,
					@DIRECCION_PERSONA,
					ISNULL(@TELEFONO,''),
					@CELULAR,
					@CELULAR2,
					@CORREO,
					0,
					@ID_GRADO_PROFESIONAL,
					@TITULO_PROFESIONAL,
					@ID_CARRERA_PROFESIONAL,
					@ID_INSTITUCION,
					@INSTITUCION_PROFESIONAL,
					@ANIO_INICIO,
					@ANIO_FIN,
					0,
					1,
					@USUARIO,
					GETDATE()					
				)
					SET @ID_PERSONA_INSTITUCION = @@IDENTITY
				END	
				ELSE
				BEGIN
					UPDATE maestro.persona_institucion
					SET ESTADO_CIVIL = @ESTADO_CIVIL,
						PAIS_PERSONA = @PAIS_PERSONA,
						UBIGEO_PERSONA = @UBIGEO_PERSONA,
						DIRECCION_PERSONA = @DIRECCION_PERSONA,
						TELEFONO = ISNULL(@TELEFONO,''),
						CELULAR = @CELULAR,
						CELULAR2 = @CELULAR2,
						CORREO = @CORREO,
						ID_GRADO_PROFESIONAL = @ID_GRADO_PROFESIONAL,
						TITULO_PROFESIONAL = @TITULO_PROFESIONAL,
						ID_CARRERA_PROFESIONAL = @ID_CARRERA_PROFESIONAL,
						INSTITUCION_PROFESIONAL = @INSTITUCION_PROFESIONAL,
						ANIO_INICIO = @ANIO_INICIO,
						ANIO_FIN = @ANIO_FIN,
						ESTADO = 1,
						USUARIO_MODIFICACION = @USUARIO,
						FECHA_MODIFICACION = GETDATE()
					WHERE ID_PERSONA_INSTITUCION = @ID_PERSONA_INSTITUCION
				END		
				
				IF @ID_PERSONAL_INSTITUCION = 0
				BEGIN
					INSERT INTO maestro.personal_institucion(
						ID_PERSONA_INSTITUCION,
						ID_PERIODOS_LECTIVOS_POR_INSTITUCION,
						CONDICION_LABORAL,
						CARGO_PERSONA,
						ID_TIPO_PERSONAL,
						ID_ROL,
						ID_PERMISO_PASSPORT,
						ES_ACTIVO,
						ESTADO,
						USUARIO_CREACION,
						FECHA_CREACION
					)VALUES(
						@ID_PERSONA_INSTITUCION,
						@ID_PERIODO_LECTIVO_INSTITUCION,
						@CONDICION_LABORAL,
						@CARGO_PERSONA,
						@ID_TIPO_PERSONAL,
						@ID_ROL,
						@ID_PERMISO_PASSPORT,
						1,
						1,
						@USUARIO,
						GETDATE()
					)
				END

			COMMIT TRANSACTION T1	
			SET @RESULT = 1			
		END TRY
		BEGIN CATCH
			IF @@ERROR = 50000
			BEGIN
				ROLLBACK TRANSACTION T1	   
				SET @RESULT = -180
			END
			ELSE
				IF @@ERROR <> 0
				BEGIN
					ROLLBACK TRANSACTION T1	   
					SET @RESULT = -1
				END
				ELSE
				BEGIN
					ROLLBACK TRANSACTION T1	   
					SET @RESULT = -2
					PRINT ERROR_MESSAGE()
				END
		END CATCH
	END


	END




SELECT @RESULT
GO


