/**********************************************************************************************************
AUTOR				:	Juan Chavez
FECHA DE CREACION	:	30/11/2021
LLAMADO POR			:
DESCRIPCION			:	Actualiza datos de un plan de estudio
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO     DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
1.0			30/11/2021		JCHAVEZ		Creación

TEST:     
  EXEC USP_INSTITUCION_UDP_CONVERTIR_PLAN_ESTUDIO 1389,'70557821'
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_INSTITUCION_UDP_CONVERTIR_PLAN_ESTUDIO]
 @ID_PLAN_ESTUDIO INT,
 @USUARIO VARCHAR(20)
AS
BEGIN
	DECLARE @MSG_TRANS VARCHAR(MAX)
	DECLARE @ID_CORRELATIVO INT,
		@NUM_CORRELATIVO INT,
		@NEW_CORRELATIVO INT,
		@CODIGO_GENERADO NVARCHAR(12)

	BEGIN TRY

		BEGIN TRAN TransactSQL

		DECLARE @FECHA_ACTUAL DATETIME = GETDATE()
		DECLARE @ID_CARRERAS_POR_INSTITUCION INT

		SET @ID_CARRERAS_POR_INSTITUCION = (SELECT ID_CARRERAS_POR_INSTITUCION FROM transaccional.plan_estudio WHERE ID_PLAN_ESTUDIO = @ID_PLAN_ESTUDIO)

		UPDATE ud SET 
			ID_TIPO_UNIDAD_DIDACTICA=(CASE ID_TIPO_UNIDAD_DIDACTICA WHEN 2 THEN 6 WHEN 1 THEN 5 END),
			ud.TEORICO_PRACTICO_HORAS_UD=NULL,ud.PRACTICO_HORAS_UD=NULL,ud.HORAS=ud.HORAS*18,
			ud.TEORICO_PRACTICO_CREDITOS_UD=NULL,ud.PRACTICO_CREDITOS_UD=NULL,ud.CREDITOS_ME=(CASE ID_TIPO_UNIDAD_DIDACTICA WHEN 2 THEN NULL WHEN 1 THEN ud.HORAS*18 END),
			USUARIO_MODIFICACION=@USUARIO,FECHA_MODIFICACION=@FECHA_ACTUAL
		FROM transaccional.plan_estudio pe
		INNER JOIN transaccional.modulo m ON pe.ID_PLAN_ESTUDIO=m.ID_PLAN_ESTUDIO
		INNER JOIN transaccional.unidad_didactica ud ON m.ID_MODULO=ud.ID_MODULO
		WHERE pe.ID_PLAN_ESTUDIO=@ID_PLAN_ESTUDIO
			
		--Convierte módulos de modulares a transversales
		INSERT INTO transaccional.modulo (ID_PLAN_ESTUDIO,ID_TIPO_MODULO,CODIGO_MODULO,NOMBRE_MODULO,HORAS_ME,CREDITOS_ME,ES_ACTIVO,ESTADO,USUARIO_CREACION,FECHA_CREACION)
		VALUES  (@ID_PLAN_ESTUDIO,160,'ConsultarJtovar','TRANSVERSALES',810,33,1,1,@USUARIO,@FECHA_ACTUAL)

		UPDATE m SET ID_TIPO_MODULO=159,TOTAL_HORAS=mx.TOTAL_HORAS,TOTAL_HORAS_UD=NULL,TOTAL_CREDITOS_UD=NULL,USUARIO_MODIFICACION=@USUARIO,FECHA_MODIFICACION=@FECHA_ACTUAL 
		FROM transaccional.modulo m
		INNER JOIN (SELECT m.ID_MODULO,TOTAL_HORAS=SUM(ud.HORAS)
					FROM transaccional.modulo m
					INNER JOIN transaccional.unidad_didactica ud ON ud.ID_MODULO = m.ID_MODULO
					WHERE m.ID_MODULO IN (SELECT ID_MODULO FROM transaccional.modulo WHERE ID_PLAN_ESTUDIO=@ID_PLAN_ESTUDIO AND ES_ACTIVO=1) AND ud.ID_TIPO_UNIDAD_DIDACTICA=5
					GROUP BY m.ID_MODULO) mx ON mx.ID_MODULO = m.ID_MODULO

		UPDATE transaccional.unidad_didactica SET ID_MODULO=@@IDENTITY,USUARIO_MODIFICACION=@USUARIO,FECHA_MODIFICACION=@FECHA_ACTUAL 
		WHERE ID_MODULO IN (SELECT ID_MODULO FROM transaccional.modulo WHERE ID_PLAN_ESTUDIO=@ID_PLAN_ESTUDIO AND ES_ACTIVO=1) AND ID_TIPO_UNIDAD_DIDACTICA=6

		--Convierte plan de estudio de modular a transversal
		UPDATE transaccional.enfoques_por_plan_estudio SET ID_ENFOQUE=NULL,USUARIO_MODIFICACION=@USUARIO,FECHA_MODIFICACION=@FECHA_ACTUAL WHERE ID_PLAN_ESTUDIO=@ID_PLAN_ESTUDIO
		
		UPDATE transaccional.plan_estudio SET ID_TIPO_ITINERARIO=100,USUARIO_MODIFICACION=@USUARIO,FECHA_MODIFICACION=@FECHA_ACTUAL WHERE ID_PLAN_ESTUDIO=@ID_PLAN_ESTUDIO

		UPDATE transaccional.carreras_por_institucion SET ID_TIPO_ITINERARIO=100,USUARIO_MODIFICACION=@USUARIO,FECHA_MODIFICACION=@FECHA_ACTUAL 
		WHERE ID_CARRERAS_POR_INSTITUCION = @ID_CARRERAS_POR_INSTITUCION

		COMMIT TRAN TransactSQL

		SELECT 1 AS Value

	END TRY

	BEGIN CATCH
		ROLLBACK TRAN TransactSQL
		DECLARE @ERROR_MESSAGE VARCHAR(MAX) = ''
		SET @ERROR_MESSAGE = ERROR_MESSAGE() + ' -- '
		SET @MSG_TRANS = (SELECT 'Error: ' + @ERROR_MESSAGE)
		SELECT -189 AS Value
	END CATCH
END