
CREATE PROCEDURE [dbo].[USP_PLANIFICACION_INS_UNIDAD_DIDACTICA_X_PROGRAMACION]
(  

@ID_UNIDADES_DIDACTICAS_POR_ENFOQUE INT,
@ID_PROGRAMACION_CLASE INT,
@ES_ACTIVO BIT=1,  
@ESTADO      smallint=1,  --118?
@USUARIO VARCHAR(20)
)  
AS 

DECLARE @RESULT INT
 BEGIN  
	

				INSERT INTO transaccional.unidades_didacticas_por_programacion_clase(
							ID_UNIDADES_DIDACTICAS_POR_ENFOQUE,
							ID_PROGRAMACION_CLASE,
							ES_ACTIVO,
							ESTADO,
							USUARIO_CREACION,
							FECHA_CREACION) 
				VALUES (	@ID_UNIDADES_DIDACTICAS_POR_ENFOQUE, 
							@ID_PROGRAMACION_CLASE,
							@ES_ACTIVO,
							@ESTADO,
							@USUARIO,
							GETDATE()
				)
	
			SET @RESULT = 1
END  
SELECT @RESULT
GO


