CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_CANTIDAD_POSTULANTES_SEDE_MODALIDAD_PAGINADO] 
(
    @ID_INSTITUCION INT,
	@ID_PERIODO_LECTIVO_INSTITUCION INT,
	@ID_SEDE_INSTITUCION INT,
	@ID_MODALIDAD INT,
	@Pagina						int		=1,
	@Registros					int		=10

	--DECLARE @ID_INSTITUCION INT=440
	--DECLARE @ID_PERIODO_LECTIVO_INSTITUCION INT=5517
	--DECLARE @ID_SEDE_INSTITUCION INT=0
	--DECLARE @ID_MODALIDAD INT=0
	--DECLARE @Pagina						int		=1
	--DECLARE @Registros					int		=10

)AS
BEGIN
SET NOCOUNT ON;

DECLARE @ID_MODALIDAD_EXONERADO INT =23 --DE ENUMERADOS
	DECLARE @desde INT , @hasta INT;
	
	SET @desde = ( @Pagina - 1 ) * @Registros;
    SET @hasta = ( @Pagina * @Registros ) + 1; 
    
	WITH    tempPaginado AS
	(

	SELECT 
	MXPA.ID_MODALIDADES_POR_PROCESO_ADMISION								IdModalidadProcesoAdmision,
	EAS.ID_EXAMEN_ADMISION_SEDE												ID_EXAMEN_ADMISION_SEDE,
	EAS.ID_MODALIDAD														IdModalidad, 
	EAS.ID_SEDE_INSTITUCION													IdSedeInstitucion, 
	SI.NOMBRE_SEDE															Sede,
	se_modalidad.VALOR_ENUMERADO											Modalidad,
	CONVERT (VARCHAR(10),  EAS.FECHA_EVALUACION, 103)						Fecha,  
	EAS.HORA_EVALUACION														Hora, 
	ISNULL(SUBCONSULTA_POSTULANTES.TOTAL_POSTULANTES_EXAMEN_SEDE, 0)		Cantidad,
	ISNULL(SUBCONSULTA_SEDES.MINIMO_AFORO_SEDE,0)							AforoMin,
	CASE WHEN SUBCONSULTA_SEDES.MINIMO_AFORO_SEDE IS NULL THEN 0 
		 WHEN SUBCONSULTA_POSTULANTES.TOTAL_POSTULANTES_EXAMEN_SEDE = SUBCONSULTA_SEDES.MINIMO_AFORO_SEDE  THEN 
		 (	SELECT CEILING(ISNULL(SUBCONSULTA_POSTULANTES.TOTAL_POSTULANTES_EXAMEN_SEDE, 0)/ISNULL(SUBCONSULTA_SEDES.MINIMO_AFORO_SEDE,1)) ) 
		 ELSE
		 --(	SELECT CEILING(ISNULL(SUBCONSULTA_POSTULANTES.TOTAL_POSTULANTES_EXAMEN_SEDE, 0)/ISNULL(SUBCONSULTA_SEDES.MINIMO_AFORO_SEDE,1)) + CASE WHEN ISNULL(SUBCONSULTA_SEDES.MINIMO_AFORO_SEDE,0)>0 THEN 1 ELSE 0 END)
		 (	SELECT convert(int, CEILING( ISNULL( convert(float,SUBCONSULTA_POSTULANTES.TOTAL_POSTULANTES_EXAMEN_SEDE), 0)
							/ISNULL( convert(float,SUBCONSULTA_SEDES.MINIMO_AFORO_SEDE),1)) ))
		 END																NroAulas,
	MXPA.FECHA_FIN_REGISTRO													FechaFinRegistroPostulantes,
	MXPA.FECHA_FIN_MODALIDAD												FechaFinModalidad,
	ROW_NUMBER() OVER ( ORDER BY EAS.ID_SEDE_INSTITUCION) AS Row,
		Total = COUNT(1) OVER ( )
FROM transaccional.examen_admision_sede EAS
INNER JOIN transaccional.proceso_admision_periodo PAP ON EAS.ID_PROCESO_ADMISION_PERIODO = PAP.ID_PROCESO_ADMISION_PERIODO AND EAS.ES_ACTIVO=1 AND PAP.ES_ACTIVO=1
INNER JOIN maestro.sede_institucion SI ON SI.ID_SEDE_INSTITUCION= EAS.ID_SEDE_INSTITUCION AND SI.ES_ACTIVO=1
INNER JOIN transaccional.modalidades_por_proceso_admision MXPA ON MXPA.ID_PROCESO_ADMISION_PERIODO= PAP.ID_PROCESO_ADMISION_PERIODO 
AND MXPA.ID_MODALIDAD = EAS.ID_MODALIDAD AND MXPA.ES_ACTIVO=1
INNER JOIN sistema.enumerado se_modalidad ON se_modalidad.ID_ENUMERADO= EAS.ID_MODALIDAD 
LEFT JOIN 
		(
			SELECT COUNT (ID_POSTULANTES_POR_MODALIDAD) TOTAL_POSTULANTES_EXAMEN_SEDE, TPXM.ID_EXAMEN_ADMISION_SEDE 
			FROM transaccional.postulantes_por_modalidad TPXM 
			INNER JOIN transaccional.modalidades_por_proceso_admision mppadmi ON TPXM.ID_MODALIDADES_POR_PROCESO_ADMISION = mppadmi.ID_MODALIDADES_POR_PROCESO_ADMISION 
			AND mppadmi.ES_ACTIVO=1 AND TPXM.ES_ACTIVO=1
			INNER JOIN transaccional.proceso_admision_periodo tpap ON tpap.ID_PROCESO_ADMISION_PERIODO= mppadmi.ID_PROCESO_ADMISION_PERIODO 
			AND tpap.ES_ACTIVO=1 and tpap.ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION
			INNER JOIN sistema.enumerado enume
			ON mppadmi.ID_MODALIDAD = enume.ID_ENUMERADO			
			group by TPXM.ID_EXAMEN_ADMISION_SEDE
		)
		SUBCONSULTA_POSTULANTES ON SUBCONSULTA_POSTULANTES.ID_EXAMEN_ADMISION_SEDE = EAS.ID_EXAMEN_ADMISION_SEDE

LEFT JOIN 
		(SELECT MIN(AFORO_AULA) MINIMO_AFORO_SEDE, ID_SEDE_INSTITUCION FROM maestro.aula MA
		WHERE MA.ES_ACTIVO=1 and MA.CATEGORIA_AULA = 10
		GROUP BY ID_SEDE_INSTITUCION
		)
		SUBCONSULTA_SEDES ON SUBCONSULTA_SEDES.ID_SEDE_INSTITUCION=EAS.ID_SEDE_INSTITUCION 
WHERE 
		PAP.ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION 
		AND (EAS.ID_SEDE_INSTITUCION = @ID_SEDE_INSTITUCION OR @ID_SEDE_INSTITUCION=0)					
		AND (EAS.ID_MODALIDAD = @ID_MODALIDAD OR @ID_MODALIDAD = 0) AND (EAS.ID_MODALIDAD <> @ID_MODALIDAD_EXONERADO OR @ID_MODALIDAD = @ID_MODALIDAD_EXONERADO)
		--AND SUBCONSULTA_SEDES.MINIMO_AFORO_SEDE IS NOT NULL AND SUBCONSULTA_POSTULANTES.TOTAL_POSTULANTES_EXAMEN_SEDE IS NOT NULL
				
	)
	SELECT  *
    FROM    tempPaginado T   WHERE   ( T.Row > @desde  AND T.Row < @hasta) OR (@Registros = 0)
END
GO


