
/*   

   [USP_SISTEMA_SEL_ENUMERADO] 5
   [USP_SISTEMA_SEL_ENUMERADO] 21


*/

CREATE PROCEDURE [dbo].[USP_SISTEMA_SEL_ENUMERADO] (
   @ID_TIPO_ENUMERADO	INT              
)AS

IF @ID_TIPO_ENUMERADO <> 39 and @ID_TIPO_ENUMERADO <> 21 and @ID_TIPO_ENUMERADO<>9 and @ID_TIPO_ENUMERADO<>5
BEGIN
SELECT 
	ID_ENUMERADO		IdEnumerado,
	ID_TIPO_ENUMERADO	IdTipoEnumerado,
	CODIGO_ENUMERADO	CodigoEnumerado,
	VALOR_ENUMERADO		ValorEnumerado,
	ORDEN_ENUMERADO		OrdenEnumerado 
FROM sistema.enumerado WHERE ID_TIPO_ENUMERADO = @ID_TIPO_ENUMERADO AND ESTADO = 1
ORDER BY VALOR_ENUMERADO
END 
ELSE
BEGIN
SELECT 
	ID_ENUMERADO		IdEnumerado,
	ID_TIPO_ENUMERADO	IdTipoEnumerado,
	CODIGO_ENUMERADO	CodigoEnumerado,
	VALOR_ENUMERADO		ValorEnumerado,
	ORDEN_ENUMERADO		OrdenEnumerado 
FROM sistema.enumerado WHERE ID_TIPO_ENUMERADO = @ID_TIPO_ENUMERADO AND ESTADO = 1
ORDER BY ORDEN_ENUMERADO
END
GO


