/**********************************************************************************************************
AUTOR				:	Juan Tovar
FECHA DE CREACION	:	20/06/2019
LLAMADO POR			:
DESCRIPCION			:	Modificac un registro de periodo lectivo para una institución
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
--  TEST:			
	EXEC USP_MAESTROS_UPD_PERIODO_LECTIVO_INSTITUCION 4,'2013-2',5,'2013-08-01','2013-12-30', 'MALVA'
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_MAESTROS_UPD_PERIODO_LECTIVO_INSTITUCION]
(	
	@ID_PERIODO_LECTIVO_INSTITUCION INT,
	@FECHA_INICIO DATE,
	@FECHA_FIN DATE,
	@USUARIO VARCHAR(20),
	@NOMBRE_PERIODO_LECTIVO_INSTITUCION VARCHAR(30),
	@ID_ROL INT,
	@DESCRIPCION VARCHAR(100),
	@ESTADO INT

	--declare @ID_PERIODO_LECTIVO_INSTITUCION INT=281
 --   declare @FECHA_INICIO DATE='2020/03/02'
	--declare @FECHA_FIN DATE='2020/09/15'
	--declare @USUARIO VARCHAR(20)='42122536'
	--declare @NOMBRE_PERIODO_LECTIVO_INSTITUCION VARCHAR(30)='2020-1'
	--declare @ID_ROL INT=84
	--declare @DESCRIPCION VARCHAR(100)=''
	--declare @ESTADO INT=0
)
AS
BEGIN
	DECLARE @ESTADO_PERIODO_LECTIVO_CREADO INT = 6
	DECLARE @RESULT INT, @ANIO INT, @ID_INSTITUCION INT, @ID_TIPO_OPCION INT
	
	SELECT @ANIO = PL.ANIO, @ID_TIPO_OPCION = PL.ID_TIPO_OPCION FROM transaccional.periodos_lectivos_por_institucion PLXI 
	INNER JOIN maestro.periodo_lectivo PL ON PLXI.ID_PERIODO_LECTIVO = PL.ID_PERIODO_LECTIVO AND PLXI.ES_ACTIVO=1
	WHERE PLXI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION= @ID_PERIODO_LECTIVO_INSTITUCION
				 
	SET @ID_INSTITUCION = (SELECT ID_INSTITUCION FROM transaccional.periodos_lectivos_por_institucion WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION)

	IF EXISTS (SELECT TOP 1 PLXI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION FROM transaccional.periodos_lectivos_por_institucion PLXI 
				INNER JOIN maestro.periodo_lectivo PL ON PLXI.ID_PERIODO_LECTIVO = PL.ID_PERIODO_LECTIVO AND PLXI.ES_ACTIVO=1
				WHERE ID_INSTITUCION = @ID_INSTITUCION
				--AND PL.ANIO = @ANIO
				AND ((@FECHA_INICIO BETWEEN PLXI.FECHA_INICIO_INSTITUCION AND PLXI.FECHA_FIN_INSTITUCION )
					OR (@FECHA_FIN BETWEEN PLXI.FECHA_INICIO_INSTITUCION AND PLXI.FECHA_FIN_INSTITUCION )) 
				AND PLXI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION <> @ID_PERIODO_LECTIVO_INSTITUCION AND PLXI.ESTADO <> @ESTADO_PERIODO_LECTIVO_CREADO
				AND PL.ID_TIPO_OPCION = @ID_TIPO_OPCION)
		SET @RESULT = -30
	ELSE
	BEGIN
		IF @ID_ROL = 1
		BEGIN
		UPDATE transaccional.periodos_lectivos_por_institucion
			SET 
				FECHA_INICIO_INSTITUCION = @FECHA_INICIO,
				FECHA_FIN_INSTITUCION = @FECHA_FIN,
				NOMBRE_PERIODO_LECTIVO_INSTITUCION = UPPER(@NOMBRE_PERIODO_LECTIVO_INSTITUCION),
				--ESTADO = @ESTADO,
				ES_ACTIVO = 1,
				FECHA_MODIFICACION = GETDATE(),
				USUARIO_MODIFICACION = @USUARIO
			WHERE 
				ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION
			SET @RESULT = 1
        END
		ELSE
		BEGIN
			IF EXISTS (SELECT TOP 1 CIERRE_PROGRAMACION FROM transaccional.evaluacion WHERE ID_EVALUACION IN (SELECT ID_EVALUACION FROM transaccional.evaluacion_detalle WHERE ID_MATRICULA_ESTUDIANTE IN (SELECT ID_MATRICULA_ESTUDIANTE FROM transaccional.matricula_estudiante 
						WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION AND ID_PERIODO_ACADEMICO IN (SELECT ID_PERIODO_ACADEMICO FROM transaccional.periodo_academico WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION AND ES_ACTIVO=1) 
						AND ES_ACTIVO=1) AND ES_ACTIVO=1) AND ES_ACTIVO=1 AND CIERRE_PROGRAMACION = 235)
				SET @RESULT = -306
			ELSE
			BEGIN
				UPDATE transaccional.periodos_lectivos_por_institucion
				SET 
					FECHA_INICIO_INSTITUCION = @FECHA_INICIO,
					FECHA_FIN_INSTITUCION = @FECHA_FIN,
					NOMBRE_PERIODO_LECTIVO_INSTITUCION = UPPER(@NOMBRE_PERIODO_LECTIVO_INSTITUCION),
					--ESTADO = @ESTADO,
					ES_ACTIVO = 1,
					FECHA_MODIFICACION = GETDATE(),
					USUARIO_MODIFICACION = @USUARIO
				WHERE 
					ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION
				SET @RESULT = 1
	
			END
		END

	--IF EXISTS (SELECT TOP 1 PLXI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION FROM transaccional.periodos_lectivos_por_institucion PLXI 
	--			INNER JOIN maestro.periodo_lectivo PL ON PLXI.ID_PERIODO_LECTIVO = PL.ID_PERIODO_LECTIVO AND PLXI.ES_ACTIVO=1
	--			WHERE ID_INSTITUCION = @ID_INSTITUCION
	--			AND PL.ANIO = @ANIO
	--			AND (	(@FECHA_INICIO BETWEEN PLXI.FECHA_INICIO_INSTITUCION AND PLXI.FECHA_FIN_INSTITUCION )
	--					OR (@FECHA_FIN BETWEEN PLXI.FECHA_INICIO_INSTITUCION AND PLXI.FECHA_FIN_INSTITUCION )) 
	--						AND PLXI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION <> @ID_PERIODO_LECTIVO_INSTITUCION)
	--			SET @RESULT = -30
	--ELSE
	--BEGIN
	--	UPDATE transaccional.periodos_lectivos_por_institucion
	--	SET 
	--		FECHA_INICIO_INSTITUCION = @FECHA_INICIO,
	--		FECHA_FIN_INSTITUCION = @FECHA_FIN,
	--		NOMBRE_PERIODO_LECTIVO_INSTITUCION = UPPER(@NOMBRE_PERIODO_LECTIVO_INSTITUCION),
	--		--ESTADO = @ESTADO,
	--		ES_ACTIVO = 1,
	--		FECHA_MODIFICACION = GETDATE(),
	--		USUARIO_MODIFICACION = @USUARIO
	--	WHERE 
	--		ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION
	--	SET @RESULT = 1
	END
	SELECT @RESULT
END
GO


