-- USP_MAESTROS_SEL_PERIODO_LECTIVO_INSTITUCION 500,'',''
-- USP_MAESTROS_SEL_PERIODO_LECTIVO_INSTITUCION 697,'',''
CREATE PROCEDURE [dbo].[USP_MAESTROS_SEL_PERIODO_LECTIVO_INSTITUCION]
(
	@ID_INSTITUCION						INT,
	@CODIGO_PERIODO_LECTIVO				VARCHAR(20),
	@NOMBRE_PERIODO_LECTIVO_INSTITUCION	VARCHAR(30),
	@Pagina								int		=1,
	@Registros							int		=10
)
AS
SET NOCOUNT ON;

DECLARE @desde INT , @hasta INT, @id_sede_institucion INT, @numerologia CHAR(1)

--SELECT @id_sede_institucion=si.ID_SEDE_INSTITUCION from maestro.sede_institucion si where si.ID_INSTITUCION=@ID_INSTITUCION and si.ES_SEDE_PRINCIPAL=1 and ES_ACTIVO=1
SELECT @numerologia = CONVERT (CHAR, VALOR_PARAMETRO) FROM sistema.parametro WHERE NOMBRE_PARAMETRO = 'Numerologia'

SET @desde = ( @Pagina - 1 ) * @Registros;
SET @hasta = ( @Pagina * @Registros ) + 1; 


	WITH    tempPaginado AS
	(
		SELECT	PLI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION	IdPeriodoLectivoInstitucion,
				PLI.ID_PERIODO_LECTIVO						IdPeriodoLectivo,
				PL.CODIGO_PERIODO_LECTIVO					CodigoPeriodoLectivo,
				CASE @numerologia
				WHEN '1' THEN CAST(PL.CODIGO_PERIODO_LECTIVO AS VARCHAR)
				WHEN 'I' THEN CAST(PL.ANIO AS VARCHAR) + '-' + dbo.UFN_CST_numero_romano(CAST(SUBSTRING(PL.CODIGO_PERIODO_LECTIVO,6,1) AS INT)) 
				WHEN 'A' THEN CAST(PL.ANIO AS VARCHAR) + '-' + dbo.UFN_CST_numero_texto(CAST(SUBSTRING(PL.CODIGO_PERIODO_LECTIVO,6,1) AS INT)) 
				ELSE CAST(PL.CODIGO_PERIODO_LECTIVO AS VARCHAR) 
				END AS NombrePeriodoLectivoInstitucion,	
				--PLI.NOMBRE_PERIODO_LECTIVO_INSTITUCION	NombrePeriodoLectivoInstitucion,
				--E.ID_ENUMERADO						IdEnumeradoTipoOpcion,
				--E.VALOR_ENUMERADO						EnumeradoTipoOpcion,		
				PL.FECHA_INICIO							FechaInicio,
				PLI.FECHA_INICIO_INSTITUCION			FechaInicioInstitucion,
				PL.FECHA_FIN							FechaFin,
				PLI.FECHA_FIN_INSTITUCION				FechaFinInstitucion,
				PLI.ESTADO								Estado,
				ROW_NUMBER() OVER ( ORDER BY PL.CODIGO_PERIODO_LECTIVO,PL.FECHA_INICIO) AS Row,
				Total = COUNT(1) OVER ( )	
				,PLI.ID_INSTITUCION			
		FROM	transaccional.periodos_lectivos_por_institucion PLI
				INNER JOIN maestro.periodo_lectivo PL ON PL.ID_PERIODO_LECTIVO = PLI.ID_PERIODO_LECTIVO
				INNER JOIN sistema.enumerado E ON E.ID_ENUMERADO = PLI.ESTADO
		WHERE 				
				---AND PL.CODIGO_PERIODO_LECTIVO LIKE @CODIGO_PERIODO_LECTIVO +'%' COLLATE LATIN1_GENERAL_CI_AI
				CASE @numerologia
				WHEN '1' THEN CAST(PL.CODIGO_PERIODO_LECTIVO AS VARCHAR)
				WHEN 'I' THEN CAST(PL.ANIO AS VARCHAR) + '-' + dbo.UFN_CST_numero_romano(CAST(SUBSTRING(PL.CODIGO_PERIODO_LECTIVO,6,1) AS INT)) 
				WHEN 'A' THEN CAST(PL.ANIO AS VARCHAR) + '-' + dbo.UFN_CST_numero_texto(CAST(SUBSTRING(PL.CODIGO_PERIODO_LECTIVO,6,1) AS INT)) 
				ELSE CAST(PL.CODIGO_PERIODO_LECTIVO AS VARCHAR) 
				END COLLATE LATIN1_GENERAL_CI_AI LIKE @CODIGO_PERIODO_LECTIVO +'%' COLLATE LATIN1_GENERAL_CI_AI
				AND PLI.NOMBRE_PERIODO_LECTIVO_INSTITUCION LIKE @NOMBRE_PERIODO_LECTIVO_INSTITUCION +'%' COLLATE LATIN1_GENERAL_CI_AI
				AND PLI.ID_INSTITUCION = @ID_INSTITUCION
				AND PLI.ES_ACTIVO = 1
				AND PLI.ESTADO IN (7,8)

	)
	SELECT  *
    FROM    tempPaginado T
    WHERE   ( T.Row > @desde  AND T.Row < @hasta) OR (@Registros = 0)
GO


