/**********************************************************************************************************
AUTOR				:	Juan Tovar
FECHA DE CREACION	:	20/06/2019
LLAMADO POR			:
DESCRIPCION			:	Obtiene la situación del postulante. 
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
1.0			20/06/2019		JTOVAR			Creación
1.1			27/01/2020		MALVA			SE OBTIENE COLUMNA IdPlanEstudio.
1.2			21/02/2022		JCHAVEZ			Se agregó ArchivoRuta, ArchivoFoto y datos de apoderado.

TEST:
	USP_ADMISION_SEL_POSTULANTE_MODALIDAD_SITUACION 266,26,'73700147'
	USP_ADMISION_SEL_POSTULANTE_MODALIDAD_SITUACION 3905,26,'45601815'
***********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_POSTULANTE_MODALIDAD_SITUACION]
(	
	@ID_PERIODO_LECTIVO_INSTITUCION	INT,
	@ID_TIPO_DOCUMENTO	INT,
	@NUMERO_DOCUMENTO	VARCHAR(15)	

	--DECLARE @ID_PERIODO_LECTIVO_INSTITUCION	INT=1209
	--DECLARE @ID_TIPO_DOCUMENTO	INT=26
	--DECLARE @NUMERO_DOCUMENTO	VARCHAR(15)='47859663'
)
AS
BEGIN
DECLARE @ID_INSTITUCION INT,
@ID_ESTADO_PENDIENTE_MODALIDAD_PROCESO_ADMISION INT = 96,
@ID_ESTADO_EVALUADO_PROCESO_ADMISION INT =97

SET @ID_INSTITUCION = (SELECT ID_INSTITUCION FROM transaccional.periodos_lectivos_por_institucion WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION= @ID_PERIODO_LECTIVO_INSTITUCION)

SELECT
		P.ID_PERSONA										IdPersona,
		PEI.ID_PERSONA_INSTITUCION							IdPersonaInstitucion,
		P.APELLIDO_PATERNO_PERSONA							ApellidoPaterno,
		P.APELLIDO_MATERNO_PERSONA							ApellidoMaterno,
		P.NOMBRE_PERSONA									Nombre,
		P.SEXO_PERSONA										IdSexo,
		PEI.ESTADO_CIVIL									IdEstadoCivil,
		P.FECHA_NACIMIENTO_PERSONA							FechaNacimiento,
		PEI.PAIS_PERSONA									IdPaisResidencia,
		URES.CODIGO_UBIGEO							        UbigeoResidencia,
		P.PAIS_NACIMIENTO									IdPaisNacimiento,
		UNAC.CODIGO_UBIGEO							        UbigeoNacimiento,
		P.ID_LENGUA_MATERNA									IdLenguaMaterna,
		P.ES_DISCAPACITADO									EsDiscapacitado,
		ISNULL(ISNULL(A.ID_TIPO_DOCUMENTO_APODERADO,TEI.ID_TIPO_DOCUMENTO_APODERADO),'')	IdTipoDocumentoApoderado,
		ISNULL(ISNULL(A.NUMERO_DOCUMENTO_APODERADO,TEI.NUMERO_DOCUMENTO_APODERADO),'')		NumeroDocumentoApoderado,
		ISNULL(ISNULL(A.NOMBRE_APODERADO,TEI.NOMBRE_APODERADO),'')							NombreApoderado,
		ISNULL(ISNULL(A.APELLIDO_APODERADO,TEI.APELLIDO_APODERADO),'')						ApellidoApoderado,
		ISNULL(ISNULL(A.ID_TIPO_PARENTEZCO,TEI.ID_TIPO_PARENTESCO),'')						IdTipoParentezco,
		PARENTESCO											Parentesco,
		--ISNULL(ISNULL(A.ARCHIVO_RUTA,TEI.ARCHIVO_RUTA),'')									ArchivoRuta,
		'' ArchivoRuta,
		ISNULL(ISNULL(A.ARCHIVO_FOTO,TEI.ARCHIVO_FOTO),'')									ArchivoFoto,
		PEI.DIRECCION_PERSONA								Direccion,
		PEI.CORREO											Correo,
		PEI.TELEFONO										Telefono,
		PEI.CELULAR											Celular,
		A.ID_PLAN_ESTUDIO,
		CASE WHEN  A.ID_PLAN_ESTUDIO <> TEI.ID_PLAN_ESTUDIO OR TEI.ID_PLAN_ESTUDIO IS NULL
		THEN A.ID_POSTULANTES_POR_MODALIDAD	ELSE 0 END		IdPostulanteModalidad,
		CASE WHEN  A.ID_PLAN_ESTUDIO <> TEI.ID_PLAN_ESTUDIO OR TEI.ID_PLAN_ESTUDIO IS NULL
		THEN ISNULL(A.ID_SEDE_INSTITUCION,0)	ELSE 0 END	IdSedeInstitucion,
		CASE WHEN  A.ID_PLAN_ESTUDIO <> TEI.ID_PLAN_ESTUDIO OR TEI.ID_PLAN_ESTUDIO IS NULL
		THEN ISNULL(A.ID_CARRERA,0)	ELSE 0 END				IdCarrera,
		CASE WHEN  A.ID_PLAN_ESTUDIO <> TEI.ID_PLAN_ESTUDIO OR TEI.ID_PLAN_ESTUDIO IS NULL
		THEN ISNULL(A.ID_TIPO_ITINERARIO,0)	ELSE 0 END		IdTipoItinerario,
		CASE WHEN  A.ID_PLAN_ESTUDIO <> TEI.ID_PLAN_ESTUDIO OR TEI.ID_PLAN_ESTUDIO IS NULL
		THEN ISNULL(A.ID_PLAN_ESTUDIO,0) ELSE 0 END			IdPlanEstudio,
		CASE WHEN  A.ID_PLAN_ESTUDIO <> TEI.ID_PLAN_ESTUDIO OR TEI.ID_PLAN_ESTUDIO IS NULL
		THEN ISNULL(A.ID_TURNOS_POR_INSTITUCION,0)	ELSE 0 END	IdTurnoInstitucion,
		A.ID_INSTITUCION_BASICA								IdInstitucionBasica,
		A.ID_TIPO_INSTITUCION_BASICA						IdTipoIEBasica,	
		A.CODIGO_MODULAR_IE_BASICA							CodigoModularBasica,
		A.ANIO_EGRESO										AnioEgreso,
		A.NOMBRE_IE_BASICA									NombreIeBasica,
		A.ID_NIVEL_IE_BASICA								IdNivelBasica,
		A.ID_TIPO_GESTION_IE_BASICA							IdTipoGestionBasica, 
		A.ID_PAIS											IdPaisBasica,
		A.UBIGEO_IE_BASICA									UbigeoBasica,
		A.DIRECCION_IE_BASICA								DireccionBasica,
		CASE WHEN TEI.ID_ESTUDIANTE_INSTITUCION IS NULL THEN 0 ELSE TEI.ID_ESTUDIANTE_INSTITUCION END IdEstudianteInstitucion,
		A.ESTADO_ACTUAL										EstadoActual,
		A.ESTADO											IdEstadoPostulante,
		A.DescEstado										DescEstado,
		A.ESTADO_MODALIDAD_PROCESO_ADMISION					EstadoModalidadProcesoAdmision,
		A.ID_MODALIDAD										IdModalidad
FROM
		maestro.persona P
		LEFT JOIN maestro.persona_institucion PEI ON PEI.ID_PERSONA = P.ID_PERSONA 	AND PEI.ID_INSTITUCION = @ID_INSTITUCION 
		LEFT JOIN db_auxiliar.dbo.UVW_UBIGEO_RENIEC URES ON URES.CODIGO_UBIGEO = PEI.UBIGEO_PERSONA
		LEFT JOIN db_auxiliar.dbo.UVW_UBIGEO_RENIEC UNAC ON UNAC.CODIGO_UBIGEO = P.UBIGEO_NACIMIENTO						
		LEFT JOIN (	
					SELECT 
					TPXM.ID_PERSONA_INSTITUCION,
					TPXM.ID_POSTULANTES_POR_MODALIDAD,
					CASE	WHEN TPPI_PROM.ID_POSTULANTES_POR_MODALIDAD_RETIRADO IS NOT NULL THEN 'P' --hay un retirado, entonces ha sido promovido
							WHEN TPPI_RET.ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO IS NOT NULL THEN 'R' --hay un promovido, entonces ha sido retirado
							WHEN TMXPA.ESTADO=@ID_ESTADO_PENDIENTE_MODALIDAD_PROCESO_ADMISION THEN 'F'  --modalidad de proceso de admisión pendiente
							WHEN TRXP.ID_RESULTADOS_POR_POSTULANTE IS NULL THEN 'S'  --no se ha procesado los resultados para este postulante
							ELSE SUBSTRING( SE_estado.VALOR_ENUMERADO, 1,1) 
							END ESTADO_ACTUAL,	
					CASE	WHEN TPPI_PROM.ID_POSTULANTES_POR_MODALIDAD_RETIRADO IS NOT NULL THEN 'PROMOVIDO' --hay un retirado, entonces ha sido promovido
							WHEN TPPI_RET.ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO IS NOT NULL THEN 'RETIRADO' --hay un promovido, entonces ha sido retirado
							WHEN TMXPA.ESTADO=@ID_ESTADO_PENDIENTE_MODALIDAD_PROCESO_ADMISION THEN 'FALTANTE'  
							WHEN TRXP.ID_RESULTADOS_POR_POSTULANTE IS NULL THEN 'SIN PROCESAR'  
							ELSE SE_estado.VALOR_ENUMERADO
							END DescEstado,	
					TMXPA.ID_MODALIDAD,
					TPPI_PROM.ID_POSTULANTES_POR_MODALIDAD_RETIRADO ID_POSTULANTE_RETIRADO, 
					TPPI_RET.ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO ID_POSTULANTE_PROMOVIDO,
					TMCID.ID_SEDE_INSTITUCION, 
					TCI.ID_CARRERA, 
					TCI.ID_TIPO_ITINERARIO, 
					pe.ID_PLAN_ESTUDIO, 
					TMCI.ID_TURNOS_POR_INSTITUCION,
					TRXP.ESTADO,
					TPXM.ANIO_EGRESO,
					TPXM.ID_INSTITUCION_BASICA, 
					IB.NOMBRE_IE_BASICA ,
					IB.ID_NIVEL_IE_BASICA,
					IB.ID_TIPO_GESTION_IE_BASICA,
					IB.ID_PAIS, 
					IB.UBIGEO_IE_BASICA,
					IB.DIRECCION_IE_BASICA,
					IB.ID_TIPO_INSTITUCION_BASICA,
					IB.CODIGO_MODULAR_IE_BASICA,								
					TMXPA.ESTADO ESTADO_MODALIDAD_PROCESO_ADMISION,							
					
					TPXM.ID_TIPO_DOCUMENTO_APODERADO,
					TPXM.NUMERO_DOCUMENTO_APODERADO,
					TPXM.NOMBRE_APODERADO,
					TPXM.APELLIDO_APODERADO,
					TPXM.ID_TIPO_PARENTEZCO,
					se_parentesco.VALOR_ENUMERADO PARENTESCO,
					TPXM.ARCHIVO_RUTA,
					TPXM.ARCHIVO_FOTO,																	 
				
					TRXP.ID_POSTULANTES_POR_MODALIDAD RESULTADO_ID_POSTULANTE,
					TRXP.NOTA_RESULTADO RESULTADO_NOTA,
					TRXP.ESTADO RESULTADO_ESTADO
					FROM transaccional.postulantes_por_modalidad TPXM		
					INNER JOIN transaccional.modalidades_por_proceso_admision TMXPA ON TPXM.ID_MODALIDADES_POR_PROCESO_ADMISION=TMXPA.ID_MODALIDADES_POR_PROCESO_ADMISION 
																				AND TMXPA.ES_ACTIVO=1
					INNER JOIN transaccional.proceso_admision_periodo TPAP ON TPAP.ID_PROCESO_ADMISION_PERIODO= TMXPA.ID_PROCESO_ADMISION_PERIODO 
																				AND TPAP.ES_ACTIVO=1
					INNER JOIN maestro.institucion_basica IB ON IB.ID_INSTITUCION_BASICA = TPXM.ID_INSTITUCION_BASICA  			
					LEFT JOIN transaccional.promover_persona_institucion TPPI_PROM on TPPI_PROM.ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO = TPXM.ID_POSTULANTES_POR_MODALIDAD
																				AND TPPI_PROM.ES_ACTIVO=1																				
					LEFT JOIN transaccional.promover_persona_institucion TPPI_RET on TPPI_RET.ID_POSTULANTES_POR_MODALIDAD_RETIRADO= TPXM.ID_POSTULANTES_POR_MODALIDAD
																				AND TPPI_RET.ES_ACTIVO=1
					LEFT JOIN transaccional.resultados_por_postulante TRXP ON TRXP.ID_POSTULANTES_POR_MODALIDAD =  (CASE WHEN TPPI_PROM.ID_POSTULANTES_POR_MODALIDAD_RETIRADO IS NOT NULL 
																																			THEN  TPPI_PROM.ID_POSTULANTES_POR_MODALIDAD_RETIRADO 
																														WHEN TPPI_RET.ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO IS NOT NULL
																																			THEN TPPI_RET.ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO
																														ELSE TPXM.ID_POSTULANTES_POR_MODALIDAD  END
																													) AND TRXP.ES_ACTIVO=1
					LEFT JOIN sistema.enumerado SE_estado ON SE_estado.ID_ENUMERADO= TRXP.ESTADO AND TPPI_PROM.ID_POSTULANTES_POR_MODALIDAD_RETIRADO IS NULL AND TPPI_RET.ID_POSTULANTES_POR_MODALIDAD_PROMOVIDO IS NULL
					LEFT JOIN transaccional.opciones_por_postulante TOXP ON TRXP.ID_OPCIONES_POR_POSTULANTE= TOXP.ID_OPCIONES_POR_POSTULANTE AND TOXP.ES_ACTIVO=1
					LEFT JOIN transaccional.meta_carrera_institucion_detalle TMCID ON TMCID.ID_META_CARRERA_INSTITUCION_DETALLE = TOXP.ID_META_CARRERA_INSTITUCION_DETALLE 
																				AND TMCID.ID_PERIODOS_LECTIVOS_POR_INSTITUCION=  @ID_PERIODO_LECTIVO_INSTITUCION
																				AND TMCID.ES_ACTIVO=1
					LEFT JOIN transaccional.meta_carrera_institucion TMCI ON TMCI.ID_META_CARRERA_INSTITUCION= TMCID.ID_META_CARRERA_INSTITUCION 
																				AND TMCI.ES_ACTIVO=1
					LEFT JOIN transaccional.carreras_por_institucion TCI ON TCI.ID_CARRERAS_POR_INSTITUCION= TMCI.ID_CARRERAS_POR_INSTITUCION 
																				AND TCI.ES_ACTIVO=1		
					LEFT JOIN transaccional.plan_estudio pe			ON pe.ID_PLAN_ESTUDIO = TMCI.ID_PLAN_ESTUDIO AND pe.ES_ACTIVO=1
					left JOIN sistema.enumerado se_parentesco on TPXM.ID_TIPO_PARENTEZCO = se_parentesco.ID_ENUMERADO		
					WHERE   TPXM.ES_ACTIVO=1 AND TPAP.ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION

				) A ON A.ID_PERSONA_INSTITUCION= PEI.ID_PERSONA_INSTITUCION
		LEFT JOIN transaccional.estudiante_institucion TEI ON TEI.ID_PERSONA_INSTITUCION=PEI.ID_PERSONA_INSTITUCION AND TEI.ES_ACTIVO=1
WHERE
		P.ID_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
		AND P.NUMERO_DOCUMENTO_PERSONA = @NUMERO_DOCUMENTO	
		
	
order by IdModalidad desc 
END
GO


