CREATE PROCEDURE [dbo].[USP_MATRICULA_SEL_TIPO_TRASLADO_LISTA]
(  
@ID_INSTITUCION_DESTINO INT,
@ID_INSTITUCION_ORIGEN INT
)  
AS  
BEGIN  
	SET NOCOUNT ON;  
		
	IF @ID_INSTITUCION_DESTINO = @ID_INSTITUCION_ORIGEN
		SELECT VALOR_ENUMERADO Text,
			   ID_ENUMERADO Value
		FROM sistema.enumerado 
		WHERE ID_TIPO_ENUMERADO = 45 
		AND ID_ENUMERADO = 141
	ELSE
		SELECT VALOR_ENUMERADO Text,
			   ID_ENUMERADO Value
		FROM sistema.enumerado 
		WHERE ID_TIPO_ENUMERADO = 45 
		AND ID_ENUMERADO = 142
END
GO


