CREATE PROCEDURE [dbo].[USP_MAESTROS_VAL_PERIODO_ACADEMICOS_CERRADOS_PL_ANT]
(
	@ID_INSTITUCION		INT,
	@ID_PEDIODO_LECTIVO INT 	
)
AS
BEGIN
DECLARE @RESULT INT = 1

DECLARE @TOTAL_PERIODOS_ACADEMICOS INT
DECLARE @FECHA_INICIO_INSTITUCION_ACT DATE -- = '2019-07-15'
DECLARE @FECHA_FIN_INSTITUCION_ACT DATE-- = '2019-11-20' 
DECLARE @TOTAL_PERIODOS_ACADEMICOS_CERRADOS INT 
DECLARE @ID_PERIODO_LECTIVO_INSTITUCION_ANT INT 

SELECT  @FECHA_INICIO_INSTITUCION_ACT = FECHA_INICIO_INSTITUCION, @FECHA_FIN_INSTITUCION_ACT= FECHA_FIN_INSTITUCION 
FROM transaccional.periodos_lectivos_por_institucion WHERE ID_PERIODO_LECTIVO= @ID_PEDIODO_LECTIVO AND ID_INSTITUCION = @ID_INSTITUCION 
AND ES_ACTIVO=1

SET @ID_PERIODO_LECTIVO_INSTITUCION_ANT =(SELECT TOP 1 ID_PERIODOS_LECTIVOS_POR_INSTITUCION FROM transaccional.periodos_lectivos_por_institucion
WHERE ID_INSTITUCION=@ID_INSTITUCION AND   @FECHA_INICIO_INSTITUCION_ACT>= FECHA_FIN_INSTITUCION ORDER BY FECHA_FIN_INSTITUCION DESC)
PRINT @ID_PERIODO_LECTIVO_INSTITUCION_ANT

SELECT 
TPA.ID_PERIODO_ACADEMICO,
	CASE ISNULL(SUB_CONSULTA_PROGRAMACION.ESTADO,1) 
					WHEN 1 THEN 'ABIERTO'
					WHEN 0 THEN 'CERRADO'
					END 	ESTADO
					INTO #TEMPORAL
FROM 
transaccional.periodo_academico TPA
LEFT JOIN (SELECT DISTINCT TPC.ID_PERIODO_ACADEMICO, TPC.ESTADO from transaccional.programacion_clase TPC 
			INNER JOIN transaccional.evaluacion TE ON TPC.ID_PROGRAMACION_CLASE = TE.ID_PROGRAMACION_CLASE AND TPC.ES_ACTIVO=1 AND TE.ES_ACTIVO=1
		  )SUB_CONSULTA_PROGRAMACION ON TPA.ID_PERIODO_ACADEMICO= SUB_CONSULTA_PROGRAMACION.ID_PERIODO_ACADEMICO 
WHERE TPA.ES_ACTIVO=1 AND TPA.ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION_ANT

SET @TOTAL_PERIODOS_ACADEMICOS= (SELECT COUNT(ID_PERIODO_ACADEMICO) FROM #TEMPORAL )
SET @TOTAL_PERIODOS_ACADEMICOS_CERRADOS = (SELECT COUNT(ID_PERIODO_ACADEMICO) FROM #TEMPORAL WHERE ESTADO='CERRADO')
DROP TABLE #TEMPORAL
IF @TOTAL_PERIODOS_ACADEMICOS != @TOTAL_PERIODOS_ACADEMICOS_CERRADOS 
BEGIN
SET @RESULT = -301
END
SELECT @RESULT 
END
GO


