CREATE PROCEDURE [dbo].[USP_PLANIFICACION_UPDA_SESION_X_PROGRAMACION]
(  
@ID_SESION_PROGRAMACION_CLASE INT,
@ID_AULA INT,
@ID_DIA INT,
@ID_TIPO_CLASE INT,
@HORA_INICIO VARCHAR(5),
@HORA_FIN VARCHAR(5),
@USUARIO VARCHAR(20)
)  
AS 

DECLARE @RESULT INT
 BEGIN  
	SET @RESULT=0

				UPDATE transaccional.sesion_programacion_clase
				SET ID_AULA = @ID_AULA, 
				DIA = @ID_DIA,
				HORA_INICIO=@HORA_INICIO,
				HORA_FIN=@HORA_FIN,
				ID_TIPO_CLASE=@ID_TIPO_CLASE,
				USUARIO_MODIFICACION=@USUARIO,
				FECHA_MODIFICACION =GETDATE()
				WHERE ID_SESION_PROGRAMACION_CLASE=@ID_SESION_PROGRAMACION_CLASE			
			SET @RESULT = 1
END  
SELECT @RESULT
GO


