/*********************************************************************************************************************
AUTOR				:	Juan Tovar
FECHA DE CREACION	:	06/03/2021
LLAMADO POR			:
DESCRIPCION			:	CREACION CARGA MASIVA NOMINA
REVISIONES			:  
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
1.0			06/03/2021		JTOVAR         CREACIÓN

TEST:			
	USP_MATRICULA_INS_CARGA_MASIVA_NOMINA 2945,'2014-I','[INICIO]1,26,''40310074'','[INICIO]1,26,''40310074'',''TERRAZAS CUEVAS HILDA'',36,25,''False'',''UNIDAD 1'',''''[FIN] [INICIO]2,26,''40310074'',''TERRAZAS CUEVAS HILDA'',36,25,''False'',''UNIDAD 2'',''


''[FIN] [INICIO]3,26,''40310074'',''TERRAZAS CUEVAS HILDA'',36,25,''False'',''UNIDAD 3'',''''[FIN] [INICIO]4,26,''41491773'',''RAMIREZ GONZALEZ CARMELA DEL PILAR'',36,25,''False'',''UNIDAD 1'',''''[FIN] [INICIO]5,26,''41491773'',''RAMIREZ GONZALEZ CARMELA


 DEL PILAR'',36,25,''False'',''UNIDAD 3'',''''[FIN] [INICIO]6,26,''40255380'',''DIAZ IGLESIAS LIZETH'',36,25,''True'',''UNIDAD 1'',''''[FIN] [INICIO]7,26,''40255380'',''DIAZ IGLESIAS LIZETH'',36,25,''True'',''UNIDAD 2'',''''[FIN] ','10113318'
*********************************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_MATRICULA_INS_CARGA_MASIVA_NOMINA]
(	
	@ID_INSTITUCION	INT,
	@NOMBRE_PERIODO_LECTIVO VARCHAR(10),
    @NOMBRE_SEDE_INSTITUCION VARCHAR(150),
    @ID_CARRERA INT,
    @NOMBRE_PLAN_ESTUDIO VARCHAR(150),
    @ID_SEMESTRE_ACADEMICO INT,
    @ID_TURNO INT,
    @ID_SECCION INT,
	@QUERY_EXCEL NVARCHAR(MAX),	
    @USUARIO_CREACION NVARCHAR(20)	
)
AS
/*
DECLARE @ID_INSTITUCION	INT=2945,
	@NOMBRE_PERIODO_LECTIVO VARCHAR(10)='2014-I',
	@NOMBRE_SEDE_INSTITUCION VARCHAR(150)='PRINCIPAL',
	@ID_CARRERA INT=1094,
	@NOMBRE_PLAN_ESTUDIO VARCHAR(150)='PLAN 2020',
	@ID_SEMESTRE_ACADEMICO INT=111,
	@ID_TURNO INT=13,
	@ID_SECCION INT=105,
	@QUERY_EXCEL NVARCHAR(MAX)='[INICIO]1,26,''40310074'',''TERRAZAS CUEVAS HILDA'',36,25,''False'',''UNIDAD 1'',''''[FIN] [INICIO]2,26,''40310074'',''TERRAZAS CUEVAS HILDA'',36,25,''False'',''UNIDAD 2'',''''[FIN] [INICIO]3,26,''40310074'',''TERRAZAS CUEVAS 

HILDA'',36,25,''False'',''UNIDAD 3'',''''[FIN] [INICIO]4,26,''41491773'',''RAMIREZ GONZALEZ CARMELA DEL PILAR'',36,25,''False'',''UNIDAD 1'',''''[FIN] [INICIO]5,26,''41491773'',''RAMIREZ GONZALEZ CARMELA DEL PILAR'',36,25,''False'',''UNIDAD 3'',''''[FIN] 

[INICIO]6,26,''40255380'',''DIAZ IGLESIAS LIZETH'',36,25,''True'',''UNIDAD 1'',''''[FIN] [INICIO]7,26,''40255380'',''DIAZ IGLESIAS LIZETH'',36,25,''True'',''UNIDAD 2'',''''[FIN] ',	
	@USUARIO_CREACION NVARCHAR(20)='10113318'
*/
DECLARE @RESULT INT
BEGIN TRY
	BEGIN TRAN InsertarCargaMasivaNominas
	
	--> DECLARACION DE VARIABLES 
	DECLARE @RESPUETA_MENSAJE	NVARCHAR(MAX);
	DECLARE @NOMBRE_TABLA_TEMPORAL VARCHAR(100) = '#tmpCargaMasivaNominaDetalle';
	DECLARE @FECHA_ACTUAL DATETIME = GETDATE();

	DECLARE @ID_CARGA_MASIVA_NOMINA INT;
	DECLARE @ID_CARGA_MASIVA_PERSONA INT;
	DECLARE @CANTIDAD_ALUMNOS INT;

	--> DECLARACION DE VARIABLES DE TABLA 
	DECLARE @Carga_masiva_nominas_tmp TABLE (ID_CARGA_MASIVA_NOMINA INT)
	DECLARE @Carga_masiva_persona_tmp TABLE (ID_CARGA_MASIVA_PERSONA INT)

	--> PROCESANDO INSERT INTO POR SEGURIDAD 	
	SET @QUERY_EXCEL = (SELECT REPLACE(@QUERY_EXCEL,'[INICIO]','INSERT INTO ' + @NOMBRE_TABLA_TEMPORAL + ' VALUES ('));
	SET @QUERY_EXCEL = (SELECT REPLACE(@QUERY_EXCEL,'','INSERT INTO'));
	SET @QUERY_EXCEL = (SELECT REPLACE(@QUERY_EXCEL,'[FIN]',')'));
		
	BEGIN --> CREAR TABLA TEMPORAL 
		CREATE TABLE #tmpCargaMasivaNominaDetalle
		( 	
			NRO INT,
			ID_TIPO_DOCUMENTO INT,
			NUMERO_DOCUMENTO VARCHAR(20),
			NOMBRE_COMPLETO VARCHAR(150),
			SEXO INT,
			EDAD INT,
			TIENE_DISCAPACIDAD VARCHAR(5),
			NOMBRE_UNIDAD_DIDACTICA VARCHAR(150),
			NOTA VARCHAR(2)
		)
	END
	PRINT 'Llenar tabla #tmpCargaMasivaNominaDetalle'
	EXECUTE (@QUERY_EXCEL);
	
	IF EXISTS (SELECT TOP 1 ID_CARGA_MASIVA_NOMINA
			   FROM transaccional.carga_masiva_nominas
			   WHERE ES_ACTIVO = 1 AND
               NOMBRE_PERIODO_LECTIVO = @NOMBRE_PERIODO_LECTIVO AND
			   ID_INSTITUCION = @ID_INSTITUCION AND
			   NOMBRE_SEDE_INSTITUCION = @NOMBRE_SEDE_INSTITUCION AND
			   ID_CARRERA = @ID_CARRERA AND
			   NOMBRE_PLAN_ESTUDIO = @NOMBRE_PLAN_ESTUDIO AND
			   ID_SEMESTRE_ACADEMICO = @ID_SEMESTRE_ACADEMICO AND
			   ID_TURNO = @ID_TURNO AND
			   ID_SECCION = @ID_SECCION
			   )
		
		SET @RESULT= -180
	ELSE
	BEGIN
		BEGIN --> INSERTAR CABECERA 
			PRINT 'INSERT transaccional.carga_masiva_nominas'
			INSERT INTO transaccional.carga_masiva_nominas
			        ( NOMBRE_PERIODO_LECTIVO,
					  ID_INSTITUCION,
					  NOMBRE_SEDE_INSTITUCION,
					  ID_CARRERA,
					  NOMBRE_PLAN_ESTUDIO,
					  ID_SEMESTRE_ACADEMICO,
					  ID_TURNO,
					  ID_SECCION,
					  CANTIDAD_ALUMNOS,
					  ES_ACTIVO,
					  ESTADO,
					  USUARIO_CREACION,
					  FECHA_CREACION
			        )
			
			OUTPUT INSERTED.ID_CARGA_MASIVA_NOMINA INTO @Carga_masiva_nominas_tmp(ID_CARGA_MASIVA_NOMINA)

			VALUES  ( @NOMBRE_PERIODO_LECTIVO,
			          @ID_INSTITUCION,
			          @NOMBRE_SEDE_INSTITUCION,
			          @ID_CARRERA,
			          @NOMBRE_PLAN_ESTUDIO,
			          @ID_SEMESTRE_ACADEMICO,
			          @ID_TURNO,
			          @ID_SECCION,
			          (SELECT COUNT(*) FROM (SELECT DISTINCT ID_TIPO_DOCUMENTO,NUMERO_DOCUMENTO FROM #tmpCargaMasivaNominaDetalle) A),
					  1,
			          1,
			          @USUARIO_CREACION,
			          @FECHA_ACTUAL
			        )
			
			SET @ID_CARGA_MASIVA_NOMINA = (SELECT ID_CARGA_MASIVA_NOMINA FROM @Carga_masiva_nominas_tmp);
		END	

		BEGIN --> INSERTAR DETALLES 
			DECLARE @I INT = 1
			DECLARE @CANT INT = (SELECT COUNT(1) FROM #tmpCargaMasivaNominaDetalle)
			DECLARE @ID_TIPO_DOCUMENTO INT, @NUMERO_DOCUMENTO VARCHAR(20)

			WHILE(@I <= @CANT)
			BEGIN
				PRINT 'Insertar detalle: Obteniendo ID_TIPO_DOCUMENTO,NUMERO_DOCUMENTO'
				SELECT @ID_TIPO_DOCUMENTO = ID_TIPO_DOCUMENTO, @NUMERO_DOCUMENTO = NUMERO_DOCUMENTO FROM #tmpCargaMasivaNominaDetalle WHERE NRO = @I
				PRINT CAST(@ID_TIPO_DOCUMENTO AS VARCHAR(20)) + ' - ' + CAST(@NUMERO_DOCUMENTO AS VARCHAR(20))

				-->INSERTAR O EDITAR PERSONA
				SET @ID_CARGA_MASIVA_PERSONA = (SELECT TOP 1 ID_CARGA_MASIVA_PERSONA FROM transaccional.carga_masiva_nominas_persona 
												WHERE ID_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO AND NUMERO_DOCUMENTO = @NUMERO_DOCUMENTO)
				PRINT CAST(@ID_CARGA_MASIVA_PERSONA AS VARCHAR(20))

				IF (@ID_CARGA_MASIVA_PERSONA IS NULL)
				BEGIN
					PRINT 'INSERT transaccional.carga_masiva_nominas_persona'
					INSERT INTO transaccional.carga_masiva_nominas_persona(ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE_COMPLETO, SEXO, EDAD, TIENE_DISCAPACIDAD, ES_ACTIVO, ESTADO, USUARIO_CREACION, FECHA_CREACION)
					OUTPUT INSERTED.ID_CARGA_MASIVA_PERSONA INTO @Carga_masiva_persona_tmp(ID_CARGA_MASIVA_PERSONA)
					SELECT ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRE_COMPLETO, SEXO, EDAD, (CASE TIENE_DISCAPACIDAD WHEN 'True' THEN 1 ELSE 0 END), 1, 1, @USUARIO_CREACION, @FECHA_ACTUAL
					FROM #tmpCargaMasivaNominaDetalle WHERE NRO = @I 

					SET @ID_CARGA_MASIVA_PERSONA = (SELECT ID_CARGA_MASIVA_PERSONA FROM @Carga_masiva_persona_tmp);
				END
				ELSE BEGIN
					PRINT 'UPDATE transaccional.carga_masiva_nominas_persona'
					UPDATE cmnp SET cmnp.NOMBRE_COMPLETO = cmnd.NOMBRE_COMPLETO,cmnp.SEXO = cmnp.SEXO,cmnp.EDAD = cmnp.EDAD,cmnp.TIENE_DISCAPACIDAD = (CASE cmnd.TIENE_DISCAPACIDAD WHEN 'True' THEN 1 ELSE 0 END),
						cmnp.ES_ACTIVO = 1, cmnp.USUARIO_MODIFICACION = @USUARIO_CREACION, cmnp.FECHA_MODIFICACION = @FECHA_ACTUAL
					FROM transaccional.carga_masiva_nominas_persona cmnp
						INNER JOIN #tmpCargaMasivaNominaDetalle cmnd ON cmnp.ID_TIPO_DOCUMENTO = cmnd.ID_TIPO_DOCUMENTO AND cmnp.NUMERO_DOCUMENTO = cmnd.NUMERO_DOCUMENTO
					WHERE ID_CARGA_MASIVA_PERSONA = @ID_CARGA_MASIVA_PERSONA AND cmnd.NRO = @I
				END

				-->INSERTAR DETALLE NÓMINA
				PRINT 'INSERT transaccional.carga_masiva_nominas_detalle'
				INSERT INTO transaccional.carga_masiva_nominas_detalle (ID_CARGA_MASIVA_NOMINA, ID_CARGA_MASIVA_PERSONA, NOMBRE_UNIDAD_DIDACTICA, NOTA, ES_ACTIVO, ESTADO, USUARIO_CREACION, FECHA_CREACION)
				SELECT @ID_CARGA_MASIVA_NOMINA, @ID_CARGA_MASIVA_PERSONA, NOMBRE_UNIDAD_DIDACTICA, (CASE NOTA WHEN '' THEN NULL ELSE NOTA END), 1, 1, @USUARIO_CREACION, @FECHA_ACTUAL
				FROM #tmpCargaMasivaNominaDetalle
				WHERE NRO = @I
				
				DELETE FROM @Carga_masiva_persona_tmp
				SET @I = @I + 1;
			END
		END
		
		UPDATE cmn SET SECCION = e.VALOR_ENUMERADO
		FROM transaccional.carga_masiva_nominas cmn
		INNER JOIN sistema.enumerado e ON e.ID_ENUMERADO = cmn.ID_SECCION
		WHERE ID_CARGA_MASIVA_NOMINA = @ID_CARGA_MASIVA_NOMINA

		UPDATE cmn SET CODIGO_MODULAR = i.CODIGO_MODULAR
		FROM transaccional.carga_masiva_nominas cmn
		INNER JOIN db_auxiliar.dbo.UVW_INSTITUCION i ON i.ID_INSTITUCION = cmn.ID_INSTITUCION
		WHERE ID_CARGA_MASIVA_NOMINA = @ID_CARGA_MASIVA_NOMINA

		UPDATE cmn SET NOMBRE_CARRERA = c.NOMBRE_CARRERA,TIPO_NIVEL_FORMACION=c.TIPO_NIVEL_FORMACION
		FROM transaccional.carga_masiva_nominas cmn
		INNER JOIN db_auxiliar.dbo.UVW_CARRERA c ON c.ID_CARRERA = cmn.ID_CARRERA
		WHERE ID_CARGA_MASIVA_NOMINA = @ID_CARGA_MASIVA_NOMINA
		
		SET @RESULT = 1
	END

	BEGIN --> ELIMINAR TABLA TEMPORAL 
		DROP TABLE #tmpCargaMasivaNominaDetalle
	END
		
	BEGIN --> RESPUESTA FINAL 
		IF @RESULT = 1 
		BEGIN

			SET @RESPUETA_MENSAJE = 'El archivo excel se registró correctamente.'
			
			--if @RESPUETA_MENSAJE ='' 			
			--set @RESPUETA_MENSAJE = 'El archivo excel se registró correctamente. No se encontraron observaciones.'			
										
			SELECT EstadoProceso = '1' ,Mensajes = @RESPUETA_MENSAJE																											

			--//VISOR DE MENSAJES SOLO PARA PRUEBA DESCOMENTAR.
			--SELECT SplitData AS 'Lista de Mensajes'  FROM dbo.UFN_SPLIT(@RESPUETA_MENSAJE,'|');
        END
		ELSE
		BEGIN
			SET @RESPUETA_MENSAJE = 'La nómina no se puede registrar porque ya existe en el sistema.'								
			SELECT EstadoProceso = '3', Mensajes = @RESPUETA_MENSAJE

		END
	END

	COMMIT TRAN InsertarCargaMasivaNominas
END	TRY
BEGIN CATCH
	SELECT 
		EstadoProceso = '0', Mensajes = @RESPUETA_MENSAJE
		--,LineaError = @LINEA_ERROR

		--PRUEBAS
		,ERROR_MESSAGE() AS 'ERROR_MESSAGE'
		,CAST(ERROR_LINE() AS VARCHAR(100)) AS 'ERROR_LINE'

		--,INDEX_NO_REGISTRADOS_NOMBRE_UD_VACIO			= @INDEX_NO_REGISTRADOS_NOMBRE_UD_VACIO
		--,INDEX_REGISTRADOS_ID_SEMESTRE_ACADEMICO_CERO	= @INDEX_REGISTRADOS_ID_SEMESTRE_ACADEMICO_CERO
		--,INDEX_REGISTRADOS_CONSOLIDADOS_CERO			= @INDEX_REGISTRADOS_CONSOLIDADOS_CERO

		,CAST(ERROR_NUMBER() AS VARCHAR(MAX)) AS 'ERROR_NUMBER'
		,CAST( ERROR_SEVERITY() AS VARCHAR(MAX)) AS 'ERROR_SEVERITY'
		,CAST(ERROR_STATE() AS VARCHAR(MAX))AS 'ERROR_STATE'
		,ERROR_PROCEDURE() AS 'ERROR_PROCEDURE'
		--,ERROR_LINE() AS 'ERROR_LINE'
		--,ERROR_MESSAGE() AS 'ERROR_MESSAGE' 

	ROLLBACK TRAN InsertarCargaMasivaNominas
END CATCH