CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_PERSONAL_INSTITUCION_LISTA]
(
	@ID_INSTITUCION					INT,
	@ID_PERIODO_LECTIVO_INSTITUCION	INT

	--DECLARE @ID_INSTITUCION					INT=1911
	--DECLARE @ID_PERIODO_LECTIVO_INSTITUCION	INT=5493
)AS 
BEGIN
	SELECT 

		A.ID_PERSONAL_INSTITUCION	Value, 
		P.APELLIDO_PATERNO_PERSONA + ' '+ P.APELLIDO_MATERNO_PERSONA + ', ' + P.NOMBRE_PERSONA Text, 
		A.ID_PERSONAL_INSTITUCION	Code
		
	FROM maestro.personal_institucion A
	JOIN maestro.persona_institucion B ON B.ID_PERSONA_INSTITUCION = A.ID_PERSONA_INSTITUCION
	JOIN maestro.persona P ON P.ID_PERSONA = B.ID_PERSONA
	WHERE B.ID_INSTITUCION = @ID_INSTITUCION
	AND A.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION
	AND A.ES_ACTIVO = 1 AND A.ESTADO = 1 AND A.ID_ROL IN (47,48,218)
	
END
GO


