CREATE PROCEDURE [dbo].[USP_MAESTROS_UPD_ESTADO_TURNO_INSTITUCION]
(
	@ID_TURNO_INSTITUCION		        INT,	
	@USUARIO					        VARCHAR(20)
)
AS
BEGIN
	DECLARE @RESULT INT	
		BEGIN	
			UPDATE maestro.turnos_por_institucion
			SET ESTADO = CASE WHEN ESTADO = 1 THEN 2 ELSE 1 END,
			USUARIO_MODIFICACION = @USUARIO,
			FECHA_MODIFICACION = GETDATE()
			WHERE ID_TURNOS_POR_INSTITUCION = @ID_TURNO_INSTITUCION
			SET @RESULT = 1
		END
SELECT @RESULT
END
GO


