--USP_CONVALIDACION_UPD_CONVALIDACION 24, 18, 199,773,113,'MALVA'

CREATE PROCEDURE [dbo].[USP_CONVALIDACION_UPD_CONVALIDACION]
(
	@ID_CONVALIDACION					INT,		
	@ID_ESTUDIANTE_INSTITUCION			INT,
	@ID_TIPO_CONVALIDACION				INT,
	@ID_TURNOS_POR_INSTITUCION			INT,
	@ID_SEMESTRE_ACADEMICO				INT,	
	@NRO_RESOLUCION                     VARCHAR(50),
	@ARCHIVO_CONVALIDACION              VARCHAR(50),
	@USUARIO							VARCHAR(20)
)
AS
DECLARE @RESULT INT
BEGIN

	BEGIN TRANSACTION T1
	BEGIN TRY

		UPDATE transaccional.estudiante_institucion
		SET ID_TURNOS_POR_INSTITUCION	=	 @ID_TURNOS_POR_INSTITUCION,
			ID_SEMESTRE_ACADEMICO		=	 @ID_SEMESTRE_ACADEMICO,
			USUARIO_MODIFICACION		=	 @USUARIO, 
			FECHA_MODIFICACION			=	 GETDATE()
		WHERE ID_ESTUDIANTE_INSTITUCION= @ID_ESTUDIANTE_INSTITUCION AND ES_ACTIVO=1

		UPDATE transaccional.convalidacion 
		SET ID_TIPO_CONVALIDACION= @ID_TIPO_CONVALIDACION,
		    NRO_RD                      =    @NRO_RESOLUCION,
			ARCHIVO_RD                  =    @ARCHIVO_CONVALIDACION,
			USUARIO_MODIFICACION		=	 @USUARIO, 
			FECHA_MODIFICACION			=	 GETDATE()
		WHERE ID_CONVALIDACION= @ID_CONVALIDACION AND ES_ACTIVO=1
	
		COMMIT TRANSACTION T1
		SET @RESULT = 1
	END TRY
	BEGIN CATCH
			IF @@ERROR<>0
			BEGIN
			   ROLLBACK TRANSACTION T1	   
			   SET @RESULT = -1
			   PRINT ERROR_MESSAGE()
			END
	END CATCH
	SELECT @RESULT
END
GO


