/**********************************************************************************************************
AUTOR				:	Juan Chavez
FECHA DE CREACION	:	13/09/2021
LLAMADO POR			:
DESCRIPCION			:	Obtiene información detallada de programas de estudios de una institución. 
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
1.0			13/09/2021		JCHAVEZ			CREACIÓN
--  TEST:			
	EXEC USP_REPORTE_MONITOREO_PROGRAMA_ESTUDIOS 3938
**********************************************************************************************************/
CREATE PROCEDURE dbo.USP_REPORTE_MONITOREO_PROGRAMA_ESTUDIOS
 @ID_PERIODO_LECTIVO_INSTITUCION INT
AS
BEGIN

	DECLARE @ID_INSTITUCION INT
	DECLARE @ID_PERIODO_LECTIVO INT

	SELECT @ID_INSTITUCION = ID_INSTITUCION, @ID_PERIODO_LECTIVO = ID_PERIODO_LECTIVO
	FROM transaccional.periodos_lectivos_por_institucion WHERE ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODO_LECTIVO_INSTITUCION

	SELECT CODIGO_PERIODO_LECTIVO = (SELECT TOP 1 CODIGO_PERIODO_LECTIVO FROM maestro.periodo_lectivo WHERE ID_PERIODO_LECTIVO = @ID_PERIODO_LECTIVO),
		i.NOMBRE_DEPARTAMENTO, i.NOMBRE_PROVINCIA, i.NOMBRE_DISTRITO, i.CODIGO_MODULAR, i.NOMBRE_INSTITUCION,i.TIPO_GESTION_NOMBRE, 
		c.NOMBRE_CARRERA,fp.CODIGO_FAMILIA_PRODUCTIVA + ' - ' + fp.FAMILIA_PRODUCTIVA FAMILIA_PRODUCTIVA,
		pestudio.NOMBRE_PLAN_ESTUDIOS,pestudio.ID_TIPO_ITINERARIO, enu.VALOR_ENUMERADO TIPO_PLAN_ESTUDIO
	FROM transaccional.carreras_por_institucion cins
	INNER JOIN db_auxiliar.dbo.UVW_CARRERA c ON cins.ID_CARRERA = c.ID_CARRERA 
	INNER JOIN db_auxiliar.dbo.UVW_INSTITUCION i ON cins.ID_INSTITUCION = i.ID_INSTITUCION 
	INNER JOIN sistema.enumerado enu ON cins.ID_TIPO_ITINERARIO = enu.ID_ENUMERADO
	LEFT JOIN transaccional.plan_estudio pestudio  ON pestudio.ID_CARRERAS_POR_INSTITUCION = cins.ID_CARRERAS_POR_INSTITUCION AND pestudio.ES_ACTIVO=1
	LEFT JOIN db_digepadron.dbo.familia_productiva fp ON c.CODIGO_FAMILIA_PRODUCTIVO = fp.CODIGO_FAMILIA_PRODUCTIVA
	WHERE cins.ID_INSTITUCION = @ID_INSTITUCION
		AND cins.ES_ACTIVO=1 
	GROUP BY i.NOMBRE_DEPARTAMENTO, i.NOMBRE_PROVINCIA, i.NOMBRE_DISTRITO, i.CODIGO_MODULAR, i.NOMBRE_INSTITUCION,i.TIPO_GESTION_NOMBRE, 
		c.NOMBRE_CARRERA,fp.CODIGO_FAMILIA_PRODUCTIVA,fp.FAMILIA_PRODUCTIVA,pestudio.ID_TIPO_ITINERARIO,pestudio.NOMBRE_PLAN_ESTUDIOS, enu.VALOR_ENUMERADO
	ORDER BY i.NOMBRE_DEPARTAMENTO, i.NOMBRE_PROVINCIA, i.NOMBRE_DISTRITO, i.CODIGO_MODULAR,c.NOMBRE_CARRERA,pestudio.ID_TIPO_ITINERARIO
END