CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_APODERADO_POSTULANTE]
(
	@ID_INSTITUCION		INT,
	@ID_TIPO_DOCUMENTO	INT,
	@NUMERO_DOCUMENTO	VARCHAR(15)
)
AS
BEGIN
SELECT
		P.ID_PERSONA					IdPersona,
		CASE WHEN PEI.ID_INSTITUCION = @ID_INSTITUCION THEN PEI.ID_PERSONA_INSTITUCION	ELSE 0 END 	IdPersonaInstitucion,
		P.APELLIDO_PATERNO_PERSONA		ApellidoPaterno,
		P.APELLIDO_MATERNO_PERSONA		ApellidoMaterno,
		P.NOMBRE_PERSONA				Nombre,
		P.SEXO_PERSONA					IdSexo,
		PEI.ESTADO_CIVIL				IdEstadoCivil,
		P.FECHA_NACIMIENTO_PERSONA		FechaNacimiento,
		PEI.PAIS_PERSONA				IdPaisResidencia,
		URES.CODIGO_UBIGEO				UbigeoResidencia,
		P.PAIS_NACIMIENTO				IdPaisNacimiento,
		UNAC.CODIGO_UBIGEO				UbigeoNacimiento,
		P.ID_LENGUA_MATERNA				IdLenguaMaterna,
		P.ES_DISCAPACITADO				EsDiscapacitado,
		
		--PINS.ID_PERSONAL_INSTITUCION	IdPersonalInstitucion,
		PEI.DIRECCION_PERSONA			Direccion
		--PEI.CORREO						Correo,
		--PEI.TELEFONO					Telefono,
		--PEI.CELULAR						Celular
FROM
		maestro.persona P
		INNER JOIN maestro.persona_institucion PEI ON PEI.ID_PERSONA = P.ID_PERSONA
		LEFT JOIN db_auxiliar.dbo.UVW_UBIGEO_RENIEC URES ON URES.CODIGO_UBIGEO = PEI.UBIGEO_PERSONA
		LEFT JOIN db_auxiliar.dbo.UVW_UBIGEO_RENIEC UNAC ON UNAC.CODIGO_UBIGEO = P.UBIGEO_NACIMIENTO
		--LEFT JOIN maestro.personal_institucion PINS ON PEI.ID_PERSONA_INSTITUCION = PINS.ID_PERSONA_INSTITUCION AND PINS.ES_ACTIVO = 1
WHERE
		P.ID_TIPO_DOCUMENTO = @ID_TIPO_DOCUMENTO
		AND P.NUMERO_DOCUMENTO_PERSONA = @NUMERO_DOCUMENTO		
END
GO


