CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_PROCESO_ADMISION_PERIODO]
(
	@ID_PERIODO_LECTIVO_INSTITUCION	INT
)
AS
SELECT TOP 1
A.ID_PROCESO_ADMISION_PERIODO	IdProcesoAdmision,
A.NOMBRE_PROCESO_ADMISION		ProcesoAdmisionPeriodo,
A.MODALIDADES					Modalidades,
A.FECHA_INICIO					FechaInicio,
A.FECHA_FIN						FechaFin,
(SELECT TOP 1 NOTA_MINIMA FROM transaccional.modalidades_por_proceso_admision
WHERE ID_PROCESO_ADMISION_PERIODO = A.ID_PROCESO_ADMISION_PERIODO AND ES_ACTIVO = 1) NotaMinima
FROM transaccional.proceso_admision_periodo A
WHERE A.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION
AND A.ES_ACTIVO = 1
GO


