CREATE PROCEDURE [dbo].[USP_MATRICULA_SEL_ESTUDIANTE_TRASLADO]
(
	@ID_TIPO_DOCUMENTO	INT,
    @NUMERO_DOCUMENTO	VARCHAR(15),
	@ID_PERSONA			INT = 0
)
AS
BEGIN

SELECT 

persona.ID_PERSONA                       IdPersona,
persona.APELLIDO_PATERNO_PERSONA +' '+ persona.APELLIDO_MATERNO_PERSONA + ' ' + persona.NOMBRE_PERSONA   Estudiante,
persona.ID_TIPO_DOCUMENTO				IdTipoDocumento,
persona.NUMERO_DOCUMENTO_PERSONA		NroDocumento
 
FROM maestro.persona persona 
WHERE
(persona.ID_TIPO_DOCUMENTO        = @ID_TIPO_DOCUMENTO 
AND UPPER(persona.NUMERO_DOCUMENTO_PERSONA) = UPPER(@NUMERO_DOCUMENTO))
OR persona.ID_PERSONA= @ID_PERSONA

END
GO


