
-- USP_MAESTROS_DEL_PERIODO_LECTIVO 1,'oo'
CREATE PROCEDURE [dbo].[USP_MAESTROS_DEL_PERIODO_LECTIVO]
(
	@ID_PERIODO_LECTIVO INT,
	@USUARIO VARCHAR(20)
)
AS

DECLARE @EXISTENTES INT ;
SELECT @EXISTENTES=count(PLI.ID_PERIODOS_LECTIVOS_POR_INSTITUCION) from transaccional.periodos_lectivos_por_institucion PLI  
WHERE PLI.ID_PERIODO_LECTIVO=@ID_PERIODO_LECTIVO AND PLI.ESTADO =7 AND PLI.ES_ACTIVO=1

IF (@EXISTENTES>0)
BEGIN
    SELECT cast(0 AS bit) as Success,@EXISTENTES AS Value
END

ELSE
BEGIN    
 --   EXEC USP_MAESTROS_DEL_PERIODO_LECTIVO_INSTITUCION_DESASIGNAR 0,@ID_PERIODO_LECTIVO,@USUARIO
    
	--UPDATE maestro.periodo_lectivo
 --   SET ES_ACTIVO=0, 
	--   USUARIO_MODIFICACION=@USUARIO,
	--   FECHA_MODIFICACION=getdate()
 --   WHERE ID_PERIODO_LECTIVO=@ID_PERIODO_LECTIVO
 --   AND ES_ACTIVO=1

 --   SELECT cast(1 AS bit) as Success,@@ROWCOUNT AS Value
	BEGIN TRANSACTION T1
	BEGIN TRY
		--DELETE FROM transaccional.periodos_lectivos_por_institucion WHERE ID_PERIODO_LECTIVO = @ID_PERIODO_LECTIVO
		--DELETE FROM maestro.periodo_lectivo WHERE ID_PERIODO_LECTIVO=@ID_PERIODO_LECTIVO

		UPDATE transaccional.periodos_lectivos_por_institucion
		SET ES_ACTIVO=0
		WHERE ID_PERIODO_LECTIVO = @ID_PERIODO_LECTIVO

		UPDATE maestro.periodo_lectivo
		SET ESTADO=0
		WHERE ID_PERIODO_LECTIVO = @ID_PERIODO_LECTIVO

	COMMIT TRANSACTION T1
		SELECT cast(1 AS bit) as Success,@@ROWCOUNT AS Value
	END TRY	   
	BEGIN CATCH
		IF @@ERROR<>0
		BEGIN
			ROLLBACK TRANSACTION T1	   
			SELECT cast(0 AS bit) as Success,-1 AS Value
		END
	END CATCH	
END
GO


