/**********************************************************************************************************
AUTOR				:	Juan Tovar
FECHA DE CREACION	:	20/06/2019
LLAMADO POR			:
DESCRIPCION			:	Modifica un registro de peridoo lectivo 
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
--  TEST:			
	EXEC USP_MAESTROS_UPD_PERIODO_LECTIVO 4,'2013-2',5,'2013-08-01','2013-12-30', 'MALVA'
**********************************************************************************************************/
CREATE PROCEDURE [dbo].[USP_MAESTROS_UPD_PERIODO_LECTIVO]
(
	@ID_PERIODO_LECTIVO	INT,
	@CODIGO_PERIODO_LECTIVO VARCHAR(20),
	@ID_ENUMERADO_TIPO_OPCION INT,
	@FECHA_INICIO DATETIME,
	@FECHA_FIN DATETIME,
	@USUARIO VARCHAR(20)
)
AS
DECLARE @RESULT INT
IF EXISTS(	SELECT pl.ID_PERIODO_LECTIVO 
			FROM maestro.periodo_lectivo pl 
			WHERE pl.ID_TIPO_OPCION = @ID_ENUMERADO_TIPO_OPCION AND 
				((@FECHA_INICIO BETWEEN pl.FECHA_INICIO AND pl.FECHA_FIN) 
				OR ( @FECHA_FIN BETWEEN pl.FECHA_INICIO AND pl.FECHA_FIN) ) 
				AND pl.ID_PERIODO_LECTIVO <> @ID_PERIODO_LECTIVO AND pl.ESTADO<>0)
BEGIN 
    SET @RESULT = -30
END
ELSE
BEGIN 
    IF EXISTS(SELECT TOP 1 ID_PERIODO_LECTIVO FROM maestro.periodo_lectivo 
    WHERE CODIGO_PERIODO_LECTIVO = UPPER(@CODIGO_PERIODO_LECTIVO) COLLATE LATIN1_GENERAL_CI_AI AND ID_PERIODO_LECTIVO <> @ID_PERIODO_LECTIVO
    AND ID_TIPO_OPCION=@ID_ENUMERADO_TIPO_OPCION AND ESTADO<>0)
		  SET @RESULT = -180
    ELSE
    BEGIN
		  UPDATE maestro.periodo_lectivo
		  SET CODIGO_PERIODO_LECTIVO = UPPER(@CODIGO_PERIODO_LECTIVO),
			 ID_TIPO_OPCION = @ID_ENUMERADO_TIPO_OPCION,
			 FECHA_INICIO = @FECHA_INICIO,
			 FECHA_FIN = @FECHA_FIN,
			 FECHA_MODIFICACION = GETDATE(),
			 USUARIO_MODIFICACION = @USUARIO
		  WHERE ID_PERIODO_LECTIVO = @ID_PERIODO_LECTIVO
		  --EXEC [USP_MAESTROS_INS_PERIODO_LECTIVO_INSTITUCION_MASIVO_DIRECTO] @ID_PERIODO_LECTIVO,@FECHA_INICIO,@FECHA_FIN,@USUARIO
		  SET @RESULT = 1
    END
END
SELECT @RESULT
GO


