CREATE PROCEDURE [dbo].[USP_MAESTROS_SEL_PROGRAMACION_MATRICULA_LISTA]
(  
	@ID_PERIODOS_LECTIVOS_POR_INSTITUCION INT
)  
AS  
BEGIN  
 SET NOCOUNT ON;  


SELECT 
	en.VALOR_ENUMERADO Text,
	ID_PROGRAMACION_MATRICULA Value
FROM 
	transaccional.programacion_matricula pm
	INNER JOIN sistema.enumerado en ON pm.ID_TIPO_MATRICULA = en.ID_ENUMERADO
WHERE
	pm.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODOS_LECTIVOS_POR_INSTITUCION

END
GO


