

CREATE PROCEDURE [dbo].[USP_MATRICULA_INS_REINGRESO_ESTUDIANTE]
(
	@ID_INSTITUCION INT,
	@ID_PERIODOLECTIVO_INSTITUCION INT,
	@ID_TIPO_DOCUMENTO INT,
	@NRO_DOCUMENTO VARCHAR(15),
	@ID_LICENCIA_ESTUDIANTE INT, 
	@ID_RESERVA_MATRICULA	INT,	
	@TIEMPO_LICENCIA VARCHAR (50),
	@USUARIO VARCHAR(20)
)
AS

DECLARE @RESULT INT


IF EXISTS(SELECT TOP 1 ID_REINGRESO_ESTUDIANTE FROM [transaccional].[reingreso_estudiante]
WHERE (ID_LICENCIA_ESTUDIANTE = @ID_LICENCIA_ESTUDIANTE OR ID_RESERVA_MATRICULA =@ID_RESERVA_MATRICULA) AND ES_ACTIVO=1 
	AND ID_PERIODOS_LECTIVOS_POR_INSTITUCION=@ID_PERIODOLECTIVO_INSTITUCION)
BEGIN
	SET @RESULT = -180 -- YA SE ENCUENTRA REGISTRADO
END
ELSE
	BEGIN    	--print 'dentro de la transaccion'
	
	INSERT INTO [transaccional].[reingreso_estudiante]
           ([ID_LICENCIA_ESTUDIANTE]
		   ,[ID_RESERVA_MATRICULA]
           ,[ID_PERIODOS_LECTIVOS_POR_INSTITUCION]
           ,[FECHA_FIN]
		   ,[TIEMPO_LICENCIA]
           ,[ES_ACTIVO]
           ,[ESTADO]
           ,[FECHA_CREACION]
           ,[USUARIO_CREACION]
		 )

     VALUES
           (CASE WHEN @ID_LICENCIA_ESTUDIANTE =0 THEN NULL ELSE @ID_LICENCIA_ESTUDIANTE END
		   ,CASE WHEN @ID_RESERVA_MATRICULA = 0 THEN NULL ELSE @ID_RESERVA_MATRICULA END
		   ,@ID_PERIODOLECTIVO_INSTITUCION	  
		   ,GETDATE()
		   ,@TIEMPO_LICENCIA 
		   ,1
		   ,1		  
		   ,GETDATE()		  
		   ,@USUARIO	  
		  )

		
	SET @RESULT = 1
END	
SELECT @RESULT
GO


