/**********************************************************************************************************
AUTOR				:	Juan Chavez
FECHA DE CREACION	:	13/09/2021
LLAMADO POR			:
DESCRIPCION			:	Obtiene información detallada de matrícula de una institución por periodo lectivo. 
REVISIONES			:
-----------------------------------------------------------------------------------------------------------
VERSIÓN		FECHA MODIF.	USUARIO			DESCRIPCIÓN
-----------------------------------------------------------------------------------------------------------
1.0			13/09/2021		JCHAVEZ			CREACIÓN
--  TEST:			
	EXEC USP_REPORTE_MONITOREO_MATRICULA 3938
**********************************************************************************************************/
CREATE PROCEDURE dbo.USP_REPORTE_MONITOREO_MATRICULA
 @ID_PERIODO_LECTIVO_INSTITUCION INT
AS
BEGIN	
	SELECT DISTINCT plec.ID_PERIODO_LECTIVO,plec.ID_INSTITUCION, i.NOMBRE_DEPARTAMENTO, i.NOMBRE_PROVINCIA, i.NOMBRE_DISTRITO, i.CODIGO_MODULAR,i.NOMBRE_INSTITUCION
	INTO ##inst_pend_cierre
	FROM transaccional.matricula_estudiante (NOLOCK) mestu 
		INNER JOIN transaccional.evaluacion_detalle (NOLOCK) edet ON mestu.ID_MATRICULA_ESTUDIANTE = edet.ID_MATRICULA_ESTUDIANTE 
		INNER JOIN transaccional.evaluacion (NOLOCK) eva ON edet.ID_EVALUACION = eva.ID_EVALUACION 
		INNER JOIN transaccional.periodos_lectivos_por_institucion (NOLOCK) plec ON mestu.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = plec.ID_PERIODOS_LECTIVOS_POR_INSTITUCION 
		INNER JOIN transaccional.programacion_clase (NOLOCK) pclase ON eva.ID_PROGRAMACION_CLASE = pclase.ID_PROGRAMACION_CLASE 
		INNER JOIN db_auxiliar.dbo.UVW_INSTITUCION (NOLOCK) i ON plec.ID_INSTITUCION = i.ID_INSTITUCION
	WHERE mestu.ES_ACTIVO=1 AND edet.ES_ACTIVO=1 AND eva.ES_ACTIVO=1 and plec.ES_ACTIVO=1 
		AND (eva.CIERRE_PROGRAMACION = 234 OR eva.CIERRE_PROGRAMACION IS NULL)

	SELECT pe.CODIGO_PERIODO_LECTIVO,i.NOMBRE_DEPARTAMENTO, i.NOMBRE_PROVINCIA, i.NOMBRE_DISTRITO, i.CODIGO_MODULAR, i.NOMBRE_INSTITUCION,i.TIPO_GESTION_NOMBRE, 
		REPLICATE('0',10-LEN(p.ID_PERSONA)) + CAST(p.ID_PERSONA AS VARCHAR(20)) ID,eins.ID_PERSONA_INSTITUCION,enu.VALOR_ENUMERADO TIPO_DOCUMENTO,p.NUMERO_DOCUMENTO_PERSONA,
		UPPER(p.APELLIDO_PATERNO_PERSONA) APELLIDO_PATERNO_PERSONA, UPPER(p.APELLIDO_MATERNO_PERSONA) APELLIDO_MATERNO_PERSONA, UPPER(p.NOMBRE_PERSONA) NOMBRE_PERSONA,
		enumera.VALOR_ENUMERADO SEXO,CONVERT(VARCHAR(10),p.FECHA_NACIMIENTO_PERSONA,103) FECHA_NACIMIENTO_PERSONA, pins.CORREO, pins.CELULAR,enulm.VALOR_ENUMERADO LENGUA_MATERNA,pais.DSCPAIS PAIS_PROCEDENCIA,
		--ISNULL(ubiieb.DEPARTAMENTO_UBIGEO,'') DEPARTAMENTO_UBIGEO_IE_BASICA,
		ibasica.UBIGEO_IE_BASICA CODIGO_UBIGEO_IE_BASICA,ubiieb.DEPARTAMENTO_UBIGEO DEPARTAMENTO_IE_BASICA, ubiieb.PROVINCIA_UBIGEO PROVINCIA_IE_BASICA, ubiieb.DISTRITO_UBIGEO DISTRITO_IE_BASICA,
		enu_ti_ieb.VALOR_ENUMERADO TIPO_INSTITUCION_IE_BASICA,ibasica.CODIGO_MODULAR_IE_BASICA,UPPER(ibasica.NOMBRE_IE_BASICA) NOMBRE_IE_BASICA,enu_tg_ieb.VALOR_ENUMERADO TIPO_GESTION_IE_BASICA,eins.ANIO_EGRESO,
		c.CODIGO_CARRERA, c.NOMBRE_CARRERA, enume.VALOR_ENUMERADO AS CICLO
		, ESTADO_PERIODO = (CASE WHEN ipc.ID_INSTITUCION IS NULL AND GETDATE()>plec.FECHA_FIN_INSTITUCION THEN 'TERMINADO' ELSE 'SIN TERMINO' END),(CONVERT(VARCHAR(10),mestu.FECHA_CREACION,103) + ' ' + CONVERT(VARCHAR(10),mestu.FECHA_CREACION,108)) FECHA_CREACION
	FROM maestro.persona (NOLOCK) p 
		INNER JOIN maestro.persona_institucion (NOLOCK) pins ON p.ID_PERSONA = pins.ID_PERSONA 
		INNER JOIN transaccional.estudiante_institucion (NOLOCK) eins ON pins.ID_PERSONA_INSTITUCION = eins.ID_PERSONA_INSTITUCION 
		INNER JOIN transaccional.matricula_estudiante (NOLOCK) mestu ON eins.ID_ESTUDIANTE_INSTITUCION = mestu.ID_ESTUDIANTE_INSTITUCION 
		INNER JOIN transaccional.periodos_lectivos_por_institucion (NOLOCK) plec ON mestu.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = plec.ID_PERIODOS_LECTIVOS_POR_INSTITUCION
		INNER JOIN maestro.periodo_lectivo (NOLOCK) pe ON plec.ID_PERIODO_LECTIVO = pe.ID_PERIODO_LECTIVO
		INNER JOIN db_auxiliar.dbo.UVW_INSTITUCION (NOLOCK) i ON plec.ID_INSTITUCION = i.ID_INSTITUCION 
		INNER JOIN sistema.enumerado (NOLOCK) enu ON p.ID_TIPO_DOCUMENTO = enu.ID_ENUMERADO 
		INNER JOIN sistema.enumerado (NOLOCK) enulm ON p.ID_LENGUA_MATERNA = enulm.ID_ENUMERADO 
		INNER JOIN transaccional.carreras_por_institucion_detalle (NOLOCK) cpidet ON eins.ID_CARRERAS_POR_INSTITUCION_DETALLE = cpidet.ID_CARRERAS_POR_INSTITUCION_DETALLE 
		INNER JOIN transaccional.carreras_por_institucion (NOLOCK) cins ON cpidet.ID_CARRERAS_POR_INSTITUCION = cins.ID_CARRERAS_POR_INSTITUCION 
		INNER JOIN db_auxiliar.dbo.UVW_CARRERA (NOLOCK) c ON cins.ID_CARRERA = c.ID_CARRERA 
		INNER JOIN sistema.enumerado (NOLOCK) enume ON mestu.ID_SEMESTRE_ACADEMICO = enume.ID_ENUMERADO 
		INNER JOIN sistema.enumerado (NOLOCK) enumera ON p.SEXO_PERSONA = enumera.ID_ENUMERADO
		LEFT JOIN db_auxiliar.dbo.UVW_PAIS pais (NOLOCK) ON p.PAIS_NACIMIENTO =  replace(ltrim(replace(pais.CODIGO,'000000',' ')),' ','0')
		LEFT JOIN maestro.institucion_basica ibasica (NOLOCK) ON eins.ID_INSTITUCION_BASICA = ibasica.ID_INSTITUCION_BASICA 
		LEFT JOIN sistema.enumerado enu_tg_ieb (NOLOCK) ON ibasica.ID_TIPO_GESTION_IE_BASICA = enu_tg_ieb.ID_ENUMERADO 
		LEFT JOIN sistema.enumerado enu_ti_ieb (NOLOCK) ON ibasica.ID_TIPO_INSTITUCION_BASICA = enu_ti_ieb.ID_ENUMERADO 
		--LEFT JOIN db_auxiliar.dbo.UVW_UBIGEO_INEI (NOLOCK) ubiieb ON ibasica.UBIGEO_IE_BASICA = ubiieb.CODIGO_UBIGEO
		LEFT JOIN db_auxiliar.dbo.UVW_UBIGEO (NOLOCK) ubiieb ON ibasica.UBIGEO_IE_BASICA = ubiieb.CODIGO_UBIGEO
		LEFT JOIN ##inst_pend_cierre ipc ON ipc.ID_INSTITUCION = i.ID_INSTITUCION AND ipc.ID_PERIODO_LECTIVO = plec.ID_PERIODO_LECTIVO 
	WHERE plec.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION
		AND eins.ES_ACTIVO=1 AND mestu.ES_ACTIVO=1
	GROUP BY pe.CODIGO_PERIODO_LECTIVO,i.NOMBRE_DEPARTAMENTO, i.NOMBRE_PROVINCIA, i.NOMBRE_DISTRITO, i.CODIGO_MODULAR, i.NOMBRE_INSTITUCION,i.TIPO_GESTION_NOMBRE, enu.VALOR_ENUMERADO,eins.ID_PERSONA_INSTITUCION,p.NUMERO_DOCUMENTO_PERSONA,
		p.ID_PERSONA,p.APELLIDO_PATERNO_PERSONA, p.APELLIDO_MATERNO_PERSONA, p.NOMBRE_PERSONA,enumera.VALOR_ENUMERADO,p.FECHA_NACIMIENTO_PERSONA, pins.CORREO, pins.CELULAR,enulm.VALOR_ENUMERADO,pais.DSCPAIS,
		ibasica.UBIGEO_IE_BASICA,ubiieb.DEPARTAMENTO_UBIGEO, ubiieb.PROVINCIA_UBIGEO, ubiieb.DISTRITO_UBIGEO,
		enu_ti_ieb.VALOR_ENUMERADO,ibasica.CODIGO_MODULAR_IE_BASICA,ibasica.NOMBRE_IE_BASICA,enu_tg_ieb.VALOR_ENUMERADO,eins.ANIO_EGRESO,
		c.CODIGO_CARRERA, c.NOMBRE_CARRERA, enume.VALOR_ENUMERADO,ipc.ID_INSTITUCION,plec.FECHA_FIN_INSTITUCION,mestu.FECHA_CREACION
	ORDER BY pe.CODIGO_PERIODO_LECTIVO,i.NOMBRE_DEPARTAMENTO, i.NOMBRE_PROVINCIA, i.NOMBRE_DISTRITO, i.CODIGO_MODULAR,
		p.APELLIDO_PATERNO_PERSONA, p.APELLIDO_MATERNO_PERSONA, p.NOMBRE_PERSONA

	DROP TABLE ##inst_pend_cierre
END