CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_VALIDACION_META]
(  

@ID_INSTITUCION INT,
@ID_PERIODO_LECTIVO_INSTITUCION INT
--DECLARE @ID_INSTITUCION INT=443
--DECLARE @ID_PERIODO_LECTIVO_INSTITUCION INT=1209

)  
AS  
BEGIN  

DECLARE @AÑO INT

SET @AÑO = (SELECT SUBSTRING(pl.CODIGO_PERIODO_LECTIVO,0,5) AS ID_PERIODO_LECTIVO FROM transaccional.periodos_lectivos_por_institucion pli INNER JOIN maestro.periodo_lectivo pl
ON pli.ID_PERIODO_LECTIVO = pl.ID_PERIODO_LECTIVO WHERE pli.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION)


	SELECT TOP 1 META from transaccional.meta_carrera_institucion WHERE ANIO=@AÑO 
   AND ID_CARRERAS_POR_INSTITUCION IN (SELECT ID_CARRERAS_POR_INSTITUCION FROM transaccional.carreras_por_institucion WHERE ID_INSTITUCION = @ID_INSTITUCION and ES_ACTIVO=1)

ORDER BY  META DESC
END
GO


