

CREATE PROCEDURE [dbo].[USP_ARCHIVO_UPD_CARGA_FINALIZACION]
(
@ID_CARGA INT
)
AS
DECLARE 
	@TOTAL_CORRECTOS INT =0,
	@TOTAL_INCORRECTOS INT =0

BEGIN
	DECLARE
	@TOTAL_REGISTROS INT


	SET @TOTAL_REGISTROS =(SELECT COUNT(1) FROM archivo.carga_detalle WHERE ID_CARGA= @ID_CARGA)

	SET @TOTAL_INCORRECTOS = (SELECT COUNT(1) FROM archivo.carga_detalle ACD WHERE ACD.ES_CORRECTO=0 AND ACD.ES_BORRADO=0 AND ACD.ID_CARGA=@ID_CARGA)
	
	SET @TOTAL_CORRECTOS = @TOTAL_REGISTROS - @TOTAL_INCORRECTOS
	UPDATE 
		archivo.carga
	SET
		ESTADO = 1,
		FECHA_CARGA= GETDATE(),	
		TOTAL_CORRECTOS= @TOTAL_CORRECTOS,
		TOTAL_INCORRECTOS= @TOTAL_INCORRECTOS
	WHERE 
		ID_CARGA= @ID_CARGA
	
END
SELECT @TOTAL_CORRECTOS TOTAL_CORRECTOS, @TOTAL_INCORRECTOS TOTAL_INCORRECTOS
GO


