CREATE PROCEDURE [dbo].[USP_ADMISION_SEL_ESTUDIANTE_AUX]
(
	@COD_MOD			VARCHAR(7),
	@CODIGO_ESTUDIANTE	VARCHAR(20)
)
AS
BEGIN

SELECT DISTINCT A.ID_ANIO AnioEgreso,CASE WHEN A.ID_GRADO = 14 THEN 1 ELSE 0 END Egresado, A.ID_GRADO, A.DSC_GRADO, A.ID_PERSONA, A.DNI, B.CODIGO_ESTUDIANTE
FROM 
	db_auxiliar.dbo.UVW_ESTUDIANTE_UTLANIO A
	INNER JOIN db_auxiliar.dbo.UVW_ESTUDIANTE B ON A.ID_PERSONA = B.ID_PERSONA
WHERE 
	A.ID_NIVEL IN ('A1','A2','A3','A5','B0','F0','E1','E2')
	AND A.PROMOVIDO = 1

	AND B.COD_MOD = @COD_MOD
	AND (A.DNI = @CODIGO_ESTUDIANTE OR B.CODIGO_ESTUDIANTE = @CODIGO_ESTUDIANTE)
END
GO


