CREATE PROCEDURE [dbo].[USP_EVALUACION_SEL_INSTITUTO_CIERRE_PERIODO] 
(
	@ID_PERIODO_LECTIVO_INSTITUCION INT
	--DECLARE @ID_PERIODO_LECTIVO_INSTITUCION INT=4095
	
)AS
BEGIN
	
	DECLARE @RESULT INT

	IF EXISTS (SELECT TOP 1 pacade.ID_PERIODO_ACADEMICO 
				FROM transaccional.periodos_lectivos_por_institucion plec 
				INNER JOIN transaccional.periodo_academico pacade ON plec.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = pacade.ID_PERIODOS_LECTIVOS_POR_INSTITUCION 
				INNER JOIN transaccional.programacion_clase pclase ON pacade.ID_PERIODO_ACADEMICO = pclase.ID_PERIODO_ACADEMICO
	WHERE plec.ID_PERIODOS_LECTIVOS_POR_INSTITUCION = @ID_PERIODO_LECTIVO_INSTITUCION AND pclase.ESTADO=0 AND plec.ES_ACTIVO=1 AND pacade.ES_ACTIVO=1 AND pclase.ES_ACTIVO=1)
	BEGIN
		SET @RESULT=1
	END
	ELSE
	BEGIN
		SET @RESULT=0
	END
	
END	
	SELECT @RESULT