CREATE TABLE [maestro].[indicador_logro] (
    [ID_INDICADOR_LOGRO]          [dbo].[ID]           NOT NULL,
    [ID_UNIDAD_COMPETENCIA]       [dbo].[ID]           NOT NULL,
    [CODIGO_INDICADOR_LOGRO]      [dbo].[CODIGO_LARGO] NOT NULL,
    [NOMBRE_INDICADOR_LOGRO]      [dbo].[NOMBRE_LARGO] NOT NULL,
    [DESCRIPCION_INDICADOR_LOGRO] [dbo].[DESCRIPCION]  NULL,
    [ESTADO]                      [dbo].[ESTADO]       NOT NULL,
    [USUARIO_CREACION]            [dbo].[USUARIO]      NOT NULL,
    [FECHA_CREACION]              [dbo].[FECHA_TIEMPO] NOT NULL,
    [USUARIO_MODIFICACION]        [dbo].[USUARIO]      NULL,
    [FECHA_MODIFICACION]          [dbo].[FECHA_TIEMPO] NULL,
    CONSTRAINT [PK_INDICADOR_LOGRO] PRIMARY KEY NONCLUSTERED ([ID_INDICADOR_LOGRO] ASC),
    CONSTRAINT [FK_INDICADO_RELATIONS_UNIDAD_C] FOREIGN KEY ([ID_UNIDAD_COMPETENCIA]) REFERENCES [maestro].[unidad_competencia] ([ID_UNIDAD_COMPETENCIA])
);

