CREATE TABLE [maestro].[institucion_basica] (
    [ID_INSTITUCION_BASICA]      [dbo].[ID]             IDENTITY (1, 1) NOT NULL,
    [ID_TIPO_INSTITUCION_BASICA] [dbo].[ID_ENUMERADO]   NOT NULL,
    [CODIGO_MODULAR_IE_BASICA]   [dbo].[CODIGO_MODULAR] NULL,
    [NOMBRE_IE_BASICA]           [dbo].[NOMBRE_LARGO]   NULL,
    [ID_NIVEL_IE_BASICA]         [dbo].[ID_ENUMERADO]   NOT NULL,
    [ID_TIPO_GESTION_IE_BASICA]  [dbo].[ID_ENUMERADO]   NOT NULL,
    [DIRECCION_IE_BASICA]        [dbo].[DIRECCION]      NULL,
    [ID_PAIS]                    [dbo].[ID]             NOT NULL,
    [UBIGEO_IE_BASICA]           [dbo].[UBIGEO]         NULL,
    [ESTADO]                     [dbo].[ESTADO]         NOT NULL,
    [USUARIO_CREACION]           [dbo].[USUARIO]        NOT NULL,
    [FECHA_CREACION]             [dbo].[FECHA_TIEMPO]   NOT NULL,
    [USUARIO_MODIFICACION]       [dbo].[USUARIO]        NULL,
    [FECHA_MODIFICACION]         [dbo].[FECHA_TIEMPO]   NULL,
    CONSTRAINT [PK_INSTITUCION_BASICA] PRIMARY KEY NONCLUSTERED ([ID_INSTITUCION_BASICA] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_INSTITUCION_BASICA1]
    ON [maestro].[institucion_basica]([ID_INSTITUCION_BASICA] ASC, [ID_PAIS] ASC)
    INCLUDE([ID_TIPO_INSTITUCION_BASICA], [CODIGO_MODULAR_IE_BASICA], [NOMBRE_IE_BASICA], [ID_NIVEL_IE_BASICA], [ID_TIPO_GESTION_IE_BASICA], [DIRECCION_IE_BASICA], [UBIGEO_IE_BASICA]);

