CREATE FUNCTION [dbo].[UFN_CONCAT_opcion_postulante] (@Number INT)
RETURNS VARCHAR(MAX)
AS
BEGIN
DECLARE @values AS NVARCHAR(300)
DECLARE @table AS TABLE (ORDEN INT,CAD NVARCHAR(MAX))
INSERT INTO @table
SELECT 
	ORDEN,
	CONVERT(VARCHAR,E2.ID_SEDE_INSTITUCION) + '|' +
	CASE WHEN E8.ES_SEDE_PRINCIPAL = 1 THEN 'PRINCIPAL' ELSE 'LOCAL' END + ' - ' + E8.NOMBRE_SEDE + '|' +
	CONVERT(VARCHAR,vc.ID_CARRERA) + '|' +
	vc.NOMBRE_CARRERA + '|' +
	ti.VALOR_ENUMERADO + '|' +
	pe.NOMBRE_PLAN_ESTUDIOS + '|' +
	CONVERT(VARCHAR,E3.ID_TURNOS_POR_INSTITUCION) + '|' +
	E7.VALOR_ENUMERADO + '|' +
	CONVERT(VARCHAR,E2.ID_META_CARRERA_INSTITUCION_DETALLE) + '|' +
	CONVERT(VARCHAR,E1.ORDEN) CAD
FROM	
	transaccional.opciones_por_postulante E1
	INNER JOIN transaccional.meta_carrera_institucion_detalle E2 ON E2.ID_META_CARRERA_INSTITUCION_DETALLE = E1.ID_META_CARRERA_INSTITUCION_DETALLE AND E2.ES_ACTIVO = 1
	INNER JOIN transaccional.meta_carrera_institucion E3 ON E3.ID_META_CARRERA_INSTITUCION = E2.ID_META_CARRERA_INSTITUCION AND E3.ES_ACTIVO = 1
	INNER JOIN transaccional.carreras_por_institucion ci ON ci.ID_CARRERAS_POR_INSTITUCION = E3.ID_CARRERAS_POR_INSTITUCION AND ci.ES_ACTIVO=1
	INNER JOIN db_auxiliar.dbo.UVW_CARRERA vc on vc.ID_CARRERA = ci.ID_CARRERA
	INNER JOIN transaccional.plan_estudio pe ON pe.ID_PLAN_ESTUDIO = E3.ID_PLAN_ESTUDIO AND pe.ES_ACTIVO=1
	INNER JOIN maestro.turnos_por_institucion E5 ON E5.ID_TURNOS_POR_INSTITUCION = E3.ID_TURNOS_POR_INSTITUCION AND E5.ES_ACTIVO = 1
	INNER JOIN maestro.turno_equivalencia E6 ON E6.ID_TURNO_EQUIVALENCIA = E5.ID_TURNO_EQUIVALENCIA
	INNER JOIN sistema.enumerado E7 ON E7.ID_ENUMERADO = E6.ID_TURNO
	INNER JOIN maestro.sede_institucion E8 ON E8.ID_SEDE_INSTITUCION = E2.ID_SEDE_INSTITUCION
	INNER JOIN sistema.enumerado ti ON ti.ID_ENUMERADO = pe.ID_TIPO_ITINERARIO
		
WHERE E1.ID_POSTULANTES_POR_MODALIDAD = @Number AND E1.ES_ACTIVO = 1
ORDER BY E1.ORDEN 

SELECT	@values = COALESCE(@values + ', ', '') + A.CAD
FROM @table A
ORDER BY ORDEN 

RETURN @values

END