// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class capacidades_por_componente
    {
       public int ID_CAPACIDADES_POR_COMPONENTE { get; set; }
        public int ID_COMPONENTE_CURRICULAR { get; set; }
        public string? CODIGO_CAPACIDAD { get; set; }
        public string? NOMBRE_CAPACIDAD { get; set; }
        public string? DESCRIPCION { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  componente_curricular ID_COMPONENTE_CURRICULARNavigation { get; set; } = null!;
        public  ICollection<indicadores_logro_por_capacidad> indicadores_logro_por_capacidad { get; set; }
    }
}