// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class carga_masiva_actas
    {
        public int ID_CARGA_MASIVA_ACTA { get; set; }
        public int ID_CARGA_MASIVA_NOMINA { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  carga_masiva_nominas ID_CARGA_MASIVA_NOMINANavigation { get; set; } = null!;
    }
}