// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class carga_masiva_nominas_persona
    {
       

        public int ID_CARGA_MASIVA_PERSONA { get; set; }
        public int ID_TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; } = null!;
        public string NOMBRE_COMPLETO { get; set; } = null!;
        public int SEXO { get; set; }
        public int EDAD { get; set; }
        public bool TIENE_DISCAPACIDAD { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  ICollection<carga_masiva_nominas_detalle> carga_masiva_nominas_detalle { get; set; }
    }
}