// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class carga_masiva_nominas
    {
       public int ID_CARGA_MASIVA_NOMINA { get; set; }
        public string NOMBRE_PERIODO_LECTIVO { get; set; } = null!;
        public int ID_INSTITUCION { get; set; }
        public string NOMBRE_SEDE_INSTITUCION { get; set; } = null!;
        public int? ID_CARRERA { get; set; }
        public string NOMBRE_PLAN_ESTUDIO { get; set; } = null!;
        public int ID_SEMESTRE_ACADEMICO { get; set; }
        public int ID_TURNO { get; set; }
        public int ID_SECCION { get; set; }
        public int CANTIDAD_ALUMNOS { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  enumerado ID_SECCIONNavigation { get; set; } = null!;
        public  enumerado ID_SEMESTRE_ACADEMICONavigation { get; set; } = null!;
        public  enumerado ID_TURNONavigation { get; set; } = null!;
        public  ICollection<carga_masiva_actas> carga_masiva_actas { get; set; }
        public  ICollection<carga_masiva_nominas_detalle> carga_masiva_nominas_detalle { get; set; }
    }
}