// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class carreras_por_institucion_detalle
    {
       
        public int ID_CARRERAS_POR_INSTITUCION_DETALLE { get; set; }
        public int ID_CARRERAS_POR_INSTITUCION { get; set; }
        public int ID_SEDE_INSTITUCION { get; set; }
        public int ID_ESTADO_PROGRAMA { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  carreras_por_institucion ID_CARRERAS_POR_INSTITUCIONNavigation { get; set; } = null!;
        public  sede_institucion ID_SEDE_INSTITUCIONNavigation { get; set; } = null!;
        public  ICollection<estudiante_institucion> estudiante_institucion { get; set; }
    }
}