// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class carreras_por_institucion
    {
      

        public int ID_CARRERAS_POR_INSTITUCION { get; set; }
        public int ID_INSTITUCION { get; set; }
        public int ID_CARRERA { get; set; }
        public int? ID_TIPO_ITINERARIO { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }
        public int? ID_CARRERA_BK { get; set; }

        public  ICollection<carga> carga { get; set; }
        public  ICollection<carreras_por_institucion_detalle> carreras_por_institucion_detalle { get; set; }
        public  ICollection<meta_carrera_institucion> meta_carrera_institucion { get; set; }
        public  ICollection<plan_estudio> plan_estudio { get; set; }
        public  ICollection<promover_persona_institucion> promover_persona_institucion { get; set; }
        public  ICollection<resoluciones_por_carreras_por_institucion> resoluciones_por_carreras_por_institucion { get; set; }
    }
}