// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class cierre_periodo_clases
    {
        public int ID_CIERRE_PERIODO_CLASES { get; set; }
        public int ID_PERIODO_ACADEMICO { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public int? USUARIO_CREACION { get; set; }
        public DateTime? FECHA_CREACION { get; set; }
        public int? USUARIO_MODFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  periodo_academico ID_PERIODO_ACADEMICONavigation { get; set; } = null!;
    }
}