// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class comision_proceso_admision
    {
        public int ID_COMISION_PROCESO_ADMISION { get; set; }
        public int ID_PERSONAL_INSTITUCION { get; set; }
        public int ID_PROCESO_ADMISION_PERIODO { get; set; }
        public int ID_CARGO { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  personal_institucion ID_PERSONAL_INSTITUCIONNavigation { get; set; } = null!;
        public  proceso_admision_periodo ID_PROCESO_ADMISION_PERIODONavigation { get; set; } = null!;
    }
}