// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class componente_curricular
    {
        public int ID_COMPONENTE_CURRICULAR { get; set; }
        public int ID_MODULO { get; set; }
        public int ID_TIPO_COMPONENTE { get; set; }
        public string? CODIGO_COMPONENTE { get; set; }
        public string NOMBRE_COMPONENTE { get; set; } = null!;
        public string? DESCRIPCION { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  modulo ID_MODULONavigation { get; set; } = null!;
        public  ICollection<capacidades_por_componente> capacidades_por_componente { get; set; }
    }
}