// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class distribucion_evaluacion_admision_detalle
    {
        public int ID_DISTRIBUCION_EVALUACION_ADMISION_DETALLE { get; set; }
        public int ID_DISTRIBUCION_EXAMEN_ADMISION { get; set; }
        public int ID_POSTULANTES_POR_MODALIDAD { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  distribucion_examen_admision ID_DISTRIBUCION_EXAMEN_ADMISIONNavigation { get; set; } = null!;
        public  postulantes_por_modalidad ID_POSTULANTES_POR_MODALIDADNavigation { get; set; } = null!;
    }
}