// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class documentos_dre
    {
      public int ID_DOCUMENTOS_DRE { get; set; }
        public int? ID_PROGRAMACION_CLASE { get; set; }
        public int? ID_CLASE_HISTORICA { get; set; }
        public int CODIGO_TIPO_ENUMERADO { get; set; }
        public bool? DESCARGADO { get; set; }
        public bool? SUBIDO { get; set; }
        public bool? VERIFICADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }
        public bool? ESTADO { get; set; }

        public  ICollection<documentos_dre_archivos> documentos_dre_archivos { get; set; }
    }
}