// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class documentos_dre_archivos
    {
        public int ID_DOCUMENTOS_DRE_ARCHIVOS { get; set; }
        public int ID_DOCUMENTOS_DRE { get; set; }
        public string? NOMBRE_DOCUMENTO { get; set; }
        public string? NOMBRE_ARCHIVO { get; set; }
        public string? RUTA_ARCHIVO { get; set; }
        public int ESTADO { get; set; }
        public int USUARIO_CREACION { get; set; }
        public DateTime FECHA_CREACION { get; set; }
        public int? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  documentos_dre ID_DOCUMENTOS_DRENavigation { get; set; } = null!;
    }
}