// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class enfoques_por_plan_estudio
    {
      public int ID_ENFOQUES_POR_PLAN_ESTUDIO { get; set; }
        public int ID_PLAN_ESTUDIO { get; set; }
        public int? ID_ENFOQUE { get; set; }
        public bool? ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  enfoque? ID_ENFOQUENavigation { get; set; }
        public  plan_estudio ID_PLAN_ESTUDIONavigation { get; set; } = null!;
        public  ICollection<unidades_didacticas_por_enfoque> unidades_didacticas_por_enfoque { get; set; }
    }
}