// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class evaluacion
    {
             public int ID_EVALUACION { get; set; }
        public int? ID_PROGRAMACION_CLASE { get; set; }
        public DateTime? FECHA_NOTA { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public int? CIERRE_PROGRAMACION { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }
        public int? ID_CARRERA { get; set; }
        public int? ID_UNIDAD_DIDACTICA { get; set; }

        public  programacion_clase? ID_PROGRAMACION_CLASENavigation { get; set; }
        public  ICollection<evaluacion_detalle> evaluacion_detalle { get; set; }
        public  ICollection<programacion_clase> programacion_clase { get; set; }
    }
}