// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class exportador_datos
    {
       public int ID_EXPORTADOR_DATOS { get; set; }
        public string NOMBRE_BASE_DATOS { get; set; } = null!;
        public string NOMBRE_ESQUEMA { get; set; } = null!;
        public string NOMBRE_OBJETO { get; set; } = null!;
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  ICollection<exportador_datos_configuracion> exportador_datos_configuracion { get; set; }
        public  ICollection<exportador_datos_detalle> exportador_datos_detalle { get; set; }
    }
}