// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class indicadores_logro_por_unidad_didactica
    {
        public int ID_INDICADORES_LOGRO_POR_UNIDAD_DIDACTICA { get; set; }
        public int ID_UNIDAD_DIDACTICA { get; set; }
        public int ID_INDICADORES_LOGRO_POR_CAPACIDAD { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  indicadores_logro_por_capacidad ID_INDICADORES_LOGRO_POR_CAPACIDADNavigation { get; set; } = null!;
        public  unidad_didactica ID_UNIDAD_DIDACTICANavigation { get; set; } = null!;
    }
}