// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class indicadores_logro_por_capacidad
    {
        public int ID_INDICADORES_LOGRO_POR_CAPACIDAD { get; set; }
        public int ID_CAPACIDADES_POR_COMPONENTE { get; set; }
        public string? CODIGO_INDICADOR_LOGRO { get; set; }
        public string NOMBRE_INDICADOR { get; set; } = null!;
        public string? DESCRIPCION { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  capacidades_por_componente ID_CAPACIDADES_POR_COMPONENTENavigation { get; set; } = null!;
        public  ICollection<indicadores_logro_por_unidad_didactica> indicadores_logro_por_unidad_didactica { get; set; }
    }
}