// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class meta_carrera_institucion_detalle
    {
     public int ID_META_CARRERA_INSTITUCION_DETALLE { get; set; }
        public int ID_META_CARRERA_INSTITUCION { get; set; }
        public int ID_SEDE_INSTITUCION { get; set; }
        public int ID_PERIODOS_LECTIVOS_POR_INSTITUCION { get; set; }
        public int? META_SEDE { get; set; }
        public int? META_ALCANZADA { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  meta_carrera_institucion ID_META_CARRERA_INSTITUCIONNavigation { get; set; } = null!;
        public  periodos_lectivos_por_institucion ID_PERIODOS_LECTIVOS_POR_INSTITUCIONNavigation { get; set; } = null!;
        public  sede_institucion ID_SEDE_INSTITUCIONNavigation { get; set; } = null!;
        public  ICollection<opciones_por_postulante> opciones_por_postulante { get; set; }
    }
}