// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class meta_carrera_institucion
    {
       public int ID_META_CARRERA_INSTITUCION { get; set; }
        public int ID_TURNOS_POR_INSTITUCION { get; set; }
        public int? ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCION { get; set; }
        public int ID_CARRERAS_POR_INSTITUCION { get; set; }
        public int ANIO { get; set; }
        public int? META { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }
        public int? ID_PLAN_ESTUDIO { get; set; }

        public  carreras_por_institucion ID_CARRERAS_POR_INSTITUCIONNavigation { get; set; } = null!;
        public  plan_estudio? ID_PLAN_ESTUDIONavigation { get; set; }
        public  resoluciones_por_periodo_lectivo_institucion? ID_RESOLUCIONES_POR_PERIODO_LECTIVO_INSTITUCIONNavigation { get; set; }
        public  turnos_por_institucion ID_TURNOS_POR_INSTITUCIONNavigation { get; set; } = null!;
        public  ICollection<meta_carrera_institucion_detalle> meta_carrera_institucion_detalle { get; set; }
    }
}