// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class modulo
    {
       public int ID_MODULO { get; set; }
        public int ID_PLAN_ESTUDIO { get; set; }
        public int? ID_TIPO_MODULO { get; set; }
        public string? CODIGO_MODULO { get; set; }
        public string? NOMBRE_MODULO { get; set; }
        public decimal? HORAS_ME { get; set; }
        public int? CREDITOS_ME { get; set; }
        public int? TOTAL_HORAS { get; set; }
        public decimal? TOTAL_HORAS_UD { get; set; }
        public decimal? TOTAL_CREDITOS_UD { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  plan_estudio ID_PLAN_ESTUDIONavigation { get; set; } = null!;
        public  ICollection<componente_curricular> componente_curricular { get; set; }
        public  ICollection<unidad_competencias_por_modulo> unidad_competencias_por_modulo { get; set; }
        public  ICollection<unidad_didactica> unidad_didactica { get; set; }
    }
}