// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class modulo_equivalencia
    {
        public int ID_MODULO_EQUIVALENCIA { get; set; }
        public int? ID_PLAN_ESTUDIO { get; set; }
        public int? ID_TIPO_MODULO { get; set; }
        public string? NOMBRE_MODULO { get; set; }
        public string? NUMERO_MODULO { get; set; }
        public decimal? TOTHORAS { get; set; }
        public decimal? TOTCREDITOS { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  plan_estudio? ID_PLAN_ESTUDIONavigation { get; set; }
        public  ICollection<modulo_unidad_competencia> modulo_unidad_competencia { get; set; }
        public  ICollection<unidad_didactica_modulo_equivalencia> unidad_didactica_modulo_equivalencia { get; set; }
    }
}