// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class opciones_por_postulante
    {
       public int ID_OPCIONES_POR_POSTULANTE { get; set; }
        public int ID_POSTULANTES_POR_MODALIDAD { get; set; }
        public int ID_META_CARRERA_INSTITUCION_DETALLE { get; set; }
        public int? ORDEN { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  meta_carrera_institucion_detalle ID_META_CARRERA_INSTITUCION_DETALLENavigation { get; set; } = null!;
        public  postulantes_por_modalidad ID_POSTULANTES_POR_MODALIDADNavigation { get; set; } = null!;
        public  ICollection<resultados_por_postulante> resultados_por_postulante { get; set; }
    }
}