// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class plan_estudio_detalle
    {
        public int ID_PLAN_ESTUDIO_DETALLE { get; set; }
        public int ID_PLAN_ESTUDIO { get; set; }
        public int? ID_TIPO_UNIDAD_DIDACTICA { get; set; }
        public string DESCRIPCION_CONSOLIDADO { get; set; } = null!;
        public int? PERIODO_ACADEMICO_I { get; set; }
        public int? PERIODO_ACADEMICO_II { get; set; }
        public int? PERIODO_ACADEMICO_III { get; set; }
        public int? PERIODO_ACADEMICO_IV { get; set; }
        public int? PERIODO_ACADEMICO_V { get; set; }
        public int? PERIODO_ACADEMICO_VI { get; set; }
        public int? SUMA_TOTAL_HORAS_POR_TIPO { get; set; }
        public decimal? TOTAL_CREDITOS_UD { get; set; }
        public decimal? SUMA_TOTAL_CREDITOS_UD { get; set; }
        public decimal? COLUMNA_L { get; set; }
        public decimal? COLUMNA_M { get; set; }
        public decimal? COLUMNA_N { get; set; }
        public decimal? COLUMNA_O { get; set; }
        public decimal? COLUMNA_P { get; set; }
        public int? SUMA_HORAS { get; set; }
        public int? SUMA_CREDITOS { get; set; }
        public int? ORDEN_VISUALIZACION { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }
        public decimal? PERIODO_ACADEMICO_VII { get; set; }
        public decimal? PERIODO_ACADEMICO_VIII { get; set; }

        public  plan_estudio ID_PLAN_ESTUDIONavigation { get; set; } = null!;
        public  tipo_unidad_didactica? ID_TIPO_UNIDAD_DIDACTICANavigation { get; set; }
    }
}