// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class plan_estudio
    {
     public int ID_PLAN_ESTUDIO { get; set; }
        public int ID_CARRERAS_POR_INSTITUCION { get; set; }
        public int ID_TIPO_ITINERARIO { get; set; }
        public string? CODIGO_PLAN_ESTUDIOS { get; set; }
        public string NOMBRE_PLAN_ESTUDIOS { get; set; } = null!;
        public bool? ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  carreras_por_institucion ID_CARRERAS_POR_INSTITUCIONNavigation { get; set; } = null!;
        public  ICollection<enfoques_por_plan_estudio> enfoques_por_plan_estudio { get; set; }
        public  ICollection<estudiante_institucion> estudiante_institucion { get; set; }
        public  ICollection<meta_carrera_institucion> meta_carrera_institucion { get; set; }
        public  ICollection<modulo> modulo { get; set; }
        public  ICollection<modulo_equivalencia> modulo_equivalencia { get; set; }
        public  ICollection<plan_estudio_detalle> plan_estudio_detalle { get; set; }
        public  ICollection<promover_persona_institucion> promover_persona_institucion { get; set; }
        public  ICollection<situacion_academica_estudiante> situacion_academica_estudiante { get; set; }
    }
}