// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class requisitos_por_traslado_estudiante
    {
        public int ID_REQUISITOS_POR_TRASLADO_ESTUDIANTE { get; set; }
        public int ID_REQUISITOS_POR_TRASLADO_INSTITUCION { get; set; }
        public int ID_TRASLADO_ESTUDIANTE { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  requisitos_por_traslado_institucion ID_REQUISITOS_POR_TRASLADO_INSTITUCIONNavigation { get; set; } = null!;
        public  traslado_estudiante ID_TRASLADO_ESTUDIANTENavigation { get; set; } = null!;
    }
}