// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class resultados_por_postulante
    {
        public int ID_RESULTADOS_POR_POSTULANTE { get; set; }
        public int ID_POSTULANTES_POR_MODALIDAD { get; set; }
        public int? ID_OPCIONES_POR_POSTULANTE { get; set; }
        public decimal? NOTA_RESULTADO { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  opciones_por_postulante? ID_OPCIONES_POR_POSTULANTENavigation { get; set; }
        public  postulantes_por_modalidad ID_POSTULANTES_POR_MODALIDADNavigation { get; set; } = null!;
    }
}