// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class situacion_academica_estudiante
    {
        public int ID_SITUACION_ACADEMICA_ESTUDIANTE { get; set; }
        public int ID_PERIODOS_LECTIVOS_POR_INSTITUCION { get; set; }
        public int ID_SEDE_INSTITUCION { get; set; }
        public int ID_PLAN_ESTUDIO { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  plan_estudio ID_PLAN_ESTUDIONavigation { get; set; } = null!;
        public  sede_institucion ID_SEDE_INSTITUCIONNavigation { get; set; } = null!;
        public  ICollection<situacion_academica_detalle> situacion_academica_detalle { get; set; }
    }
}