// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class traslado_estudiante_detalle
    {
        public int ID_TRASLADO_ESTUDIANTE_DETALLE { get; set; }
        public int ID_TRASLADO_ESTUDIANTE { get; set; }
        public int ID_INSTITUCION { get; set; }
        public DateTime? FECHA { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  traslado_estudiante ID_TRASLADO_ESTUDIANTENavigation { get; set; } = null!;
    }
}