// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class unidades_didacticas_por_programacion_clase
    {
        public int ID_UNIDADES_DIDACTICAS_POR_PROGRAMACION_CLASE { get; set; }
        public int ID_UNIDADES_DIDACTICAS_POR_ENFOQUE { get; set; }
        public int ID_PROGRAMACION_CLASE { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  programacion_clase ID_PROGRAMACION_CLASENavigation { get; set; } = null!;
        public  unidades_didacticas_por_enfoque ID_UNIDADES_DIDACTICAS_POR_ENFOQUENavigation { get; set; } = null!;
    }
}