// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class unidad_competencias_por_modulo
    {
        public int ID_UNIDAD_COMPETENCIAS_POR_MODULO { get; set; }
        public int ID_MODULO { get; set; }
        public int ID_UNIDAD_COMPETENCIA { get; set; }
        public int? ORDEN_VISUALIZACION { get; set; }
        public bool? ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  modulo ID_MODULONavigation { get; set; } = null!;
        public  unidad_competencia ID_UNIDAD_COMPETENCIANavigation { get; set; } = null!;
    }
}