// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class unidades_didacticas_por_enfoque
    {
       public int ID_UNIDADES_DIDACTICAS_POR_ENFOQUE { get; set; }
        public int ID_ENFOQUES_POR_PLAN_ESTUDIO { get; set; }
        public int ID_UNIDAD_DIDACTICA { get; set; }
        public int? ID_TIPO_UNIDAD_DIDACTICA { get; set; }
        public int? HORAS_EMPRESA { get; set; }
        public int? CREDITOS_VIRTUALES { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  enfoques_por_plan_estudio ID_ENFOQUES_POR_PLAN_ESTUDIONavigation { get; set; } = null!;
        public  tipo_unidad_didactica? ID_TIPO_UNIDAD_DIDACTICANavigation { get; set; }
        public  unidad_didactica ID_UNIDAD_DIDACTICANavigation { get; set; } = null!;
        public  ICollection<evaluacion_experiencia_formativa> evaluacion_experiencia_formativa { get; set; }
        public  ICollection<unidades_didacticas_por_programacion_clase> unidades_didacticas_por_programacion_clase { get; set; }
    }
}