// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity.Audit;

namespace MINEDU.IEST.Estudiante.Contexto.Data.Audit.Configurations
{
    public partial class LogConfiguration : IEntityTypeConfiguration<Log>
    {
        public void Configure(EntityTypeBuilder<Log> entity)
        {
            entity.ToTable("Log", "Audit");

            entity.Property(e => e.Application)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Level)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Logged).HasColumnType("datetime");

            entity.Property(e => e.Logger).HasMaxLength(250);

            entity.Property(e => e.Message).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Log> entity);
    }
}
