// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron
{
    public partial class digePadronDbContext : DbContext
    {
        public digePadronDbContext()
        {
        }

        public digePadronDbContext(DbContextOptions<digePadronDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ActividadEconomica> ActividadEconomicas { get; set; }
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<CarreraAdicional> CarreraAdicionals { get; set; }
        public virtual DbSet<CarreraDcb> CarreraDcbs { get; set; }
        public virtual DbSet<CarreraDcby> CarreraDcbIes { get; set; }
        public virtual DbSet<CatalogoOfertaFormativa> CatalogoOfertaFormativas { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<DetalleExpediente> DetalleExpedientes { get; set; }
        public virtual DbSet<DetallePausaExpediente> DetallePausaExpedientes { get; set; }
        public virtual DbSet<DireccionSede> DireccionSedes { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Distrito> Distritos { get; set; }
        public virtual DbSet<DocumentoRespuestaDetalle> DocumentoRespuestaDetalles { get; set; }
        public virtual DbSet<DocumentoRespuestum> DocumentoRespuesta { get; set; }
        public virtual DbSet<Etapa> Etapas { get; set; }
        public virtual DbSet<Expediente> Expedientes { get; set; }
        public virtual DbSet<FamiliaProductiva> FamiliaProductivas { get; set; }
        public virtual DbSet<Feriado> Feriados { get; set; }
        public virtual DbSet<IndicadorLogro> IndicadorLogros { get; set; }
        public virtual DbSet<Institucion> Institucions { get; set; }
        public virtual DbSet<InstitucionAutoridad> InstitucionAutoridads { get; set; }
        public virtual DbSet<InstitucionCarrera> InstitucionCarreras { get; set; }
        public virtual DbSet<InstitucionMovimiento> InstitucionMovimientos { get; set; }
        public virtual DbSet<Local> Locals { get; set; }
        public virtual DbSet<MovimientoExpediente> MovimientoExpedientes { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Promotor> Promotors { get; set; }
        public virtual DbSet<Provincium> Provincia { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<Sede> Sedes { get; set; }
        public virtual DbSet<Tipo> Tipos { get; set; }
        public virtual DbSet<TipoExpediente> TipoExpedientes { get; set; }
        public virtual DbSet<TipoNivelEstudio> TipoNivelEstudios { get; set; }
        public virtual DbSet<UnidadCompetenciaCarrera> UnidadCompetenciaCarreras { get; set; }
        public virtual DbSet<UnidadCompetencium> UnidadCompetencia { get; set; }
        public virtual DbSet<UvwCarrera> UvwCarreras { get; set; }
        public virtual DbSet<UvwInstitucion> UvwInstitucions { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Latin1_General_CS_AS");

            modelBuilder.ApplyConfiguration(new Configurations.ActividadEconomicaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CarreraConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CarreraAdicionalConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CarreraDcbConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CarreraDcbyConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CatalogoOfertaFormativaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DepartamentoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DetalleExpedienteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DetallePausaExpedienteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DireccionSedeConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DirectorConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DistritoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DocumentoRespuestaDetalleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.DocumentoRespuestumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.EtapaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ExpedienteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.FamiliaProductivaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.FeriadoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.IndicadorLogroConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.InstitucionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.InstitucionAutoridadConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.InstitucionCarreraConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.InstitucionMovimientoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.LocalConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MovimientoExpedienteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PaiConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PersonaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PromotorConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProvinciumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SectorConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SedeConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TipoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TipoExpedienteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TipoNivelEstudioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UnidadCompetenciaCarreraConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UnidadCompetenciumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UvwCarreraConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UvwInstitucionConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
