// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class carga_detalleConfiguration : IEntityTypeConfiguration<carga_detalle>
    {
        public void Configure(EntityTypeBuilder<carga_detalle> entity)
        {
            entity.HasKey(e => e.ID_DET_ARCHIVO);

            entity.ToTable("carga_detalle", "archivo");

            entity.Property(e => e.APELLIDO_MATERNO)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.APELLIDO_PATERNO)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.DIRECCION_RESIDENCIA)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_NACIMIENTO).HasColumnType("datetime");

            entity.Property(e => e.NOMBRES)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.NUMERO_DOCUMENTO)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.UBIGEO_NACIMIENTO)
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.Property(e => e.UBIGEO_RESIDENCIA)
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_CARGANavigation)
                .WithMany(p => p.carga_detalle)
                .HasForeignKey(d => d.ID_CARGA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_carga_detalle_carga");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<carga_detalle> entity);
    }
}
