// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class cargaConfiguration : IEntityTypeConfiguration<carga>
    {
        public void Configure(EntityTypeBuilder<carga> entity)
        {
            entity.HasKey(e => e.ID_CARGA)
                .HasName("PK_archivo.carga");

            entity.ToTable("carga", "archivo");

            entity.Property(e => e.FECHA_CARGA).HasColumnType("datetime");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.MENSAJE)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.NOMBRE_ARCHIVO)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_CARRERAS_POR_INSTITUCIONNavigation)
                .WithMany(p => p.carga)
                .HasForeignKey(d => d.ID_CARRERAS_POR_INSTITUCION)
                .HasConstraintName("FK_carga_carrera_inst");

            entity.HasOne(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCIONNavigation)
                .WithMany(p => p.carga)
                .HasForeignKey(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_carga_periodo_lect_inst");

            entity.HasOne(d => d.ID_PERIODO_ACADEMICONavigation)
                .WithMany(p => p.carga)
                .HasForeignKey(d => d.ID_PERIODO_ACADEMICO)
                .HasConstraintName("FK_carga_periodo_acad");

            entity.HasOne(d => d.ID_PROGRAMACION_MATRICULANavigation)
                .WithMany(p => p.carga)
                .HasForeignKey(d => d.ID_PROGRAMACION_MATRICULA)
                .HasConstraintName("FK_carga_prog_matricula");

            entity.HasOne(d => d.ID_SEDE_INSTITUCIONNavigation)
                .WithMany(p => p.carga)
                .HasForeignKey(d => d.ID_SEDE_INSTITUCION)
                .HasConstraintName("FK_carga_sede_inst");

            entity.HasOne(d => d.ID_TURNOS_POR_INSTITUCIONNavigation)
                .WithMany(p => p.carga)
                .HasForeignKey(d => d.ID_TURNOS_POR_INSTITUCION)
                .HasConstraintName("FK_carga_turnos_inst");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<carga> entity);
    }
}
