// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class carrera_profesionalConfiguration : IEntityTypeConfiguration<carrera_profesional>
    {
        public void Configure(EntityTypeBuilder<carrera_profesional> entity)
        {
            entity.HasKey(e => e.ID_CARRERA_PROFESIONAL)
                .HasName("PK_CARRERA_PROFESIONAL")
                .IsClustered(false);

            entity.ToTable("carrera_profesional", "maestro");

            entity.Property(e => e.DESCRIPCION_CARRERA_PROFESIONAL)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_CARRERA_PROFESIONAL)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<carrera_profesional> entity);
    }
}
