// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class carreras_por_institucionConfiguration : IEntityTypeConfiguration<carreras_por_institucion>
    {
        public void Configure(EntityTypeBuilder<carreras_por_institucion> entity)
        {
            entity.HasKey(e => e.ID_CARRERAS_POR_INSTITUCION)
                .HasName("PK_CARRERAS_POR_INSTITUCION")
                .IsClustered(false);

            entity.ToTable("carreras_por_institucion", "transaccional");

            entity.HasIndex(e => new { e.ID_CARRERA, e.ES_ACTIVO, e.ID_INSTITUCION }, "IDX_CARRERAS_POR_INSTITUCION1");

            entity.HasIndex(e => new { e.ID_CARRERAS_POR_INSTITUCION, e.ES_ACTIVO, e.ID_TIPO_ITINERARIO, e.ID_CARRERA, e.ID_INSTITUCION }, "IDX_CARRERAS_POR_INSTITUCION2");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<carreras_por_institucion> entity);
    }
}
