// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class componente_curricularConfiguration : IEntityTypeConfiguration<componente_curricular>
    {
        public void Configure(EntityTypeBuilder<componente_curricular> entity)
        {
            entity.HasKey(e => e.ID_COMPONENTE_CURRICULAR)
                .HasName("PK_COMPONENTE_CURRICULAR")
                .IsClustered(false);

            entity.ToTable("componente_curricular", "transaccional");

            entity.Property(e => e.CODIGO_COMPONENTE)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_COMPONENTE)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_MODULONavigation)
                .WithMany(p => p.componente_curricular)
                .HasForeignKey(d => d.ID_MODULO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_COMPONEN_FK_MODULO_MODULO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<componente_curricular> entity);
    }
}
