// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class convalidacionConfiguration : IEntityTypeConfiguration<convalidacion>
    {
        public void Configure(EntityTypeBuilder<convalidacion> entity)
        {
            entity.HasKey(e => e.ID_CONVALIDACION)
                .HasName("PK_CONVALIDACION")
                .IsClustered(false);

            entity.ToTable("convalidacion", "transaccional");

            entity.Property(e => e.ARCHIVO_CONVALIDACION)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ARCHIVO_RD)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('NULL')");

            entity.Property(e => e.ARCHIVO_RUTA)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasDefaultValueSql("('NULL')");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NRO_RD)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<convalidacion> entity);
    }
}
