// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class cronograma_meta_atencionConfiguration : IEntityTypeConfiguration<cronograma_meta_atencion>
    {
        public void Configure(EntityTypeBuilder<cronograma_meta_atencion> entity)
        {
            entity.HasKey(e => e.ID_CRONOGRAMA_META_ATENCION)
                .HasName("PK_CRONOGRAMA_META_ATENCION")
                .IsClustered(false);

            entity.ToTable("cronograma_meta_atencion", "maestro");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_FIN).HasColumnType("datetime");

            entity.Property(e => e.FECHA_INICIO).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_CRONOGRAMA_META)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PERIODO_LECTIVONavigation)
                .WithMany(p => p.cronograma_meta_atencion)
                .HasForeignKey(d => d.ID_PERIODO_LECTIVO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CRONOGRA_RELATIONS_PERIODO_");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<cronograma_meta_atencion> entity);
    }
}
