// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class distribucion_examen_admisionConfiguration : IEntityTypeConfiguration<distribucion_examen_admision>
    {
        public void Configure(EntityTypeBuilder<distribucion_examen_admision> entity)
        {
            entity.HasKey(e => e.ID_DISTRIBUCION_EXAMEN_ADMISION)
                .HasName("PK_DISTRIBUCION_EXAMEN_ADMISIO")
                .IsClustered(false);

            entity.ToTable("distribucion_examen_admision", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_AULANavigation)
                .WithMany(p => p.distribucion_examen_admision)
                .HasForeignKey(d => d.ID_AULA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DISTRIBU_RELATIONS_AULA");

            entity.HasOne(d => d.ID_EVALUADOR_ADMISION_MODALIDADNavigation)
                .WithMany(p => p.distribucion_examen_admision)
                .HasForeignKey(d => d.ID_EVALUADOR_ADMISION_MODALIDAD)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DISTRIBU_RELATIONS_EVALUADO");

            entity.HasOne(d => d.ID_EXAMEN_ADMISION_SEDENavigation)
                .WithMany(p => p.distribucion_examen_admision)
                .HasForeignKey(d => d.ID_EXAMEN_ADMISION_SEDE)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DISTRIBU_RELATIONS_EXAMEN_A");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<distribucion_examen_admision> entity);
    }
}
