// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class documentos_dreConfiguration : IEntityTypeConfiguration<documentos_dre>
    {
        public void Configure(EntityTypeBuilder<documentos_dre> entity)
        {
            entity.HasKey(e => e.ID_DOCUMENTOS_DRE)
                .HasName("PK_DOCUMENTOS_DRE")
                .IsClustered(false);

            entity.ToTable("documentos_dre", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<documentos_dre> entity);
    }
}
