// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class exportador_datosConfiguration : IEntityTypeConfiguration<exportador_datos>
    {
        public void Configure(EntityTypeBuilder<exportador_datos> entity)
        {
            entity.HasKey(e => e.ID_EXPORTADOR_DATOS);

            entity.ToTable("exportador_datos", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_BASE_DATOS)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.NOMBRE_ESQUEMA)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.NOMBRE_OBJETO)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<exportador_datos> entity);
    }
}
