// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class familia_productivaConfiguration : IEntityTypeConfiguration<familia_productiva>
    {
        public void Configure(EntityTypeBuilder<familia_productiva> entity)
        {
            entity.HasKey(e => e.ID_FAMILIA_PRODUCTIVA)
                .HasName("PK_FAMILIA_PRODUCTIVA")
                .IsClustered(false);

            entity.ToTable("familia_productiva", "maestro");

            entity.Property(e => e.CODIGO_FAMILIA_PRODUCTIVA)
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.Property(e => e.DESCRIPCION_FAMILIA_PRODUCTIVA)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_FAMILIA_PRODUCTIVA)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_SECTORNavigation)
                .WithMany(p => p.familia_productiva)
                .HasForeignKey(d => d.ID_SECTOR)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FAMILIA__FK_SECTOR_SECTOR");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<familia_productiva> entity);
    }
}
