// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class liberacion_estudianteConfiguration : IEntityTypeConfiguration<liberacion_estudiante>
    {
        public void Configure(EntityTypeBuilder<liberacion_estudiante> entity)
        {
            entity.HasKey(e => e.ID_LIBERACION_ESTUDIANTE)
                .HasName("PK__liberaci__5E5B0866F987A876");

            entity.ToTable("liberacion_estudiante", "transaccional");

            entity.Property(e => e.ARCHIVO_RD)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('NULL')");

            entity.Property(e => e.ARCHIVO_RUTA)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasDefaultValueSql("('NULL')");

            entity.Property(e => e.ESTADO).HasDefaultValueSql("((1))");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NRO_RD)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('NULL')");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_ESTUDIANTE_INSTITUCIONNavigation)
                .WithMany(p => p.liberacion_estudiante)
                .HasForeignKey(d => d.ID_ESTUDIANTE_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_liberacion_estudiante_ID_ESTUDIANTE_INSTITUCION");

            entity.HasOne(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCIONNavigation)
                .WithMany(p => p.liberacion_estudiante)
                .HasForeignKey(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_liberacion_estudiante_ID_PERIODOS_LECTIVOS_POR_INSTITUCION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<liberacion_estudiante> entity);
    }
}
