// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class modulo_unidad_competenciaConfiguration : IEntityTypeConfiguration<modulo_unidad_competencia>
    {
        public void Configure(EntityTypeBuilder<modulo_unidad_competencia> entity)
        {
            entity.HasKey(e => e.ID_UNIDAD_COMPETENCIA)
                .HasName("PK_UNIDAD_COMPETENCIA")
                .IsClustered(false);

            entity.ToTable("modulo_unidad_competencia", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_MODULO_EQUIVALENCIANavigation)
                .WithMany(p => p.modulo_unidad_competencia)
                .HasForeignKey(d => d.ID_MODULO_EQUIVALENCIA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UNIDAD_COMPETENCIA_MODULO_EQUIVALENCIA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<modulo_unidad_competencia> entity);
    }
}
