// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class opciones_por_postulanteConfiguration : IEntityTypeConfiguration<opciones_por_postulante>
    {
        public void Configure(EntityTypeBuilder<opciones_por_postulante> entity)
        {
            entity.HasKey(e => e.ID_OPCIONES_POR_POSTULANTE)
                .HasName("PK_OPCIONES_POR_POSTULANTE")
                .IsClustered(false);

            entity.ToTable("opciones_por_postulante", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_META_CARRERA_INSTITUCION_DETALLENavigation)
                .WithMany(p => p.opciones_por_postulante)
                .HasForeignKey(d => d.ID_META_CARRERA_INSTITUCION_DETALLE)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OPCIONES_RELATIONS_META_CAR");

            entity.HasOne(d => d.ID_POSTULANTES_POR_MODALIDADNavigation)
                .WithMany(p => p.opciones_por_postulante)
                .HasForeignKey(d => d.ID_POSTULANTES_POR_MODALIDAD)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OPCIONES_RELATIONS_POSTULAN");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<opciones_por_postulante> entity);
    }
}
