// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class persona_institucionConfiguration : IEntityTypeConfiguration<persona_institucion>
    {
        public void Configure(EntityTypeBuilder<persona_institucion> entity)
        {
            entity.HasKey(e => e.ID_PERSONA_INSTITUCION)
                .HasName("PK_PERSONA_INSTITUCION")
                .IsClustered(false);

            entity.ToTable("persona_institucion", "maestro");

            entity.HasIndex(e => e.ID_PERSONA_INSTITUCION, "IDX_PERSONA_INSTITUCION1");

            entity.HasIndex(e => new { e.ID_PERSONA_INSTITUCION, e.ID_PERSONA, e.PAIS_PERSONA, e.UBIGEO_PERSONA }, "IDX_PERSONA_INSTITUCION2");

            entity.Property(e => e.CELULAR)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.CELULAR2)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.CORREO)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.DIRECCION_PERSONA)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.INSTITUCION_PROFESIONAL)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.OCUPACION_PERSONA)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.TELEFONO)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.TITULO_PROFESIONAL)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.UBIGEO_PERSONA)
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_CARRERA_PROFESIONALNavigation)
                .WithMany(p => p.persona_institucion)
                .HasForeignKey(d => d.ID_CARRERA_PROFESIONAL)
                .HasConstraintName("FK_PERSONA__RELATIONS_CARRERA_");

            entity.HasOne(d => d.ID_PERSONANavigation)
                .WithMany(p => p.persona_institucion)
                .HasForeignKey(d => d.ID_PERSONA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PERSONA__FK_PERSON_PERSONA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<persona_institucion> entity);
    }
}
