// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class programacion_claseConfiguration : IEntityTypeConfiguration<programacion_clase>
    {
        public void Configure(EntityTypeBuilder<programacion_clase> entity)
        {
            entity.HasKey(e => e.ID_PROGRAMACION_CLASE)
                .HasName("PK_PROGRAMACION_CLASE")
                .IsClustered(false);

            entity.ToTable("programacion_clase", "transaccional");

            entity.HasIndex(e => new { e.ID_PROGRAMACION_CLASE, e.ES_ACTIVO }, "IDX_PROGRAMACION_CLASE1");

            entity.Property(e => e.CODIGO_CLASE)
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_CLASE)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_EVALUACIONNavigation)
                .WithMany(p => p.programacion_clase)
                .HasForeignKey(d => d.ID_EVALUACION)
                .HasConstraintName("FK_PROGRAMA_RELATIONS_EVALUACI");

            entity.HasOne(d => d.ID_PERIODO_ACADEMICONavigation)
                .WithMany(p => p.programacion_clase)
                .HasForeignKey(d => d.ID_PERIODO_ACADEMICO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROGRAMA_RELATIONS_PERIODO_");

            entity.HasOne(d => d.ID_SEDE_INSTITUCIONNavigation)
                .WithMany(p => p.programacion_clase)
                .HasForeignKey(d => d.ID_SEDE_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROG_CLASE_FK_SED_INST_ID");

            entity.HasOne(d => d.ID_TURNOS_POR_INSTITUCIONNavigation)
                .WithMany(p => p.programacion_clase)
                .HasForeignKey(d => d.ID_TURNOS_POR_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROGRAMACION_FK_TURNOS_INSTITUCION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<programacion_clase> entity);
    }
}
