// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class reingreso_estudianteConfiguration : IEntityTypeConfiguration<reingreso_estudiante>
    {
        public void Configure(EntityTypeBuilder<reingreso_estudiante> entity)
        {
            entity.HasKey(e => e.ID_REINGRESO_ESTUDIANTE)
                .HasName("PK_REINGRESO_ESTUDIANTE")
                .IsClustered(false);

            entity.ToTable("reingreso_estudiante", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_FIN).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.TIEMPO_LICENCIA)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_LICENCIA_ESTUDIANTENavigation)
                .WithMany(p => p.reingreso_estudiante)
                .HasForeignKey(d => d.ID_LICENCIA_ESTUDIANTE)
                .HasConstraintName("FK_REINGRESO_FK_LICENCIA");

            entity.HasOne(d => d.ID_RESERVA_MATRICULANavigation)
                .WithMany(p => p.reingreso_estudiante)
                .HasForeignKey(d => d.ID_RESERVA_MATRICULA)
                .HasConstraintName("FK_REINGRESO_FK_RESERVA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<reingreso_estudiante> entity);
    }
}
