// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class requisitos_por_tipo_modalidadConfiguration : IEntityTypeConfiguration<requisitos_por_tipo_modalidad>
    {
        public void Configure(EntityTypeBuilder<requisitos_por_tipo_modalidad> entity)
        {
            entity.HasKey(e => e.ID_REQUISITOS_POR_TIPO_MODALIDAD)
                .HasName("PK_REQUISITOS_POR_TIPO_MODALID")
                .IsClustered(false);

            entity.ToTable("requisitos_por_tipo_modalidad", "maestro");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_REQUISITONavigation)
                .WithMany(p => p.requisitos_por_tipo_modalidad)
                .HasForeignKey(d => d.ID_REQUISITO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_REQUISITO_REQUISITOS_POR_TIPO_MODALIDAD");

            entity.HasOne(d => d.ID_TIPOS_MODALIDAD_POR_INSTITUCIONNavigation)
                .WithMany(p => p.requisitos_por_tipo_modalidad)
                .HasForeignKey(d => d.ID_TIPOS_MODALIDAD_POR_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_REQUISIT_RELATIONS_TIPOS_MO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<requisitos_por_tipo_modalidad> entity);
    }
}
