// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class resolucionConfiguration : IEntityTypeConfiguration<resolucion>
    {
        public void Configure(EntityTypeBuilder<resolucion> entity)
        {
            entity.HasKey(e => e.ID_RESOLUCION)
                .HasName("PK_RESOLUCION")
                .IsClustered(false);

            entity.ToTable("resolucion", "maestro");

            entity.Property(e => e.ARCHIVO_RESOLUCION)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NUMERO_RESOLUCION)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<resolucion> entity);
    }
}
