// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class traslado_estudiante_detalleConfiguration : IEntityTypeConfiguration<traslado_estudiante_detalle>
    {
        public void Configure(EntityTypeBuilder<traslado_estudiante_detalle> entity)
        {
            entity.HasKey(e => e.ID_TRASLADO_ESTUDIANTE_DETALLE)
                .HasName("PK_TRASLADO_ESTUDIANTE_DETALLE")
                .IsClustered(false);

            entity.ToTable("traslado_estudiante_detalle", "transaccional");

            entity.Property(e => e.FECHA).HasColumnType("datetime");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_TRASLADO_ESTUDIANTENavigation)
                .WithMany(p => p.traslado_estudiante_detalle)
                .HasForeignKey(d => d.ID_TRASLADO_ESTUDIANTE)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TRASLADO_RELATIONS_TRASLADO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<traslado_estudiante_detalle> entity);
    }
}
