// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class unidad_didactica_modulo_equivalenciaConfiguration : IEntityTypeConfiguration<unidad_didactica_modulo_equivalencia>
    {
        public void Configure(EntityTypeBuilder<unidad_didactica_modulo_equivalencia> entity)
        {
            entity.HasKey(e => e.ID_UNIDAD_DIDACTICA_MODULO_EQUIVALENCIA)
                .HasName("PK_UNIDAD_DIDACTICA_MODULO_EQUIVALENCIA")
                .IsClustered(false);

            entity.ToTable("unidad_didactica_modulo_equivalencia", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_MODULO_EQUIVALENCIANavigation)
                .WithMany(p => p.unidad_didactica_modulo_equivalencia)
                .HasForeignKey(d => d.ID_MODULO_EQUIVALENCIA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UNIDAD_DIDACTICA_ID_MODULO_EQUIVALENCIA");

            entity.HasOne(d => d.ID_UNIDAD_DIDACTICANavigation)
                .WithMany(p => p.unidad_didactica_modulo_equivalencia)
                .HasForeignKey(d => d.ID_UNIDAD_DIDACTICA)
                .HasConstraintName("FK__unidad_di__ID_UN__4262CC11");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<unidad_didactica_modulo_equivalencia> entity);
    }
}
