// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;

#nullable disable

namespace MINEDU.IEST.Estudiante.Contexto.Data.Estudiante.Configurations
{
    public partial class unidad_competencias_por_moduloConfiguration : IEntityTypeConfiguration<unidad_competencias_por_modulo>
    {
        public void Configure(EntityTypeBuilder<unidad_competencias_por_modulo> entity)
        {
            entity.HasKey(e => e.ID_UNIDAD_COMPETENCIAS_POR_MODULO)
                .HasName("PK_UNIDAD_COMPETENCIAS_POR_MOD")
                .IsClustered(false);

            entity.ToTable("unidad_competencias_por_modulo", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_MODULONavigation)
                .WithMany(p => p.unidad_competencias_por_modulo)
                .HasForeignKey(d => d.ID_MODULO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UNIDAD_C_RELATIONS_MODULO");

            entity.HasOne(d => d.ID_UNIDAD_COMPETENCIANavigation)
                .WithMany(p => p.unidad_competencias_por_modulo)
                .HasForeignKey(d => d.ID_UNIDAD_COMPETENCIA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UNIDAD_COMP_MOD_FK_UNIDAD_COMP");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<unidad_competencias_por_modulo> entity);
    }
}
