CREATE TABLE [archivo].[carga] (
    [ID_CARGA]                             INT                  IDENTITY (1, 1) NOT NULL,
    [ID_TIPO_CARGA]                        INT                  NOT NULL,
    [NOMBRE_ARCHIVO]                       VARCHAR (100)        NULL,
    [FECHA_CARGA]                          DATETIME             NULL,
    [ES_BORRADO]                           BIT                  NOT NULL,
    [FECHA_CREACION]                       DATETIME             NOT NULL,
    [USUARIO_CREACION]                     VARCHAR (20)         NOT NULL,
    [ESTADO]                               BIT                  NOT NULL,
    [TOTAL_CORRECTOS]                      INT                  NOT NULL,
    [TOTAL_INCORRECTOS]                    INT                  NOT NULL,
    [MENSAJE]                              VARCHAR (500)        NULL,
    [ID_PERIODOS_LECTIVOS_POR_INSTITUCION] [dbo].[ID]           NOT NULL,
    [ID_SEDE_INSTITUCION]                  [dbo].[ID]           NULL,
    [ID_PERIODO_ACADEMICO]                 [dbo].[ID]           NULL,
    [ID_CARRERAS_POR_INSTITUCION]          [dbo].[ID]           NULL,
    [ID_PROGRAMACION_MATRICULA]            [dbo].[ID]           NULL,
    [ID_SEMESTRE_ACADEMICO]                [dbo].[ID_ENUMERADO] NULL,
    [ID_SECCION]                           [dbo].[ID_ENUMERADO] NULL,
    [ID_TURNOS_POR_INSTITUCION]            [dbo].[ID]           NULL,
    CONSTRAINT [PK_archivo.carga] PRIMARY KEY CLUSTERED ([ID_CARGA] ASC),
    CONSTRAINT [FK_carga_carrera_inst] FOREIGN KEY ([ID_CARRERAS_POR_INSTITUCION]) REFERENCES [transaccional].[carreras_por_institucion] ([ID_CARRERAS_POR_INSTITUCION]),
    CONSTRAINT [FK_carga_periodo_acad] FOREIGN KEY ([ID_PERIODO_ACADEMICO]) REFERENCES [transaccional].[periodo_academico] ([ID_PERIODO_ACADEMICO]),
    CONSTRAINT [FK_carga_periodo_lect_inst] FOREIGN KEY ([ID_PERIODOS_LECTIVOS_POR_INSTITUCION]) REFERENCES [transaccional].[periodos_lectivos_por_institucion] ([ID_PERIODOS_LECTIVOS_POR_INSTITUCION]),
    CONSTRAINT [FK_carga_prog_matricula] FOREIGN KEY ([ID_PROGRAMACION_MATRICULA]) REFERENCES [transaccional].[programacion_matricula] ([ID_PROGRAMACION_MATRICULA]),
    CONSTRAINT [FK_carga_sede_inst] FOREIGN KEY ([ID_SEDE_INSTITUCION]) REFERENCES [maestro].[sede_institucion] ([ID_SEDE_INSTITUCION]),
    CONSTRAINT [FK_carga_tipo_carga] FOREIGN KEY ([ID_TIPO_CARGA]) REFERENCES [sistema].[tipo_carga] ([ID_TIPO_CARGA]),
    CONSTRAINT [FK_carga_turnos_inst] FOREIGN KEY ([ID_TURNOS_POR_INSTITUCION]) REFERENCES [maestro].[turnos_por_institucion] ([ID_TURNOS_POR_INSTITUCION])
);

