CREATE TABLE [sistema].[enumerado] (
    [ID_ENUMERADO]         [dbo].[ID]            IDENTITY (1, 1) NOT NULL,
    [ID_TIPO_ENUMERADO]    [dbo].[ID]            NOT NULL,
    [CODIGO_ENUMERADO]     [dbo].[NUMERO_ENTERO] NULL,
    [VALOR_ENUMERADO]      [dbo].[NOMBRE_LARGO]  NULL,
    [ORDEN_ENUMERADO]      [dbo].[NUMERO_ENTERO] NULL,
    [ES_EDITABLE]          [dbo].[BOOLEANO]      NOT NULL,
    [ESTADO]               [dbo].[ESTADO]        NOT NULL,
    [USUARIO_CREACION]     [dbo].[USUARIO]       NOT NULL,
    [FECHA_CREACION]       [dbo].[FECHA_TIEMPO]  NOT NULL,
    [USUARIO_MODIFICACION] [dbo].[USUARIO]       NULL,
    [FECHA_MODIFICACION]   [dbo].[FECHA_TIEMPO]  NULL,
    CONSTRAINT [PK_ENUMERADO] PRIMARY KEY NONCLUSTERED ([ID_ENUMERADO] ASC),
    CONSTRAINT [FK_ENUMERAD_FK_TIPO_E_TIPO_ENU] FOREIGN KEY ([ID_TIPO_ENUMERADO]) REFERENCES [sistema].[tipo_enumerado] ([ID_TIPO_ENUMERADO])
);


GO
CREATE NONCLUSTERED INDEX [IDX_ENUMERADO1]
    ON [sistema].[enumerado]([ID_TIPO_ENUMERADO] ASC, [ESTADO] ASC)
    INCLUDE([ID_ENUMERADO], [CODIGO_ENUMERADO], [VALOR_ENUMERADO], [ORDEN_ENUMERADO]);

