CREATE TABLE [sistema].[tabla_xml] (
    [ID_TABLA_XML]   [dbo].[ID]           IDENTITY (1, 1) NOT NULL,
    [DESCRIPCION]    [dbo].[DESCRIPCION]  NOT NULL,
    [SQL_TABLAS_XML] [dbo].[DESCRIPCION]  NOT NULL,
    [ES_VIGENTE]     [dbo].[BOOLEANO]     NOT NULL,
    [FECHA_CREACION] [dbo].[FECHA_TIEMPO] NOT NULL,
    CONSTRAINT [PK_TABLA_XML] PRIMARY KEY NONCLUSTERED ([ID_TABLA_XML] ASC)
);

