// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class ActividadEconomica
    {

        public int IdActividadEconomica { get; set; }
        public int? IdFamiliaProductiva { get; set; }
        public string CodigoDivision { get; set; }
        public string CodigoActividadEconomica { get; set; }
        public string Descripcion { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public  FamiliaProductiva IdFamiliaProductivaNavigation { get; set; }
        public  ICollection<CarreraDcb> CarreraDcbs { get; set; }
    }
}