// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class CarreraAdicional
    {
        public int IdCarreraAdicional { get; set; }
        public string CodigoCarreraAdicional { get; set; }
        public string NombreCarreraAdicional { get; set; }
        public int? CodigoCampoEducativo { get; set; }
        public int? CodigoCampoEspecifico { get; set; }
        public int? CodigoCampoDetallado { get; set; }
        public int? IdNivelEstudio { get; set; }
        public string Duracion { get; set; }
        public int? IdDocumentoRespuesta { get; set; }
        public int? IdCarrera { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? TipoPeriodoDuracion { get; set; }
        public string CodigoSector { get; set; }
        public string CodigoFamiliaProductivo { get; set; }
        public string Division { get; set; }
        public string MencionCarreraAdicional { get; set; }
        public int? TipoClasificador { get; set; }
        public string CodigoRamaActividad { get; set; }
        public string NombreRamaActividad { get; set; }
        public string NombreSector { get; set; }

        public  TipoNivelEstudio IdNivelEstudioNavigation { get; set; }
    }
}