// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class Carrera
    {
        public int IdCarrera { get; set; }
        public int? TipoClasificador { get; set; }
        public string CodigoClasificador { get; set; }
        public string NombreCarrera { get; set; }
        public int? CodigoCampoEducativo { get; set; }
        public string NombreCampoEducativo { get; set; }
        public int? CodigoCampoEspecifico { get; set; }
        public string NombreCampoEspecifico { get; set; }
        public int? CodigoCampoDetallado { get; set; }
        public string NombreCampoDetallado { get; set; }
        public string CodigoSector { get; set; }
        public string NombreSector { get; set; }
        public string CodigoFamiliaProductivo { get; set; }
        public string NombreFamiliaProductivo { get; set; }
        public string Division { get; set; }
        public int? TipoNivelFormacion { get; set; }
        public int? CodigoEquivalencia { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? IdNivelEstudio { get; set; }
        public int? TipoCarrera { get; set; }
        public string MencionCarrera { get; set; }
    }
}