// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class DetalleExpediente
    {
        public int IdDetalleExpediente { get; set; }
        public int? IdExpediente { get; set; }
        public string NumeroExpediente { get; set; }
        public DateTime? FechaExpediente { get; set; }
        public DateTime? FechaIngresoArea { get; set; }
        public int? NumeroFolios { get; set; }
        public int? Plazo { get; set; }
        public string Comentario { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? TipoDetalleExpediente { get; set; }
        public int? TipoExpedienteActivo { get; set; }

        public  Expediente IdExpedienteNavigation { get; set; }
    }
}