// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class Distrito
    {
        public string CodigoDistrito { get; set; }
        public string CodigoDepartamento { get; set; }
        public string CodigoProvincia { get; set; }
        public string NombreDistrito { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        [NotMapped]
        public string ubigeoCompleto { get; set; }
    }
}