// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class DocumentoRespuestaDetalle
    {
        public int IdDocumentoRespuestaDetalle { get; set; }
        public int? IdDocumentoRespuesta { get; set; }
        public int? IdSede { get; set; }
        public int? TipoCodigoCarrera { get; set; }
        public int? IdCarrera { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public string Meta { get; set; }
        public string Horas { get; set; }
        public string Creditos { get; set; }
        public int? TipoTramiteCarrera { get; set; }
        public string MencionCarrera { get; set; }

        public  DocumentoRespuestum IdDocumentoRespuestaNavigation { get; set; }
    }
}