// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class Expediente
    {
        public Expediente()
        {
            DetalleExpedientes = new HashSet<DetalleExpediente>();
            MovimientoExpedientes = new HashSet<MovimientoExpediente>();
        }

        public int IdExpediente { get; set; }
        public int? IdIntitucion { get; set; }
        public int? IdTipoExpediente { get; set; }
        public int? IdAnteriorMovimiento { get; set; }
        public int? IdUltimoMovimiento { get; set; }
        public string Descripcion { get; set; }
        public int? TipoEstadoExpediente { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public  TipoExpediente IdTipoExpedienteNavigation { get; set; }
        public  ICollection<DetalleExpediente> DetalleExpedientes { get; set; }
        public  ICollection<MovimientoExpediente> MovimientoExpedientes { get; set; }
    }
}