// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class FamiliaProductiva
    {
        public FamiliaProductiva()
        {
            ActividadEconomicas = new HashSet<ActividadEconomica>();
        }

        public string CodigoFamiliaProductiva { get; set; }
        public string FamiliaProductiva1 { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int IdFamiliaProductiva { get; set; }
        public int? IdSector { get; set; }

        public  Sector IdSectorNavigation { get; set; }
        public  ICollection<ActividadEconomica> ActividadEconomicas { get; set; }
    }
}