// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class InstitucionAutoridad
    {
        public int CodigoInstitucionAutoridad { get; set; }
        public string CodigoModular { get; set; }
        public string NumeroDocumento { get; set; }
        public string NombreAutoridad { get; set; }
        public int? TipoAutoridad { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
    }
}