// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class Institucion
    {
        public Institucion()
        {
            Directors = new HashSet<Director>();
            DocumentoRespuesta = new HashSet<DocumentoRespuestum>();
            InstitucionMovimientos = new HashSet<InstitucionMovimiento>();
            Locals = new HashSet<Local>();
            Promotors = new HashSet<Promotor>();
            Sedes = new HashSet<Sede>();
        }

        public int IdInstitucion { get; set; }
        public int? IdExpediente { get; set; }
        public string CodigoModular { get; set; }
        public string NombreInstitucion { get; set; }
        public int? TipoRegistroInstitucion { get; set; }
        public int? TipoInstitucion { get; set; }
        public int? TipoGestion { get; set; }
        public string NombreGestionDetalle { get; set; }
        public int? ModeloArticulacion { get; set; }
        public int? EstadoEscale { get; set; }
        public bool? ValidadoEscale { get; set; }
        public DateTime? FechaValidacion { get; set; }
        public int? TipoInconsistencia { get; set; }
        public string NombreEscale { get; set; }
        public int? Orden { get; set; }
        public int? Grupo { get; set; }
        public DateTime? FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public int? EstadoLicenciamiento { get; set; }
        public string PaginaWeb { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public bool? RealizaAdmision { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public bool? Habilitada { get; set; }
        public string CodigoModularTemp { get; set; }
        public string CodigoPais { get; set; }

        public  ICollection<Director> Directors { get; set; }
        public  ICollection<DocumentoRespuestum> DocumentoRespuesta { get; set; }
        public  ICollection<InstitucionMovimiento> InstitucionMovimientos { get; set; }
        public  ICollection<Local> Locals { get; set; }
        public  ICollection<Promotor> Promotors { get; set; }
        public  ICollection<Sede> Sedes { get; set; }
    }
}