// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class InstitucionCarrera
    {
        public int IdInstitucionCarrera { get; set; }
        public string CodigoModular { get; set; }
        public int? IdSede { get; set; }
        public int? TipoModalidadEnsenanza { get; set; }
        public int? Duracion { get; set; }
        public int? CodigoCarrera { get; set; }
        public int? TipoNivelCapacitacion { get; set; }
        public int? IdDocumentoRespuesta { get; set; }
        public DateTime? AutorizacionFechaInicio { get; set; }
        public DateTime? AutorizacionFechaFin { get; set; }
        public int? PeriodoInicioAnio { get; set; }
        public int? PeriodoInicioCiclo { get; set; }
        public bool? EsModular { get; set; }
        public bool? EsAsignatura { get; set; }
        public string ArchivoResolucion { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? IdInstitucion { get; set; }
        public int? IdLocal { get; set; }

        public  Sede IdSedeNavigation { get; set; }
    }
}