// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class MovimientoExpediente
    {
        public MovimientoExpediente()
        {
            DetallePausaExpedientes = new HashSet<DetallePausaExpediente>();
        }

        public int IdMovimientoExpediente { get; set; }
        public int? IdExpediente { get; set; }
        public int? IdResponsable { get; set; }
        public int? IdResponsablePosesion { get; set; }
        public int? IdEtapa { get; set; }
        public int? IdEtapaPosesion { get; set; }
        public int? IdEtapaDias { get; set; }
        public int? TipoEstadoMovimientoExpediente { get; set; }
        public int? TipoDocumento { get; set; }
        public string DocumentoSustento { get; set; }
        public int? PlazoAtencion { get; set; }
        public string Comentario { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public DateTime? FechaInicioEtapa { get; set; }
        public DateTime? FechaFinEtapa { get; set; }
        public DateTime? FechaFinEtapaDias { get; set; }
        public DateTime? FechaMovimiento { get; set; }
        public int? DiasTranscurridos { get; set; }

        public  Expediente IdExpedienteNavigation { get; set; }
        public  ICollection<DetallePausaExpediente> DetallePausaExpedientes { get; set; }
    }
}