// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class Persona
    {
        public Persona()
        {
            Directors = new HashSet<Director>();
            Promotors = new HashSet<Promotor>();
        }

        public int IdPersona { get; set; }
        public int? TipoPersona { get; set; }
        public int? TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string DireccionDepartamento { get; set; }
        public string DireccionProvincia { get; set; }
        public string DireccionDistrito { get; set; }
        public string Direccion { get; set; }
        public int? Sexo { get; set; }
        public string Email { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoCelular { get; set; }
        public string PartidaRegistral { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public string NombreCarnesis { get; set; }

        public  ICollection<Director> Directors { get; set; }
        public  ICollection<Promotor> Promotors { get; set; }
    }
}