// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class Sector
    {
        public Sector()
        {
            FamiliaProductivas = new HashSet<FamiliaProductiva>();
        }

        public int IdSector { get; set; }
        public string CodigoSector { get; set; }
        public string NombreSector { get; set; }
        public string Descripcion { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public  ICollection<FamiliaProductiva> FamiliaProductivas { get; set; }
    }
}