// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class Sede
    {
        public Sede()
        {
            InstitucionCarreras = new HashSet<InstitucionCarrera>();
        }

        public int IdSede { get; set; }
        public int? IdInstitucion { get; set; }
        public string CodigoModular { get; set; }
        public int? TipoSede { get; set; }
        public string NombreSede { get; set; }
        public string Direccion { get; set; }
        public string CodigoDepartamento { get; set; }
        public string CodigoProvincia { get; set; }
        public string CodigoDistrito { get; set; }
        public string CentroPoblado { get; set; }
        public string Telefono { get; set; }
        public string CodigoSede { get; set; }
        public int? IdInstitucionSuperior { get; set; }
        public int? TipoZona { get; set; }
        public int? TipoEntidadReguladora { get; set; }
        public string CodigoEntidadReguladora { get; set; }
        public string NombreEntidadReguladora { get; set; }
        public int? TipoEstado { get; set; }
        public string DirectorGeneral { get; set; }
        public string ResponsableAcademico { get; set; }
        public string DreGre { get; set; }
        public int? TipoCargoAcademico { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public  Institucion IdInstitucionNavigation { get; set; }
        public  ICollection<InstitucionCarrera> InstitucionCarreras { get; set; }
    }
}