// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class TipoExpediente
    {
        public TipoExpediente()
        {
            Etapas = new HashSet<Etapa>();
            Expedientes = new HashSet<Expediente>();
        }

        public int IdTipoExpediente { get; set; }
        public string Nombre { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public  ICollection<Etapa> Etapas { get; set; }
        public  ICollection<Expediente> Expedientes { get; set; }
    }
}