// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity.DigePadron
{
    public partial class UnidadCompetencium
    {
        public UnidadCompetencium()
        {
            IndicadorLogros = new HashSet<IndicadorLogro>();
        }

        public int IdUnidadCompetencia { get; set; }
        public string CodigoUnidadCompetencia { get; set; }
        public int? IdCarreraDcb { get; set; }
        public string Descripcion { get; set; }
        public int? Estado { get; set; }
        public int? UsuarioInsercion { get; set; }
        public DateTime? FechaInsercion { get; set; }
        public int? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? IdSector { get; set; }
        public int? IdFamiliaProductiva { get; set; }
        public string Correlativo { get; set; }
        public int? IdActividadEconomica { get; set; }

        public  CarreraDcb IdCarreraDcbNavigation { get; set; }
        public  ICollection<IndicadorLogro> IndicadorLogros { get; set; }
    }
}