// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class actividad_economicaConfiguration : IEntityTypeConfiguration<actividad_economica>
    {
        public void Configure(EntityTypeBuilder<actividad_economica> entity)
        {
            entity.HasKey(e => e.ID_ACTIVIDAD_ECONOMICA)
                .HasName("PK_ACTIVIDAD_ECONOMICA")
                .IsClustered(false);

            entity.ToTable("actividad_economica", "maestro");

            entity.Property(e => e.CODIGO_ACTIVIDAD_ECONOMICA)
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.Property(e => e.DESCRIPCION_ACTIVIDAD_ECONOMICA)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_ACTIVIDAD_ECONOMICA)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_FAMILIA_PRODUCTIVANavigation)
                .WithMany(p => p.actividad_economica)
                .HasForeignKey(d => d.ID_FAMILIA_PRODUCTIVA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ACTIVIDA_FK_FAMILI_FAMILIA_");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<actividad_economica> entity);
    }
}
