// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class asignación_institucion_cargaConfiguration : IEntityTypeConfiguration<asignación_institucion_carga>
    {
        public void Configure(EntityTypeBuilder<asignación_institucion_carga> entity)
        {
            entity.HasKey(e => e.ID_ASIGNACION_INSTITUCION_CARGA)
                .HasName("PK_ASIGNACION_INSTITUCION_CARGA")
                .IsClustered(false);

            entity.ToTable("asignación_institucion_carga", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<asignación_institucion_carga> entity);
    }
}
