// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class capacidades_por_componenteConfiguration : IEntityTypeConfiguration<capacidades_por_componente>
    {
        public void Configure(EntityTypeBuilder<capacidades_por_componente> entity)
        {
            entity.HasKey(e => e.ID_CAPACIDADES_POR_COMPONENTE)
                .HasName("PK_CAPACIDADES_POR_COMPONENTE")
                .IsClustered(false);

            entity.ToTable("capacidades_por_componente", "transaccional");

            entity.Property(e => e.CODIGO_CAPACIDAD)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_CAPACIDAD)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_COMPONENTE_CURRICULARNavigation)
                .WithMany(p => p.capacidades_por_componente)
                .HasForeignKey(d => d.ID_COMPONENTE_CURRICULAR)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CAPACIDA_FK_COMPON_COMPONEN");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<capacidades_por_componente> entity);
    }
}
