// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class carga_masiva_actasConfiguration : IEntityTypeConfiguration<carga_masiva_actas>
    {
        public void Configure(EntityTypeBuilder<carga_masiva_actas> entity)
        {
            entity.HasKey(e => e.ID_CARGA_MASIVA_ACTA)
                .HasName("PK__carga_ma__172B4E2FF175A880");

            entity.ToTable("carga_masiva_actas", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_CARGA_MASIVA_NOMINANavigation)
                .WithMany(p => p.carga_masiva_actas)
                .HasForeignKey(d => d.ID_CARGA_MASIVA_NOMINA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CARGA_MASIVA_NOMINAS_ACTAS_CARGA_MASIVA_NOMINAS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<carga_masiva_actas> entity);
    }
}
