// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class enfoques_por_plan_estudioConfiguration : IEntityTypeConfiguration<enfoques_por_plan_estudio>
    {
        public void Configure(EntityTypeBuilder<enfoques_por_plan_estudio> entity)
        {
            entity.HasKey(e => e.ID_ENFOQUES_POR_PLAN_ESTUDIO)
                .HasName("PK_ENFOQUES_POR_PLAN_ESTUDIO")
                .IsClustered(false);

            entity.ToTable("enfoques_por_plan_estudio", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_ENFOQUENavigation)
                .WithMany(p => p.enfoques_por_plan_estudio)
                .HasForeignKey(d => d.ID_ENFOQUE)
                .HasConstraintName("FK_ENFOQUES_RELATIONS_ENFOQUE");

            entity.HasOne(d => d.ID_PLAN_ESTUDIONavigation)
                .WithMany(p => p.enfoques_por_plan_estudio)
                .HasForeignKey(d => d.ID_PLAN_ESTUDIO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ENFOQUES_FK_PLAN_E_PLAN_EST");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<enfoques_por_plan_estudio> entity);
    }
}
