// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class estudiante_institucionConfiguration : IEntityTypeConfiguration<estudiante_institucion>
    {
        public void Configure(EntityTypeBuilder<estudiante_institucion> entity)
        {
            entity.HasKey(e => e.ID_ESTUDIANTE_INSTITUCION)
                .HasName("PK_ESTUDIANTE_INSTITUCION")
                .IsClustered(false);

            entity.ToTable("estudiante_institucion", "transaccional");

            entity.HasIndex(e => e.ES_ACTIVO, "IDX_ESTUDIANTE_INSTITUCION1");

            entity.Property(e => e.APELLIDO_APODERADO)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.ARCHIVO_FOTO)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ARCHIVO_RUTA)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.CODIGO_ESTUDIANTE)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_APODERADO)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.NUMERO_DOCUMENTO_APODERADO)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_CARRERAS_POR_INSTITUCION_DETALLENavigation)
                .WithMany(p => p.estudiante_institucion)
                .HasForeignKey(d => d.ID_CARRERAS_POR_INSTITUCION_DETALLE)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ESTUDIAN_FK_CARR_POR_INSTIT_DET_ID");

            entity.HasOne(d => d.ID_INSTITUCION_BASICANavigation)
                .WithMany(p => p.estudiante_institucion)
                .HasForeignKey(d => d.ID_INSTITUCION_BASICA)
                .HasConstraintName("FK_ESTUDIAN_FK_INSTIT_BASICA_ID");

            entity.HasOne(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCIONNavigation)
                .WithMany(p => p.estudiante_institucion)
                .HasForeignKey(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EST_INST_FK_PERI_LECT_INS");

            entity.HasOne(d => d.ID_PERSONA_INSTITUCIONNavigation)
                .WithMany(p => p.estudiante_institucion)
                .HasForeignKey(d => d.ID_PERSONA_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ESTUDIAN_FK_PERSONA_INST_ID");

            entity.HasOne(d => d.ID_PLAN_ESTUDIONavigation)
                .WithMany(p => p.estudiante_institucion)
                .HasForeignKey(d => d.ID_PLAN_ESTUDIO)
                .HasConstraintName("FK_ESTUDIAN_FK_PLAN_ESTUDIO_ID");

            entity.HasOne(d => d.ID_TURNOS_POR_INSTITUCIONNavigation)
                .WithMany(p => p.estudiante_institucion)
                .HasForeignKey(d => d.ID_TURNOS_POR_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ESTUDIAN_FK_TURN_POR_INSTIT_ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<estudiante_institucion> entity);
    }
}
