// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class evaluacion_extraordinaria_detalleConfiguration : IEntityTypeConfiguration<evaluacion_extraordinaria_detalle>
    {
        public void Configure(EntityTypeBuilder<evaluacion_extraordinaria_detalle> entity)
        {
            entity.HasKey(e => e.ID_EVALUACION_EXTRAORDINARIA_DETALLE)
                .HasName("PK_EVALUACION_EXTRAORDINARIA_DETALLE")
                .IsClustered(false);

            entity.ToTable("evaluacion_extraordinaria_detalle", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOTA).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_EVALUACION_EXTRAORDINARIANavigation)
                .WithMany(p => p.evaluacion_extraordinaria_detalle)
                .HasForeignKey(d => d.ID_EVALUACION_EXTRAORDINARIA)
                .HasConstraintName("FK_ID_EVALUACION_EXTRAORDINARIA");

            entity.HasOne(d => d.ID_UNIDAD_DIDACTICANavigation)
                .WithMany(p => p.evaluacion_extraordinaria_detalle)
                .HasForeignKey(d => d.ID_UNIDAD_DIDACTICA)
                .HasConstraintName("FK_ID_UNIDAD_DIDACTICA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<evaluacion_extraordinaria_detalle> entity);
    }
}
