// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class evaluacionConfiguration : IEntityTypeConfiguration<evaluacion>
    {
        public void Configure(EntityTypeBuilder<evaluacion> entity)
        {
            entity.HasKey(e => e.ID_EVALUACION)
                .HasName("PK_EVALUACION")
                .IsClustered(false);

            entity.ToTable("evaluacion", "transaccional");

            entity.HasIndex(e => new { e.ID_PROGRAMACION_CLASE, e.ES_ACTIVO }, "IDX_EVALUACION1");

            entity.HasIndex(e => new { e.ID_PROGRAMACION_CLASE, e.ID_CARRERA, e.ID_UNIDAD_DIDACTICA }, "idx_evaluacion_programacion_carrera_unidad");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_NOTA).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PROGRAMACION_CLASENavigation)
                .WithMany(p => p.evaluacion)
                .HasForeignKey(d => d.ID_PROGRAMACION_CLASE)
                .HasConstraintName("FK_EVALUACI_RELATIONS_PROGRAMA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<evaluacion> entity);
    }
}
