// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class evaluador_admision_modalidadConfiguration : IEntityTypeConfiguration<evaluador_admision_modalidad>
    {
        public void Configure(EntityTypeBuilder<evaluador_admision_modalidad> entity)
        {
            entity.HasKey(e => e.ID_EVALUADOR_ADMISION_MODALIDAD)
                .HasName("PK_EVALUADOR_ADMISION_MODALIDA")
                .IsClustered(false);

            entity.ToTable("evaluador_admision_modalidad", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_MODALIDADES_POR_PROCESO_ADMISIONNavigation)
                .WithMany(p => p.evaluador_admision_modalidad)
                .HasForeignKey(d => d.ID_MODALIDADES_POR_PROCESO_ADMISION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EVALUADO_RELATIONS_MODALIDA");

            entity.HasOne(d => d.ID_PERSONAL_INSTITUCIONNavigation)
                .WithMany(p => p.evaluador_admision_modalidad)
                .HasForeignKey(d => d.ID_PERSONAL_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EVALUADO_RELATIONS_PERSONAL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<evaluador_admision_modalidad> entity);
    }
}
