// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class exportador_datos_configuracion_detalleConfiguration : IEntityTypeConfiguration<exportador_datos_configuracion_detalle>
    {
        public void Configure(EntityTypeBuilder<exportador_datos_configuracion_detalle> entity)
        {
            entity.HasKey(e => e.ID_EXPORTADOR_DATOS_CONFIGURACION_DETALLE);

            entity.ToTable("exportador_datos_configuracion_detalle", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_EXPORTADOR_DATOS_CONFIGURACIONNavigation)
                .WithMany(p => p.exportador_datos_configuracion_detalle)
                .HasForeignKey(d => d.ID_EXPORTADOR_DATOS_CONFIGURACION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_exportador_datos_configuracion_detalle_exportador_datos_configuracion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<exportador_datos_configuracion_detalle> entity);
    }
}
