// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class indicadores_logro_por_unidad_didacticaConfiguration : IEntityTypeConfiguration<indicadores_logro_por_unidad_didactica>
    {
        public void Configure(EntityTypeBuilder<indicadores_logro_por_unidad_didactica> entity)
        {
            entity.HasKey(e => e.ID_INDICADORES_LOGRO_POR_UNIDAD_DIDACTICA)
                .HasName("PK_INDICADORES_LOGRO_POR_UNIDA")
                .IsClustered(false);

            entity.ToTable("indicadores_logro_por_unidad_didactica", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_INDICADORES_LOGRO_POR_CAPACIDADNavigation)
                .WithMany(p => p.indicadores_logro_por_unidad_didactica)
                .HasForeignKey(d => d.ID_INDICADORES_LOGRO_POR_CAPACIDAD)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_INDICADO_FK_INDICA_INDICADO");

            entity.HasOne(d => d.ID_UNIDAD_DIDACTICANavigation)
                .WithMany(p => p.indicadores_logro_por_unidad_didactica)
                .HasForeignKey(d => d.ID_UNIDAD_DIDACTICA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_INDICADO_FK_UNIDAD_UNIDAD_D");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<indicadores_logro_por_unidad_didactica> entity);
    }
}
