// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class indicadores_logroConfiguration : IEntityTypeConfiguration<indicadores_logro>
    {
        public void Configure(EntityTypeBuilder<indicadores_logro> entity)
        {
            entity.HasKey(e => e.ID_INDICADORES_LOGRO)
                .HasName("PK_INDICADORES_LOGRO")
                .IsClustered(false);

            entity.ToTable("indicadores_logro", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_UNIDAD_COMPETENCIANavigation)
                .WithMany(p => p.indicadores_logro)
                .HasForeignKey(d => d.ID_UNIDAD_COMPETENCIA)
                .HasConstraintName("FK_UNIDAD_COMPETENCIA_INDICADORES_LOGRO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<indicadores_logro> entity);
    }
}
