// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class modulo_equivalenciaConfiguration : IEntityTypeConfiguration<modulo_equivalencia>
    {
        public void Configure(EntityTypeBuilder<modulo_equivalencia> entity)
        {
            entity.HasKey(e => e.ID_MODULO_EQUIVALENCIA)
                .HasName("PK_MODULO_EQUIVALENCIA")
                .IsClustered(false);

            entity.ToTable("modulo_equivalencia", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.TOTCREDITOS).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.TOTHORAS).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PLAN_ESTUDIONavigation)
                .WithMany(p => p.modulo_equivalencia)
                .HasForeignKey(d => d.ID_PLAN_ESTUDIO)
                .HasConstraintName("FK__modulo_eq__ID_PL__38D961D7");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<modulo_equivalencia> entity);
    }
}
