// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class periodo_academicoConfiguration : IEntityTypeConfiguration<periodo_academico>
    {
        public void Configure(EntityTypeBuilder<periodo_academico> entity)
        {
            entity.HasKey(e => e.ID_PERIODO_ACADEMICO)
                .HasName("PK_PERIODO_ACADEMICO")
                .IsClustered(false);

            entity.ToTable("periodo_academico", "transaccional");

            entity.HasIndex(e => new { e.ID_PERIODOS_LECTIVOS_POR_INSTITUCION, e.ES_ACTIVO }, "IDX_PERIODO_ACADEMICO1");

            entity.HasIndex(e => new { e.ID_PERIODOS_LECTIVOS_POR_INSTITUCION, e.ES_ACTIVO }, "IDX_PERIODO_ACADEMICO2");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_FIN).HasColumnType("datetime");

            entity.Property(e => e.FECHA_INICIO).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_PERIODO_ACADEMICO)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCIONNavigation)
                .WithMany(p => p.periodo_academico)
                .HasForeignKey(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PERIODO__RELATIONS_PERIODOS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<periodo_academico> entity);
    }
}
