// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class personaConfiguration : IEntityTypeConfiguration<persona>
    {
        public void Configure(EntityTypeBuilder<persona> entity)
        {
            entity.HasKey(e => e.ID_PERSONA)
                .HasName("PK_PERSONA")
                .IsClustered(false);

            entity.ToTable("persona", "maestro");

            entity.HasIndex(e => e.ID_PERSONA, "IDX_PERSONA1");

            entity.Property(e => e.APELLIDO_MATERNO_PERSONA)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.APELLIDO_PATERNO_PERSONA)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_NACIMIENTO_PERSONA).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_PERSONA)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.NUMERO_DOCUMENTO_PERSONA)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.UBIGEO_NACIMIENTO)
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<persona> entity);
    }
}
