// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class postulantes_por_modalidadConfiguration : IEntityTypeConfiguration<postulantes_por_modalidad>
    {
        public void Configure(EntityTypeBuilder<postulantes_por_modalidad> entity)
        {
            entity.HasKey(e => e.ID_POSTULANTES_POR_MODALIDAD)
                .HasName("PK_POSTULANTES_POR_MODALIDAD")
                .IsClustered(false);

            entity.ToTable("postulantes_por_modalidad", "transaccional");

            entity.HasIndex(e => new { e.ID_POSTULANTES_POR_MODALIDAD, e.ID_MODALIDADES_POR_PROCESO_ADMISION, e.ID_TIPOS_MODALIDAD_POR_INSTITUCION, e.ID_EXAMEN_ADMISION_SEDE, e.ID_PERSONA_INSTITUCION, e.ID_INSTITUCION_BASICA, e.ID_TIPO_DOCUMENTO_APODERADO, e.NUMERO_DOCUMENTO_APODERADO, e.ID_TIPO_PARENTEZCO, e.ES_ACTIVO, e.ESTADO }, "IDX_POSTULANTES_POR_MODALIDAD1");

            entity.Property(e => e.APELLIDO_APODERADO)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.ARCHIVO_COMPROBANTE)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ARCHIVO_COMPROBANTE_RUTA)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.ARCHIVO_FOTO)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ARCHIVO_RUTA)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.CODIGO_POSTULANTE)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.MONTO_PAGO).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.MOTIVO_EXONERACION)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.NOMBRE_APODERADO)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.NUMERO_COMPROBANTE)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.NUMERO_DOCUMENTO_APODERADO)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e._CODIGO_ESTUDIANTE)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_EXAMEN_ADMISION_SEDENavigation)
                .WithMany(p => p.postulantes_por_modalidad)
                .HasForeignKey(d => d.ID_EXAMEN_ADMISION_SEDE)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_POSTULAN_RELATIONS_EXAMEN_A");

            entity.HasOne(d => d.ID_INSTITUCION_BASICANavigation)
                .WithMany(p => p.postulantes_por_modalidad)
                .HasForeignKey(d => d.ID_INSTITUCION_BASICA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_POSTULAN_RELATIONS_INSTITUC");

            entity.HasOne(d => d.ID_MODALIDADES_POR_PROCESO_ADMISIONNavigation)
                .WithMany(p => p.postulantes_por_modalidad)
                .HasForeignKey(d => d.ID_MODALIDADES_POR_PROCESO_ADMISION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_POSTULAN_FK_MODALI_MODALIDA");

            entity.HasOne(d => d.ID_PERSONA_INSTITUCIONNavigation)
                .WithMany(p => p.postulantes_por_modalidad)
                .HasForeignKey(d => d.ID_PERSONA_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_POSTULAN_PERSONA_I_PERSONA_");

            entity.HasOne(d => d.ID_TIPOS_MODALIDAD_POR_INSTITUCIONNavigation)
                .WithMany(p => p.postulantes_por_modalidad)
                .HasForeignKey(d => d.ID_TIPOS_MODALIDAD_POR_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_POSTULAN_RELATIONS_TIPOS_MO");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<postulantes_por_modalidad> entity);
    }
}
