// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class proceso_admision_periodoConfiguration : IEntityTypeConfiguration<proceso_admision_periodo>
    {
        public void Configure(EntityTypeBuilder<proceso_admision_periodo> entity)
        {
            entity.HasKey(e => e.ID_PROCESO_ADMISION_PERIODO)
                .HasName("PK_PROCESO_ADMISION_PERIODO")
                .IsClustered(false);

            entity.ToTable("proceso_admision_periodo", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_FIN).HasColumnType("datetime");

            entity.Property(e => e.FECHA_INICIO).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.MODALIDADES)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.NOMBRE_PROCESO_ADMISION)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCIONNavigation)
                .WithMany(p => p.proceso_admision_periodo)
                .HasForeignKey(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROCESO__RELATIONS_PERIODOS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<proceso_admision_periodo> entity);
    }
}
