// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class programacion_clase_por_matricula_estudianteConfiguration : IEntityTypeConfiguration<programacion_clase_por_matricula_estudiante>
    {
        public void Configure(EntityTypeBuilder<programacion_clase_por_matricula_estudiante> entity)
        {
            entity.HasKey(e => e.ID_PROGRAMACION_CLASE_POR_MATRICULA_ESTUDIANTE)
                .HasName("PK_PROGRAMACION_CLASE_POR_MATRICULA_ESTUDIANTE")
                .IsClustered(false);

            entity.ToTable("programacion_clase_por_matricula_estudiante", "transaccional");

            entity.HasIndex(e => new { e.ID_MATRICULA_ESTUDIANTE, e.ES_ACTIVO }, "IDX_PROGRAMACION_CLASE_MATR_EST1");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_MATRICULA_ESTUDIANTENavigation)
                .WithMany(p => p.programacion_clase_por_matricula_estudiante)
                .HasForeignKey(d => d.ID_MATRICULA_ESTUDIANTE)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROG_CLAS_POR_MATR_EST_FK_MATR_EST");

            entity.HasOne(d => d.ID_PROGRAMACION_CLASENavigation)
                .WithMany(p => p.programacion_clase_por_matricula_estudiante)
                .HasForeignKey(d => d.ID_PROGRAMACION_CLASE)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PROG_CLAS_POR_MATR_EST_FK_PROG_CLASE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<programacion_clase_por_matricula_estudiante> entity);
    }
}
