// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class promocion_institucion_estudianteConfiguration : IEntityTypeConfiguration<promocion_institucion_estudiante>
    {
        public void Configure(EntityTypeBuilder<promocion_institucion_estudiante> entity)
        {
            entity.HasNoKey();

            entity.ToTable("promocion_institucion_estudiante", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.ID_PROMOCION_INSTITUCION_ESTUDIANTE).ValueGeneratedOnAdd();

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<promocion_institucion_estudiante> entity);
    }
}
