// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class requisitos_por_postulanteConfiguration : IEntityTypeConfiguration<requisitos_por_postulante>
    {
        public void Configure(EntityTypeBuilder<requisitos_por_postulante> entity)
        {
            entity.HasKey(e => e.ID_REQUISITOS_POR_POSTULANTE)
                .HasName("PK_REQUISITOS_POR_POSTULANTE")
                .IsClustered(false);

            entity.ToTable("requisitos_por_postulante", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_POSTULANTES_POR_MODALIDADNavigation)
                .WithMany(p => p.requisitos_por_postulante)
                .HasForeignKey(d => d.ID_POSTULANTES_POR_MODALIDAD)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_REQUISIT_RELATIONS_POSTULAN");

            entity.HasOne(d => d.ID_REQUISITOS_POR_TIPO_MODALIDADNavigation)
                .WithMany(p => p.requisitos_por_postulante)
                .HasForeignKey(d => d.ID_REQUISITOS_POR_TIPO_MODALIDAD)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_REQUISITOS_POR_TIPO_MODALIDAD_REQUISITOS_POR_POSTULANTE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<requisitos_por_postulante> entity);
    }
}
