// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class retiro_estudianteConfiguration : IEntityTypeConfiguration<retiro_estudiante>
    {
        public void Configure(EntityTypeBuilder<retiro_estudiante> entity)
        {
            entity.HasKey(e => e.ID_RETIRO_ESTUDIANTE)
                .HasName("PK_RETIRO_ESTUDIANTE");

            entity.ToTable("retiro_estudiante", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_ESTUDIANTE_INSTITUCIONNavigation)
                .WithMany(p => p.retiro_estudiante)
                .HasForeignKey(d => d.ID_ESTUDIANTE_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RETIRO_FK_ESTUDIANTE");

            entity.HasOne(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCIONNavigation)
                .WithMany(p => p.retiro_estudiante)
                .HasForeignKey(d => d.ID_PERIODOS_LECTIVOS_POR_INSTITUCION)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RETIRO_FK_PERIODOS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<retiro_estudiante> entity);
    }
}
