// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class sede_institucionConfiguration : IEntityTypeConfiguration<sede_institucion>
    {
        public void Configure(EntityTypeBuilder<sede_institucion> entity)
        {
            entity.HasKey(e => e.ID_SEDE_INSTITUCION)
                .HasName("PK_SEDE_INSTITUCION")
                .IsClustered(false);

            entity.ToTable("sede_institucion", "maestro");

            entity.HasIndex(e => e.ES_ACTIVO, "IDX_SEDE_INSTITUCION1");

            entity.HasIndex(e => e.ID_INSTITUCION, "IDX_SEDE_INSTITUCION_IDINSTITUCION");

            entity.Property(e => e.ARCHIVO_RESOLUCION)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.ARCHIVO_RUTA)
                .HasMaxLength(300)
                .IsUnicode(false);

            entity.Property(e => e.CODIGO_SEDE)
                .HasMaxLength(7)
                .IsUnicode(false);

            entity.Property(e => e.CODIGO_UBIGEO_SEDE)
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.Property(e => e.CORREO_SEDE)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.DIRECCION_SEDE)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.DIRECTOR_SEDE)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_SEDE)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.NRO_RESOLUCION)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.TELEFONO_SEDE)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<sede_institucion> entity);
    }
}
