// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class situacion_academica_detalleConfiguration : IEntityTypeConfiguration<situacion_academica_detalle>
    {
        public void Configure(EntityTypeBuilder<situacion_academica_detalle> entity)
        {
            entity.HasKey(e => e.ID_SITUACION_ACADEMICA_DETALLE)
                .HasName("PK_SITUACION_ACADEMICA_DETALLE")
                .IsClustered(false);

            entity.ToTable("situacion_academica_detalle", "transaccional");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOTA).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_SITUACION_ACADEMICA_ESTUDIANTENavigation)
                .WithMany(p => p.situacion_academica_detalle)
                .HasForeignKey(d => d.ID_SITUACION_ACADEMICA_ESTUDIANTE)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SITUACIO_FK_SITUAC_SITUACIO");

            entity.HasOne(d => d.ID_UNIDAD_DIDACTICANavigation)
                .WithMany(p => p.situacion_academica_detalle)
                .HasForeignKey(d => d.ID_UNIDAD_DIDACTICA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SITUACIO_FK_UNIDAD_UNIDAD_D");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<situacion_academica_detalle> entity);
    }
}
