// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class tipo_unidad_didacticaConfiguration : IEntityTypeConfiguration<tipo_unidad_didactica>
    {
        public void Configure(EntityTypeBuilder<tipo_unidad_didactica> entity)
        {
            entity.HasKey(e => e.ID_TIPO_UNIDAD_DIDACTICA)
                .HasName("PK_TIPO_UNIDAD_DIDACTICA")
                .IsClustered(false);

            entity.ToTable("tipo_unidad_didactica", "maestro");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.NOMBRE_TIPO_UNIDAD)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<tipo_unidad_didactica> entity);
    }
}
