// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class turnos_por_institucionConfiguration : IEntityTypeConfiguration<turnos_por_institucion>
    {
        public void Configure(EntityTypeBuilder<turnos_por_institucion> entity)
        {
            entity.HasKey(e => e.ID_TURNOS_POR_INSTITUCION)
                .HasName("PK_TURNOS_POR_INSTITUCION")
                .IsClustered(false);

            entity.ToTable("turnos_por_institucion", "maestro");

            entity.HasIndex(e => new { e.ID_TURNOS_POR_INSTITUCION, e.ES_ACTIVO }, "IDX_TURNOS_POR_INSTITUCION1");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_TURNO_EQUIVALENCIANavigation)
                .WithMany(p => p.turnos_por_institucion)
                .HasForeignKey(d => d.ID_TURNO_EQUIVALENCIA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TURNOS_P_RELATIONS_TURNO_EQ");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<turnos_por_institucion> entity);
    }
}
