// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class unidades_didacticas_por_programacion_claseConfiguration : IEntityTypeConfiguration<unidades_didacticas_por_programacion_clase>
    {
        public void Configure(EntityTypeBuilder<unidades_didacticas_por_programacion_clase> entity)
        {
            entity.HasKey(e => e.ID_UNIDADES_DIDACTICAS_POR_PROGRAMACION_CLASE)
                .HasName("PK_UNIDADES_DIDACTICAS_POR_PRO")
                .IsClustered(false);

            entity.ToTable("unidades_didacticas_por_programacion_clase", "transaccional");

            entity.HasIndex(e => new { e.ID_UNIDADES_DIDACTICAS_POR_ENFOQUE, e.ES_ACTIVO }, "IDX_UNIDADES_DIDACTICAS_PROG_CLAS1");

            entity.HasIndex(e => new { e.ID_PROGRAMACION_CLASE, e.ES_ACTIVO }, "IDX_UNIDADES_DIDACTICAS_PROG_CLAS2");

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_PROGRAMACION_CLASENavigation)
                .WithMany(p => p.unidades_didacticas_por_programacion_clase)
                .HasForeignKey(d => d.ID_PROGRAMACION_CLASE)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UNIDADES_FK_PROGRA_PROGRAMA");

            entity.HasOne(d => d.ID_UNIDADES_DIDACTICAS_POR_ENFOQUENavigation)
                .WithMany(p => p.unidades_didacticas_por_programacion_clase)
                .HasForeignKey(d => d.ID_UNIDADES_DIDACTICAS_POR_ENFOQUE)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UNIDADES_DIDACTICAS_POR_ENFOQUE_UNIDADES_DIDACTICAS_POR_PROGRAMACION_CLASE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<unidades_didacticas_por_programacion_clase> entity);
    }
}
