// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class unidad_didacticaConfiguration : IEntityTypeConfiguration<unidad_didactica>
    {
        public void Configure(EntityTypeBuilder<unidad_didactica> entity)
        {
            entity.HasKey(e => e.ID_UNIDAD_DIDACTICA)
                .HasName("PK_UNIDAD_DIDACTICA")
                .IsClustered(false);

            entity.ToTable("unidad_didactica", "transaccional");

            entity.HasIndex(e => new { e.ID_SEMESTRE_ACADEMICO, e.ES_ACTIVO }, "IDX_UNIDAD_DIDACTICA1");

            entity.HasIndex(e => new { e.ID_MODULO, e.ES_ACTIVO }, "IDX_UNIDAD_DIDACTICA2");

            entity.HasIndex(e => new { e.ID_UNIDAD_DIDACTICA, e.ES_ACTIVO }, "IDX_UNIDAD_DIDACTICA3");

            entity.Property(e => e.CODIGO_UNIDAD_DIDACTICA)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.CREDITOS).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.DESCRIPCION)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.HORAS).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.NOMBRE_UNIDAD_DIDACTICA)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.PERIODO_ACADEMICO_I).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.PERIODO_ACADEMICO_II).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.PERIODO_ACADEMICO_III).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.PERIODO_ACADEMICO_IV).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.PERIODO_ACADEMICO_V).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.PERIODO_ACADEMICO_VI).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.PERIODO_ACADEMICO_VII).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.PERIODO_ACADEMICO_VIII).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.PRACTICO_CREDITOS_UD).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.PRACTICO_HORAS_UD).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.TEORICO_PRACTICO_CREDITOS_UD).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.TEORICO_PRACTICO_HORAS_UD).HasColumnType("decimal(5, 1)");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_MODULONavigation)
                .WithMany(p => p.unidad_didactica)
                .HasForeignKey(d => d.ID_MODULO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UNIDAD_D_FK_MODULO_MODULO");

            entity.HasOne(d => d.ID_TIPO_UNIDAD_DIDACTICANavigation)
                .WithMany(p => p.unidad_didactica)
                .HasForeignKey(d => d.ID_TIPO_UNIDAD_DIDACTICA)
                .HasConstraintName("FK_UNID_FK_UNID_TIP");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<unidad_didactica> entity);
    }
}
