// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Entity;
using System;
using System.Collections.Generic;

#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.Configurations
{
    public partial class unidad_didactica_detalleConfiguration : IEntityTypeConfiguration<unidad_didactica_detalle>
    {
        public void Configure(EntityTypeBuilder<unidad_didactica_detalle> entity)
        {
            entity.HasKey(e => e.ID_UNIDAD_DIDACTICA_DETALLE)
                .HasName("PK_UNIDAD_DIDACTICA_DETALLE")
                .IsClustered(false);

            entity.ToTable("unidad_didactica_detalle", "transaccional");

            entity.Property(e => e.CODIGO_PREDECESORA)
                .HasMaxLength(16)
                .IsUnicode(false);

            entity.Property(e => e.FECHA_CREACION).HasColumnType("datetime");

            entity.Property(e => e.FECHA_MODIFICACION).HasColumnType("datetime");

            entity.Property(e => e.USUARIO_CREACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.USUARIO_MODIFICACION)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_UNIDAD_DIDACTICANavigation)
                .WithMany(p => p.unidad_didactica_detalle)
                .HasForeignKey(d => d.ID_UNIDAD_DIDACTICA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UNID_DIDAC_DET_FK_UNID_DIDAC");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<unidad_didactica_detalle> entity);
    }
}
