// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class actividad_economica
    {
       

        public int ID_ACTIVIDAD_ECONOMICA { get; set; }
        public int ID_FAMILIA_PRODUCTIVA { get; set; }
        public string CODIGO_ACTIVIDAD_ECONOMICA { get; set; } = null!;
        public int CODIGO_DIVISION_ACTIVIDAD_ECONOMICA { get; set; }
        public string NOMBRE_ACTIVIDAD_ECONOMICA { get; set; } = null!;
        public string? DESCRIPCION_ACTIVIDAD_ECONOMICA { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  familia_productiva ID_FAMILIA_PRODUCTIVANavigation { get; set; } = null!;
        public  ICollection<unidad_competencia> unidad_competencia { get; set; }
    }
}