// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class aula
    {
      

        public int ID_AULA { get; set; }
        public int ID_SEDE_INSTITUCION { get; set; }
        public int ID_PISO { get; set; }
        public string? NOMBRE_AULA { get; set; }
        public int CATEGORIA_AULA { get; set; }
        public int AFORO_AULA { get; set; }
        public string? UBICACION_AULA { get; set; }
        public string? OBSERVACION_AULA { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  sede_institucion ID_SEDE_INSTITUCIONNavigation { get; set; } = null!;
        public  ICollection<distribucion_examen_admision> distribucion_examen_admision { get; set; }
        public  ICollection<sesion_programacion_clase> sesion_programacion_clase { get; set; }
    }
}