// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class cronograma_meta_atencion
    {
        public int ID_CRONOGRAMA_META_ATENCION { get; set; }
        public int ID_PERIODO_LECTIVO { get; set; }
        public string? NOMBRE_CRONOGRAMA_META { get; set; }
        public DateTime? FECHA_INICIO { get; set; }
        public DateTime? FECHA_FIN { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  periodo_lectivo ID_PERIODO_LECTIVONavigation { get; set; } = null!;
    }
}