// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class familia_productiva
    {
      

        public int ID_FAMILIA_PRODUCTIVA { get; set; }
        public int ID_SECTOR { get; set; }
        public string CODIGO_FAMILIA_PRODUCTIVA { get; set; } = null!;
        public string NOMBRE_FAMILIA_PRODUCTIVA { get; set; } = null!;
        public string? DESCRIPCION_FAMILIA_PRODUCTIVA { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  sector ID_SECTORNavigation { get; set; } = null!;
        public  ICollection<actividad_economica> actividad_economica { get; set; }
    }
}