// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class indicador_logro
    {
        public int ID_INDICADOR_LOGRO { get; set; }
        public int ID_UNIDAD_COMPETENCIA { get; set; }
        public string CODIGO_INDICADOR_LOGRO { get; set; } = null!;
        public string NOMBRE_INDICADOR_LOGRO { get; set; } = null!;
        public string? DESCRIPCION_INDICADOR_LOGRO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  unidad_competencia ID_UNIDAD_COMPETENCIANavigation { get; set; } = null!;
    }
}