// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class parametros_institucion
    {
        public int ID_PARAMETROS_INSTITUCION { get; set; }
        public int ID_INSTITUCION { get; set; }
        public string NOMBRE_PARAMETRO { get; set; } = null!;
        public string VALOR_PARAMETRO { get; set; } = null!;
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }
    }
}