// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class periodo_lectivo
    {
      
        public int ID_PERIODO_LECTIVO { get; set; }
        public string? CODIGO_PERIODO_LECTIVO { get; set; }
        public int ID_TIPO_OPCION { get; set; }
        public DateTime FECHA_INICIO { get; set; }
        public DateTime FECHA_FIN { get; set; }
        public int ANIO { get; set; }
        public bool? ES_ASIGNADO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  ICollection<cronograma_meta_atencion> cronograma_meta_atencion { get; set; }
        public  ICollection<periodos_lectivos_por_institucion> periodos_lectivos_por_institucion { get; set; }
    }
}