// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class persona
    {


        public int ID_PERSONA { get; set; }
        public int ID_TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO_PERSONA { get; set; } = null!;
        public string NOMBRE_PERSONA { get; set; } = null!;
        public string APELLIDO_PATERNO_PERSONA { get; set; } = null!;
        public string? APELLIDO_MATERNO_PERSONA { get; set; }
        public DateTime FECHA_NACIMIENTO_PERSONA { get; set; }
        public short SEXO_PERSONA { get; set; }
        public int ID_LENGUA_MATERNA { get; set; }
        public bool? ES_DISCAPACITADO { get; set; }
        public string? UBIGEO_NACIMIENTO { get; set; }
        public int PAIS_NACIMIENTO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public List<persona_institucion> persona_institucion { get; set; }
    }
}