// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class requisitos_por_tipo_modalidad
    {
       

        public int ID_REQUISITOS_POR_TIPO_MODALIDAD { get; set; }
        public int ID_TIPOS_MODALIDAD_POR_INSTITUCION { get; set; }
        public int ID_REQUISITO { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  requisito ID_REQUISITONavigation { get; set; } = null!;
        public  tipos_modalidad_por_institucion ID_TIPOS_MODALIDAD_POR_INSTITUCIONNavigation { get; set; } = null!;
        public  ICollection<requisitos_por_postulante> requisitos_por_postulante { get; set; }
    }
}