// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class resolucion
    {
       
        public int ID_RESOLUCION { get; set; }
        public string? NUMERO_RESOLUCION { get; set; }
        public string? ARCHIVO_RESOLUCION { get; set; }
        public int ID_TIPO_RESOLUCION { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  ICollection<resoluciones_por_carreras_por_institucion> resoluciones_por_carreras_por_institucion { get; set; }
        public  ICollection<resoluciones_por_periodo_lectivo_institucion> resoluciones_por_periodo_lectivo_institucion { get; set; }
    }
}