// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class sede_institucion
    {
     

        public int ID_SEDE_INSTITUCION { get; set; }
        public int ID_INSTITUCION { get; set; }
        public string CODIGO_SEDE { get; set; } = null!;
        public string NOMBRE_SEDE { get; set; } = null!;
        public string? CODIGO_UBIGEO_SEDE { get; set; }
        public string? DIRECCION_SEDE { get; set; }
        public string? DIRECTOR_SEDE { get; set; }
        public string? TELEFONO_SEDE { get; set; }
        public string? CORREO_SEDE { get; set; }
        public bool ES_SEDE_PRINCIPAL { get; set; }
        public int ID_TIPO_SEDE { get; set; }
        public bool ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }
        public string? NRO_RESOLUCION { get; set; }
        public string? ARCHIVO_RESOLUCION { get; set; }
        public string? ARCHIVO_RUTA { get; set; }

        public  ICollection<aula> aula { get; set; }
        public  ICollection<carga> carga { get; set; }
        public  ICollection<carreras_por_institucion_detalle> carreras_por_institucion_detalle { get; set; }
        public  ICollection<examen_admision_sede> examen_admision_sede { get; set; }
        public  ICollection<meta_carrera_institucion_detalle> meta_carrera_institucion_detalle { get; set; }
        public  ICollection<programacion_clase> programacion_clase { get; set; }
        public  ICollection<promover_persona_institucion> promover_persona_institucion { get; set; }
        public  ICollection<resoluciones_por_carreras_por_institucion> resoluciones_por_carreras_por_institucion { get; set; }
        public  ICollection<situacion_academica_estudiante> situacion_academica_estudiante { get; set; }
    }
}