// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class tipo_modalidad
    {
     

        public int ID_TIPO_MODALIDAD { get; set; }
        public int ID_MODALIDAD { get; set; }
        public string? NOMBRE_TIPO_MODALIDAD { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  ICollection<tipos_modalidad_por_institucion> tipos_modalidad_por_institucion { get; set; }
    }
}