// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class tipo_unidad_didactica
    {
      

        public int ID_TIPO_UNIDAD_DIDACTICA { get; set; }
        public string NOMBRE_TIPO_UNIDAD { get; set; } = null!;
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  ICollection<plan_estudio_detalle> plan_estudio_detalle { get; set; }
        public  ICollection<unidad_didactica> unidad_didactica { get; set; }
        public  ICollection<unidades_didacticas_por_enfoque> unidades_didacticas_por_enfoque { get; set; }
    }
}