// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class turno_equivalencia
    {
     
        public int ID_TURNO_EQUIVALENCIA { get; set; }
        public int ID_TURNO { get; set; }
        public int COD_TUR { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  ICollection<turnos_por_institucion> turnos_por_institucion { get; set; }
    }
}