// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class turnos_por_institucion
    {
      

        public int ID_TURNOS_POR_INSTITUCION { get; set; }
        public int ID_TURNO_EQUIVALENCIA { get; set; }
        public int ID_INSTITUCION { get; set; }
        public bool? ES_ACTIVO { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  turno_equivalencia ID_TURNO_EQUIVALENCIANavigation { get; set; } = null!;
        public  ICollection<carga> carga { get; set; }
        public  ICollection<estudiante_institucion> estudiante_institucion { get; set; }
        public  ICollection<meta_carrera_institucion> meta_carrera_institucion { get; set; }
        public  ICollection<programacion_clase> programacion_clase { get; set; }
    }
}