CREATE TABLE [transaccional].[carga_masiva_nominas_cabecera] (
    [ID_CARGA_MASIVA_NOMINAS_CABECERA] [dbo].[ID]           IDENTITY (1, 1) NOT NULL,
    [CARRERA]                          VARCHAR (MAX)        NOT NULL,
    [PERIODO_ACADEMICO]                VARCHAR (MAX)        NOT NULL,
    [CICLO]                            VARCHAR (MAX)        NOT NULL,
    [NOMBRE_SEDE]                      VARCHAR (MAX)        NOT NULL,
    [TURNO]                            VARCHAR (MAX)        NOT NULL,
    [PLAN_ESTUDIO]                     VARCHAR (MAX)        NOT NULL,
    [SECCION]                          VARCHAR (MAX)        NOT NULL,
    [CANTIDAD_ALUMNOS]                 VARCHAR (MAX)        NOT NULL,
    [PERIODO_LECTIVO]                  VARCHAR (MAX)        NOT NULL,
    [DRE_GRE]                          VARCHAR (MAX)        NOT NULL,
    [NOMBRE_IEST]                      VARCHAR (MAX)        NOT NULL,
    [DEPARTAMENTO]                     VARCHAR (MAX)        NOT NULL,
    [PROVINCIA]                        VARCHAR (MAX)        NOT NULL,
    [DISTRITO]                         VARCHAR (MAX)        NOT NULL,
    [CENTRO_POBLADO]                   VARCHAR (MAX)        NOT NULL,
    [NIVEL_FORMATIVO]                  VARCHAR (MAX)        NOT NULL,
    [DIRECCION_IESTP]                  VARCHAR (MAX)        NOT NULL,
    [NUMERO_CODIGO_MODULAR]            VARCHAR (MAX)        NOT NULL,
    [TIPO_GESTION]                     VARCHAR (MAX)        NOT NULL,
    [ES_ACTIVO]                        [dbo].[BOOLEANO]     NOT NULL,
    [ESTADO]                           [dbo].[ESTADO]       NOT NULL,
    [USUARIO_CREACION]                 [dbo].[USUARIO]      NOT NULL,
    [FECHA_CREACION]                   [dbo].[FECHA_TIEMPO] NOT NULL,
    [USUARIO_MODIFICACION]             [dbo].[USUARIO]      NULL,
    [FECHA_MODIFICACION]               [dbo].[FECHA_TIEMPO] NULL,
    [FECHA_MATRICULA]                  [dbo].[FECHA]        NOT NULL,
    CONSTRAINT [PK_CARGA_MASIVA_NOMINAS_CABECERA] PRIMARY KEY NONCLUSTERED ([ID_CARGA_MASIVA_NOMINAS_CABECERA] ASC)
);

