CREATE TABLE [transaccional].[matricula_estudiante] (
    [ID_MATRICULA_ESTUDIANTE]              [dbo].[ID]           IDENTITY (1, 1) NOT NULL,
    [ID_PROGRAMACION_MATRICULA]            [dbo].[ID]           NOT NULL,
    [ID_ESTUDIANTE_INSTITUCION]            [dbo].[ID]           NOT NULL,
    [ID_PERIODOS_LECTIVOS_POR_INSTITUCION] [dbo].[ID]           NOT NULL,
    [ID_PERIODO_ACADEMICO]                 [dbo].[ID]           NOT NULL,
    [ID_SEMESTRE_ACADEMICO]                [dbo].[ID_ENUMERADO] NOT NULL,
    [ES_ACTIVO]                            [dbo].[BOOLEANO]     NOT NULL,
    [ESTADO]                               [dbo].[ESTADO]       NOT NULL,
    [USUARIO_CREACION]                     [dbo].[USUARIO]      NOT NULL,
    [FECHA_CREACION]                       [dbo].[FECHA_TIEMPO] NOT NULL,
    [USUARIO_MODIFICACION]                 [dbo].[USUARIO]      NULL,
    [FECHA_MODIFICACION]                   [dbo].[FECHA_TIEMPO] NULL,
    [FECHA_MATRICULA]                      [dbo].[FECHA]        NOT NULL,
    CONSTRAINT [PK_MATRICULA_ESTUDIANTE] PRIMARY KEY NONCLUSTERED ([ID_MATRICULA_ESTUDIANTE] ASC),
    CONSTRAINT [FK_MATR_EST_FK_PERIO_LECT] FOREIGN KEY ([ID_PERIODOS_LECTIVOS_POR_INSTITUCION]) REFERENCES [transaccional].[periodos_lectivos_por_institucion] ([ID_PERIODOS_LECTIVOS_POR_INSTITUCION]),
    CONSTRAINT [FK_MATRICUL_FK_ESTUDI_ESTUDIAN] FOREIGN KEY ([ID_ESTUDIANTE_INSTITUCION]) REFERENCES [transaccional].[estudiante_institucion] ([ID_ESTUDIANTE_INSTITUCION]),
    CONSTRAINT [FK_MATRICUL_FK_PERIOD_PERIODO_] FOREIGN KEY ([ID_PERIODO_ACADEMICO]) REFERENCES [transaccional].[periodo_academico] ([ID_PERIODO_ACADEMICO]),
    CONSTRAINT [FK_MATRICUL_FK_PROGRA_PROGRAMA] FOREIGN KEY ([ID_PROGRAMACION_MATRICULA]) REFERENCES [transaccional].[programacion_matricula] ([ID_PROGRAMACION_MATRICULA])
);


GO
CREATE NONCLUSTERED INDEX [IDX_MATRICULA_ESTUDIANTE3]
    ON [transaccional].[matricula_estudiante]([ID_ESTUDIANTE_INSTITUCION] ASC, [ID_MATRICULA_ESTUDIANTE] ASC, [ID_PROGRAMACION_MATRICULA] ASC, [ID_PERIODOS_LECTIVOS_POR_INSTITUCION] ASC, [ID_PERIODO_ACADEMICO] ASC, [ES_ACTIVO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_MATRICULA_ESTUDIANTE2]
    ON [transaccional].[matricula_estudiante]([ID_MATRICULA_ESTUDIANTE] ASC, [ES_ACTIVO] ASC)
    INCLUDE([ID_ESTUDIANTE_INSTITUCION], [ID_PERIODOS_LECTIVOS_POR_INSTITUCION]);


GO
CREATE NONCLUSTERED INDEX [IDX_MATRICULA_ESTUDIANTE1]
    ON [transaccional].[matricula_estudiante]([ID_PERIODOS_LECTIVOS_POR_INSTITUCION] ASC, [ID_PERIODO_ACADEMICO] ASC, [ES_ACTIVO] ASC)
    INCLUDE([ID_MATRICULA_ESTUDIANTE], [ID_ESTUDIANTE_INSTITUCION]);

