CREATE TABLE [transaccional].[plan_estudio_detalle] (
    [ID_PLAN_ESTUDIO_DETALLE]   [dbo].[ID]            IDENTITY (1, 1) NOT NULL,
    [ID_PLAN_ESTUDIO]           [dbo].[ID]            NOT NULL,
    [ID_TIPO_UNIDAD_DIDACTICA]  [dbo].[ID]            NULL,
    [DESCRIPCION_CONSOLIDADO]   [dbo].[DESCRIPCION]   NOT NULL,
    [PERIODO_ACADEMICO_I]       [dbo].[NUMERO_ENTERO] NULL,
    [PERIODO_ACADEMICO_II]      [dbo].[NUMERO_ENTERO] NULL,
    [PERIODO_ACADEMICO_III]     [dbo].[NUMERO_ENTERO] NULL,
    [PERIODO_ACADEMICO_IV]      [dbo].[NUMERO_ENTERO] NULL,
    [PERIODO_ACADEMICO_V]       [dbo].[NUMERO_ENTERO] NULL,
    [PERIODO_ACADEMICO_VI]      [dbo].[NUMERO_ENTERO] NULL,
    [SUMA_TOTAL_HORAS_POR_TIPO] [dbo].[NUMERO_ENTERO] NULL,
    [TOTAL_CREDITOS_UD]         DECIMAL (5, 1)        NULL,
    [SUMA_TOTAL_CREDITOS_UD]    DECIMAL (5, 1)        NULL,
    [COLUMNA_L]                 DECIMAL (10, 2)       NULL,
    [COLUMNA_M]                 DECIMAL (10, 2)       NULL,
    [COLUMNA_N]                 DECIMAL (10, 2)       NULL,
    [COLUMNA_O]                 DECIMAL (10, 2)       NULL,
    [COLUMNA_P]                 DECIMAL (10, 2)       NULL,
    [SUMA_HORAS]                [dbo].[NUMERO_ENTERO] NULL,
    [SUMA_CREDITOS]             [dbo].[NUMERO_ENTERO] NULL,
    [ORDEN_VISUALIZACION]       [dbo].[NUMERO_ENTERO] NULL,
    [ES_ACTIVO]                 [dbo].[BOOLEANO]      NOT NULL,
    [ESTADO]                    [dbo].[ESTADO]        NOT NULL,
    [USUARIO_CREACION]          [dbo].[USUARIO]       NOT NULL,
    [FECHA_CREACION]            [dbo].[FECHA_TIEMPO]  NOT NULL,
    [USUARIO_MODIFICACION]      [dbo].[USUARIO]       NULL,
    [FECHA_MODIFICACION]        [dbo].[FECHA_TIEMPO]  NULL,
    [PERIODO_ACADEMICO_VII]     DECIMAL (5, 1)        NULL,
    [PERIODO_ACADEMICO_VIII]    DECIMAL (5, 1)        NULL,
    CONSTRAINT [PK_plan_estudio_detalle] PRIMARY KEY NONCLUSTERED ([ID_PLAN_ESTUDIO_DETALLE] ASC),
    CONSTRAINT [FK_PLAN_FK_PLAN_DET] FOREIGN KEY ([ID_PLAN_ESTUDIO]) REFERENCES [transaccional].[plan_estudio] ([ID_PLAN_ESTUDIO]),
    CONSTRAINT [FK_PLAN_FK_TIPO_UD] FOREIGN KEY ([ID_TIPO_UNIDAD_DIDACTICA]) REFERENCES [maestro].[tipo_unidad_didactica] ([ID_TIPO_UNIDAD_DIDACTICA])
);

