CREATE TABLE [transaccional].[requisitos_por_postulante] (
    [ID_REQUISITOS_POR_POSTULANTE]     [dbo].[ID]           IDENTITY (1, 1) NOT NULL,
    [ID_POSTULANTES_POR_MODALIDAD]     [dbo].[ID]           NOT NULL,
    [ID_REQUISITOS_POR_TIPO_MODALIDAD] [dbo].[ID]           NOT NULL,
    [ES_ACTIVO]                        [dbo].[BOOLEANO]     NOT NULL,
    [ESTADO]                           [dbo].[ESTADO]       NOT NULL,
    [USUARIO_CREACION]                 [dbo].[USUARIO]      NOT NULL,
    [FECHA_CREACION]                   [dbo].[FECHA_TIEMPO] NOT NULL,
    [USUARIO_MODIFICACION]             [dbo].[USUARIO]      NULL,
    [FECHA_MODIFICACION]               [dbo].[FECHA_TIEMPO] NULL,
    CONSTRAINT [PK_REQUISITOS_POR_POSTULANTE] PRIMARY KEY NONCLUSTERED ([ID_REQUISITOS_POR_POSTULANTE] ASC),
    CONSTRAINT [FK_REQUISIT_RELATIONS_POSTULAN] FOREIGN KEY ([ID_POSTULANTES_POR_MODALIDAD]) REFERENCES [transaccional].[postulantes_por_modalidad] ([ID_POSTULANTES_POR_MODALIDAD]),
    CONSTRAINT [FK_REQUISITOS_POR_TIPO_MODALIDAD_REQUISITOS_POR_POSTULANTE] FOREIGN KEY ([ID_REQUISITOS_POR_TIPO_MODALIDAD]) REFERENCES [maestro].[requisitos_por_tipo_modalidad] ([ID_REQUISITOS_POR_TIPO_MODALIDAD])
);

