// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class tipo_enumerado
    {
      
        public int ID_TIPO_ENUMERADO { get; set; }
        public int CODIGO_TIPO_ENUMERADO { get; set; }
        public string? DESCRIPCION_TIPO_ENUMERADO { get; set; }
        public bool? ES_EDITABLE { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public DateTime FECHA_CREACION { get; set; }
        public string? USUARIO_MODIFICACION { get; set; }
        public DateTime? FECHA_MODIFICACION { get; set; }

        public  ICollection<enumerado> enumerado { get; set; }
    }
}