// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using MINEDU.IEST.Estudiante.Entity.StoreProcedure;

namespace MINEDU.IEST.Estudiante.Contexto.Data.StoreProcedure
{
    public partial class SpDbContext
    {
        private ISpDbContextProcedures _procedures;

        public virtual ISpDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new SpDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ISpDbContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<USP_MATRICULA_SEL_DATOS_GENERALES_MATRICULAResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<USP_MATRICULA_SEL_UNIDADES_DIDACTICAS_PAGINADOResult>().HasNoKey().ToView(null);
        }
    }

    public partial class SpDbContextProcedures : ISpDbContextProcedures
    {
        private readonly SpDbContext _context;

        public SpDbContextProcedures(SpDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<USP_MATRICULA_SEL_DATOS_GENERALES_MATRICULAResult>> USP_MATRICULA_SEL_DATOS_GENERALES_MATRICULAAsync(int? ID_PLAN_ESTUDIO, int? ID_SEMESTRE_ACADEMICO, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ID_PLAN_ESTUDIO",
                    Value = ID_PLAN_ESTUDIO ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ID_SEMESTRE_ACADEMICO",
                    Value = ID_SEMESTRE_ACADEMICO ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<USP_MATRICULA_SEL_DATOS_GENERALES_MATRICULAResult>("EXEC @returnValue = [dbo].[USP_MATRICULA_SEL_DATOS_GENERALES_MATRICULA] @ID_PLAN_ESTUDIO, @ID_SEMESTRE_ACADEMICO", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<USP_MATRICULA_SEL_UNIDADES_DIDACTICAS_PAGINADOResult>> USP_MATRICULA_SEL_UNIDADES_DIDACTICAS_PAGINADOAsync(int? ID_INSTITUCION, int? ID_PERIODO_ACADEMICO, int? ID_PLAN_ESTUDIO, int? ID_SEMESTRE_ACADEMICO_ACTUAL, int? ID_ESTUDIANTE_INSTITUCION, int? ID_MATRICULA_ESTUDIANTE, bool? _ES_UNIDAD_DIDACTICA_EF, int? Pagina, int? Registros, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ID_INSTITUCION",
                    Value = ID_INSTITUCION ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ID_PERIODO_ACADEMICO",
                    Value = ID_PERIODO_ACADEMICO ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ID_PLAN_ESTUDIO",
                    Value = ID_PLAN_ESTUDIO ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ID_SEMESTRE_ACADEMICO_ACTUAL",
                    Value = ID_SEMESTRE_ACADEMICO_ACTUAL ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ID_ESTUDIANTE_INSTITUCION",
                    Value = ID_ESTUDIANTE_INSTITUCION ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ID_MATRICULA_ESTUDIANTE",
                    Value = ID_MATRICULA_ESTUDIANTE ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "_ES_UNIDAD_DIDACTICA_EF",
                    Value = _ES_UNIDAD_DIDACTICA_EF ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "Pagina",
                    Value = Pagina ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Registros",
                    Value = Registros ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<USP_MATRICULA_SEL_UNIDADES_DIDACTICAS_PAGINADOResult>("EXEC @returnValue = [dbo].[USP_MATRICULA_SEL_UNIDADES_DIDACTICAS_PAGINADO] @ID_INSTITUCION, @ID_PERIODO_ACADEMICO, @ID_PLAN_ESTUDIO, @ID_SEMESTRE_ACADEMICO_ACTUAL, @ID_ESTUDIANTE_INSTITUCION, @ID_MATRICULA_ESTUDIANTE, @_ES_UNIDAD_DIDACTICA_EF, @Pagina, @Registros", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
