// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.Auxiliar;
using MINEDU.IEST.Estudiante.Entity.Auxiliar;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.Auxiliar.Configurations
{
    public partial class UvwCarreraConfiguration : IEntityTypeConfiguration<UvwCarrera>
    {
        public void Configure(EntityTypeBuilder<UvwCarrera> entity)
        {
            entity.HasNoKey();

            entity.ToView("UVW_CARRERA");

            entity.Property(e => e.ActividadEconomica)
                .HasMaxLength(400)
                .HasColumnName("ACTIVIDAD_ECONOMICA");

            entity.Property(e => e.CodigoActividad)
                .HasMaxLength(10)
                .HasColumnName("CODIGO_ACTIVIDAD");

            entity.Property(e => e.CodigoCarrera)
                .HasMaxLength(14)
                .HasColumnName("CODIGO_CARRERA");

            entity.Property(e => e.CodigoFamiliaProductivo)
                .HasMaxLength(3)
                .HasColumnName("CODIGO_FAMILIA_PRODUCTIVO");

            entity.Property(e => e.CodigoSector)
                .HasMaxLength(2)
                .HasColumnName("CODIGO_SECTOR");

            entity.Property(e => e.IdCarrera).HasColumnName("ID_CARRERA");

            entity.Property(e => e.IdNivelFormacion).HasColumnName("ID_NIVEL_FORMACION");

            entity.Property(e => e.NivelFormacion)
                .HasMaxLength(300)
                .HasColumnName("NIVEL_FORMACION");

            entity.Property(e => e.NombreCarrera)
                .HasMaxLength(500)
                .HasColumnName("NOMBRE_CARRERA");

            entity.Property(e => e.NombreFamiliaProductiva)
                .HasMaxLength(300)
                .HasColumnName("NOMBRE_FAMILIA_PRODUCTIVA");

            entity.Property(e => e.NombreSector)
                .HasMaxLength(400)
                .HasColumnName("NOMBRE_SECTOR");

            entity.Property(e => e.TipoCodigoCarrera).HasColumnName("TIPO_CODIGO_CARRERA");

            entity.Property(e => e.TipoNivelFormacion).HasColumnName("TIPO_NIVEL_FORMACION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UvwCarrera> entity);
    }
}
