// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.Auxiliar;
using MINEDU.IEST.Estudiante.Entity.Auxiliar;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.Auxiliar.Configurations
{
    public partial class UvwInstitucionConfiguration : IEntityTypeConfiguration<UvwInstitucion>
    {
        public void Configure(EntityTypeBuilder<UvwInstitucion> entity)
        {
            entity.HasNoKey();

            entity.ToView("UVW_INSTITUCION");

            entity.Property(e => e.Celular)
                .HasMaxLength(9)
                .HasColumnName("CELULAR");

            entity.Property(e => e.CentroPoblado)
                .HasMaxLength(100)
                .HasColumnName("CENTRO_POBLADO");

            entity.Property(e => e.CodigoDepartamento)
                .HasMaxLength(2)
                .HasColumnName("CODIGO_DEPARTAMENTO");

            entity.Property(e => e.CodigoDistrito)
                .HasMaxLength(6)
                .HasColumnName("CODIGO_DISTRITO");

            entity.Property(e => e.CodigoModular)
                .IsRequired()
                .HasMaxLength(14)
                .HasColumnName("CODIGO_MODULAR");

            entity.Property(e => e.CodigoProvincia)
                .HasMaxLength(4)
                .HasColumnName("CODIGO_PROVINCIA");

            entity.Property(e => e.Direccion)
                .HasMaxLength(500)
                .HasColumnName("DIRECCION");

            entity.Property(e => e.DreGre)
                .HasMaxLength(114)
                .HasColumnName("DRE_GRE");

            entity.Property(e => e.Email)
                .HasMaxLength(250)
                .HasColumnName("EMAIL");

            entity.Property(e => e.EstadoEscale)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .HasColumnName("ESTADO_ESCALE");

            entity.Property(e => e.FechaFin)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_FIN");

            entity.Property(e => e.FechaInicio)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INICIO");

            entity.Property(e => e.Grupo).HasColumnName("GRUPO");

            entity.Property(e => e.Habilitada).HasColumnName("HABILITADA");

            entity.Property(e => e.IdInstitucion).HasColumnName("ID_INSTITUCION");

            entity.Property(e => e.NombreDepartamento)
                .HasMaxLength(100)
                .HasColumnName("NOMBRE_DEPARTAMENTO");

            entity.Property(e => e.NombreDistrito)
                .HasMaxLength(100)
                .HasColumnName("NOMBRE_DISTRITO");

            entity.Property(e => e.NombreInstitucion)
                .HasMaxLength(500)
                .HasColumnName("NOMBRE_INSTITUCION");

            entity.Property(e => e.NombreProvincia)
                .HasMaxLength(100)
                .HasColumnName("NOMBRE_PROVINCIA");

            entity.Property(e => e.Orden).HasColumnName("ORDEN");

            entity.Property(e => e.PaginaWeb)
                .HasMaxLength(250)
                .HasColumnName("PAGINA_WEB");

            entity.Property(e => e.PermiteAdmision).HasColumnName("PERMITE_ADMISION");

            entity.Property(e => e.RealizaAdmision).HasColumnName("REALIZA_ADMISION");

            entity.Property(e => e.Telefono)
                .HasMaxLength(9)
                .HasColumnName("TELEFONO");

            entity.Property(e => e.TipoGestion).HasColumnName("TIPO_GESTION");

            entity.Property(e => e.TipoGestionNombre)
                .HasMaxLength(300)
                .HasColumnName("TIPO_GESTION_NOMBRE");

            entity.Property(e => e.TipoInstitucion).HasColumnName("TIPO_INSTITUCION");

            entity.Property(e => e.TipoInstitucionNombre)
                .HasMaxLength(300)
                .HasColumnName("TIPO_INSTITUCION_NOMBRE");

            entity.Property(e => e.ValidadoEscale)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("VALIDADO_ESCALE");

            entity.Property(e => e.EmailSoporteEstudiante)
                         .HasMaxLength(300)
                         .IsUnicode(false)
                         .HasColumnName("EMAIL_SOPORTE_ESTUDIANTE");

            entity.Property(e => e.TelefonoSoporteEstudiante)
             .HasMaxLength(300)
             .IsUnicode(false)
             .HasColumnName("TELEFONO_SOPORTE_ESTUDIANTE");

            entity.Property(e => e.CelularSoporteEstudiante)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("CELULAR_SOPORTE_ESTUDIANTE");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UvwInstitucion> entity);
    }
}
