// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class CarreraDcbConfiguration : IEntityTypeConfiguration<CarreraDcb>
    {
        public void Configure(EntityTypeBuilder<CarreraDcb> entity)
        {
            entity.HasKey(e => e.IdCarreraDcb)
                .HasName("PK_CARRERA_DCB");

            entity.ToTable("carrera_dcb");

            entity.Property(e => e.IdCarreraDcb)
                .ValueGeneratedNever()
                .HasColumnName("ID_CARRERA_DCB");

            entity.Property(e => e.CodigoCarreraDcb)
                .HasMaxLength(14)
                .HasColumnName("CODIGO_CARRERA_DCB");

            entity.Property(e => e.Correlativo)
                .HasMaxLength(3)
                .HasColumnName("CORRELATIVO");

            entity.Property(e => e.Creditos)
                .HasMaxLength(6)
                .HasColumnName("CREDITOS");

            entity.Property(e => e.Duracion)
                .HasMaxLength(10)
                .HasColumnName("DURACION");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.Horas).HasColumnName("HORAS");

            entity.Property(e => e.IdActividadEconomica).HasColumnName("ID_ACTIVIDAD_ECONOMICA");

            entity.Property(e => e.IdFamiliaProductiva).HasColumnName("ID_FAMILIA_PRODUCTIVA");

            entity.Property(e => e.IdNivelEstudio).HasColumnName("ID_NIVEL_ESTUDIO");

            entity.Property(e => e.IdSector).HasColumnName("ID_SECTOR");

            entity.Property(e => e.NombreCarreraDcb)
                .HasMaxLength(500)
                .HasColumnName("NOMBRE_CARRERA_DCB");

            entity.Property(e => e.TipoClasificador).HasColumnName("TIPO_CLASIFICADOR");

            entity.Property(e => e.TipoPeriodoDuracion).HasColumnName("TIPO_PERIODO_DURACION");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            entity.Property(e => e.Vigencia).HasColumnName("VIGENCIA");

            entity.HasOne(d => d.IdActividadEconomicaNavigation)
                .WithMany(p => p.CarreraDcbs)
                .HasForeignKey(d => d.IdActividadEconomica)
                .HasConstraintName("FK_CARRERA__REFERENCE_ACTIVIDA");

            entity.HasOne(d => d.IdNivelEstudioNavigation)
                .WithMany(p => p.CarreraDcbs)
                .HasForeignKey(d => d.IdNivelEstudio)
                .HasConstraintName("FK_CARRERA__REFERENCE_TIPO_NIV_DCB");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CarreraDcb> entity);
    }
}
