// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class CarreraConfiguration : IEntityTypeConfiguration<Carrera>
    {
        public void Configure(EntityTypeBuilder<Carrera> entity)
        {
            entity.HasKey(e => e.IdCarrera)
                .HasName("PK_CARRERA");

            entity.ToTable("carrera");

            entity.Property(e => e.IdCarrera)
                .ValueGeneratedNever()
                .HasColumnName("ID_CARRERA");

            entity.Property(e => e.CodigoCampoDetallado).HasColumnName("CODIGO_CAMPO_DETALLADO");

            entity.Property(e => e.CodigoCampoEducativo).HasColumnName("CODIGO_CAMPO_EDUCATIVO");

            entity.Property(e => e.CodigoCampoEspecifico).HasColumnName("CODIGO_CAMPO_ESPECIFICO");

            entity.Property(e => e.CodigoClasificador)
                .HasMaxLength(14)
                .HasColumnName("CODIGO_CLASIFICADOR");

            entity.Property(e => e.CodigoEquivalencia).HasColumnName("CODIGO_EQUIVALENCIA");

            entity.Property(e => e.CodigoFamiliaProductivo)
                .HasMaxLength(3)
                .HasColumnName("CODIGO_FAMILIA_PRODUCTIVO");

            entity.Property(e => e.CodigoSector)
                .HasMaxLength(2)
                .HasColumnName("CODIGO_SECTOR");

            entity.Property(e => e.Division)
                .HasMaxLength(3)
                .HasColumnName("DIVISION");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.IdNivelEstudio).HasColumnName("ID_NIVEL_ESTUDIO");

            entity.Property(e => e.MencionCarrera)
                .HasMaxLength(300)
                .HasColumnName("MENCION_CARRERA");

            entity.Property(e => e.NombreCampoDetallado)
                .HasMaxLength(300)
                .HasColumnName("NOMBRE_CAMPO_DETALLADO");

            entity.Property(e => e.NombreCampoEducativo)
                .HasMaxLength(100)
                .HasColumnName("NOMBRE_CAMPO_EDUCATIVO");

            entity.Property(e => e.NombreCampoEspecifico)
                .HasMaxLength(300)
                .HasColumnName("NOMBRE_CAMPO_ESPECIFICO");

            entity.Property(e => e.NombreCarrera)
                .HasMaxLength(500)
                .HasColumnName("NOMBRE_CARRERA");

            entity.Property(e => e.NombreFamiliaProductivo)
                .HasMaxLength(300)
                .HasColumnName("NOMBRE_FAMILIA_PRODUCTIVO");

            entity.Property(e => e.NombreSector)
                .HasMaxLength(300)
                .HasColumnName("NOMBRE_SECTOR");

            entity.Property(e => e.TipoCarrera).HasColumnName("TIPO_CARRERA");

            entity.Property(e => e.TipoClasificador).HasColumnName("TIPO_CLASIFICADOR");

            entity.Property(e => e.TipoNivelFormacion).HasColumnName("TIPO_NIVEL_FORMACION");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Carrera> entity);
    }
}
