// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class DetalleExpedienteConfiguration : IEntityTypeConfiguration<DetalleExpediente>
    {
        public void Configure(EntityTypeBuilder<DetalleExpediente> entity)
        {
            entity.HasKey(e => e.IdDetalleExpediente);

            entity.ToTable("detalle_expediente");

            entity.Property(e => e.IdDetalleExpediente)
                .ValueGeneratedNever()
                .HasColumnName("ID_DETALLE_EXPEDIENTE");

            entity.Property(e => e.Comentario)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("COMENTARIO");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaExpediente)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_EXPEDIENTE");

            entity.Property(e => e.FechaIngresoArea)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INGRESO_AREA");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.IdExpediente).HasColumnName("ID_EXPEDIENTE");

            entity.Property(e => e.NumeroExpediente)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NUMERO_EXPEDIENTE");

            entity.Property(e => e.NumeroFolios).HasColumnName("NUMERO_FOLIOS");

            entity.Property(e => e.Plazo).HasColumnName("PLAZO");

            entity.Property(e => e.TipoDetalleExpediente).HasColumnName("TIPO_DETALLE_EXPEDIENTE");

            entity.Property(e => e.TipoExpedienteActivo).HasColumnName("TIPO_EXPEDIENTE_ACTIVO");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            entity.HasOne(d => d.IdExpedienteNavigation)
                .WithMany(p => p.DetalleExpedientes)
                .HasForeignKey(d => d.IdExpediente)
                .HasConstraintName("FK_detalle_expediente_expediente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DetalleExpediente> entity);
    }
}
