// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class DireccionSedeConfiguration : IEntityTypeConfiguration<DireccionSede>
    {
        public void Configure(EntityTypeBuilder<DireccionSede> entity)
        {
            entity.HasKey(e => e.IdDireccionSede);

            entity.ToTable("direccion_sede");

            entity.Property(e => e.IdDireccionSede)
                .ValueGeneratedNever()
                .HasColumnName("ID_DIRECCION_SEDE");

            entity.Property(e => e.CentroPoblado)
                .HasMaxLength(100)
                .HasColumnName("CENTRO_POBLADO");

            entity.Property(e => e.CodigoDepartamento)
                .HasMaxLength(2)
                .HasColumnName("CODIGO_DEPARTAMENTO");

            entity.Property(e => e.CodigoDistrito)
                .HasMaxLength(6)
                .HasColumnName("CODIGO_DISTRITO");

            entity.Property(e => e.CodigoProvincia)
                .HasMaxLength(4)
                .HasColumnName("CODIGO_PROVINCIA");

            entity.Property(e => e.Direccion)
                .HasMaxLength(300)
                .HasColumnName("DIRECCION");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("date")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("date")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.IdDocumentoRespuesta).HasColumnName("ID_DOCUMENTO_RESPUESTA");

            entity.Property(e => e.IdSede).HasColumnName("ID_SEDE");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DireccionSede> entity);
    }
}
