// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class DocumentoRespuestumConfiguration : IEntityTypeConfiguration<DocumentoRespuestum>
    {
        public void Configure(EntityTypeBuilder<DocumentoRespuestum> entity)
        {
            entity.HasKey(e => e.IdDocumentoRespuesta)
                .HasName("PK_DOCUNENTO_RESPUESTA");

            entity.ToTable("documento_respuesta");

            entity.HasIndex(e => e.NumeroDocumento, "IDX_DOCUMENTO_RESPUESTA_DATA_01");

            entity.Property(e => e.IdDocumentoRespuesta)
                .ValueGeneratedNever()
                .HasColumnName("ID_DOCUMENTO_RESPUESTA");

            entity.Property(e => e.AnioDocumento).HasColumnName("ANIO_DOCUMENTO");

            entity.Property(e => e.CodigoModular)
                .HasMaxLength(14)
                .HasColumnName("CODIGO_MODULAR");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaDocumento)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_DOCUMENTO");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.IdInstitucion).HasColumnName("ID_INSTITUCION");

            entity.Property(e => e.NombreArchivo)
                .HasMaxLength(400)
                .HasColumnName("NOMBRE_ARCHIVO");

            entity.Property(e => e.NombreDocumento)
                .HasMaxLength(100)
                .HasColumnName("NOMBRE_DOCUMENTO");

            entity.Property(e => e.NombreTramite)
                .HasMaxLength(100)
                .HasColumnName("NOMBRE_TRAMITE");

            entity.Property(e => e.NumeroDocumento)
                .HasMaxLength(10)
                .HasColumnName("NUMERO_DOCUMENTO");

            entity.Property(e => e.Observacion)
                .HasMaxLength(300)
                .HasColumnName("OBSERVACION");

            entity.Property(e => e.PeriodoVigencia)
                .HasMaxLength(10)
                .HasColumnName("PERIODO_VIGENCIA");

            entity.Property(e => e.RutaArchivo)
                .HasMaxLength(300)
                .HasColumnName("RUTA_ARCHIVO");

            entity.Property(e => e.TipoDocumento).HasColumnName("TIPO_DOCUMENTO");

            entity.Property(e => e.TipoRespuestaAdministrativa).HasColumnName("TIPO_RESPUESTA_ADMINISTRATIVA");

            entity.Property(e => e.TipoTramite).HasColumnName("TIPO_TRAMITE");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            entity.HasOne(d => d.IdInstitucionNavigation)
                .WithMany(p => p.DocumentoRespuesta)
                .HasForeignKey(d => d.IdInstitucion)
                .HasConstraintName("FK_documento_respuesta_institucion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentoRespuestum> entity);
    }
}
