// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class ExpedienteConfiguration : IEntityTypeConfiguration<Expediente>
    {
        public void Configure(EntityTypeBuilder<Expediente> entity)
        {
            entity.HasKey(e => e.IdExpediente);

            entity.ToTable("expediente");

            entity.Property(e => e.IdExpediente)
                .ValueGeneratedNever()
                .HasColumnName("ID_EXPEDIENTE");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(250)
                .HasColumnName("DESCRIPCION");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.IdAnteriorMovimiento).HasColumnName("ID_ANTERIOR_MOVIMIENTO");

            entity.Property(e => e.IdIntitucion).HasColumnName("ID_INTITUCION");

            entity.Property(e => e.IdTipoExpediente).HasColumnName("ID_TIPO_EXPEDIENTE");

            entity.Property(e => e.IdUltimoMovimiento).HasColumnName("ID_ULTIMO_MOVIMIENTO");

            entity.Property(e => e.TipoEstadoExpediente).HasColumnName("TIPO_ESTADO_EXPEDIENTE");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            entity.HasOne(d => d.IdTipoExpedienteNavigation)
                .WithMany(p => p.Expedientes)
                .HasForeignKey(d => d.IdTipoExpediente)
                .HasConstraintName("FK_expediente_tipo_expediente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Expediente> entity);
    }
}
