// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class InstitucionCarreraConfiguration : IEntityTypeConfiguration<InstitucionCarrera>
    {
        public void Configure(EntityTypeBuilder<InstitucionCarrera> entity)
        {
            entity.HasKey(e => e.IdInstitucionCarrera)
                .HasName("PK_INSTITUCION_CARRERA");

            entity.ToTable("institucion_carrera");

            entity.Property(e => e.IdInstitucionCarrera)
                .ValueGeneratedNever()
                .HasColumnName("ID_INSTITUCION_CARRERA");

            entity.Property(e => e.ArchivoResolucion)
                .HasMaxLength(150)
                .HasColumnName("ARCHIVO_RESOLUCION");

            entity.Property(e => e.AutorizacionFechaFin)
                .HasColumnType("date")
                .HasColumnName("AUTORIZACION_FECHA_FIN");

            entity.Property(e => e.AutorizacionFechaInicio)
                .HasColumnType("date")
                .HasColumnName("AUTORIZACION_FECHA_INICIO");

            entity.Property(e => e.CodigoCarrera).HasColumnName("CODIGO_CARRERA");

            entity.Property(e => e.CodigoModular)
                .HasMaxLength(14)
                .HasColumnName("CODIGO_MODULAR");

            entity.Property(e => e.Duracion).HasColumnName("DURACION");

            entity.Property(e => e.EsAsignatura).HasColumnName("ES_ASIGNATURA");

            entity.Property(e => e.EsModular).HasColumnName("ES_MODULAR");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.IdDocumentoRespuesta).HasColumnName("ID_DOCUMENTO_RESPUESTA");

            entity.Property(e => e.IdInstitucion).HasColumnName("ID_INSTITUCION");

            entity.Property(e => e.IdLocal).HasColumnName("ID_LOCAL");

            entity.Property(e => e.IdSede).HasColumnName("ID_SEDE");

            entity.Property(e => e.PeriodoInicioAnio).HasColumnName("PERIODO_INICIO_ANIO");

            entity.Property(e => e.PeriodoInicioCiclo).HasColumnName("PERIODO_INICIO_CICLO");

            entity.Property(e => e.TipoModalidadEnsenanza).HasColumnName("TIPO_MODALIDAD_ENSENANZA");

            entity.Property(e => e.TipoNivelCapacitacion).HasColumnName("TIPO_NIVEL_CAPACITACION");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            entity.HasOne(d => d.IdSedeNavigation)
                .WithMany(p => p.InstitucionCarreras)
                .HasForeignKey(d => d.IdSede)
                .HasConstraintName("FK_INSTITUC_REFERENCE_SEDE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InstitucionCarrera> entity);
    }
}
