// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class InstitucionAutoridadConfiguration : IEntityTypeConfiguration<InstitucionAutoridad>
    {
        public void Configure(EntityTypeBuilder<InstitucionAutoridad> entity)
        {
            entity.HasKey(e => e.CodigoInstitucionAutoridad)
                .HasName("PK_INSTITUCION_AUTORIDAD");

            entity.ToTable("institucion_autoridad");

            entity.Property(e => e.CodigoInstitucionAutoridad)
                .ValueGeneratedNever()
                .HasColumnName("CODIGO_INSTITUCION_AUTORIDAD");

            entity.Property(e => e.CodigoModular)
                .HasMaxLength(14)
                .HasColumnName("CODIGO_MODULAR");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.NombreAutoridad)
                .HasMaxLength(300)
                .HasColumnName("NOMBRE_AUTORIDAD");

            entity.Property(e => e.NumeroDocumento)
                .HasMaxLength(10)
                .HasColumnName("NUMERO_DOCUMENTO");

            entity.Property(e => e.TipoAutoridad).HasColumnName("TIPO_AUTORIDAD");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InstitucionAutoridad> entity);
    }
}
