// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class LocalConfiguration : IEntityTypeConfiguration<Local>
    {
        public void Configure(EntityTypeBuilder<Local> entity)
        {
            entity.HasKey(e => e.IdLocal);

            entity.ToTable("local");

            entity.Property(e => e.IdLocal).HasColumnName("ID_LOCAL");

            entity.Property(e => e.ArchivoResolucion)
                .HasMaxLength(150)
                .HasColumnName("ARCHIVO_RESOLUCION");

            entity.Property(e => e.CentroPoblado)
                .HasMaxLength(100)
                .HasColumnName("CENTRO_POBLADO");

            entity.Property(e => e.CodigoDepartamento)
                .HasMaxLength(2)
                .HasColumnName("CODIGO_DEPARTAMENTO");

            entity.Property(e => e.CodigoDistrito)
                .HasMaxLength(6)
                .HasColumnName("CODIGO_DISTRITO");

            entity.Property(e => e.CodigoLocal)
                .HasMaxLength(14)
                .HasColumnName("CODIGO_LOCAL");

            entity.Property(e => e.CodigoProvincia)
                .HasMaxLength(4)
                .HasColumnName("CODIGO_PROVINCIA");

            entity.Property(e => e.DreGre)
                .HasMaxLength(50)
                .HasColumnName("DRE_GRE");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.IdInstitucion).HasColumnName("ID_INSTITUCION");

            entity.Property(e => e.NombreLocal)
                .HasMaxLength(100)
                .HasColumnName("NOMBRE_LOCAL");

            entity.Property(e => e.NombreVia)
                .HasMaxLength(250)
                .HasColumnName("NOMBRE_VIA");

            entity.Property(e => e.Numero).HasColumnName("NUMERO");

            entity.Property(e => e.NumeroVia)
                .HasMaxLength(20)
                .HasColumnName("NUMERO_VIA");

            entity.Property(e => e.TipoLocal).HasColumnName("TIPO_LOCAL");

            entity.Property(e => e.TipoVia).HasColumnName("TIPO_VIA");

            entity.Property(e => e.TipoZona).HasColumnName("TIPO_ZONA");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            entity.HasOne(d => d.IdInstitucionNavigation)
                .WithMany(p => p.Locals)
                .HasForeignKey(d => d.IdInstitucion)
                .HasConstraintName("FK_local_institucion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Local> entity);
    }
}
