// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class MovimientoExpedienteConfiguration : IEntityTypeConfiguration<MovimientoExpediente>
    {
        public void Configure(EntityTypeBuilder<MovimientoExpediente> entity)
        {
            entity.HasKey(e => e.IdMovimientoExpediente);

            entity.ToTable("movimiento_expediente");

            entity.Property(e => e.IdMovimientoExpediente)
                .ValueGeneratedNever()
                .HasColumnName("ID_MOVIMIENTO_EXPEDIENTE");

            entity.Property(e => e.Comentario)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("COMENTARIO");

            entity.Property(e => e.DiasTranscurridos).HasColumnName("DIAS_TRANSCURRIDOS");

            entity.Property(e => e.DocumentoSustento)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("DOCUMENTO_SUSTENTO");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaFinEtapa)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_FIN_ETAPA");

            entity.Property(e => e.FechaFinEtapaDias)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_FIN_ETAPA_DIAS");

            entity.Property(e => e.FechaInicioEtapa)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INICIO_ETAPA");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.FechaMovimiento)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MOVIMIENTO");

            entity.Property(e => e.IdEtapa).HasColumnName("ID_ETAPA");

            entity.Property(e => e.IdEtapaDias).HasColumnName("ID_ETAPA_DIAS");

            entity.Property(e => e.IdEtapaPosesion).HasColumnName("ID_ETAPA_POSESION");

            entity.Property(e => e.IdExpediente).HasColumnName("ID_EXPEDIENTE");

            entity.Property(e => e.IdResponsable).HasColumnName("ID_RESPONSABLE");

            entity.Property(e => e.IdResponsablePosesion).HasColumnName("ID_RESPONSABLE_POSESION");

            entity.Property(e => e.PlazoAtencion).HasColumnName("PLAZO_ATENCION");

            entity.Property(e => e.TipoDocumento).HasColumnName("TIPO_DOCUMENTO");

            entity.Property(e => e.TipoEstadoMovimientoExpediente).HasColumnName("TIPO_ESTADO_MOVIMIENTO_EXPEDIENTE");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            entity.HasOne(d => d.IdExpedienteNavigation)
                .WithMany(p => p.MovimientoExpedientes)
                .HasForeignKey(d => d.IdExpediente)
                .HasConstraintName("FK_movimiento_expediente_expediente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MovimientoExpediente> entity);
    }
}
