// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class TipoConfiguration : IEntityTypeConfiguration<Tipo>
    {
        public void Configure(EntityTypeBuilder<Tipo> entity)
        {
            entity.HasKey(e => e.CodigoTipo)
                .HasName("PK_TIPO");

            entity.ToTable("tipo");

            entity.Property(e => e.CodigoTipo)
                .ValueGeneratedNever()
                .HasColumnName("CODIGO_TIPO");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.GrupoTipo)
                .HasMaxLength(100)
                .HasColumnName("GRUPO_TIPO");

            entity.Property(e => e.NombreTipo)
                .HasMaxLength(300)
                .HasColumnName("NOMBRE_TIPO");

            entity.Property(e => e.SiglaTipo)
                .HasMaxLength(5)
                .HasColumnName("SIGLA_TIPO");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tipo> entity);
    }
}
