// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class TipoNivelEstudioConfiguration : IEntityTypeConfiguration<TipoNivelEstudio>
    {
        public void Configure(EntityTypeBuilder<TipoNivelEstudio> entity)
        {
            entity.HasKey(e => e.IdNivelEstudio)
                .HasName("PK_TIPO_NIVEL_ESTUDIO");

            entity.ToTable("tipo_nivel_estudio");

            entity.Property(e => e.IdNivelEstudio)
                .ValueGeneratedNever()
                .HasColumnName("ID_NIVEL_ESTUDIO");

            entity.Property(e => e.DigitoNivelFormativoDcb).HasColumnName("DIGITO_NIVEL_FORMATIVO_DCB");

            entity.Property(e => e.DuracionMinima)
                .HasMaxLength(10)
                .HasColumnName("DURACION_MINIMA");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICACION");

            entity.Property(e => e.NombreNivelEstudio)
                .HasMaxLength(100)
                .HasColumnName("NOMBRE_NIVEL_ESTUDIO");

            entity.Property(e => e.TipoNivelFormacion).HasColumnName("TIPO_NIVEL_FORMACION");

            entity.Property(e => e.TipoPeriodoDuracion)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("TIPO_PERIODO_DURACION")
                .IsFixedLength();

            entity.Property(e => e.UltimoDigitoClasificador).HasColumnName("ULTIMO_DIGITO_CLASIFICADOR");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TipoNivelEstudio> entity);
    }
}
