// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MINEDU.IEST.Estudiante.Contexto.Data.DigePadron;
using MINEDU.IEST.Estudiante.Entity.DigePadron;
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Contexto.Data.DigePadron.Configurations
{
    public partial class UnidadCompetenciaCarreraConfiguration : IEntityTypeConfiguration<UnidadCompetenciaCarrera>
    {
        public void Configure(EntityTypeBuilder<UnidadCompetenciaCarrera> entity)
        {
            entity.HasKey(e => e.IdUnidadCompetenciaCarrera)
                .HasName("PK_UNIDAD_COMPETENCIA_CARRERA");

            entity.ToTable("unidad_competencia_carrera");

            entity.Property(e => e.IdUnidadCompetenciaCarrera)
                .ValueGeneratedNever()
                .HasColumnName("ID_UNIDAD_COMPETENCIA_CARRERA");

            entity.Property(e => e.Estado)
                .HasColumnName("ESTADO")
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.FechaInsercion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_INSERCION")
                .HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.FechaModificaion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_MODIFICAION");

            entity.Property(e => e.IdCarreraDcb).HasColumnName("ID_CARRERA_DCB");

            entity.Property(e => e.UsuarioInsercion).HasColumnName("USUARIO_INSERCION");

            entity.Property(e => e.UsuarioModificacion).HasColumnName("USUARIO_MODIFICACION");

            entity.HasOne(d => d.IdCarreraDcbNavigation)
                .WithMany(p => p.UnidadCompetenciaCarreras)
                .HasForeignKey(d => d.IdCarreraDcb)
                .HasConstraintName("FK_UNIDAD_C_REFERENCE_CARRERA_");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UnidadCompetenciaCarrera> entity);
    }
}
