// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MINEDU.IEST.Estudiante.Entity.SecurityApi
{
    public partial class Role
    {
       
        public string Id { get; set; }
        public string Name { get; set; }
        public string NormalizedName { get; set; }
        public string ConcurrencyStamp { get; set; }

        public List<RoleClaim> RoleClaims { get; set; }
        public List<UserRole> UserRoles { get; set; }

    }
}