// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class carga
    {
       
        public int ID_CARGA { get; set; }
        public int ID_TIPO_CARGA { get; set; }
        public string? NOMBRE_ARCHIVO { get; set; }
        public DateTime? FECHA_CARGA { get; set; }
        public bool ES_BORRADO { get; set; }
        public DateTime FECHA_CREACION { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;
        public bool ESTADO { get; set; }
        public int TOTAL_CORRECTOS { get; set; }
        public int TOTAL_INCORRECTOS { get; set; }
        public string? MENSAJE { get; set; }
        public int ID_PERIODOS_LECTIVOS_POR_INSTITUCION { get; set; }
        public int? ID_SEDE_INSTITUCION { get; set; }
        public int? ID_PERIODO_ACADEMICO { get; set; }
        public int? ID_CARRERAS_POR_INSTITUCION { get; set; }
        public int? ID_PROGRAMACION_MATRICULA { get; set; }
        public int? ID_SEMESTRE_ACADEMICO { get; set; }
        public int? ID_SECCION { get; set; }
        public int? ID_TURNOS_POR_INSTITUCION { get; set; }

        public carreras_por_institucion? ID_CARRERAS_POR_INSTITUCIONNavigation { get; set; }
        public periodos_lectivos_por_institucion ID_PERIODOS_LECTIVOS_POR_INSTITUCIONNavigation { get; set; } = null!;
        public periodo_academico? ID_PERIODO_ACADEMICONavigation { get; set; }
        public programacion_matricula? ID_PROGRAMACION_MATRICULANavigation { get; set; }
        public sede_institucion? ID_SEDE_INSTITUCIONNavigation { get; set; }
        public turnos_por_institucion? ID_TURNOS_POR_INSTITUCIONNavigation { get; set; }
        public ICollection<carga_detalle> carga_detalle { get; set; }
    }
}