// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MINEDU.IEST.Estudiante.Entity
{
    public partial class carga_detalle
    {
       

        public int ID_DET_ARCHIVO { get; set; }
        public int ID_CARGA { get; set; }
        public int? ID_TIPO_DOCUMENTO { get; set; }
        public string? NUMERO_DOCUMENTO { get; set; }
        public string? APELLIDO_PATERNO { get; set; }
        public string? APELLIDO_MATERNO { get; set; }
        public string? NOMBRES { get; set; }
        public int? ID_SEXO { get; set; }
        public DateTime? FECHA_NACIMIENTO { get; set; }
        public bool? ES_DISCAPACITADO { get; set; }
        public int? ID_TIPO_DISCAPACIDAD { get; set; }
        public string? UNIDADES_DIDACTICAS { get; set; }
        public string? UBIGEO_NACIMIENTO { get; set; }
        public string? UBIGEO_RESIDENCIA { get; set; }
        public int? ID_ESTADO_CIVIL { get; set; }
        public int? ID_PAIS_NACIMIENTO { get; set; }
        public int? ID_PAIS_RESIDENCIA { get; set; }
        public string? DIRECCION_RESIDENCIA { get; set; }
        public bool ES_CORRECTO { get; set; }
        public bool ES_BORRADO { get; set; }
        public DateTime FECHA_CREACION { get; set; }
        public string USUARIO_CREACION { get; set; } = null!;

        public  carga ID_CARGANavigation { get; set; } = null!;
        public  ICollection<log_carga> log_carga { get; set; }
    }
}