// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace MINEDU.IEST.Estudiante.Entity.StoreProcedure
{
    public partial class USP_EVALUACION_SEL_LISTA_HISTORIAL_ACADEMICO_ESTUDIANTEResult
    {
        public long Total { get; set; }

        public string CODIGO_PERIODO_LECTIVO { get; set; }

        public string SEMESTRE_ACTUAL { get; set; }

        public long ID_INSTITUCION { get; set; }

        public string CODIGO_MODULAR { get; set; }

        public string NOMBRE_INSTITUCION { get; set; }

        public long ID_SEDE_INSTITUCION { get; set; }

        public string NOMBRE_SEDE { get; set; }

        public long ID_CARRERA { get; set; }

        public string NOMBRE_CARRERA { get; set; }

        public long ID_PLAN_ESTUDIO { get; set; }

        public string NOMBRE_PLAN_ESTUDIOS { get; set; }

        public long ID_TIPO_ITINERARIO { get; set; }

        public string NOMBRE_TIPO_ITINERARIO { get; set; }

        public string NUMERO_DOCUMENTO_PERSONA { get; set; }

        public string TIPO_DOCUMENTO_PERSONA { get; set; }

        public string ESTUDIANTE { get; set; }

        public string FOTO { get; set; }

        public string SEMESTRE_ACADEMICO_UD { get; set; }

        public long ID_UNIDAD_DIDACTICA { get; set; }

        public string NOMBRE_UNIDAD_DIDACTICA { get; set; }

        public double HORAS { get; set; }

        public double CREDITOS { get; set; }

        public double? NOTA { get; set; }

       
    }
}
